/**
 * @revealui/contracts/entities
 *
 * Domain entity contracts (User, Site, Page)
 */

export {
  AGENT_CONTEXT_SCHEMA_VERSION,
  type AgentContext,
  type AgentContextAgent,
  AgentContextAgentSchema,
  AgentContextBaseSchema,
  type AgentContextInsert,
  AgentContextInsertSchema,
  AgentContextObjectSchema,
  AgentContextSchema,
  type AgentContextWithComputed,
  AgentContextWithComputedSchema,
  agentContextToAgent,
  agentContextToHuman,
  CONTEXT_LIMITS,
  calculateCosineSimilarity,
  createAgentContextInsert,
  EMBEDDING_CONFIG,
  type EmbeddingVector,
  EmbeddingVectorSchema,
  estimateContextSize,
  generateContextId,
  getPriorityCategory,
  hasCircularReference,
  hasValidEmbedding,
  isHighPriority,
  isLowPriority,
  isValidContextId,
  normalizeEmbedding,
  normalizePriority,
  PRIORITY_CONFIG,
  parseContextId,
  updateAgentContext,
  validateContextData,
  validateContextKey,
  validateContextSize,
  validateEmbeddingDimensions,
  validateEmbeddingValues,
} from './agent-context.js'
export {
  ACCESS_THRESHOLDS,
  AGENT_MEMORY_SCHEMA_VERSION,
  type AgentMemory,
  type AgentMemoryAgent,
  AgentMemoryAgentSchema,
  AgentMemoryBaseSchema,
  type AgentMemoryInsert,
  AgentMemoryInsertSchema,
  AgentMemoryObjectSchema,
  AgentMemorySchema,
  type AgentMemoryWithComputed,
  AgentMemoryWithComputedSchema,
  agentMemoryToAgent,
  agentMemoryToHuman,
  calculateRelevanceScore,
  createAgentMemoryInsert,
  createExpirationDate,
  createVerification,
  type EmbeddingMetadata,
  EmbeddingMetadataSchema,
  getAccessFrequency,
  getImportance,
  getImportanceCategory,
  getTimeUntilExpiration,
  hasEmbeddingMetadata,
  hasValidEmbedding as hasValidMemoryEmbedding,
  IMPORTANCE_LEVELS,
  isAgentScoped,
  isCorrectionMemory,
  isCriticalImportance,
  isDecisionMemory,
  isExpired,
  isFactMemory,
  isFeedbackMemory,
  isFrequentlyAccessed,
  isGlobalMemory,
  isNearExpiration,
  isPermanent,
  isPreferenceMemory,
  isRarelyAccessed,
  isSiteScoped,
  isStale,
  isVerified,
  isWarningMemory,
  MEMORY_EMBEDDING_CONFIG,
  MEMORY_TYPES,
  type MemoryEmbeddingVector,
  MemoryEmbeddingVectorSchema,
  type MemoryMetadata,
  MemoryMetadataSchema,
  type MemorySource,
  MemorySourceSchema,
  type MemoryType,
  needsVerification,
  recordAccess,
  revokeVerification,
  SOURCE_TYPES,
  type SourceType,
  updateAgentMemory,
} from './agent-memory.js'
export {
  type CreatePageInput,
  CreatePageInputSchema,
  computePagePath,
  createPage,
  createPageLock,
  estimateWordCount,
  getPageBreadcrumbs,
  isLockedByUser,
  isPageLocked,
  PAGE_SCHEMA_VERSION,
  type Page,
  type PageLock,
  PageLockSchema,
  PageSchema,
  type PageSeo,
  PageSeoSchema,
  type PageStatus,
  PageStatusSchema,
  type UpdatePageInput,
  UpdatePageInputSchema,
} from './page.js'
export {
  CreatePriceContract,
  type CreatePriceInput,
  CreatePriceInputSchema,
  formatPriceAmount,
  getDisplayAmount,
  getIntervalDescription,
  hasStripePrice,
  hasTieredPricing,
  isOneTimePrice,
  isPublishedPrice,
  isRecurringPrice,
  PRICE_SCHEMA_VERSION,
  type Price,
  PriceContract,
  PriceSchema,
  type PriceStatus,
  PriceStatusSchema,
  type PriceWithCategories,
  PriceWithCategoriesSchema,
  type PriceWithRelated,
  PriceWithRelatedSchema,
  type StripePriceData,
  StripePriceDataSchema,
  type StripePriceID,
  StripePriceIDSchema,
  UpdatePriceContract,
  type UpdatePriceInput,
  UpdatePriceInputSchema,
} from './price.js'
export {
  CreateProductContract,
  type CreateProductInput,
  CreateProductInputSchema,
  formatPriceRange,
  getAvailablePrices,
  getDefaultPriceId,
  getPriceCount,
  getPriceRange,
  hasProductImages,
  hasProductPrices,
  hasStripeProduct,
  isPublishedProduct,
  PRODUCT_SCHEMA_VERSION,
  type Product,
  ProductContract,
  ProductSchema,
  type ProductStatus,
  ProductStatusSchema,
  type ProductWithCategories,
  ProductWithCategoriesSchema,
  type ProductWithRelated,
  ProductWithRelatedSchema,
  type StripePriceList,
  StripePriceListSchema,
  type StripeProductData,
  StripeProductDataSchema,
  type StripeProductID,
  StripeProductIDSchema,
  UpdateProductContract,
  type UpdateProductInput,
  UpdateProductInputSchema,
} from './product.js'
export {
  calculateExpiresAt,
  calculateSessionDuration,
  createSessionInsert,
  getSessionAge,
  getSessionTimeRemaining,
  isSessionExpired,
  isSessionNearExpiration,
  isSessionValid,
  needsActivityUpdate,
  SESSION_DURATION,
  SESSION_SCHEMA_VERSION,
  type Session,
  SessionAgentSchema,
  SessionBaseSchema,
  type SessionInsert,
  SessionInsertSchema,
  SessionObjectSchema,
  SessionSchema,
  type SessionWithComputed,
  SessionWithComputedSchema,
  sessionToAgent,
  sessionToHuman,
  updateSessionActivity,
  validateIpAddress,
  validateTokenHash,
} from './session.js'
export {
  type CreateSiteInput,
  CreateSiteInputSchema,
  canAgentEditSite,
  canUserPerformAction,
  createSite,
  SITE_SCHEMA_VERSION,
  type Site,
  type SiteCollaborator,
  SiteCollaboratorSchema,
  SiteSchema,
  type SiteSeo,
  SiteSeoSchema,
  type SiteSettings,
  SiteSettingsSchema,
  type SiteStatus,
  SiteStatusSchema,
  type SiteTheme,
  SiteThemeSchema,
  type UpdateSiteInput,
  UpdateSiteInputSchema,
} from './site.js'
export {
  type CreateUserInput,
  CreateUserInputSchema,
  createUser,
  type UpdateUserInput,
  UpdateUserInputSchema,
  USER_SCHEMA_VERSION,
  type User,
  type UserPreferences,
  UserPreferencesSchema,
  type UserRole,
  UserRoleSchema,
  UserSchema,
  type UserStatus,
  UserStatusSchema,
  type UserType,
  UserTypeSchema,
} from './user.js'
