/**
 * Environment file generator
 *
 * Writes `.env.development.local` into a scaffolded project. Next.js and
 * Vite only load that file in development, so the generated secret and test
 * placeholders never reach a production runtime (unlike `.env.local`, which
 * Next.js also loads in production).
 */

import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import type { DatabaseConfig } from '../prompts/database.js';
import type { PaymentConfig } from '../prompts/payments.js';
import type { StorageConfig } from '../prompts/storage.js';

export interface EnvConfig {
  database: DatabaseConfig;
  storage: StorageConfig;
  payment: PaymentConfig;
}

export async function generateEnvFile(projectPath: string, config: EnvConfig): Promise<void> {
  // Generate REVEALUI_SECRET
  const secret = crypto.randomBytes(32).toString('hex');

  const lines: string[] = [
    '# RevealUI Environment Variables',
    '# Generated by @revealui/cli - fill in the remaining placeholders before running `pnpm dev`',
    '',
    '# =============================================================================',
    '# REQUIRED - REVEALUI CORE',
    '# =============================================================================',
    '',
    `REVEALUI_SECRET=${secret}`,
    'REVEALUI_PUBLIC_SERVER_URL=http://localhost:4000',
    'NEXT_PUBLIC_SERVER_URL=http://localhost:4000',
    '',
    '# =============================================================================',
    '# REQUIRED - DATABASE',
    '# =============================================================================',
    '',
  ];

  // Database configuration
  if (config.database.provider !== 'skip' && config.database.postgresUrl) {
    lines.push(`POSTGRES_URL=${config.database.postgresUrl}`);
  } else {
    lines.push('# Local Postgres default - matches the Dev Container / Devbox database.');
    lines.push('# Point this at a hosted Postgres (e.g. NeonDB) when you have one.');
    lines.push('POSTGRES_URL=postgresql://postgres:postgres@localhost:5432/revealui');
  }

  lines.push('');
  lines.push('# =============================================================================');
  lines.push('# REQUIRED - STORAGE');
  lines.push('# =============================================================================');
  lines.push('');

  // Storage configuration — Cloudflare R2 is the canonical (and sole) backend.
  if (config.storage.provider === 'r2') {
    lines.push(`R2_ACCOUNT_ID=${config.storage.r2AccountId ?? ''}`);
    lines.push(`R2_ACCESS_KEY_ID=${config.storage.r2AccessKeyId ?? ''}`);
    lines.push(`R2_SECRET_ACCESS_KEY=${config.storage.r2SecretAccessKey ?? ''}`);
    lines.push(`R2_BUCKET=${config.storage.r2Bucket ?? ''}`);
    lines.push(`R2_PUBLIC_BASE_URL=${config.storage.r2PublicBaseUrl ?? ''}`);
  } else {
    lines.push('# Cloudflare R2 (recommended, S3-compatible). Create a bucket + API token in');
    lines.push('# the Cloudflare dashboard (R2 > Manage R2 API Tokens), then set all five:');
    lines.push('# R2_ACCOUNT_ID=your-cloudflare-account-id');
    lines.push('# R2_ACCESS_KEY_ID=your-r2-access-key-id');
    lines.push('# R2_SECRET_ACCESS_KEY=your-r2-secret-access-key');
    lines.push('# R2_BUCKET=your-bucket-name');
    lines.push('# R2_PUBLIC_BASE_URL=https://<account-id>.r2.cloudflarestorage.com/<bucket>');
  }

  lines.push('');
  lines.push('# =============================================================================');
  lines.push('# REQUIRED - STRIPE PAYMENTS');
  lines.push('# =============================================================================');
  lines.push('');

  // Payment configuration. Test placeholders stay uncommented to mirror the
  // template `.env.example` shape.
  if (config.payment.enabled) {
    lines.push(`STRIPE_SECRET_KEY=${config.payment.stripeSecretKey ?? 'sk_test_placeholder'}`);
    lines.push(
      `NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${config.payment.stripePublishableKey ?? 'pk_test_placeholder'}`,
    );
    if (config.payment.stripeWebhookSecret) {
      lines.push(`STRIPE_WEBHOOK_SECRET=${config.payment.stripeWebhookSecret}`);
    } else {
      lines.push('STRIPE_WEBHOOK_SECRET=whsec_placeholder');
      lines.push('# Run: stripe listen --forward-to localhost:4000/api/webhooks/stripe');
    }
  } else {
    lines.push('# Use test keys during development: https://dashboard.stripe.com/test/apikeys');
    lines.push('STRIPE_SECRET_KEY=sk_test_placeholder');
    lines.push('NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_placeholder');
    lines.push('STRIPE_WEBHOOK_SECRET=whsec_placeholder');
  }

  lines.push('');
  lines.push('# =============================================================================');
  lines.push('# OPTIONAL - CORS & SECURITY');
  lines.push('# =============================================================================');
  lines.push('');
  lines.push('REVEALUI_CORS_ORIGINS=http://localhost:3000,http://localhost:4000');
  lines.push('');
  lines.push('# =============================================================================');
  lines.push('# ADMIN BOOTSTRAP (first run only)');
  lines.push('# =============================================================================');
  lines.push('');
  lines.push('# Set a strong password (min 12 chars) before first run.');
  lines.push('REVEALUI_ADMIN_EMAIL=admin@example.com');
  lines.push('REVEALUI_ADMIN_PASSWORD=');

  // Write to .env.development.local
  const envPath = path.join(projectPath, '.env.development.local');
  await fs.writeFile(envPath, `${lines.join('\n')}\n`, 'utf-8');
}
