/**
 * Environment file generator
 */

import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import type { DatabaseConfig } from '../prompts/database.js';
import type { PaymentConfig } from '../prompts/payments.js';
import type { StorageConfig } from '../prompts/storage.js';

export interface EnvConfig {
  database: DatabaseConfig;
  storage: StorageConfig;
  payment: PaymentConfig;
}

export async function generateEnvFile(projectPath: string, config: EnvConfig): Promise<void> {
  // Generate REVEALUI_SECRET
  const secret = crypto.randomBytes(32).toString('hex');

  const lines: string[] = [
    '# RevealUI Environment Variables',
    '# Generated by @revealui/cli',
    '',
    '# =============================================================================',
    '# REQUIRED - REVEALUI CORE',
    '# =============================================================================',
    '',
    `REVEALUI_SECRET=${secret}`,
    'REVEALUI_PUBLIC_SERVER_URL=http://localhost:4000',
    'NEXT_PUBLIC_SERVER_URL=http://localhost:4000',
    '',
    '# =============================================================================',
    '# REQUIRED - DATABASE',
    '# =============================================================================',
    '',
  ];

  // Database configuration
  if (config.database.provider !== 'skip' && config.database.postgresUrl) {
    lines.push(`POSTGRES_URL=${config.database.postgresUrl}`);
  } else {
    lines.push('# POSTGRES_URL=postgresql://user:password@host:port/database?sslmode=require');
    lines.push('# Configure your database connection string');
  }

  lines.push('');
  lines.push('# =============================================================================');
  lines.push('# REQUIRED - STORAGE');
  lines.push('# =============================================================================');
  lines.push('');

  // Storage configuration — Cloudflare R2 is the canonical backend; Vercel Blob
  // is the legacy fallback (being retired, GAP-208).
  if (config.storage.provider === 'r2') {
    lines.push(`R2_ACCOUNT_ID=${config.storage.r2AccountId ?? ''}`);
    lines.push(`R2_ACCESS_KEY_ID=${config.storage.r2AccessKeyId ?? ''}`);
    lines.push(`R2_SECRET_ACCESS_KEY=${config.storage.r2SecretAccessKey ?? ''}`);
    lines.push(`R2_BUCKET=${config.storage.r2Bucket ?? ''}`);
    lines.push(`R2_PUBLIC_BASE_URL=${config.storage.r2PublicBaseUrl ?? ''}`);
  } else if (config.storage.provider === 'vercel-blob' && config.storage.blobToken) {
    lines.push('# Cloudflare R2 is the canonical backend; Vercel Blob is legacy (being retired).');
    lines.push(`BLOB_READ_WRITE_TOKEN=${config.storage.blobToken}`);
  } else {
    lines.push('# Cloudflare R2 (recommended, S3-compatible). Create a bucket + API token in');
    lines.push('# the Cloudflare dashboard (R2 > Manage R2 API Tokens), then set all five:');
    lines.push('# R2_ACCOUNT_ID=your-cloudflare-account-id');
    lines.push('# R2_ACCESS_KEY_ID=your-r2-access-key-id');
    lines.push('# R2_SECRET_ACCESS_KEY=your-r2-secret-access-key');
    lines.push('# R2_BUCKET=your-bucket-name');
    lines.push('# R2_PUBLIC_BASE_URL=https://<account-id>.r2.cloudflarestorage.com/<bucket>');
    lines.push('# Legacy alternative (being retired): BLOB_READ_WRITE_TOKEN=vercel_blob_rw_...');
  }

  lines.push('');
  lines.push('# =============================================================================');
  lines.push('# REQUIRED - STRIPE PAYMENTS');
  lines.push('# =============================================================================');
  lines.push('');

  // Payment configuration
  if (config.payment.enabled) {
    if (config.payment.stripeSecretKey) {
      lines.push(`STRIPE_SECRET_KEY=${config.payment.stripeSecretKey}`);
    }
    if (config.payment.stripePublishableKey) {
      lines.push(`NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${config.payment.stripePublishableKey}`);
    }
    if (config.payment.stripeWebhookSecret) {
      lines.push(`STRIPE_WEBHOOK_SECRET=${config.payment.stripeWebhookSecret}`);
    } else {
      lines.push('# STRIPE_WEBHOOK_SECRET=whsec_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx');
      lines.push('# Run: stripe listen --forward-to localhost:4000/api/webhooks/stripe');
    }
  } else {
    lines.push('# STRIPE_SECRET_KEY=sk_test_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx');
    lines.push('# NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx');
    lines.push('# STRIPE_WEBHOOK_SECRET=whsec_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx');
  }

  lines.push('');
  lines.push('# =============================================================================');
  lines.push('# OPTIONAL - CORS & SECURITY');
  lines.push('# =============================================================================');
  lines.push('');
  lines.push('REVEALUI_CORS_ORIGINS=http://localhost:3000,http://localhost:4000');
  lines.push('');

  // Write to .env.development.local
  const envPath = path.join(projectPath, '.env.development.local');
  await fs.writeFile(envPath, lines.join('\n'), 'utf-8');
}
