/**
 * Environment file generator
 */

import crypto from 'node:crypto'
import fs from 'node:fs/promises'
import path from 'node:path'
import type { DatabaseConfig } from '../prompts/database.js'
import type { PaymentConfig } from '../prompts/payments.js'
import type { StorageConfig } from '../prompts/storage.js'

export interface EnvConfig {
  database: DatabaseConfig
  storage: StorageConfig
  payment: PaymentConfig
}

export async function generateEnvFile(projectPath: string, config: EnvConfig): Promise<void> {
  // Generate REVEALUI_SECRET
  const secret = crypto.randomBytes(32).toString('hex')

  const lines: string[] = [
    '# RevealUI Environment Variables',
    '# Generated by @revealui/cli',
    '',
    '# =============================================================================',
    '# REQUIRED - REVEALUI CORE',
    '# =============================================================================',
    '',
    `REVEALUI_SECRET=${secret}`,
    'REVEALUI_PUBLIC_SERVER_URL=http://localhost:4000',
    'NEXT_PUBLIC_SERVER_URL=http://localhost:4000',
    '',
    '# =============================================================================',
    '# REQUIRED - DATABASE',
    '# =============================================================================',
    '',
  ]

  // Database configuration
  if (config.database.provider !== 'skip' && config.database.postgresUrl) {
    lines.push(`POSTGRES_URL=${config.database.postgresUrl}`)
  } else {
    lines.push('# POSTGRES_URL=postgresql://user:password@host:port/database?sslmode=require')
    lines.push('# Configure your database connection string')
  }

  lines.push('')
  lines.push('# =============================================================================')
  lines.push('# REQUIRED - STORAGE')
  lines.push('# =============================================================================')
  lines.push('')

  // Storage configuration
  if (config.storage.provider === 'vercel-blob' && config.storage.blobToken) {
    lines.push(`BLOB_READ_WRITE_TOKEN=${config.storage.blobToken}`)
  } else if (config.storage.provider === 'supabase') {
    if (config.storage.supabaseUrl) {
      lines.push(`NEXT_PUBLIC_SUPABASE_URL=${config.storage.supabaseUrl}`)
    }
    if (config.storage.supabaseAnonKey) {
      lines.push(`NEXT_PUBLIC_SUPABASE_ANON_KEY=${config.storage.supabaseAnonKey}`)
    }
  } else {
    lines.push('# BLOB_READ_WRITE_TOKEN=vercel_blob_rw_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
    lines.push('# Configure your Vercel Blob token')
  }

  lines.push('')
  lines.push('# =============================================================================')
  lines.push('# REQUIRED - STRIPE PAYMENTS')
  lines.push('# =============================================================================')
  lines.push('')

  // Payment configuration
  if (config.payment.enabled) {
    if (config.payment.stripeSecretKey) {
      lines.push(`STRIPE_SECRET_KEY=${config.payment.stripeSecretKey}`)
    }
    if (config.payment.stripePublishableKey) {
      lines.push(`NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${config.payment.stripePublishableKey}`)
    }
    if (config.payment.stripeWebhookSecret) {
      lines.push(`STRIPE_WEBHOOK_SECRET=${config.payment.stripeWebhookSecret}`)
    } else {
      lines.push('# STRIPE_WEBHOOK_SECRET=whsec_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
      lines.push('# Run: stripe listen --forward-to localhost:4000/api/webhooks/stripe')
    }
  } else {
    lines.push('# STRIPE_SECRET_KEY=sk_test_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
    lines.push('# NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
    lines.push('# STRIPE_WEBHOOK_SECRET=whsec_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
  }

  lines.push('')
  lines.push('# =============================================================================')
  lines.push('# OPTIONAL - CORS & SECURITY')
  lines.push('# =============================================================================')
  lines.push('')
  lines.push('REVEALUI_CORS_ORIGINS=http://localhost:3000,http://localhost:4000')
  lines.push('')

  // Write to .env.development.local
  const envPath = path.join(projectPath, '.env.development.local')
  await fs.writeFile(envPath, lines.join('\n'), 'utf-8')
}
