#!/usr/bin/env tsx
/**
 * Script to copy generated types to the centralized generated package.
 * This ensures generated types are accessible across the monorepo.
 *
 * Now uses modularized generators from scripts/lib/generators/types/
 *
 * Features:
 * - Dynamic table discovery from source files
 * - Automatic import generation
 * - Validation of transformations
 * - Comprehensive error handling
 *
 * Usage:
 *   pnpm tsx scripts/generate/copy-generated-types.ts        # Copy all
 *   pnpm tsx scripts/generate/copy-generated-types.ts --cms   # Copy CMS only
 *   pnpm tsx scripts/generate/copy-generated-types.ts --neon  # Copy Neon only
 *
 * @dependencies
 * - scripts/lib/generators/types - Modularized type generators
 * - scripts/lib/index.js - Logger and utilities
 */

import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createLogger } from '../lib/index.js'
import { copyFileWithTransform } from '../lib/generators/types/index.js'

const logger = createLogger({ prefix: 'TypeCopy' })

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const rootDir = join(__dirname, '../..')

// =============================================================================
// File Paths
// =============================================================================

// Source files (generated by other processes)
const cmsTypesSource = join(rootDir, 'apps/cms/src/types/revealui.ts')
const supabaseTypesSource = join(rootDir, 'packages/services/src/supabase/types.ts')
const neonTypesSource = join(rootDir, 'packages/db/src/types/database.ts')

// Destination files (centralized in @revealui/schema)
const cmsTypesDest = join(rootDir, 'packages/schema/src/generated/types/cms.ts')
const supabaseTypesDest = join(rootDir, 'packages/schema/src/generated/types/supabase.ts')
const neonTypesDest = join(rootDir, 'packages/schema/src/generated/types/neon.ts')

// =============================================================================
// Main Execution
// =============================================================================

try {
  logger.header('Copying Generated Types')

  // Copy CMS types
  if (process.argv.includes('--cms') || process.argv.length === 2) {
    copyFileWithTransform(cmsTypesSource, cmsTypesDest, 'CMS types', {
      transformImports: false,
      validate: false,
      rootDir,
    })
  }

  // Copy Supabase types
  if (process.argv.includes('--supabase') || process.argv.length === 2) {
    copyFileWithTransform(supabaseTypesSource, supabaseTypesDest, 'Supabase types', {
      transformImports: false,
      validate: false,
      rootDir,
    })
  }

  // Copy NeonDB types with import transformation
  // Note: neon.ts uses sub-module imports from @revealui/db/schema/*
  if (process.argv.includes('--neon') || process.argv.length === 2) {
    copyFileWithTransform(neonTypesSource, neonTypesDest, 'NeonDB types', {
      transformImports: true,
      validate: true,
      rootDir,
    })
  }

  logger.success('Type copying complete!')
} catch (error) {
  logger.error(`Type copying failed: ${error instanceof Error ? error.message : String(error)}`)
  if (error instanceof Error && error.stack) {
    logger.error(`Stack trace: ${error.stack}`)
  }
  process.exit(1)
}
