/**
 * Project creation command
 *
 * Copies template files, writes .env.local, installs dependencies,
 * and initialises a git repo.
 */

import crypto from 'node:crypto';
import { existsSync } from 'node:fs';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createLogger } from '@revealui/setup/utils';
import ora from 'ora';
import { generateDevbox } from '../generators/devbox.js';
import { generateDevContainer } from '../generators/devcontainer.js';
import { generateReadme } from '../generators/readme.js';
import { installDependencies, isPnpmInstalled } from '../installers/dependencies.js';
import type { DatabaseConfig } from '../prompts/database.js';
import type { DevEnvConfig } from '../prompts/devenv.js';
import type { PaymentConfig } from '../prompts/payments.js';
import type { ProjectConfig } from '../prompts/project.js';
import type { StorageConfig } from '../prompts/storage.js';
import { createInitialCommit, initializeGitRepo, isGitInstalled } from '../utils/git.js';

const logger = createLogger({ prefix: 'Create' });

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Templates live at packages/cli/templates/
// In source: __dirname = src/commands/ → ../../templates
// After tsup: __dirname = dist/ → ../templates
// Detect by checking which path actually exists
const TEMPLATES_DIR = existsSync(path.resolve(__dirname, '../../templates'))
  ? path.resolve(__dirname, '../../templates')
  : path.resolve(__dirname, '../templates');

export interface CreateProjectConfig {
  project: ProjectConfig;
  database: DatabaseConfig;
  storage: StorageConfig;
  payment: PaymentConfig;
  devenv: DevEnvConfig;
  skipGit?: boolean;
  skipInstall?: boolean;
}

/**
 * Build the .env.local content from user-provided config values.
 */
function buildEnvLocal(cfg: CreateProjectConfig): string {
  const lines: string[] = [
    '# Generated by @revealui/cli — fill in the remaining placeholders before running `pnpm dev`',
    '',
    '# Core',
    `REVEALUI_SECRET=${generateSecret()}`,
    `REVEALUI_PUBLIC_SERVER_URL=http://localhost:4000`,
    `NEXT_PUBLIC_SERVER_URL=http://localhost:4000`,
    '',
    '# Database',
  ];

  if (cfg.database.postgresUrl) {
    lines.push(`POSTGRES_URL=${cfg.database.postgresUrl}`);
  } else {
    lines.push('POSTGRES_URL=postgresql://postgres:postgres@localhost:5432/revealui');
  }

  lines.push('', '# Storage (Vercel Blob)');
  if (cfg.storage.provider === 'vercel-blob' && cfg.storage.blobToken) {
    lines.push(`BLOB_READ_WRITE_TOKEN=${cfg.storage.blobToken}`);
  } else {
    lines.push('BLOB_READ_WRITE_TOKEN=vercel_blob_rw_placeholder');
  }

  lines.push('', '# Stripe');
  if (cfg.payment.enabled && cfg.payment.stripeSecretKey) {
    lines.push(`STRIPE_SECRET_KEY=${cfg.payment.stripeSecretKey}`);
    lines.push(`STRIPE_WEBHOOK_SECRET=${cfg.payment.stripeWebhookSecret || 'whsec_placeholder'}`);
    lines.push(
      `NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${cfg.payment.stripePublishableKey || 'pk_test_placeholder'}`,
    );
  } else {
    lines.push('STRIPE_SECRET_KEY=sk_test_placeholder');
    lines.push('STRIPE_WEBHOOK_SECRET=whsec_placeholder');
    lines.push('NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_placeholder');
  }

  lines.push('', '# Admin bootstrap (used on first run only)');
  lines.push('REVEALUI_ADMIN_EMAIL=admin@example.com');
  lines.push('REVEALUI_ADMIN_PASSWORD=changeme-min-12-chars');

  return `${lines.join('\n')}\n`;
}

/** Generate a cryptographically random 48-char hex secret */
function generateSecret(): string {
  return crypto.randomBytes(24).toString('hex');
}

/**
 * List template directories that actually exist on disk.
 */
async function listAvailableTemplates(): Promise<string[]> {
  try {
    const entries = await fs.readdir(TEMPLATES_DIR, { withFileTypes: true });
    return entries.filter((e) => e.isDirectory()).map((e) => e.name);
  } catch {
    return [];
  }
}

/**
 * Copy a template directory recursively into the target path.
 */
async function copyTemplate(templateName: string, targetPath: string): Promise<void> {
  const templatePath = path.join(TEMPLATES_DIR, templateName);

  // Verify the template exists
  try {
    await fs.access(templatePath);
  } catch {
    const available = await listAvailableTemplates();
    const listing =
      available.length > 0
        ? `Available templates: ${available.join(', ')}`
        : `No templates found in ${TEMPLATES_DIR}`;
    throw new Error(`Template "${templateName}" not found at ${templatePath}. ${listing}`);
  }

  await copyDir(templatePath, targetPath);
}

async function copyDir(src: string, dest: string): Promise<void> {
  await fs.mkdir(dest, { recursive: true });
  const entries = await fs.readdir(src, { withFileTypes: true });

  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    // npm always strips .gitignore from tarballs; we store it as _gitignore and rename on copy
    const destName = entry.name === '_gitignore' ? '.gitignore' : entry.name;
    const destPath = path.join(dest, destName);

    if (entry.isDirectory()) {
      await copyDir(srcPath, destPath);
    } else {
      await fs.copyFile(srcPath, destPath);
    }
  }
}

/**
 * Map the CLI template name to the directory name under templates/.
 * All non-starter templates fall back to starter for now.
 */
function resolveTemplateName(template: ProjectConfig['template']): string {
  const map: Record<ProjectConfig['template'], string> = {
    'basic-blog': 'basic-blog',
    'e-commerce': 'e-commerce',
    portfolio: 'portfolio',
  };
  return map[template] ?? 'starter';
}

/**
 * Pull OSS AI rules from the revealui-rules repo.
 * Best-effort — if the network is unavailable or the repo doesn't exist yet, skip silently.
 */
async function pullContentRules(projectPath: string): Promise<void> {
  const baseUrl =
    process.env.REVEALUI_RULES_URL ??
    'https://raw.githubusercontent.com/RevealUIStudio/editor-configs/main/harnesses';

  const spinner = ora('Pulling AI coding rules...').start();
  try {
    const manifestRes = await fetch(`${baseUrl}/manifest.json`, {
      signal: AbortSignal.timeout(10_000),
    });
    if (!manifestRes.ok) {
      spinner.info('AI rules not available — skipping');
      return;
    }

    const manifest = (await manifestRes.json()) as {
      definitions: Array<{
        tier: string;
        generatorPaths: Record<string, string[]>;
      }>;
    };

    // Only pull OSS definitions, rendered for Claude Code
    const generatorId = 'claude-code';
    const ossDefs = manifest.definitions.filter((d) => d.tier === 'oss');
    let written = 0;

    for (const def of ossDefs) {
      const paths = def.generatorPaths[generatorId] ?? [];
      for (const relPath of paths) {
        try {
          const fileRes = await fetch(`${baseUrl}/generators/${generatorId}/${relPath}`, {
            signal: AbortSignal.timeout(5_000),
          });
          if (!fileRes.ok) continue;
          const content = await fileRes.text();
          const absolutePath = path.join(projectPath, relPath);
          await fs.mkdir(path.dirname(absolutePath), { recursive: true });
          await fs.writeFile(absolutePath, content, 'utf-8');
          written++;
        } catch {
          // Individual file failures are non-fatal
        }
      }
    }

    if (written > 0) {
      spinner.succeed(`Pulled ${written} AI coding rules`);
    } else {
      spinner.info('No AI rules pulled');
    }
  } catch {
    spinner.info('AI rules not available — skipping');
  }
}

/**
 * Main project creation function — wires everything together.
 */
export async function createProject(cfg: CreateProjectConfig): Promise<void> {
  const { project, skipGit = false, skipInstall = false } = cfg;
  const { projectPath, projectName, template } = project;

  // 1. Copy template files
  const spinner = ora(`Copying template "${template}"...`).start();
  try {
    await copyTemplate(resolveTemplateName(template), projectPath);
    spinner.succeed('Template files copied');
  } catch (err) {
    spinner.fail('Failed to copy template files');
    throw err;
  }

  // 2. Replace {{PROJECT_NAME}} placeholders in package.json / other files
  const pkgJsonPath = path.join(projectPath, 'package.json');
  try {
    const raw = await fs.readFile(pkgJsonPath, 'utf-8');
    await fs.writeFile(pkgJsonPath, raw.replaceAll('{{PROJECT_NAME}}', projectName), 'utf-8');
  } catch {
    // package.json placeholder replacement is best-effort
  }

  // 3. Write .env.local
  const envSpinner = ora('Writing .env.local...').start();
  try {
    await fs.writeFile(path.join(projectPath, '.env.local'), buildEnvLocal(cfg), 'utf-8');
    envSpinner.succeed('.env.local written');
  } catch (err) {
    envSpinner.fail('Failed to write .env.local');
    throw err;
  }

  // 4. Generate README
  await generateReadme(projectPath, project);
  logger.success('README.md generated');

  // 4b. Generate dev environment configs
  if (cfg.devenv.createDevContainer) {
    await generateDevContainer(projectPath);
    logger.success('.devcontainer/ generated');
  }
  if (cfg.devenv.createDevbox) {
    await generateDevbox(projectPath);
    logger.success('devbox.json generated');
  }

  // 4c. Pull OSS AI rules from the rules repo (best-effort)
  await pullContentRules(projectPath);

  // 5. Install dependencies
  if (!skipInstall) {
    const pnpmOk = await isPnpmInstalled();
    if (!pnpmOk) {
      logger.warn(
        'pnpm not found — skipping dependency installation. Run `pnpm install` manually.',
      );
    } else {
      await installDependencies(projectPath);
    }
  } else {
    logger.info('Skipping dependency installation (--skip-install)');
  }

  // 6. Git init
  if (!skipGit) {
    const gitOk = await isGitInstalled();
    if (!gitOk) {
      logger.warn('git not found — skipping repository initialisation.');
    } else {
      await initializeGitRepo(projectPath);
      await createInitialCommit(projectPath);
    }
  } else {
    logger.info('Skipping git initialisation (--skip-git)');
  }
}
