/**
 * @revealui/core/types/schema
 *
 * Schema contract types only.
 * Use this subpath to import only schema types without framework types.
 */

// Re-export entity types from main schema package
export type {
  // Block Contracts
  AccordionBlock,
  // Representation Contracts
  AgentActionDefinition,
  // Agent Contracts
  AgentActionRecord,
  AgentConstraint,
  AgentContext,
  AgentDefinition,
  AgentMemory,
  AgentRelation,
  AgentRepresentation,
  AgentState,
  Block,
  BlockMeta,
  BlockStyle,
  BlockType,
  ButtonBlock,
  CodeBlock,
  ColumnsBlock,
  ComponentBlock,
  Conversation,
  ConversationMessage,
  // Page Contracts
  CreatePageInput,
  // Site Contracts
  CreateSiteInput,
  DividerBlock,
  DualEntity,
  EmbedBlock,
  Embedding,
  EmbeddingModel,
  FormBlock,
  GridBlock,
  HeadingBlock,
  HtmlBlock,
  HumanRepresentation,
  ImageBlock,
  Intent,
  IntentType,
  ListBlock,
  MemorySource,
  MemoryType,
  Page,
  PageLock,
  PageSeo,
  PageStatus,
  QuoteBlock,
  Site,
  SiteCollaborator,
  SiteSeo,
  SiteSettings,
  SiteStatus,
  SiteTheme,
  SpacerBlock,
  TableBlock,
  TabsBlock,
  TextBlock,
  ToolDefinition,
  ToolParameter,
  UpdatePageInput,
  UpdateSiteInput,
  VideoBlock,
} from '@revealui/contracts';

export type {
  // Core Contracts - from @revealui/contracts/admin
  AccessArgs,
  AccessFunction,
  AccessResult,
  AfterChangeHookArgs,
  AfterReadHookArgs,
  ArrayField,
  AuthConfig,
  BeforeChangeHookArgs,
  BeforeValidateHookArgs,
  CollectionAccess,
  CollectionAccessConfig,
  CollectionAdminConfig,
  CollectionAfterChangeHook,
  CollectionAfterReadHook,
  CollectionBeforeChangeHook,
  CollectionBeforeReadHook,
  CollectionBeforeValidateHook,
  CollectionConfig,
  CollectionHooks,
  CollectionHooksConfig,
  CollectionLabels,
  CollectionStructure,
  Config,
  // User Contracts
  // CreateUserInput,
  CustomFieldTypeConfig,
  Field,
  FieldAccess,
  FieldAccessArgs,
  FieldAccessConfig,
  FieldAccessFunction,
  FieldAdminConfig,
  FieldHooksConfig,
  FieldOption,
  FieldStructure,
  FieldType,
  FieldValidateArgs,
  // FieldValidateFunction,
  GlobalAccess,
  GlobalAccessConfig,
  GlobalAdminConfig,
  GlobalConfig,
  GlobalHooks,
  GlobalHooksConfig,
  GlobalLabels,
  GlobalStructure,
  GlobalVersionsConfig,
  GroupField,
  NumberField,
  PluginFieldExtension,
  RelationshipField,
  RevealRequest,
  RevealUICollectionConfig,
  RevealUIExtensions,
  RevealUIGlobalConfig,
  RowField,
  SanitizedCollectionConfig,
  SanitizedConfig,
  SanitizedGlobalConfig,
  SelectField,
  // Session,
  TabDefinition,
  TabsField,
  TextField,
  TypedCollectionConfig,
  TypedGlobalConfig,
  // UpdateUserInput,
  UploadConfig,
  // User,
  // UserPreferences,
  // UserRole,
  // UserStatus,
  // UserType,
  ValidationResult,
  // VersionsConfig,
  Where,
} from '@revealui/contracts/admin';
