/**
 * Host local inference lifecycle (Ollama + Inference Snaps) + profile tiers.
 *
 * Catalog must lockstep `@revealui/ai` PRODUCT_INFERENCE_SNAP_CATALOG / US_ORIGIN
 * (boundary: harnesses cannot hard-require @revealui/ai — tested in
 * inference-service-snaps.test.ts).
 *
 * Profile JSON path matches `@revealui/ai` local-ai-profile.ts so
 * createLLMClientFromEnv can read it.
 */

import { execFile, spawn } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);

// ── Types ───────────────────────────────────────────────────────────

export interface OllamaStatus {
  installed: boolean;
  running: boolean;
  version: string | null;
}

export interface OllamaModel {
  name: string;
  size: string;
  modified: string;
}

export interface ModelPullResult {
  success: boolean;
  message: string;
}

export interface SnapStatus {
  installed: boolean;
  running: boolean;
  snapName: string;
  endpoint: string | null;
  version: string | null;
}

export interface SnapModel {
  name: string;
  description: string;
  installed: boolean;
}

export type LocalAiTier = 'idle' | 'daily' | 'snaps' | 'heavy';

export interface LocalAiProfile {
  tier: LocalAiTier;
  provider: 'ollama' | 'inference-snaps' | null;
  model: string | null;
  baseURL: string | null;
  ollamaModelsDir: string | null;
  keepAlive: string | null;
  updatedAt: string;
  note?: string;
}

export interface LocalAiProfileView extends LocalAiProfile {
  memAvailableGiB: number | null;
  ollamaRunning: boolean;
  snapsRunning: string[];
}

// ── Configuration ───────────────────────────────────────────────────

/**
 * Product install/list catalog (US-origin only).
 * Lockstep with packages/ai PRODUCT_INFERENCE_SNAP_CATALOG.
 */
export const PRODUCT_INFERENCE_SNAPS: ReadonlyArray<readonly [string, string]> = [
  ['nemotron-3-nano', 'NVIDIA (US) — general + tools; product default on capable hosts'],
  ['nemotron-3-nano-omni', 'NVIDIA (US) — multimodal (text/image/video/audio in)'],
  ['gemma4', 'Google (US) — general + vision + tools'],
  ['gemma3', 'Google (US) — general + vision; prefer 270m on low-RAM hosts'],
] as const;

const KNOWN_SNAPS = PRODUCT_INFERENCE_SNAPS;
const SNAP_IDS = PRODUCT_INFERENCE_SNAPS.map(([id]) => id);

const DEFAULT_DAILY_OLLAMA = 'gemma3:1b';
const DEFAULT_SNAPS_SNAP = 'gemma3';
const DEFAULT_HEAVY_SNAP = 'nemotron-3-nano';

function profilePath(): string {
  return (
    process.env.REVEALUI_INFERENCE_PROFILE_PATH ??
    join(homedir(), '.local', 'share', 'revealui', 'inference-profile.json')
  );
}

function activeEnvPath(): string {
  return join(homedir(), '.config', 'revealui', 'local-ai.active.env');
}

function hotOllamaDir(): string {
  return (
    process.env.OLLAMA_MODELS ??
    (existsSync('/mnt/studio/models/ollama')
      ? '/mnt/studio/models/ollama'
      : join(homedir(), '.ollama', 'models'))
  );
}

function emptyIdleProfile(): LocalAiProfile {
  return {
    tier: 'idle',
    provider: null,
    model: null,
    baseURL: null,
    ollamaModelsDir: hotOllamaDir(),
    keepAlive: '0',
    updatedAt: new Date().toISOString(),
    note: 'AI stopped — IDE/dev headroom',
  };
}

function saveProfile(profile: LocalAiProfile): void {
  const path = profilePath();
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${JSON.stringify(profile, null, 2)}\n`, 'utf8');

  const envPath = activeEnvPath();
  mkdirSync(dirname(envPath), { recursive: true });
  const lines = [
    `# generated by InferenceService.profileApply ${profile.updatedAt}`,
    `export REVEALUI_LOCAL_AI_TIER=${profile.tier}`,
  ];
  if (profile.ollamaModelsDir) lines.push(`export OLLAMA_MODELS=${profile.ollamaModelsDir}`);
  if (profile.keepAlive != null) lines.push(`export OLLAMA_KEEP_ALIVE=${profile.keepAlive}`);
  if (profile.provider) lines.push(`export LLM_PROVIDER=${profile.provider}`);
  else lines.push('unset LLM_PROVIDER');
  if (profile.model) lines.push(`export LLM_MODEL=${profile.model}`);
  else lines.push('unset LLM_MODEL');
  if (profile.provider === 'inference-snaps' && profile.baseURL) {
    lines.push(`export INFERENCE_SNAPS_BASE_URL=${profile.baseURL}`);
  } else {
    lines.push('unset INFERENCE_SNAPS_BASE_URL');
  }
  if (profile.provider === 'ollama' && profile.baseURL) {
    lines.push(`export OLLAMA_BASE_URL=${profile.baseURL}`);
  }
  writeFileSync(envPath, `${lines.join('\n')}\n`, 'utf8');
}

function loadProfile(): LocalAiProfile | null {
  try {
    const path = profilePath();
    if (!existsSync(path)) return null;
    return JSON.parse(readFileSync(path, 'utf8')) as LocalAiProfile;
  } catch {
    return null;
  }
}

// ── Helpers ─────────────────────────────────────────────────────────

async function commandExists(cmd: string): Promise<boolean> {
  try {
    await execFileAsync('which', [cmd]);
    return true;
  } catch {
    return false;
  }
}

const ALLOWED_COMMANDS = new Set(['ollama', 'snap', 'which', 'killall']);

async function run(cmd: string, args: string[]): Promise<{ stdout: string; stderr: string }> {
  if (!ALLOWED_COMMANDS.has(cmd)) {
    throw new Error(`Command not allowed: ${cmd}`);
  }
  return execFileAsync(cmd, args, { timeout: 30_000 });
}

function parseSnapOpenaiUrl(statusStdout: string): string | null {
  const match = statusStdout.match(/openai:\s*(\S+)/i);
  return match?.[1] ?? null;
}

function readMemAvailableGiB(): number | null {
  try {
    const text = readFileSync('/proc/meminfo', 'utf8');
    const line = text.split('\n').find((l) => l.startsWith('MemAvailable:'));
    if (!line) return null;
    const kb = Number.parseInt(line.replace(/\D+/g, ''), 10);
    if (!Number.isFinite(kb)) return null;
    return Math.round((kb / 1024 / 1024) * 10) / 10;
  } catch {
    return null;
  }
}

// ── Service ─────────────────────────────────────────────────────────

/**
 * Manages local inference engines (Ollama, Snaps) on the daemon host.
 */
export class InferenceService {
  async ollamaStatus(): Promise<OllamaStatus> {
    const installed = await commandExists('ollama');
    if (!installed) return { installed: false, running: false, version: null };

    let version: string | null = null;
    try {
      const { stdout } = await run('ollama', ['--version']);
      version = stdout.trim() || null;
    } catch {
      // ignore
    }

    let running = false;
    try {
      await run('ollama', ['list']);
      running = true;
    } catch {
      // not running
    }

    return { installed, running, version };
  }

  async ollamaModels(): Promise<OllamaModel[]> {
    const { stdout } = await run('ollama', ['list']);
    const models: OllamaModel[] = [];
    for (const line of stdout.split('\n').slice(1)) {
      const trimmed = line.trim();
      if (!trimmed) continue;
      const parts = trimmed.split(/\s+/);
      if (parts.length >= 3) {
        models.push({
          name: parts[0] ?? '',
          size: parts[2] ?? '',
          modified: parts.slice(3).join(' '),
        });
      }
    }
    return models;
  }

  async ollamaPull(modelName: string): Promise<ModelPullResult> {
    if (!/^[\w./:@-]+$/.test(modelName)) {
      return { success: false, message: `Invalid model name: ${modelName}` };
    }
    try {
      const { stdout, stderr } = await execFileAsync('ollama', ['pull', modelName], {
        timeout: 600_000,
      });
      return { success: true, message: stdout || stderr };
    } catch (err) {
      return { success: false, message: err instanceof Error ? err.message : String(err) };
    }
  }

  async ollamaDelete(modelName: string): Promise<void> {
    if (!/^[\w./:@-]+$/.test(modelName)) {
      throw new Error(`Invalid model name: ${modelName}`);
    }
    await run('ollama', ['rm', modelName]);
  }

  async ollamaStart(): Promise<void> {
    const modelsDir = hotOllamaDir();
    const child = spawn('ollama', ['serve'], {
      stdio: 'ignore',
      detached: true,
      env: {
        ...process.env,
        OLLAMA_MODELS: modelsDir,
        OLLAMA_KEEP_ALIVE: process.env.OLLAMA_KEEP_ALIVE ?? '0',
        OLLAMA_MAX_LOADED_MODELS: process.env.OLLAMA_MAX_LOADED_MODELS ?? '1',
        OLLAMA_NUM_PARALLEL: process.env.OLLAMA_NUM_PARALLEL ?? '1',
      },
    });
    child.unref();
  }

  async ollamaStop(): Promise<void> {
    try {
      await run('killall', ['ollama']);
    } catch {
      // no process
    }
  }

  async snapList(): Promise<SnapModel[]> {
    const results: SnapModel[] = [];
    for (const [name, description] of KNOWN_SNAPS) {
      let installed = false;
      try {
        await run('snap', ['list', name]);
        installed = true;
      } catch {
        // not installed
      }
      results.push({ name, description, installed });
    }
    return results;
  }

  async snapStatus(snapName: string): Promise<SnapStatus> {
    if (!KNOWN_SNAPS.some(([name]) => name === snapName)) {
      throw new Error(`Unknown inference snap: ${snapName}`);
    }

    let installed = false;
    let version: string | null = null;
    try {
      const { stdout } = await run('snap', ['list', snapName]);
      installed = true;
      const secondLine = stdout.split('\n')[1];
      if (secondLine) version = secondLine.split(/\s+/)[1] ?? null;
    } catch {
      return { installed: false, running: false, snapName, endpoint: null, version: null };
    }

    let running = false;
    let endpoint: string | null = null;
    try {
      const { stdout } = await run(snapName, ['status']);
      running = true;
      endpoint = parseSnapOpenaiUrl(stdout) ?? 'http://127.0.0.1:9090/v1';
    } catch {
      // not running
    }

    return { installed, running, snapName, endpoint, version };
  }

  async snapInstall(snapName: string): Promise<ModelPullResult> {
    if (!KNOWN_SNAPS.some(([name]) => name === snapName)) {
      throw new Error(`Unknown inference snap: ${snapName}`);
    }
    try {
      const { stdout, stderr } = await execFileAsync('sudo', ['snap', 'install', snapName], {
        timeout: 300_000,
      });
      return { success: true, message: stdout || stderr };
    } catch (err) {
      return { success: false, message: err instanceof Error ? err.message : String(err) };
    }
  }

  async snapRemove(snapName: string): Promise<void> {
    if (!KNOWN_SNAPS.some(([name]) => name === snapName)) {
      throw new Error(`Unknown inference snap: ${snapName}`);
    }
    await execFileAsync('sudo', ['snap', 'remove', snapName], { timeout: 60_000 });
  }

  private async stopAllProductSnaps(opts: { disableBoot: boolean }): Promise<void> {
    for (const id of SNAP_IDS) {
      try {
        await run('snap', ['list', id]);
      } catch {
        continue;
      }
      try {
        const args = opts.disableBoot ? ['snap', 'stop', '--disable', id] : ['snap', 'stop', id];
        await execFileAsync('sudo', args, { timeout: 60_000 });
      } catch {
        // best-effort
      }
    }
  }

  async profileGet(): Promise<LocalAiProfileView> {
    const stored = loadProfile() ?? emptyIdleProfile();
    const ollama = await this.ollamaStatus();
    const snapsRunning: string[] = [];
    for (const id of SNAP_IDS) {
      try {
        const st = await this.snapStatus(id);
        if (st.running) snapsRunning.push(id);
      } catch {
        // ignore
      }
    }
    return {
      ...stored,
      memAvailableGiB: readMemAvailableGiB(),
      ollamaRunning: ollama.running,
      snapsRunning,
    };
  }

  async profileApply(tier: LocalAiTier): Promise<LocalAiProfileView> {
    let profile = emptyIdleProfile();
    profile.tier = tier;
    profile.updatedAt = new Date().toISOString();

    if (tier === 'idle') {
      await this.ollamaStop();
      await this.stopAllProductSnaps({ disableBoot: true });
      profile.note = 'AI stopped — IDE/dev headroom';
    } else if (tier === 'daily') {
      await this.stopAllProductSnaps({ disableBoot: true });
      await this.ollamaStart();
      for (let i = 0; i < 20; i++) {
        if ((await this.ollamaStatus()).running) break;
        await new Promise((r) => setTimeout(r, 250));
      }
      profile = {
        ...profile,
        tier: 'daily',
        provider: 'ollama',
        model: DEFAULT_DAILY_OLLAMA,
        baseURL: 'http://127.0.0.1:11434',
        keepAlive: '0',
        note: 'Ollama small US model; weights unload after each request',
      };
    } else if (tier === 'snaps') {
      await this.ollamaStop();
      const snapName = DEFAULT_SNAPS_SNAP;
      try {
        await run('snap', ['list', snapName]);
      } catch {
        throw new Error(
          `Snap ${snapName} is not installed. Install: sudo snap install ${snapName}`,
        );
      }
      try {
        await execFileAsync('sudo', ['snap', 'start', '--enable', snapName], { timeout: 60_000 });
      } catch {
        await execFileAsync('sudo', ['snap', 'start', snapName], { timeout: 60_000 }).catch(
          () => undefined,
        );
      }
      if (snapName === 'gemma3') {
        try {
          await execFileAsync(
            'bash',
            ['-c', 'yes | sudo timeout 45 gemma3 use-model 270m || true'],
            { timeout: 60_000 },
          );
        } catch {
          // optional
        }
      }
      let endpoint: string | null = null;
      for (let i = 0; i < 30; i++) {
        const st = await this.snapStatus(snapName);
        if (st.running && st.endpoint) {
          endpoint = st.endpoint;
          break;
        }
        await new Promise((r) => setTimeout(r, 500));
      }
      profile = {
        ...profile,
        tier: 'snaps',
        provider: 'inference-snaps',
        model: snapName,
        baseURL: endpoint,
        keepAlive: null,
        note: 'Inference Snap product path (US-origin allowlist)',
      };
    } else if (tier === 'heavy') {
      await this.ollamaStop();
      for (const id of SNAP_IDS) {
        if (id === DEFAULT_HEAVY_SNAP) continue;
        try {
          await execFileAsync('sudo', ['snap', 'stop', '--disable', id], { timeout: 60_000 });
        } catch {
          // ignore
        }
      }
      const snapName = DEFAULT_HEAVY_SNAP;
      try {
        await run('snap', ['list', snapName]);
      } catch {
        throw new Error(
          `Snap ${snapName} is not installed. Install: sudo snap install ${snapName}`,
        );
      }
      try {
        await execFileAsync('sudo', ['snap', 'start', '--enable', snapName], { timeout: 60_000 });
      } catch {
        await execFileAsync('sudo', ['snap', 'start', snapName], { timeout: 60_000 }).catch(
          () => undefined,
        );
      }
      let endpoint: string | null = null;
      for (let i = 0; i < 30; i++) {
        const st = await this.snapStatus(snapName);
        if (st.running && st.endpoint) {
          endpoint = st.endpoint;
          break;
        }
        await new Promise((r) => setTimeout(r, 500));
      }
      const mem = readMemAvailableGiB();
      profile = {
        ...profile,
        tier: 'heavy',
        provider: 'inference-snaps',
        model: snapName,
        baseURL: endpoint,
        keepAlive: null,
        note:
          mem != null && mem < 6
            ? `Heavy snap on ~${mem}Gi available RAM — expect thrash; prefer daily/snaps for IDE work`
            : 'Heavy snap — needs substantial RAM',
      };
    }

    saveProfile(profile);
    return this.profileGet();
  }
}
