import {
  API_HEALTH,
  BLOG_CHROME,
  CLAIMS_LEDGER,
  LEGAL_COOKIES_CONTENT,
  LEGAL_HIPAA_CONTENT,
  LEGAL_PRIVACY_CONTENT,
  LEGAL_REFUND_CONTENT,
  LEGAL_SECURITY_CONTENT,
  LEGAL_SLA_CONTENT,
  LEGAL_SUBPROCESSORS_CONTENT,
  LEGAL_SUPPORT_CONTENT,
  LEGAL_TERMS_CONTENT,
  LICENSE_MIT,
  NAV_CONTENT,
  NOT_FOUND_CONTENT,
  OPEN_WEIGHT,
  SELF_HOST,
  STATUS_CONTENT,
  THIS_SITE,
} from './shared-refs.js';
import type { ClaimEntry } from './types.js';

export const claimsPart8: readonly ClaimEntry[] = [
  {
    file: 'nav.ts',
    exportPath: 'FOOTER_TAGLINE',
    text: 'Agentic business runtime. People, content, offers, payments, and agents, pre-wired, open source, and ready to deploy.',
    evidence: [NAV_CONTENT, LICENSE_MIT, THIS_SITE],
  },
  {
    file: 'nav.ts',
    exportPath: 'FOOTER_SOLO_OPERATOR_NOTE',
    text: 'Built by one engineer in Tennessee. See our SLA for response times.',
    evidence: [NAV_CONTENT, LEGAL_SLA_CONTENT],
  },
  {
    file: 'nav.ts',
    exportPath: 'FOOTER_CLAIMS_LEDGER_NOTE.prefix',
    text: 'Every sentence on this site is indexed against the code.',
    evidence: [
      CLAIMS_LEDGER,
      NAV_CONTENT,
      {
        kind: 'test',
        ref: 'apps/marketing/app/content/__tests__/content.test.ts#indexes leftover chrome modules on the claims-evidence gate',
        note: 'nav/status/blog/not-found stay on COVERED_FILES so leftover chrome cannot drift unsigned',
      },
      {
        kind: 'test',
        ref: 'apps/marketing/app/routes/__tests__/ClaimsPage.test.tsx#renders a section for every covered file',
        note: 'public /claims ledger renders one section per covered module including nav.ts',
      },
    ],
  },
  {
    file: 'nav.ts',
    exportPath: 'FOOTER_NEWSLETTER.body',
    text: 'Product updates and engineering insights. No spam.',
    evidence: [NAV_CONTENT],
  },
  {
    file: 'status.ts',
    exportPath: 'STATUS_HERO.subtitle',
    text: 'Live probe and link surface for the four RevealUI properties.',
    evidence: [STATUS_CONTENT, THIS_SITE],
  },
  {
    file: 'status.ts',
    exportPath: 'STATUS_SUMMARY.pending',
    text: 'Checking current status...',
    evidence: [STATUS_CONTENT],
  },
  {
    file: 'status.ts',
    exportPath: 'STATUS_SUMMARY.down',
    text: 'Some surfaces are not responding',
    evidence: [STATUS_CONTENT],
  },
  {
    file: 'status.ts',
    exportPath: 'STATUS_SUMMARY.up',
    text: 'All probed surfaces are operational',
    evidence: [STATUS_CONTENT, API_HEALTH],
  },
  {
    file: 'status.ts',
    exportPath: 'STATUS_SUMMARY.body',
    text: 'This page probes the API health endpoint in your browser when you load it. It reflects what your network sees right now, not a separate uptime service. Solo-operator company: we do not run 24×7 manned monitoring you can subscribe to.',
    evidence: [STATUS_CONTENT, API_HEALTH],
  },
  {
    file: 'status.ts',
    exportPath: 'STATUS_MONITOR.intro',
    text: 'RevealUI Studio is a solo-operator company. We run a single API health endpoint that this page probes when you load it. We do not currently offer email or SMS subscriptions for status changes. Honest answers about what we do and do not have:',
    evidence: [STATUS_CONTENT, API_HEALTH],
  },
  {
    file: 'status.ts',
    exportPath: 'STATUS_MONITOR.worksToday',
    text: 'The probe above reflects current API reachability from your browser. Vercel runs its own platform health checks; we receive alerts when their checks fail.',
    evidence: [STATUS_CONTENT, API_HEALTH],
  },
  {
    file: 'status.ts',
    exportPath: 'STATUS_MONITOR.watching',
    text: 'A separate public uptime history with subscribable incident channels is queued for after we have paying customers. Until then, this live-probe page is the honest interim.',
    evidence: [STATUS_CONTENT],
  },
  {
    file: 'status.ts',
    exportPath: 'STATUS_MONITOR.missing',
    text: 'A 24×7 on-call rotation. Multi-region failover. A separate paid status page domain. We will publish these on this page when they ship, not before.',
    evidence: [STATUS_CONTENT],
  },
  {
    file: 'status.ts',
    exportPath: 'STATUS_INCIDENTS.body',
    text: 'No incidents have been disclosed here yet. When one occurs, we will post a brief notice with timestamps, impact, root cause (once known), and remediation. We commit to disclosing real incidents rather than hiding them.',
    evidence: [STATUS_CONTENT],
  },
  {
    file: 'status.ts',
    exportPath: 'STATUS_OUTAGE.heading',
    text: 'Are you experiencing an outage?',
    evidence: [STATUS_CONTENT],
  },
  {
    file: 'status.ts',
    exportPath: 'STATUS_OUTAGE.body',
    text: 'If this page shows all surfaces operational but you are still seeing issues, the problem is probably between your network and ours, or specific to a feature this page does not probe yet. Email support with the URL you hit, the time you first saw the issue, and any error message. We treat outage reports as higher priority than standard support email.',
    evidence: [STATUS_CONTENT],
  },
  {
    file: 'status.ts',
    exportPath: 'STATUS_OUTAGE.security',
    text: 'For confirmed security incidents, follow the security policy instead. That channel has different SLAs.',
    evidence: [STATUS_CONTENT, LEGAL_SECURITY_CONTENT, LEGAL_SLA_CONTENT],
  },
  {
    file: 'status.ts',
    exportPath: 'STATUS_BADGES.self',
    text: 'Operational (you are here)',
    evidence: [STATUS_CONTENT, THIS_SITE],
  },
  {
    file: 'blog.ts',
    exportPath: 'BLOG_INDEX.subtitle',
    text: 'Updates, guides, and insights from the RevealUI team.',
    evidence: [BLOG_CHROME],
  },
  {
    file: 'blog.ts',
    exportPath: 'BLOG_INDEX.empty',
    text: 'No posts yet. Check back soon for updates from the RevealUI team.',
    evidence: [BLOG_CHROME],
  },
  {
    file: 'blog.ts',
    exportPath: 'BLOG_INDEX.notifyHeading',
    text: 'Get notified when we publish',
    evidence: [BLOG_CHROME],
  },
  {
    file: 'blog.ts',
    exportPath: 'BLOG_INDEX.notifyBody',
    text: 'Engineering insights, product updates, and launch announcements. No spam.',
    evidence: [BLOG_CHROME],
  },
  {
    file: 'not-found.ts',
    exportPath: 'NOT_FOUND.body',
    text: "The page you're looking for doesn't exist or has moved.",
    evidence: [NOT_FOUND_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_META.notice.title',
    text: 'Status: drafted in good faith, pending counsel review',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_META.notice.body',
    text: 'This page describes our actual privacy practices today. The wording has not yet been reviewed by an attorney; we disclose this rather than hide it. The substance will not change after review. Only the wording may tighten. Privacy questions or data-rights requests in the meantime:',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/terms.ts',
    exportPath: 'TERMS_META.notice.title',
    text: 'Status: drafted in good faith, pending counsel review',
    evidence: [LEGAL_TERMS_CONTENT],
  },
  {
    file: 'legal/terms.ts',
    exportPath: 'TERMS_META.notice.body',
    text: 'This page describes our actual practices and commitments today. The wording has not yet been reviewed by an attorney; we disclose this rather than hide it. The substance will not change after review. Only the wording may tighten. Questions in the meantime?',
    evidence: [LEGAL_TERMS_CONTENT],
  },
  {
    file: 'legal/cookies.ts',
    exportPath: 'COOKIES_META.notice.title',
    text: 'Status: drafted in good faith, pending counsel review',
    evidence: [LEGAL_COOKIES_CONTENT],
  },
  {
    file: 'legal/cookies.ts',
    exportPath: 'COOKIES_META.notice.body',
    text: 'This page describes the cookies and similar technologies we actually use today. The wording has not yet been reviewed by an attorney. Questions:',
    evidence: [LEGAL_COOKIES_CONTENT],
  },
  {
    file: 'legal/hipaa.ts',
    exportPath: 'HIPAA_META.notice.body',
    text: 'This page does not claim that RevealUI is HIPAA certified. It describes the technical controls in the product and the contract steps that are still required. Counsel questions:',
    evidence: [LEGAL_HIPAA_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_META.notice.title',
    text: 'Safe-harbor commitment to good-faith researchers',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_META.notice.body',
    text: 'If you act in good faith and follow this policy, we will not pursue or support legal action against you for your security research. Email the security address to report a vulnerability. The machine-readable policy is at /.well-known/security.txt.',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_META.notice.title',
    text: 'One channel for direct support, three for community + docs',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_META.notice.body',
    text: 'The fastest path is to check the documentation first. For account-specific issues, billing, or anything sensitive, email support. We reply within 24 hours during business hours (Mon-Fri, U.S. Central), and within 4 hours any day for a critical issue. Full detail is on our SLA page.',
    evidence: [LEGAL_SUPPORT_CONTENT, LEGAL_SLA_CONTENT],
  },
  {
    file: 'legal/refund-policy.ts',
    exportPath: 'REFUND_POLICY_META.notice.body',
    text: 'First purchase, monthly or annual, and Pro Perpetual, gets a full refund within 14 days of the first paid charge, no questions asked. After 14 days there is no prorate. Details below.',
    evidence: [LEGAL_REFUND_CONTENT],
  },
  {
    file: 'legal/sla.ts',
    exportPath: 'SLA_META.notice.body',
    text: 'We respond within 24 hours during U.S. business hours, and within 4 hours for anything critical. Our license and download infrastructure targets 99% monthly uptime. Live status is always at revealui.com/status.',
    evidence: [LEGAL_SLA_CONTENT, STATUS_CONTENT],
  },
  {
    file: 'legal/subprocessors.ts',
    exportPath: 'SUBPROCESSORS_META.notice.title',
    text: 'Dated subprocessor registry, updated before changes ship',
    evidence: [LEGAL_SUBPROCESSORS_CONTENT],
  },
  {
    file: 'legal/subprocessors.ts',
    exportPath: 'SUBPROCESSORS_META.notice.body',
    text: 'We commit to updating this page before adding a new subprocessor, not after. Every entry in the table below is accurate as of the date in the header. There is no subscribe-to-changes channel yet (queued for after we have customers); for now, watch this file in the repository or email support to be notified by email.',
    evidence: [LEGAL_SUBPROCESSORS_CONTENT],
  },
  {
    file: 'legal/subprocessors.ts',
    exportPath: 'SUBPROCESSORS_NOT.heading',
    text: 'What is not a subprocessor',
    evidence: [LEGAL_SUBPROCESSORS_CONTENT],
  },
  {
    file: 'legal/subprocessors.ts',
    exportPath: 'SUBPROCESSORS_QUESTIONS.heading',
    text: 'Questions about a specific subprocessor',
    evidence: [LEGAL_SUBPROCESSORS_CONTENT],
  },
  {
    file: 'legal/subprocessors.ts',
    exportPath: 'SUBPROCESSORS_CHANGELOG_INTRO.body',
    text: 'Append-only. Every change to the table above lands here in the same commit. Most recent first.',
    evidence: [LEGAL_SUBPROCESSORS_CONTENT],
  },
  {
    file: 'legal/subprocessors.ts',
    exportPath: 'SUBPROCESSORS_QUESTIONS.privacy',
    text: 'For privacy-specific questions (data rights, DSR requests, GDPR / CCPA), see the Privacy Policy.',
    evidence: [LEGAL_SUBPROCESSORS_CONTENT, LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/subprocessors.ts',
    exportPath: 'SUBPROCESSORS_NOT.preamble',
    text: 'The following are NOT customer-data subprocessors and do not appear in the table:',
    evidence: [LEGAL_SUBPROCESSORS_CONTENT],
  },
  {
    file: 'legal/subprocessors.ts',
    exportPath: 'SUBPROCESSORS_NOT.items[0].body',
    text: 'we use it for source code hosting only; customer data does not flow through GitHub.',
    evidence: [LEGAL_SUBPROCESSORS_CONTENT],
  },
  {
    file: 'legal/subprocessors.ts',
    exportPath: 'SUBPROCESSORS_NOT.items[1].body',
    text: 'we publish our packages there; customer data does not flow through npm.',
    evidence: [LEGAL_SUBPROCESSORS_CONTENT],
  },
  {
    file: 'legal/subprocessors.ts',
    exportPath: 'SUBPROCESSORS_NOT.items[2].body',
    text: "Ollama and Inference Snaps run on the customer's own infrastructure, not ours; data does not leave the customer boundary.",
    evidence: [LEGAL_SUBPROCESSORS_CONTENT, OPEN_WEIGHT, SELF_HOST],
  },
  {
    file: 'legal/subprocessors.ts',
    exportPath: 'SUBPROCESSORS_NOT.items[3].body',
    text: "the customer configures themselves (a customer's own Sentry account, their own analytics, their own LLM provider): those are the customer's subprocessors, not ours.",
    evidence: [LEGAL_SUBPROCESSORS_CONTENT],
  },
];
