import {
  AGENT_ROUTES,
  AUDIT_PUBLIC_KEY_ROUTE,
  AUDIT_SIGNING,
  AUDIT_SIGNING_TEST,
  AUTH_SESSIONS,
  BILLING,
  CI_GATE,
  CLI_CREATE,
  COLLECTIONS,
  COMMERCIAL_POLICY,
  DEPLOY_TARGETS,
  DOCS,
  INFRA_COST_ESTIMATE,
  LICENSE_MIT,
  LICENSE_SPLIT,
  MCP_CONTENT,
  MCP_RESOURCE_DEFAULT,
  MEMORY,
  NO_TELEMETRY,
  OPEN_STANDARDS,
  OPEN_WEIGHT,
  PERPETUAL,
  POSTGRES,
  PRICING_FALLBACKS,
  PROVIDERS,
  RBAC_ABAC,
  RECONCILE,
  REPO,
  ROADMAP,
  SELF_HOST,
  THIS_SITE,
  TIER_GATES,
  TIER_LIMITS,
  TRIAL,
  WEBHOOKS,
  X402,
} from './shared-refs.js';
import type { ClaimEntry } from './types.js';

export const claimsPart1: readonly ClaimEntry[] = [
  {
    file: 'site.ts',
    exportPath: 'SITE.brandTagline',
    text: 'The open runtime for businesses that run their own AI.',
    evidence: [LICENSE_MIT, OPEN_WEIGHT, SELF_HOST],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_HERO.eyebrow',
    proofGrade: 'behavior',
    text: 'Open source. Self-hostable.',
    evidence: [LICENSE_MIT, SELF_HOST],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_HERO.h1',
    proofGrade: 'outcome',
    text: 'Build it once. Every product after starts ahead.',
    evidence: [
      {
        kind: 'code',
        ref: 'packages',
        note: 'five primitives implemented once and reused across products on one monorepo runtime',
      },
      {
        kind: 'test',
        ref: 'apps/marketing/app/__tests__/hero-variant.test.ts#serves the L1 default hero by default',
        note: 'locks the L1 H1 string as the homepage default after owner ruling 2026-07-29',
      },
      LICENSE_MIT,
      SELF_HOST,
    ],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_HERO_OWNERSHIP.h1',
    proofGrade: 'outcome',
    text: 'Run your whole business on one runtime you own.',
    evidence: [
      {
        kind: 'code',
        ref: 'packages',
        note: 'prior default H1 retained as ?hero=ownership rollback preview',
      },
      {
        kind: 'test',
        ref: 'apps/marketing/app/__tests__/hero-variant.test.ts#serves the ownership rollback for ?hero=ownership',
        note: 'locks ownership H1 as optional rollback variant',
      },
      LICENSE_MIT,
      SELF_HOST,
    ],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_HERO.subtitle.sentence1',
    proofGrade: 'outcome',
    text: 'RevealUI is the self-hosted runtime where your business and the AI agents that run it live under one roof.',
    evidence: [SELF_HOST, AGENT_ROUTES, TIER_GATES],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_HERO.subtitle.sentence2',
    proofGrade: 'outcome',
    text: 'Every agent is a governed and audited user that lives on your infrastructure.',
    evidence: [
      AGENT_ROUTES,
      RBAC_ABAC,
      TIER_GATES,
      AUDIT_SIGNING,
      AUDIT_SIGNING_TEST,
      AUDIT_PUBLIC_KEY_ROUTE,
      {
        kind: 'code',
        ref: 'packages/auth/src/server/auth.ts',
        note: 'agents authenticate as first-class principals under the same session/auth surface as human users',
      },
      {
        kind: 'test',
        ref: 'packages/core/src/collections/operations/__tests__/access-enforcement.test.ts#authenticated() allows when user is present',
        note: 'identity-gated access: a principal must authenticate before protected operations; agents use the same gate surface as human users',
      },
      {
        kind: 'code',
        ref: 'scripts/validate/agent-audit-chokepoints.ts',
        note: 'CI enforcer: agent execution chokepoints emit audit (GAP-355 Stage 5/6)',
      },
      SELF_HOST,
    ],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_HERO.subtitle.support',
    proofGrade: 'behavior',
    text: 'It runs on any AI provider you choose.',
    evidence: [PROVIDERS, OPEN_WEIGHT],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_HERO_FOUNDATION.h1',
    proofGrade: 'outcome',
    text: 'The foundation your business runs on.',
    evidence: [
      {
        kind: 'code',
        ref: 'packages',
        note: 'sanctioned A/B variant of HOME_HERO.h1; same grounding',
      },
    ],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_HERO_L2.h1',
    proofGrade: 'outcome',
    text: 'Ship your next product on the work your last one finished.',
    evidence: [
      {
        kind: 'code',
        ref: 'packages',
        note: 'corpus L2 leverage-frame A/B (06-copy-corpus §4.1); owner go 2026-07-31 via ?hero=l2, not default traffic',
      },
      {
        kind: 'test',
        ref: 'apps/marketing/app/__tests__/hero-variant.test.ts#serves the L2 leverage-frame for ?hero=l2',
        note: 'locks L2 H1 as optional experiment variant',
      },
      LICENSE_MIT,
      SELF_HOST,
    ],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_PROBLEM.heading',
    proofGrade: 'outcome',
    text: 'Tired of tools that don’t talk — and agents you can’t audit?',
    evidence: [
      {
        kind: 'code',
        ref: 'packages',
        note: 'framing sentence; the three-path comparison below carries the claims',
      },
    ],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_PROBLEM.body',
    proofGrade: 'outcome',
    text: 'Teams either stitch a vendor for each slice, or start with agents and rebuild the rest. RevealUI is one self-hosted runtime for the business and the agents that run it.',
    evidence: [AUTH_SESSIONS, COLLECTIONS, BILLING, LICENSE_MIT],
  },
  // pathBlurbs claims retired (GAP-480 landing de-dupe): blurbs removed from
  // the Problem band; body + matrix remain the single comparison device.
  {
    file: 'home.ts',
    exportPath: 'HOME_PROBLEM.rows[0].sprawl',
    proofGrade: 'path',
    text: 'A separate auth product, priced per seat',
    evidence: [
      {
        kind: 'url',
        ref: 'https://revealui.com/pricing',
        note: 'competitor-column framing; cost detail lives on the pricing page',
      },
    ],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_PROBLEM.rows[0].revealui',
    proofGrade: 'behavior',
    text: 'Sign-in, roles, and policies built in',
    evidence: [AUTH_SESSIONS, RBAC_ABAC],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_PROBLEM.rows[1].sprawl',
    proofGrade: 'path',
    text: 'A CMS plus a team to wire it',
    evidence: [
      {
        kind: 'url',
        ref: 'https://revealui.com/pricing',
        note: 'competitor-column framing; cost detail lives on the pricing page',
      },
    ],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_PROBLEM.rows[1].revealui',
    proofGrade: 'behavior',
    text: 'Your content model, with admin UI and API',
    evidence: [COLLECTIONS, OPEN_STANDARDS],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_PROBLEM.rows[2].revealui',
    proofGrade: 'behavior',
    text: 'Test-mode checkout, subscriptions, and webhook handling',
    evidence: [BILLING, WEBHOOKS, RECONCILE],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_PROBLEM.rows[3].revealui',
    proofGrade: 'behavior',
    text: 'Agents use the same data and gates as your team',
    evidence: [MCP_CONTENT, MCP_RESOURCE_DEFAULT],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_PROBLEM.footnote',
    proofGrade: 'behavior',
    text: 'Capability only. Pricing is on the pricing page (interpolated: Pro price from pricing-fallbacks). Vercel, Cloudflare, and Fly are deploy targets, not competitors.',
    match: 'path',
    evidence: [PRICING_FALLBACKS, DEPLOY_TARGETS],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_DEMO.heading',
    proofGrade: 'outcome',
    text: 'From one command to a running stack in about a minute.',
    evidence: [CLI_CREATE],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_DEMO.body',
    proofGrade: 'outcome',
    text: 'Install on your machine. Take a test payment. Connect an agent to the same data your admin already uses.',
    evidence: [CLI_CREATE, BILLING, MCP_CONTENT],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_DEMO.mockupCaption.prefix',
    proofGrade: 'path',
    text: 'Live admin chrome composed from',
    evidence: [
      {
        kind: 'code',
        ref: 'apps/marketing/app/components/landing/ProductFrame.tsx',
        note: 'composed from StatusDot/VerdictChip, not a screenshot',
      },
    ],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_DEMO.mockupCaption.suffix',
    proofGrade: 'path',
    text: 'components. The three beats are the local install path.',
    evidence: [CLI_CREATE],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_DEMO.beats[0].body',
    proofGrade: 'behavior',
    text: 'One command. Sign-in, content, admin, billing, and agent tooling run locally.',
    evidence: [CLI_CREATE, AUTH_SESSIONS, WEBHOOKS, MCP_CONTENT],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_DEMO.beats[1].title',
    proofGrade: 'behavior',
    text: 'Customer flow, end to end.',
    evidence: [BILLING],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_DEMO.beats[1].body',
    proofGrade: 'behavior',
    text: 'A user signs up, picks a plan, and test-mode checkout completes. Switch to live mode when you take real money.',
    evidence: [
      AUTH_SESSIONS,
      BILLING,
      {
        kind: 'code',
        ref: 'apps/server/src/lib/validate-startup.ts',
        note: 'STRIPE_LIVE_MODE flip validated at boot',
      },
    ],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_DEMO.beats[2].body',
    proofGrade: 'behavior',
    text: 'Connect a model. Agents use the same content, sign-in, and plan rules as your team.',
    evidence: [PROVIDERS, MCP_CONTENT, TIER_GATES],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_FAQ.items[0].answer',
    proofGrade: 'behavior',
    text: 'No. You keep your data in plain Postgres, your code in your repo, and your deploy on infrastructure you choose. Open standards throughout. RevealUI is the runtime, not the prison. Details live in the docs.',
    evidence: [OPEN_STANDARDS, POSTGRES, SELF_HOST],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_FAQ.items[1].answer',
    proofGrade: 'behavior',
    text: 'Changes clear automated tests and security checks before they land. This site and the agency site at revealuistudio.com both run on RevealUI in production today.',
    evidence: [CI_GATE, THIS_SITE],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_FAQ.items[2].question',
    proofGrade: 'path',
    text: 'How is this different from stitching separate tools together?',
    evidence: [
      { kind: 'code', ref: 'packages', note: 'question copy; the answer carries the claims' },
    ],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_FAQ.items[2].answer',
    proofGrade: 'outcome',
    text: 'Each vendor covers one slice. RevealUI is the whole runtime: people, content, billing, admin, and agents, self-hosted at all tiers. Deploy targets such as Vercel, Cloudflare, and Fly are places it runs, not competitors.',
    evidence: [AUTH_SESSIONS, COLLECTIONS, BILLING, AGENT_ROUTES, DEPLOY_TARGETS],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_FAQ.items[3].answer',
    proofGrade: 'behavior',
    text: 'Yes. Most packages are MIT forever. A small Pro set is Fair Source and converts to MIT two years after each release. Self-host the full stack on your infrastructure at any tier. License detail is on the Fair Source page.',
    evidence: [LICENSE_SPLIT, LICENSE_MIT, SELF_HOST, POSTGRES],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_FAQ.items[4].question',
    proofGrade: 'path',
    text: 'What does agent-native mean for my product?',
    evidence: [
      {
        kind: 'code',
        ref: 'packages/mcp/src',
        note: 'question copy; the answer carries the claims',
      },
    ],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_FAQ.items[4].answer',
    proofGrade: 'behavior',
    text: 'Agents sign in like users and face the same plan rules. They work on your content through the same APIs your app uses. How the wire protocol works is covered in the docs.',
    evidence: [TIER_GATES, MCP_CONTENT, MCP_RESOURCE_DEFAULT, OPEN_STANDARDS],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_FAQ.items[5].question',
    proofGrade: 'path',
    text: 'How does AI inference work?',
    evidence: [OPEN_WEIGHT],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_FAQ.items[5].answer',
    proofGrade: 'behavior',
    text: 'By default, agents run on an open-weight model on infrastructure you own. Add Claude, GPT, or another provider when you choose. The local AI page walks through the full path.',
    evidence: [OPEN_WEIGHT, PROVIDERS],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_FAQ.items[6].question',
    proofGrade: 'path',
    text: 'How do agent payments work?',
    evidence: [X402],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_FAQ.items[6].answer',
    proofGrade: 'behavior',
    text: 'RevealUI speaks the HTTP 402 payment protocol so agents can pay over standard HTTP. Payment rails are still in development. See the agents section on the pricing page for current status.',
    evidence: [X402],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_GET_STARTED.heading',
    proofGrade: 'outcome',
    text: 'Start on your machine today.',
    evidence: [CLI_CREATE],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_GET_STARTED.body',
    proofGrade: 'outcome',
    text: 'Install with npx create-revealui@latest, a public GitHub template (starter, basic-blog, portfolio, or e-commerce), or the live Apify actor (pay-per-event; receipt verification is $0.00001, not free).',
    evidence: [
      CLI_CREATE,
      {
        kind: 'code',
        ref: 'apps/server/src/lib/validate-startup.ts',
        note: 'live-mode flip validated at boot',
      },
    ],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_GET_STARTED.cli.caption',
    proofGrade: 'behavior',
    text: 'Local stack in about a minute. No credit card.',
    evidence: [
      CLI_CREATE,
      {
        kind: 'code',
        ref: 'apps/admin/src/app/api/auth/sign-up/route.ts',
        note: 'signup takes no payment method',
      },
    ],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_GET_STARTED.newsletter.label',
    proofGrade: 'path',
    text: 'Not ready to start? Get product updates when they ship.',
    evidence: [
      {
        kind: 'code',
        ref: 'apps/server/src/routes/waitlist.ts',
        note: 'newsletter capture endpoint',
      },
    ],
  },
  {
    file: 'primitives.ts',
    exportPath: 'HOME_PRIMITIVES_SECTION.eyebrow',
    proofGrade: 'behavior',
    text: 'Five primitives. One login.',
    evidence: [
      AUTH_SESSIONS,
      {
        kind: 'code',
        ref: 'packages/engines/src',
        note: 'the five business primitives behind one session',
      },
    ],
  },
  {
    file: 'primitives.ts',
    exportPath: 'HOME_PRIMITIVES_SECTION.heading',
    proofGrade: 'outcome',
    text: 'The five things every business runs on.',
    evidence: [
      {
        kind: 'code',
        ref: 'packages/engines/src',
        note: 'people, content, offers, payments, agents',
      },
    ],
  },
  {
    file: 'primitives.ts',
    exportPath: 'HOME_PRIMITIVES_SECTION.body',
    proofGrade: 'outcome',
    text: 'Each one ships ready for your team and for agents. One login covers the whole set.',
    evidence: [OPEN_STANDARDS, COLLECTIONS, AGENT_ROUTES],
  },
  {
    file: 'primitives.ts',
    exportPath: 'HOME_PRIMITIVES_SECTION.docsLink.label',
    proofGrade: 'path',
    text: 'See the primitive reference →',
    evidence: [DOCS],
  },
  {
    file: 'primitives.ts',
    exportPath: 'HOME_PRIMITIVES[0].body',
    proofGrade: 'outcome',
    text: 'Your team signs in once. Roles and policies decide who can do what.',
    evidence: [AUTH_SESSIONS, RBAC_ABAC],
  },
  {
    file: 'primitives.ts',
    exportPath: 'HOME_PRIMITIVES[1].body',
    proofGrade: 'outcome',
    text: 'Define your content once. The admin UI and API come with it.',
    evidence: [
      COLLECTIONS,
      { kind: 'code', ref: 'packages/core/src/richtext', note: 'Lexical rich text' },
    ],
  },
  {
    file: 'primitives.ts',
    exportPath: 'HOME_PRIMITIVES[2].body',
    proofGrade: 'outcome',
    text: 'Plans and feature gates decide what each customer and agent can use.',
    evidence: [
      TIER_GATES,
      TIER_LIMITS,
      { kind: 'code', ref: 'packages/core/src/features.ts', note: 'tier feature matrix' },
    ],
  },
  {
    file: 'primitives.ts',
    exportPath: 'HOME_PRIMITIVES[3].body',
    proofGrade: 'behavior',
    text: 'Test-mode checkout and subscriptions ship ready, including webhooks. Go live when you take real money.',
    evidence: [BILLING, WEBHOOKS, RECONCILE],
  },
  {
    file: 'primitives.ts',
    exportPath: 'HOME_PRIMITIVES[4].body',
    proofGrade: 'outcome',
    text: 'Agents run on models you host by default. Add a hosted provider when you choose.',
    evidence: [OPEN_WEIGHT, PROVIDERS],
  },
  {
    file: 'proof.ts',
    exportPath: 'PROOF_SECTION.heading',
    proofGrade: 'outcome',
    text: 'Read the code before you build on it.',
    evidence: [REPO],
  },
  {
    file: 'proof.ts',
    exportPath: 'PROOF_SECTION.body',
    proofGrade: 'behavior',
    text: 'The whole runtime lives in a public repo under an open license. Inspect it, run it, or fork it before you commit.',
    evidence: [REPO, LICENSE_MIT],
  },
  {
    file: 'proof.ts',
    exportPath: 'PROOF_TRUST.body',
    proofGrade: 'behavior',
    text: 'Your security team can read the full source. The runtime is open source, MIT or Fair Source, in the public repo. There is no closed binary to explain when procurement asks.',
    evidence: [REPO, LICENSE_SPLIT],
  },
  {
    file: 'proof.ts',
    exportPath: 'PROOF_TRUST.changelogCta.label',
    proofGrade: 'path',
    text: 'See what shipped this month →',
    evidence: [
      { kind: 'url', ref: 'https://github.com/RevealUIStudio/revealui/blob/main/CHANGELOG.md' },
    ],
  },
  {
    file: 'proof.ts',
    exportPath: 'LIVE_METRICS.heading',
    proofGrade: 'behavior',
    text: 'Every number here is pinned to the codebase.',
    evidence: [LICENSE_SPLIT],
  },
  {
    file: 'proof.ts',
    exportPath: 'LIVE_METRICS.body',
    proofGrade: 'behavior',
    text: 'These counts are checked on each pull request. If the code changes and a number drifts, the build fails before it can ship.',
    evidence: [LICENSE_SPLIT, CI_GATE],
  },
  {
    file: 'proof.ts',
    exportPath: 'PROOF_DEPLOYERS.heading',
    proofGrade: 'outcome',
    text: 'Built for people who deploy, not only demo.',
    evidence: [
      {
        kind: 'url',
        ref: 'https://revealuistudio.com',
        note: 'Studio/agency is the reference forward-deploy practice (ADR 2026-07-21)',
      },
    ],
  },
  {
    file: 'proof.ts',
    exportPath: 'PROOF_DEPLOYERS.body',
    proofGrade: 'outcome',
    text: 'Install yourself, hire Studio, or bring your own forward-deployed engineer. The outcome is the same: a self-hosted runtime on infrastructure you own.',
    evidence: [
      REPO,
      {
        kind: 'url',
        ref: 'https://revealuistudio.com',
        note: 'hire-us path; Fleet Stamp / Custom Build on agency services',
      },
      {
        kind: 'url',
        ref: 'https://revealui.com',
        note: 'self-install product path',
      },
    ],
  },
  {
    file: 'proof.ts',
    exportPath: 'PROOF_DEPLOYERS.foil',
    proofGrade: 'outcome',
    text: 'Cloud platforms rent you an outcome. A handoff leaves a runtime you run.',
    evidence: [
      REPO,
      {
        kind: 'url',
        ref: 'https://revealuistudio.com',
        note: 'positioning foil: customer-owned runtime after handoff, not a rented outcome',
      },
    ],
  },
  {
    file: 'pricing-teaser.ts',
    exportPath: 'PRICING_TEASER_SECTION.heading',
    proofGrade: 'outcome',
    text: 'Start free. Pay when you scale.',
    evidence: [LICENSE_MIT, TIER_LIMITS],
  },
  {
    file: 'pricing-teaser.ts',
    exportPath: 'PRICING_TEASER_SECTION.body',
    proofGrade: 'behavior',
    text: 'Self-host the open stack at no cost. Pro, Max, and Enterprise add agent capacity and support. Pro and Max include a 7-day free trial.',
    evidence: [LICENSE_MIT, TIER_GATES, TIER_LIMITS, TRIAL],
  },
  {
    file: 'pricing-teaser.ts',
    exportPath: 'PRICING_TEASER_TIERS[0].description',
    proofGrade: 'behavior',
    text: 'Run the open stack on your own infrastructure. Most packages stay MIT forever. No telemetry.',
    evidence: [LICENSE_SPLIT, NO_TELEMETRY],
  },
  {
    file: 'pricing-teaser.ts',
    exportPath: 'PRICING_TEASER_TIERS[0].features[3]',
    proofGrade: 'behavior',
    text: 'Bring your own model (open-weight default)',
    evidence: [OPEN_WEIGHT, PROVIDERS],
  },
  {
    file: 'pricing-teaser.ts',
    exportPath: 'PRICING_TEASER_TIERS[1].description',
    proofGrade: 'behavior',
    text: 'Add the AI layer, an agent task allowance, and priority support when you scale agents.',
    evidence: [TIER_GATES, TIER_LIMITS],
  },
  {
    file: 'pricing-teaser.ts',
    exportPath: 'PRICING_TEASER_TIERS[1].features[1]',
    proofGrade: 'behavior',
    text: '10,000 agent tasks / month included',
    evidence: [TIER_LIMITS],
  },
  {
    file: 'pricing-teaser.ts',
    exportPath: 'PRICING_TEASER_TIERS[1].features[2]',
    proofGrade: 'behavior',
    text: 'Pro AI features (agents, MCP, memory), beta in production',
    evidence: [
      TIER_GATES,
      MEMORY,
      { kind: 'code', ref: 'packages/mcp/src', note: 'MCP hypervisor + servers' },
    ],
  },
  {
    file: 'pricing-teaser.ts',
    exportPath: 'PRICING_TEASER_LINKS[0].description',
    proofGrade: 'behavior',
    text: 'Max adds unattended inference and RevKit environment provisioning.',
    evidence: [MEMORY, { kind: 'code', ref: 'packages/ai/src/inference', note: 'inference layer' }],
  },
  {
    file: 'pricing-teaser.ts',
    exportPath: 'PRICING_TEASER_LINKS[1].description',
    proofGrade: 'behavior',
    text: 'Enterprise is scoped with sales.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'pricing-teaser.ts',
    exportPath: 'PRICING_TEASER_FOOTER.caption.prefix',
    proofGrade: 'behavior',
    text: 'Deploys to Vercel, Cloudflare, Fly, Hetzner, or self-host.',
    evidence: [DEPLOY_TARGETS],
  },
  {
    file: 'pricing-teaser.ts',
    exportPath: 'PRICING_TEASER_FOOTER.caption.suffix',
    proofGrade: 'behavior',
    text: 'produces a standard Node bundle.',
    evidence: [{ kind: 'command', ref: 'pnpm build', note: 'turbo build to a plain Node bundle' }],
  },
  {
    file: 'products.ts',
    exportPath: 'PRODUCTS_PAGE_HERO.subtitle',
    proofGrade: 'outcome',
    text: 'License the self-hosted runtime. Free, Pro, Max, Enterprise inquire, and Pro Perpetual. Studio SKUs live on revealuistudio.com. Zero paying customers.',
    evidence: [REPO, SELF_HOST, TIER_GATES],
  },
  {
    file: 'products.ts',
    exportPath: 'PRODUCTS_FLAGSHIP.priceLabel',
    proofGrade: 'behavior',
    text: 'Free to self-host · Pro tier optional',
    evidence: [LICENSE_MIT, SELF_HOST, TIER_GATES],
  },
  {
    file: 'products.ts',
    exportPath: 'PRODUCTS_FLAGSHIP.tagline',
    proofGrade: 'outcome',
    text: 'The self-hosted business runtime',
    evidence: [AGENT_ROUTES, SELF_HOST],
  },
  {
    file: 'products.ts',
    exportPath: 'PRODUCTS_FLAGSHIP.body',
    proofGrade: 'outcome',
    text: 'People, content, offers, payments, and agents in one runtime your team and your agents share. Licensed as Free, Pro, Max, Enterprise inquire, or Pro Perpetual.',
    evidence: [AUTH_SESSIONS, COLLECTIONS, BILLING, AGENT_ROUTES, MCP_CONTENT],
  },
  {
    file: 'products.ts',
    exportPath: 'PRODUCTS_STATS_SECTION.heading',
    proofGrade: 'outcome',
    text: 'Built to production standards',
    evidence: [CI_GATE],
  },
  {
    file: 'products.ts',
    exportPath: 'PRODUCTS_STATS_SECTION.body',
    proofGrade: 'outcome',
    text: 'Not a starter template. A complete runtime with tested code you can inspect in the public repo.',
    evidence: [CI_GATE, REPO],
  },
  {
    file: 'products.ts',
    exportPath: 'PRODUCTS_CTA_SECTION.body',
    proofGrade: 'outcome',
    text: 'Start with the runtime. One command, full source, ready for your first deploy.',
    evidence: [REPO, CLI_CREATE],
  },
  {
    file: 'products.ts',
    exportPath: 'PRODUCTS_CTA_SECTION.cliSnippet',
    proofGrade: 'behavior',
    text: 'npx create-revealui@latest my-app',
    evidence: [CLI_CREATE],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_HERO.subtitle',
    text: 'Tired of tools that don’t talk — and agents you can’t audit?',
    evidence: [PERPETUAL, TIER_LIMITS],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_HERO_SUBTEXT.prefix',
    text: 'All plans run as self-hosted installations under your license. Enterprise is a license, not a hosted VM. Need a human?',
    evidence: [SELF_HOST, COMMERCIAL_POLICY, PERPETUAL, ROADMAP],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_HERO_SUBTEXT.suffix',
    text: 'Studio SKUs live on that site, not on this catalog.',
    evidence: [PERPETUAL],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_TRACK_A_SECTION.heading',
    text: 'Subscribe monthly or annually',
    evidence: [BILLING],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_TRACK_A_SECTION.body',
    text: 'Every subscription includes an agent task allowance. 7-day free trial on Pro and Max.',
    evidence: [TIER_LIMITS, TRIAL],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_VALUE_BAND.body',
    text: 'Teams shipping more than one product typically rent auth, content, billing, and observability from four or five vendors, and the bill climbs further once enterprise SSO or compliance tiers enter. RevealUI replaces the rented stack with one runtime you own. You still pay for your own Postgres and compute.',
    evidence: [INFRA_COST_ESTIMATE, SELF_HOST],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_VALUE_BAND.points[0]',
    text: 'One runtime, not five separate SaaS subscriptions',
    evidence: [INFRA_COST_ESTIMATE, SELF_HOST],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_VALUE_BAND.points[1]',
    text: 'Self-host on Vercel, Cloudflare, Fly, Hetzner, or your own metal',
    evidence: [DEPLOY_TARGETS],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_VALUE_BAND.points[2]',
    text: 'Full source code access on every tier',
    evidence: [LICENSE_MIT, REPO],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_VALUE_BAND.points[3]',
    text: "Open-weight AI by default: your bill doesn't scale with usage",
    evidence: [OPEN_WEIGHT],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_TRIAL_NOTE',
    text: 'Pro and Max include a 7-day free trial. Cancel during the trial and you pay nothing. First purchase, including annual, has a 14-day refund. No prorate after 14 days.',
    evidence: [TRIAL],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_TRACK_C_SECTION.body',
    text: 'A perpetual license costs about three years of the subscription. Pay once, own it forever, and renew support only if you want it.',
    evidence: [PERPETUAL, COMMERCIAL_POLICY],
  },
];
