import { LEGAL_COOKIES_CONTENT, LEGAL_HIPAA_CONTENT } from './shared-refs.js';
import type { ClaimEntry } from './types.js';

export const claimsPart7: readonly ClaimEntry[] = [
  {
    file: 'legal/cookies.ts',
    exportPath: 'COOKIES_META.intro',
    text: 'This Cookie Policy describes the cookies and similar technologies used on revealui.com, admin.revealui.com, api.revealui.com, and docs.revealui.com. It sits next to the Privacy Policy. Optional cookies stay off until you accept them. A HIPAA configuration never turns optional cookies on.',
    evidence: [LEGAL_COOKIES_CONTENT],
  },
  {
    file: 'legal/cookies.ts',
    exportPath: 'COOKIES_SECTIONS[0].paragraphs[0]',
    text: 'On your first visit we show a banner with Accept all, Reject all, and Customize. Reject is as easy as Accept. We honor Global Privacy Control and Do Not Track as a reject of optional categories. You can change the choice later from Cookie settings in the footer. We remember the choice for six months.',
    evidence: [LEGAL_COOKIES_CONTENT],
  },
  {
    file: 'legal/cookies.ts',
    exportPath: 'COOKIES_SECTIONS[1].listPreamble',
    text: 'Necessary cookies run to provide the service. They do not require consent under the ePrivacy rules we follow.',
    evidence: [LEGAL_COOKIES_CONTENT],
  },
  {
    file: 'legal/cookies.ts',
    exportPath: 'COOKIES_SECTIONS[1].listItems[0]',
    text: 'revealui-session (necessary): set on sign-in to keep you authenticated. httpOnly, Secure in production, SameSite=Lax. Up to 7 days (1 day when MFA is in use).',
    evidence: [LEGAL_COOKIES_CONTENT],
  },
  {
    file: 'legal/cookies.ts',
    exportPath: 'COOKIES_SECTIONS[1].listItems[1]',
    text: 'revealui-role (necessary): a role hint so the admin proxy can route admin-only paths. httpOnly, Secure in production, SameSite=Lax.',
    evidence: [LEGAL_COOKIES_CONTENT],
  },
  {
    file: 'legal/cookies.ts',
    exportPath: 'COOKIES_SECTIONS[1].listItems[2]',
    text: 'revealui-must-rotate (necessary): set when a password must be changed before the session continues. Host-only.',
    evidence: [LEGAL_COOKIES_CONTENT],
  },
  {
    file: 'legal/cookies.ts',
    exportPath: 'COOKIES_SECTIONS[1].listItems[3]',
    text: 'revealui-csrf (necessary): double-submit CSRF token for state-changing requests. Readable by JavaScript on purpose. SameSite=Strict. 24 hours.',
    evidence: [LEGAL_COOKIES_CONTENT],
  },
  {
    file: 'legal/cookies.ts',
    exportPath: 'COOKIES_SECTIONS[1].listItems[4]',
    text: 'revealui-node-id (necessary): stable identifier for collaborative editing. httpOnly, Secure in production, SameSite=Lax. 1 year.',
    evidence: [LEGAL_COOKIES_CONTENT],
  },
  {
    file: 'legal/cookies.ts',
    exportPath: 'COOKIES_SECTIONS[1].listItems[5]',
    text: 'revealui-cookie-consent (necessary): stores this cookie choice so we do not ask every page load. First-party, SameSite=Lax. 180 days.',
    evidence: [LEGAL_COOKIES_CONTENT],
  },
  {
    file: 'legal/cookies.ts',
    exportPath: 'COOKIES_SECTIONS[2].listItems[0]',
    text: 'Vercel Speed Insights: first-party performance timings (Core Web Vitals). Loaded only after analytics consent, and never in a HIPAA configuration.',
    evidence: [LEGAL_COOKIES_CONTENT],
  },
  {
    file: 'legal/cookies.ts',
    exportPath: 'COOKIES_SECTIONS[2].listItems[1]',
    text: 'Product analytics: a Plausible-compatible beacon with the event name, page URL, and referrer. No advertising cookies and no user id. Sent only after analytics consent, and never when Do Not Track is set.',
    evidence: [LEGAL_COOKIES_CONTENT],
  },
  {
    file: 'legal/cookies.ts',
    exportPath: 'COOKIES_SECTIONS[2].listItems[2]',
    text: 'Sentry error tracking: crash diagnostics. Session replay and performance tracing load only after analytics consent. A HIPAA configuration keeps Sentry replay and tracing off.',
    evidence: [LEGAL_COOKIES_CONTENT],
  },
  {
    file: 'legal/cookies.ts',
    exportPath: 'COOKIES_SECTIONS[2].paragraphs[0]',
    text: 'We do not use advertising cookies, marketing pixels, or cross-site profiling. The Marketing category exists in the banner so a future tool cannot ship without an explicit accept.',
    evidence: [LEGAL_COOKIES_CONTENT],
  },
  {
    file: 'legal/cookies.ts',
    exportPath: 'COOKIES_SECTIONS[3].paragraphs[0]',
    text: 'Set REVEALUI_COMPLIANCE_PROFILE=hipaa on a deployment that may hold protected health information. That profile refuses optional cookies and third-party browser telemetry, blocks the default Gmail API mail path, and signs the admin out after 15 minutes of idle time. Proton Mail is one allowed email vendor, not a blanket for the rest of the stack. See the HIPAA page.',
    evidence: [LEGAL_COOKIES_CONTENT],
  },
  {
    file: 'legal/cookies.ts',
    exportPath: 'COOKIES_SECTIONS[4].paragraphs[0]',
    text: '(interpolated: SITE email / domain embedded at runtime)',
    match: 'path',
    evidence: [LEGAL_COOKIES_CONTENT],
  },
  {
    file: 'legal/hipaa.ts',
    exportPath: 'HIPAA_META.intro',
    text: 'This page states what RevealUI does, and does not do, for HIPAA. We do not claim that RevealUI Cloud or a default self-host is HIPAA certified. We ship technical controls a covered entity can turn on, and we will sign a Business Associate Agreement when counsel has one ready and the deployment is in the HIPAA configuration.',
    evidence: [LEGAL_HIPAA_CONTENT],
  },
  {
    file: 'legal/hipaa.ts',
    exportPath: 'HIPAA_SECTIONS[0].paragraphs[0]',
    text: 'HIPAA applies when a covered entity or business associate creates, receives, maintains, or transmits protected health information. RevealUI is general-purpose software. It becomes a HIPAA surface only if you put PHI in it.',
    evidence: [LEGAL_HIPAA_CONTENT],
  },
  {
    file: 'legal/hipaa.ts',
    exportPath: 'HIPAA_SECTIONS[0].paragraphs[1]',
    text: 'Do not send PHI to hosted RevealUI (admin.revealui.com, api.revealui.com) until a signed BAA is in place and the tenant is running the HIPAA configuration. The Studio MSA already says that, absent a HIPAA addendum, customers will not provide regulated data.',
    evidence: [LEGAL_HIPAA_CONTENT],
  },
  {
    file: 'legal/hipaa.ts',
    exportPath: 'HIPAA_SECTIONS[1].listPreamble',
    text: 'Set REVEALUI_COMPLIANCE_PROFILE=hipaa (or VITE_COMPLIANCE_PROFILE / NEXT_PUBLIC_COMPLIANCE_PROFILE). The profile:',
    evidence: [LEGAL_HIPAA_CONTENT],
  },
  {
    file: 'legal/hipaa.ts',
    exportPath: 'HIPAA_SECTIONS[1].listItems[0]',
    text: 'Refuses optional cookies and does not load Speed Insights, product analytics, or Sentry session replay',
    evidence: [LEGAL_HIPAA_CONTENT],
  },
  {
    file: 'legal/hipaa.ts',
    exportPath: 'HIPAA_SECTIONS[1].listItems[1]',
    text: 'Signs the admin session out after 15 minutes of idle time',
    evidence: [LEGAL_HIPAA_CONTENT],
  },
  {
    file: 'legal/hipaa.ts',
    exportPath: 'HIPAA_SECTIONS[1].listItems[2]',
    text: 'Leaves necessary cookies (session, CSRF, role) in place so the product still works',
    evidence: [LEGAL_HIPAA_CONTENT],
  },
  {
    file: 'legal/hipaa.ts',
    exportPath: 'HIPAA_SECTIONS[1].paragraphs[0]',
    text: 'These controls match HIPAA Security Rule addressable specifications we can enforce in software (automatic logoff, transmission of optional telemetry). They are not a substitute for a risk analysis, workforce training, or physical safeguards on your side.',
    evidence: [LEGAL_HIPAA_CONTENT],
  },
  {
    file: 'legal/hipaa.ts',
    exportPath: 'HIPAA_SECTIONS[2].paragraphs[0]',
    text: 'A BAA is a contract, not a product flag. RevealUI Studio will execute a customer BAA only through counsel, and only for a tenant that runs the HIPAA configuration.',
    evidence: [LEGAL_HIPAA_CONTENT],
  },
  {
    file: 'legal/hipaa.ts',
    exportPath: 'HIPAA_SECTIONS[2].paragraphs[1]',
    text: 'Self-host is the honest path for PHI today. You then sign BAAs with the vendors you actually use (your database, your host, your email). Our hosted subprocessors publish their own DPA pages; a HIPAA BAA with each of them is a separate commercial step and is not in place by default.',
    evidence: [LEGAL_HIPAA_CONTENT],
  },
  {
    file: 'legal/hipaa.ts',
    exportPath: 'HIPAA_SECTIONS[3].paragraphs[0]',
    text: 'Studio human mail, file shares, calendar, VPN, and operator passwords can sit on Proton (Mail, Drive, Calendar, VPN, Pass) under one Proton BAA. That BAA does not cover the product runtime.',
    evidence: [LEGAL_HIPAA_CONTENT],
  },
  {
    file: 'legal/hipaa.ts',
    exportPath: 'HIPAA_SECTIONS[3].paragraphs[1]',
    text: 'RevealUI transactional email defaults to the Gmail API. In the HIPAA profile that path is blocked. Use customer SMTP or Proton Bridge, or keep PHI out of email.',
    evidence: [LEGAL_HIPAA_CONTENT],
  },
  {
    file: 'legal/hipaa.ts',
    exportPath: 'HIPAA_SECTIONS[3].paragraphs[2]',
    text: 'Coverage is per surface. Files, database, hosting, object storage, payments, error telemetry, and support each need their own allowed vendor. Proton is one option for mail and files. It is not a blanket for Neon, Vercel, R2, Stripe, or Sentry.',
    evidence: [LEGAL_HIPAA_CONTENT],
  },
  {
    file: 'legal/hipaa.ts',
    exportPath: 'HIPAA_SECTIONS[4].listItems[0]',
    text: 'Put "HIPAA compliant" or "HIPAA certified" on marketing pages while no BAA and no independent assessment exist',
    evidence: [LEGAL_HIPAA_CONTENT],
  },
  {
    file: 'legal/hipaa.ts',
    exportPath: 'HIPAA_SECTIONS[4].listItems[1]',
    text: 'Send session replay, page analytics, or Speed Insights from a HIPAA-profile deployment',
    evidence: [LEGAL_HIPAA_CONTENT],
  },
  {
    file: 'legal/hipaa.ts',
    exportPath: 'HIPAA_SECTIONS[4].listItems[2]',
    text: 'Accept PHI on the agency site, in a support inbox, or in an un-BAA cloud share',
    evidence: [LEGAL_HIPAA_CONTENT],
  },
  {
    file: 'legal/hipaa.ts',
    exportPath: 'HIPAA_SECTIONS[5].paragraphs[0]',
    text: '(interpolated: SITE email / domain embedded at runtime)',
    match: 'path',
    evidence: [LEGAL_HIPAA_CONTENT],
  },
];
