import { PAID_SUPPORT_POLICY } from '@revealui/contracts/public-catalog';
import { SITE } from '../site.js';
import {
  AUDIT_LOG_SCHEMA,
  AUTH_SESSIONS,
  BILLING,
  CI_GATE,
  LEGAL_SECURITY_CONTENT,
  LEGAL_SLA_CONTENT,
  LEGAL_SUBPROCESSORS_CONTENT,
  LEGAL_SUPPORT_CONTENT,
  LEGAL_TERMS_CONTENT,
  PAID_SUPPORT_POLICY_CONTENT,
  PAID_SUPPORT_POLICY_RENDERED_TEST,
  POSTGRES,
  RBAC_ABAC,
  REFUND_ROUTE,
} from './shared-refs.js';
import type { ClaimEntry } from './types.js';

export const claimsPart5: readonly ClaimEntry[] = [
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[2].listItems[1]',
    text: 'admin.revealui.com (admin dashboard)',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[2].listItems[2]',
    text: 'api.revealui.com (REST API)',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[2].listItems[3]',
    text: 'docs.revealui.com (documentation site)',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[2].listItems[4]',
    text: 'The published source code in the RevealUIStudio organization on GitHub',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[3].listItems[0]',
    text: 'Third-party services we use (Vercel, NeonDB, Stripe, Cloudflare, etc.): report directly to those vendors.',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[3].listItems[1]',
    text: 'Social-engineering attacks against employees, contractors, or customers.',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[3].listItems[2]',
    text: 'Denial-of-service attacks, traffic flooding, or any test that affects availability.',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[3].listItems[3]',
    text: 'Vulnerabilities in software you have self-hosted using RevealUI but modified: please report against an unmodified build.',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[3].listItems[4]',
    text: 'Findings that require physical access to a device we do not own.',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[3].listItems[5]',
    text: 'Reports of missing security headers without a demonstrated exploit.',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[3].listItems[6]',
    text: 'Reports based solely on automated-scanner output without manual verification.',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[4].listItems[0]',
    text: 'We will not silently fix issues without notifying the reporter when a fix ships.',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[4].listItems[1]',
    text: 'We will not delay disclosure indefinitely to avoid embarrassment. We aim to publish a brief notice within 90 days of resolution, or sooner if the issue has been independently disclosed.',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[4].listItems[2]',
    text: 'We will not retaliate against researchers who follow this policy.',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[5].heading',
    text: '6. Our security posture (summary)',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[5].paragraphs[0]',
    text: 'Customers who run RevealUI inherit a security baseline we take seriously. The current posture, in plain English:',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[5].listItems[0]',
    text: 'Authentication uses session cookies signed with a server-side secret, with bcrypt password hashing (cost factor 12), brute-force protection, and rate limiting.',
    evidence: [LEGAL_SECURITY_CONTENT, AUTH_SESSIONS],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[5].listItems[1]',
    text: 'Authorization is enforced by an RBAC + ABAC policy engine with database-level access checks on every collection operation.',
    evidence: [LEGAL_SECURITY_CONTENT, AUTH_SESSIONS, RBAC_ABAC],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[5].listItems[2]',
    text: 'Encryption for sensitive fields uses AES-256-GCM with non-extractable keys by default.',
    evidence: [
      LEGAL_SECURITY_CONTENT,
      {
        kind: 'code',
        ref: 'packages/security/src',
        note: 'crypto helpers; AES-256-GCM field encryption surface',
      },
    ],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[5].listItems[3]',
    text: 'Standard browser security headers (CSP, HSTS, X-Frame-Options, Referrer-Policy, Permissions-Policy) are configured on every deployed app.',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[5].listItems[4]',
    text: 'Continuous integration runs CodeQL, Gitleaks, dependency auditing, and an AST-based code-pattern analyzer on every push.',
    evidence: [LEGAL_SECURITY_CONTENT, CI_GATE],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[5].listItems[5]',
    text: 'GitHub branch protection requires CI passage before merge to main; production deploys are gated on the deploy workflow, not direct pushes.',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[5].listItems[6]',
    text: 'Internal security documentation (incident response runbook, information security policy, credential rotation runbook) is maintained alongside this site and available for customer review on request.',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[6].subsections[0].heading',
    text: 'What is your independent-assessment status?',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[6].subsections[0].paragraph',
    text: 'RevealUI Studio is a Tennessee LLC operating as a solo-operator company. We do not currently hold SOC 2, ISO 27001, or PCI DSS attestations. These are planned for later phases of the company; we will publish progress on this page when those audits begin.',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[6].subsections[1].heading',
    text: 'Can I arrange a Data Processing Agreement?',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[6].subsections[1].paragraph',
    text: 'For data protection: we are GDPR-aware in our framework design (consent, deletion, anonymization primitives are in the platform), but a Data Processing Agreement template is not yet finalized for EU B2B customers. If you require a DPA before purchase, contact us before signing up.',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[7].heading',
    text: '8. Machine-readable policy',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[7].paragraphs[0]',
    text: 'This policy is also published as an RFC 9116 security.txt file at https://revealui.com/.well-known/security.txt. Automated security tooling should read that file for contact and policy URLs. GitHub Security Advisories (same reporting channel): https://github.com/RevealUIStudio/revealui/security/policy.',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[8].paragraphs[0]',
    text: 'We will list researchers here as they are credited. The list is empty today, pre-launch, but we plan to keep it updated as the program runs.',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[9].paragraphs[0]',
    text: '(interpolated: SITE email / domain embedded at runtime)',
    match: 'path',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/sla.ts',
    exportPath: 'SLA_META.intro',
    text: 'RevealUI Studio is a solo-operated company. This page states our support response targets and infrastructure uptime commitment, who they cover, and how to report an issue.',
    evidence: [LEGAL_SLA_CONTENT],
  },
  {
    file: 'legal/sla.ts',
    exportPath: 'SLA_SECTIONS[0].listItems[0]',
    text: PAID_SUPPORT_POLICY.standardResponse,
    evidence: [PAID_SUPPORT_POLICY_CONTENT, PAID_SUPPORT_POLICY_RENDERED_TEST, LEGAL_SLA_CONTENT],
  },
  {
    file: 'legal/sla.ts',
    exportPath: 'SLA_SECTIONS[0].listItems[1]',
    text: PAID_SUPPORT_POLICY.criticalResponse,
    evidence: [PAID_SUPPORT_POLICY_CONTENT, PAID_SUPPORT_POLICY_RENDERED_TEST, LEGAL_SLA_CONTENT],
  },
  {
    file: 'legal/sla.ts',
    exportPath: 'SLA_SECTIONS[0].paragraphs[0]',
    text: '(interpolated: SITE email / domain embedded at runtime)',
    match: 'path',
    evidence: [LEGAL_SLA_CONTENT],
  },
  {
    file: 'legal/sla.ts',
    exportPath: 'SLA_SECTIONS[0].paragraphs[1]',
    text: PAID_SUPPORT_POLICY.applicability,
    evidence: [PAID_SUPPORT_POLICY_CONTENT, PAID_SUPPORT_POLICY_RENDERED_TEST, LEGAL_SLA_CONTENT],
  },
  {
    file: 'legal/sla.ts',
    exportPath: 'SLA_SECTIONS[1].paragraphs[0]',
    text: 'For the license validation endpoint and the download and release endpoint, we target 99% uptime, measured monthly. That allows about 7.3 hours of downtime in an average month.',
    evidence: [LEGAL_SLA_CONTENT],
  },
  {
    file: 'legal/sla.ts',
    exportPath: 'SLA_SECTIONS[1].paragraphs[1]',
    text: 'If you self-host RevealUI, this uptime commitment covers our infrastructure (license validation, downloads, and updates), not your infrastructure. Your deployment runs on servers you control, and its uptime is your responsibility.',
    evidence: [LEGAL_SLA_CONTENT],
  },
  {
    file: 'legal/sla.ts',
    exportPath: 'SLA_SECTIONS[1].paragraphs[2]',
    text: 'A hosted RevealUI product beyond license and download infrastructure does not yet carry a published uptime commitment. When that changes, this page will say so.',
    evidence: [LEGAL_SLA_CONTENT],
  },
  {
    file: 'legal/sla.ts',
    exportPath: 'SLA_SECTIONS[2].paragraphs[0]',
    text: 'When we need to take infrastructure down for planned maintenance, we give at least 48 hours of advance notice by email to affected customers and on our status page.',
    evidence: [
      LEGAL_SLA_CONTENT,
      {
        kind: 'url',
        ref: 'https://revealui.com/status',
        note: 'public status page for hosted surfaces',
      },
    ],
  },
  {
    file: 'legal/sla.ts',
    exportPath: 'SLA_SECTIONS[3].heading',
    text: '4. What happens if our license service is down',
    evidence: [LEGAL_SLA_CONTENT],
  },
  {
    file: 'legal/sla.ts',
    exportPath: 'SLA_SECTIONS[3].paragraphs[0]',
    text: 'If license validation or a hosted service fails, contact support with the error and affected deployment. Availability depends on the configured deployment and service providers. Our Terms explain subscription cancellation and continued use of acquired perpetual versions.',
    evidence: [LEGAL_SLA_CONTENT],
  },
  {
    file: 'legal/sla.ts',
    exportPath: 'SLA_SECTIONS[4].paragraphs[0]',
    text: PAID_SUPPORT_POLICY.coverage,
    evidence: [PAID_SUPPORT_POLICY_CONTENT, PAID_SUPPORT_POLICY_RENDERED_TEST, LEGAL_SLA_CONTENT],
  },
  {
    file: 'legal/sla.ts',
    exportPath: 'SLA_SECTIONS[5].heading',
    text: '6. Status and live updates',
    evidence: [
      LEGAL_SLA_CONTENT,
      {
        kind: 'url',
        ref: 'https://revealui.com/status',
        note: 'public status page for hosted surfaces',
      },
    ],
  },
  {
    file: 'legal/sla.ts',
    exportPath: 'SLA_SECTIONS[5].paragraphs[0]',
    text: 'Real-time status for revealui.com, admin.revealui.com, api.revealui.com, and docs.revealui.com is published at https://revealui.com/status.',
    evidence: [
      LEGAL_SLA_CONTENT,
      {
        kind: 'url',
        ref: 'https://revealui.com/status',
        note: 'public status page for hosted surfaces',
      },
    ],
  },
  {
    file: 'legal/sla.ts',
    exportPath: 'SLA_SECTIONS[6].paragraphs[0]',
    text: '(interpolated: SITE email / domain embedded at runtime)',
    match: 'path',
    evidence: [LEGAL_SLA_CONTENT],
  },
  {
    file: 'legal/subprocessors.ts',
    exportPath: 'SUBPROCESSORS[0].role',
    text: 'Application hosting (marketing, admin, API, docs)',
    evidence: [LEGAL_SUBPROCESSORS_CONTENT],
  },
  {
    file: 'legal/subprocessors.ts',
    exportPath: 'SUBPROCESSORS[0].location',
    text: 'United States (primary: us-east-1)',
    evidence: [LEGAL_SUBPROCESSORS_CONTENT],
  },
  {
    file: 'legal/subprocessors.ts',
    exportPath: 'SUBPROCESSORS[0].dataCategories[2]',
    text: 'Edge logs (IP, user agent, request path)',
    evidence: [LEGAL_SUBPROCESSORS_CONTENT],
  },
  {
    file: 'legal/subprocessors.ts',
    exportPath: 'SUBPROCESSORS[0].dataCategories[3]',
    text: 'Speed Insights telemetry (anonymous)',
    evidence: [LEGAL_SUBPROCESSORS_CONTENT],
  },
  {
    file: 'legal/subprocessors.ts',
    exportPath: 'SUBPROCESSORS[1].role',
    text: 'PostgreSQL database (primary store)',
    evidence: [LEGAL_SUBPROCESSORS_CONTENT, POSTGRES],
  },
  {
    file: 'legal/subprocessors.ts',
    exportPath: 'SUBPROCESSORS[1].location',
    text: 'United States (primary: us-east-1)',
    evidence: [LEGAL_SUBPROCESSORS_CONTENT],
  },
  {
    file: 'legal/subprocessors.ts',
    exportPath: 'SUBPROCESSORS[2].role',
    text: 'Object storage (media uploads, generated assets)',
    evidence: [LEGAL_SUBPROCESSORS_CONTENT],
  },
  {
    file: 'legal/subprocessors.ts',
    exportPath: 'SUBPROCESSORS[3].role',
    text: 'Payment processing (subscriptions, perpetual licenses, refunds)',
    evidence: [LEGAL_SUBPROCESSORS_CONTENT],
  },
  {
    file: 'legal/subprocessors.ts',
    exportPath: 'SUBPROCESSORS[3].location',
    text: 'United States (PCI DSS Level 1)',
    evidence: [LEGAL_SUBPROCESSORS_CONTENT],
  },
  {
    file: 'legal/subprocessors.ts',
    exportPath: 'SUBPROCESSORS[3].dataCategories[0]',
    text: 'Billing identity (name, email, billing address)',
    evidence: [LEGAL_SUBPROCESSORS_CONTENT],
  },
  {
    file: 'legal/subprocessors.ts',
    exportPath: 'SUBPROCESSORS[4].role',
    text: 'Transactional email delivery (receipts, license keys, support)',
    evidence: [LEGAL_SUBPROCESSORS_CONTENT],
  },
  {
    file: 'legal/subprocessors.ts',
    exportPath: 'SUBPROCESSORS[4].dataCategories[1]',
    text: 'Message content for delivery',
    evidence: [LEGAL_SUBPROCESSORS_CONTENT],
  },
  {
    file: 'legal/subprocessors.ts',
    exportPath: 'SUBPROCESSORS_CHANGELOG[0].summary',
    text: "Corrected NeonDB's data categories: removed 'audit logs'. Production audit-log storage does not persist to Postgres today, so listing it as a stored data category was inaccurate.",
    evidence: [LEGAL_SUBPROCESSORS_CONTENT, POSTGRES, AUDIT_LOG_SCHEMA],
  },
  {
    file: 'legal/subprocessors.ts',
    exportPath: 'SUBPROCESSORS_CHANGELOG[1].summary',
    text: 'Initial published list: Vercel, NeonDB, Cloudflare R2, Stripe, Google Workspace. Sentry is listed in the Privacy Policy as an anticipated subprocessor for error tracking; it will appear here once the SDK is wired and a DSN is configured.',
    evidence: [LEGAL_SUBPROCESSORS_CONTENT, BILLING, POSTGRES],
  },
  {
    file: 'legal/subprocessors.ts',
    exportPath: 'SUBPROCESSORS_META.intro',
    text: 'A subprocessor is a third-party service we use to operate RevealUI on your behalf. Every entry below stores, processes, or transmits some category of customer data. The table is dated and we commit to updating it before adding a new subprocessor, not after. See the change-log at the bottom of this page.',
    evidence: [LEGAL_SUBPROCESSORS_CONTENT],
  },
  {
    file: 'legal/subprocessors.ts',
    exportPath: 'SUBPROCESSORS_NOTES.subscribeAdvice',
    text: 'There is no subscribe-to-changes channel for this page yet. Material customers can request notification by email and we will email them when an entry is added. Watch the RevealUI repository on GitHub to receive a notification when this file changes in source.',
    evidence: [LEGAL_SUBPROCESSORS_CONTENT],
  },
  {
    file: 'legal/subprocessors.ts',
    exportPath: 'SUBPROCESSORS_NOTES.contactPrefix',
    text: 'Questions about a specific subprocessor (including its DPA, regional data handling, or sub-processors of its own) should go to ',
    evidence: [LEGAL_SUBPROCESSORS_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_META.intro',
    text: 'RevealUI Studio is a solo-operator company. We want to help you succeed with RevealUI, and we want to be honest about what kind of help we can offer, on what timeline, and through which channels. This page covers all three.',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[0].listPreamble',
    text: 'Different questions land best in different places. In rough order of speed:',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[0].listItems[0]',
    text: '**[Documentation](https://docs.revealui.com)**: covers setup, configuration, the API surface, and most "how do I do X with RevealUI" questions. Always check here first; if the answer is there, you have it now instead of waiting on an email reply.',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[0].listItems[1]',
    text: '**[GitHub Discussions](https://github.com/RevealUIStudio/revealui/discussions)**: community-friendly format for design questions, "is there a better way to do X", and ideas. Other users and the maintainer both watch this. Best for questions where a public answer benefits more than just you.',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[0].listItems[2]',
    text: '**[GitHub Issues](https://github.com/RevealUIStudio/revealui/issues)**: for confirmed bugs and feature requests. Include reproduction steps. See §5 below for "bug vs support" guidance.',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[0].listItems[3]',
    text: '(interpolated: SITE email / domain embedded at runtime)',
    match: 'path',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[0].listItems[4]',
    text: '**Paid license buyers:** after purchase we may send a private invite for onboarding questions. That invite is manual and is not a public join link. Billing and license issues still go to email.',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[0].listItems[5]',
    text: '**[Essays and product notes](https://substack.com/@revealuistudio)**: the public broadcast list. It is not a support desk.',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[1].heading',
    text: '2. Response targets and earlier agreements',
    evidence: [PAID_SUPPORT_POLICY_CONTENT, LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[1].paragraphs[0]',
    text: `Email ${SITE.emails.support}. ${PAID_SUPPORT_POLICY.standardResponse} ${PAID_SUPPORT_POLICY.criticalResponse} Complex issues may need multiple rounds of correspondence after that first response. Full detail is on our [SLA page](https://revealui.com/sla).`,
    evidence: [
      PAID_SUPPORT_POLICY_CONTENT,
      PAID_SUPPORT_POLICY_RENDERED_TEST,
      LEGAL_SUPPORT_CONTENT,
      LEGAL_SLA_CONTENT,
    ],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[1].paragraphs[1]',
    text: PAID_SUPPORT_POLICY.coverage,
    evidence: [
      PAID_SUPPORT_POLICY_CONTENT,
      PAID_SUPPORT_POLICY_RENDERED_TEST,
      LEGAL_SUPPORT_CONTENT,
    ],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[1].paragraphs[2]',
    text: PAID_SUPPORT_POLICY.applicability,
    evidence: [
      PAID_SUPPORT_POLICY_CONTENT,
      PAID_SUPPORT_POLICY_RENDERED_TEST,
      LEGAL_SUPPORT_CONTENT,
    ],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[1].paragraphs[3]',
    text: 'GitHub Issues and Discussions: best-effort. We read them, but we may not respond instantly. If something is urgent, email is the right channel.',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[1].paragraphs[4]',
    text: 'Security reports: see the dedicated [security policy](https://revealui.com/security). Those go to a separate address with a separate response commitment.',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[2].listItems[0]',
    text: 'Setup and installation issues with `create-revealui` and the published packages',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[2].listItems[1]',
    text: 'Configuration questions about the admin engine, auth, billing integration, or AI agents',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[2].listItems[2]',
    text: 'License key issues (lost keys, transfer, downgrade, refund within window)',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[2].listItems[3]',
    text: 'Bugs in the published RevealUI source code (OSS and Pro packages)',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[2].listItems[4]',
    text: 'Questions about the documented API surface',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[2].listItems[5]',
    text: 'Account changes, plan changes, and cancellations',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[2].listItems[6]',
    text: 'Genuine "is RevealUI the right tool for X" pre-purchase questions',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[3].heading',
    text: '4. What we cannot help with',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[3].paragraphs[0]',
    text: 'Support covers the product and documented setup paths. Implementation work and ongoing operation need a separately agreed scope.',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[3].listItems[0]',
    text: 'We do not write your application code for you. RevealUI is a framework; you build with it.',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[3].listItems[1]',
    text: 'Private codebase review is separately scoped work. Contact [RevealUI Studio](https://revealuistudio.com/contact) to discuss it; a product license does not include consulting.',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[3].listItems[2]',
    text: 'We do not debug deployments to specific hosting environments (Kubernetes clusters, exotic Docker setups, customer VPNs) beyond the documented Vercel / Fly / Hetzner / Docker paths.',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[3].listItems[3]',
    text: 'We cannot recover data from a self-hosted instance that has been lost. We do not have access to your database. Always maintain your own backups.',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[3].listItems[4]',
    text: 'For architecture or implementation work beyond product support, discuss a scoped engagement with [RevealUI Studio](https://revealuistudio.com/contact).',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[3].listItems[5]',
    text: 'We do not provide live phone or video support at the Pro tier. Email-and-async only.',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[4].heading',
    text: '5. When to file a bug vs ask for support',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[4].listPreamble',
    text: 'A useful rule of thumb when deciding where to take an issue:',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[4].listItems[0]',
    text: '**File a bug** (GitHub Issue) when: the documented behavior does not match the actual behavior; you have a reliable reproduction; the issue would affect other users; the fix probably lives in the public source code.',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[4].listItems[1]',
    text: '(interpolated: SITE email / domain embedded at runtime)',
    match: 'path',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[4].listItems[2]',
    text: '**Open a Discussion** when: you are not sure if it is a bug; you want input from the community; you want to influence the roadmap.',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[5].paragraphs[0]',
    text: 'Live status of revealui.com, admin.revealui.com, api.revealui.com, and docs.revealui.com is published on the [status page](https://revealui.com/status) with a live probe of the API health endpoint and an honest disclosure of our monitoring posture (we are a solo-operator company; we do not run 24×7 manned monitoring).',
    evidence: [
      LEGAL_SUPPORT_CONTENT,
      PAID_SUPPORT_POLICY_CONTENT,
      {
        kind: 'url',
        ref: 'https://revealui.com/status',
        note: 'public status page for hosted surfaces',
      },
    ],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[5].paragraphs[1]',
    text: 'If you are experiencing an outage that the status page does not yet reflect, email support and include the surface you are hitting and the time you first saw the issue.',
    evidence: [
      LEGAL_SUPPORT_CONTENT,
      PAID_SUPPORT_POLICY_CONTENT,
      {
        kind: 'url',
        ref: 'https://revealui.com/status',
        note: 'public status page for hosted surfaces',
      },
    ],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[6].paragraphs[0]',
    text: `Every paid tier has the same prospective response targets: ${PAID_SUPPORT_POLICY.summary}. We do not offer a faster staffed tier. Earlier agreements retain their stated support commitments.`,
    evidence: [
      PAID_SUPPORT_POLICY_CONTENT,
      PAID_SUPPORT_POLICY_RENDERED_TEST,
      LEGAL_SUPPORT_CONTENT,
      LEGAL_SLA_CONTENT,
    ],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[6].paragraphs[1]',
    text: 'Enterprise customers who need a dedicated Slack channel, a named technical contact, or scheduled architecture reviews should contact us before purchase to confirm scope and timeline.',
    evidence: [LEGAL_SUPPORT_CONTENT, LEGAL_SLA_CONTENT],
  },
  {
    file: 'legal/support.ts',
    exportPath: 'SUPPORT_SECTIONS[7].paragraphs[0]',
    text: '(interpolated: SITE email / domain embedded at runtime)',
    match: 'path',
    evidence: [LEGAL_SUPPORT_CONTENT],
  },
  {
    file: 'legal/terms.ts',
    exportPath: 'TERMS_META.intro',
    text: 'These Terms of Service ("Terms") govern your use of the RevealUI platform provided by REVEALUI STUDIO L.L.C., a Tennessee limited liability company ("we", "us", "our"). By creating an account or using the Service, you agree to these Terms.',
    evidence: [LEGAL_TERMS_CONTENT],
  },
  {
    file: 'legal/terms.ts',
    exportPath: 'TERMS_SECTIONS[0].paragraphs[0]',
    text: 'RevealUI is an open-source agentic business runtime for software companies. It includes a content engine, authentication, billing integration, AI agents, and UI components. The Service is available in four tiers: Free (OSS), Pro, Max, and Enterprise.',
    evidence: [LEGAL_TERMS_CONTENT],
  },
  {
    file: 'legal/terms.ts',
    exportPath: 'TERMS_SECTIONS[1].listItems[0]',
    text: 'You must provide accurate information when creating an account.',
    evidence: [LEGAL_TERMS_CONTENT],
  },
  {
    file: 'legal/terms.ts',
    exportPath: 'TERMS_SECTIONS[1].listItems[1]',
    text: 'You are responsible for maintaining the security of your account credentials.',
    evidence: [LEGAL_TERMS_CONTENT],
  },
  {
    file: 'legal/terms.ts',
    exportPath: 'TERMS_SECTIONS[1].listItems[2]',
    text: 'You must be at least 13 years old to use the Service.',
    evidence: [LEGAL_TERMS_CONTENT],
  },
  {
    file: 'legal/terms.ts',
    exportPath: 'TERMS_SECTIONS[1].listItems[3]',
    text: 'One person or organization may not maintain more than one free account.',
    evidence: [LEGAL_TERMS_CONTENT],
  },
  {
    file: 'legal/terms.ts',
    exportPath: 'TERMS_SECTIONS[2].paragraphs[0]',
    text: 'The Free tier is licensed under the MIT License. You may use, modify, and distribute the open-source code freely, subject to the MIT License terms. The Free tier includes limited features (1 site, 3 users, community support).',
    evidence: [LEGAL_TERMS_CONTENT],
  },
  {
    file: 'legal/terms.ts',
    exportPath: 'TERMS_SECTIONS[3].heading',
    text: '4. Paid Tiers (Pro, Max & Enterprise)',
    evidence: [LEGAL_TERMS_CONTENT],
  },
  {
    file: 'legal/terms.ts',
    exportPath: 'TERMS_SECTIONS[3].subsections[0].listItems[0]',
    text: 'Subscription prices for Pro, Max, and Enterprise are as published at https://revealui.com/pricing at the time of purchase, in U.S. dollars and exclusive of applicable taxes. You will see the price you agree to before completing checkout.',
    evidence: [LEGAL_TERMS_CONTENT],
  },
  {
    file: 'legal/terms.ts',
    exportPath: 'TERMS_SECTIONS[3].subsections[0].listItems[1]',
    text: 'Pro and Max include a 7-day free trial. Enterprise pricing is published with the option to contact sales for annual rates.',
    evidence: [LEGAL_TERMS_CONTENT],
  },
  {
    file: 'legal/terms.ts',
    exportPath: 'TERMS_SECTIONS[3].subsections[0].listItems[2]',
    text: "Payment is processed by Stripe. You agree to Stripe's terms of service when you complete checkout.",
    evidence: [LEGAL_TERMS_CONTENT],
  },
  {
    file: 'legal/terms.ts',
    exportPath: 'TERMS_SECTIONS[3].subsections[1].paragraph',
    text: 'The Pro and Max tiers include a 7-day free trial. You will not be charged during the trial period. If you do not cancel before the trial ends, your subscription will automatically begin and you will be charged the price for the monthly or annual billing interval selected at checkout.',
    evidence: [LEGAL_TERMS_CONTENT],
  },
  {
    file: 'legal/terms.ts',
    exportPath: 'TERMS_SECTIONS[3].subsections[2].paragraph',
    text: 'You may cancel your subscription at any time through the Stripe billing portal or by contacting us. Cancellation takes effect at the end of your current billing period. You retain access to paid features until then.',
    evidence: [LEGAL_TERMS_CONTENT],
  },
  {
    file: 'legal/terms.ts',
    exportPath: 'TERMS_SECTIONS[3].subsections[3].paragraph',
    text: '(interpolated: SITE email / domain embedded at runtime)',
    match: 'path',
    evidence: [LEGAL_TERMS_CONTENT, REFUND_ROUTE],
  },
  {
    file: 'legal/terms.ts',
    exportPath: 'TERMS_SECTIONS[3].subsections[4].heading',
    text: 'License continuity and validation',
    evidence: [LEGAL_TERMS_CONTENT],
  },
  {
    file: 'legal/terms.ts',
    exportPath: 'TERMS_SECTIONS[3].subsections[4].listItems[0]',
    text: 'Pro and Max subscriptions provide paid features during the paid entitlement period. Canceling renewal takes effect at the end of your current billing period. Export the data you need before changing your deployment or plan.',
    evidence: [LEGAL_TERMS_CONTENT],
  },
  {
    file: 'legal/terms.ts',
    exportPath: 'TERMS_SECTIONS[3].subsections[4].listItems[1]',
    text: 'Pro Perpetual permits continued use of the acquired Pro version. Renewal is optional and is required only for future updates and support after the included coverage ends. A support renewal lapse does not block reads or writes in the acquired version or remove its purchased Pro features.',
    evidence: [LEGAL_TERMS_CONTENT],
  },
  {
    file: 'legal/terms.ts',
    exportPath: 'TERMS_SECTIONS[3].subsections[4].listItems[2]',
    text: 'Self-hosted installations validate the configured license key. Availability of hosted APIs and integrations also depends on your deployment and service providers. If license validation or a hosted service fails, contact support with the error and affected deployment.',
    evidence: [LEGAL_TERMS_CONTENT],
  },
  {
    file: 'legal/terms.ts',
    exportPath: 'TERMS_SECTIONS[3].subsections[4].listItems[3]',
    text: 'A license may be revoked following a refund, chargeback, or terms violation. Revocation removes the associated paid entitlement.',
    evidence: [LEGAL_TERMS_CONTENT],
  },
  {
    file: 'legal/terms.ts',
    exportPath: 'TERMS_SECTIONS[3].subsections[4].listItems[4]',
    text: 'Invalid or missing license key: configure a valid key to establish the paid entitlement.',
    evidence: [LEGAL_TERMS_CONTENT],
  },
  {
    file: 'legal/terms.ts',
    exportPath: 'TERMS_SECTIONS[3].subsections[5].paragraph',
    text: `${PAID_SUPPORT_POLICY.summary}. ${PAID_SUPPORT_POLICY.coverage} ${PAID_SUPPORT_POLICY.applicability} See https://revealui.com/support and https://revealui.com/sla for hours, scope, and contact details.`,
    evidence: [PAID_SUPPORT_POLICY_CONTENT, PAID_SUPPORT_POLICY_RENDERED_TEST, LEGAL_TERMS_CONTENT],
  },
  {
    file: 'legal/terms.ts',
    exportPath: 'TERMS_SECTIONS[4].paragraphs[0]',
    text: 'Pro packages (@revealui/ai, @revealui/engines, @revealui/harnesses, @revealui/mcp, @revealui/services) are commercially licensed. Paid runtime entitlements are granted by subscription or the purchased perpetual option and are non-transferable. Source use follows each package’s published license. See LICENSE.commercial in the repository for the licensing overview.',
    evidence: [LEGAL_TERMS_CONTENT],
  },
  {
    file: 'legal/terms.ts',
    exportPath: 'TERMS_SECTIONS[5].listItems[0]',
    text: 'Use the Service for any unlawful purpose',
    evidence: [LEGAL_TERMS_CONTENT],
  },
  {
    file: 'legal/terms.ts',
    exportPath: 'TERMS_SECTIONS[5].listItems[1]',
    text: 'Attempt to gain unauthorized access to the Service or its infrastructure',
    evidence: [LEGAL_TERMS_CONTENT],
  },
  {
    file: 'legal/terms.ts',
    exportPath: 'TERMS_SECTIONS[5].listItems[2]',
    text: 'Distribute malware, spam, or harmful content through the Service',
    evidence: [LEGAL_TERMS_CONTENT],
  },
  {
    file: 'legal/terms.ts',
    exportPath: 'TERMS_SECTIONS[5].listItems[3]',
    text: 'Exceed reasonable usage limits or abuse API rate limits',
    evidence: [LEGAL_TERMS_CONTENT],
  },
];
