import {
  BILLING,
  BIO,
  COLLECTIONS,
  COMMERCIAL_POLICY,
  FAIR_SOURCE_PAGE,
  FSL_PEERS_CITATION,
  HARNESS_ADAPTER,
  HARNESS_WORKBOARD,
  HYPERVISOR,
  LICENSE_MIT,
  LICENSE_SPLIT,
  LLM_CLIENT,
  MARKET_CITATIONS,
  MCP_SERVERS,
  MEMORY,
  NO_TELEMETRY,
  OLLAMA,
  OPEN_WEIGHT,
  OPENAI_COMPAT,
  ORCHESTRATOR,
  PROVIDERS,
  RBAC_ABAC,
  REPO,
  ROADMAP,
  SELF_HOST,
  SERVICES_STRIPE,
} from './shared-refs.js';
import type { ClaimEntry } from './types.js';

export const claimsPart3: readonly ClaimEntry[] = [
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_CLOSING.body',
    proofGrade: 'outcome',
    text: "A free 30-minute discovery call. We walk through what you're building, whether we're the right team for it, and what a scoped engagement would look like.",
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators-how-it-works.ts',
    exportPath: 'FO_HIW_HERO.subtitle',
    proofGrade: 'outcome',
    text: '(operator-lane studio-voice copy; path-pinned so the phrasing stays out of the fleet-voice register scan)',
    match: 'path',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators-how-it-works.ts',
    exportPath: 'FO_HIW_STEPS.steps[0].body',
    proofGrade: 'outcome',
    text: "30 minutes, free. We walk through what you're building and whether RevealUI Studio is the right team for it. If we are, we move to scope. If we're not, we tell you and point you somewhere that is.",
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators-how-it-works.ts',
    exportPath: 'FO_HIW_STEPS.steps[1].body',
    proofGrade: 'outcome',
    text: "A written statement of work: what we'll build, what the deliverable looks like, what's in and out of scope, and the engagement timeline. Fixed-bid. No surprise change orders.",
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators-how-it-works.ts',
    exportPath: 'FO_HIW_STEPS.steps[2].body',
    proofGrade: 'outcome',
    text: 'You stay in the loop. We send a checkpoint at the end of each milestone with screenshots, links, and what is next. The build is the engagement; nothing is hidden until launch.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators-how-it-works.ts',
    exportPath: 'FO_HIW_STEPS.steps[3].body',
    proofGrade: 'outcome',
    text: 'At delivery, you receive: the admin login, the hosting account credentials in your name, the Stripe account in your name, and the source code in a Git repository you control. You operate the product without us.',
    evidence: [SELF_HOST, REPO],
  },
  {
    file: 'for-operators-how-it-works.ts',
    exportPath: 'FO_HIW_STEPS.steps[4].title',
    proofGrade: 'behavior',
    text: 'Ongoing support is optional.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators-how-it-works.ts',
    exportPath: 'FO_HIW_STEPS.steps[4].body',
    proofGrade: 'outcome',
    text: 'If you want a retainer for ongoing work (new features, scaled support, expansion engagements), we offer one. If you want to take it from here, you take it from here. There is no lock-in either way.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators-how-it-works.ts',
    exportPath: 'FO_HIW_FEAR.heading',
    proofGrade: 'outcome',
    text: 'Do I need a developer after this?',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators-how-it-works.ts',
    exportPath: 'FO_HIW_FEAR.paragraph1',
    proofGrade: 'behavior',
    text: "No, to operate the product. You log into the admin, manage your products, customers, content, and orders. The dashboard is the interface; you don't touch the code.",
    evidence: [COMMERCIAL_POLICY, COLLECTIONS],
  },
  {
    file: 'for-operators-how-it-works.ts',
    exportPath: 'FO_HIW_FEAR.paragraph2',
    proofGrade: 'behavior',
    text: 'Yes, to change the software itself. Adding a new feature, a new page, a new integration: that is engineering work. Two honest options:',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators-how-it-works.ts',
    exportPath: 'FO_HIW_FEAR.options[0].title',
    proofGrade: 'behavior',
    text: 'Hire RevealUI Studio for the change.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators-how-it-works.ts',
    exportPath: 'FO_HIW_FEAR.options[0].body',
    proofGrade: 'outcome',
    text: 'We know the codebase; we built it. This is a scoped follow-on engagement, not a retainer.',
    evidence: [COMMERCIAL_POLICY, BIO],
  },
  {
    file: 'for-operators-how-it-works.ts',
    exportPath: 'FO_HIW_FEAR.options[1].body',
    proofGrade: 'outcome',
    text: 'The code we hand over is standard TypeScript on standard tools: React, Vite, Hono, Drizzle. Any competent React engineer can pick it up.',
    evidence: [REPO],
  },
  {
    file: 'for-operators-how-it-works.ts',
    exportPath: 'FO_HIW_FEAR.closing',
    proofGrade: 'behavior',
    text: 'We do not pretend you become self-sufficient on the codebase. We do promise you are self-sufficient on operating the product.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators-how-it-works.ts',
    exportPath: 'FO_HIW_OWNERSHIP.heading',
    proofGrade: 'outcome',
    text: 'What ownership means at delivery.',
    evidence: [SELF_HOST],
  },
  {
    file: 'for-operators-how-it-works.ts',
    exportPath: 'FO_HIW_OWNERSHIP.intro',
    proofGrade: 'behavior',
    text: 'Three concrete claims, true today, not roadmap:',
    evidence: [SELF_HOST],
  },
  {
    file: 'for-operators-how-it-works.ts',
    exportPath: 'FO_HIW_OWNERSHIP.claims[0].body',
    proofGrade: 'outcome',
    text: 'The open-source RevealUI runtime plus your configuration, in a Git repository you control.',
    evidence: [REPO, LICENSE_MIT],
  },
  {
    file: 'for-operators-how-it-works.ts',
    exportPath: 'FO_HIW_OWNERSHIP.claims[1].title',
    proofGrade: 'behavior',
    text: 'The infrastructure is in your name.',
    evidence: [SELF_HOST],
  },
  {
    file: 'for-operators-how-it-works.ts',
    exportPath: 'FO_HIW_OWNERSHIP.claims[1].body',
    proofGrade: 'outcome',
    text: 'Vercel account, Neon database, Stripe account: all registered to your business, not RevealUI Studio.',
    evidence: [SELF_HOST],
  },
  {
    file: 'for-operators-how-it-works.ts',
    exportPath: 'FO_HIW_OWNERSHIP.claims[2].title',
    proofGrade: 'behavior',
    text: 'There is no vendor lock-in.',
    evidence: [SELF_HOST],
  },
  {
    file: 'for-operators-how-it-works.ts',
    exportPath: 'FO_HIW_OWNERSHIP.claims[2].body',
    proofGrade: 'outcome',
    text: 'If you walk away from RevealUI Studio tomorrow, your product keeps running and a different engineer can pick up the codebase. No proprietary platform to migrate off.',
    evidence: [SELF_HOST, REPO],
  },
  {
    file: 'for-operators-how-it-works.ts',
    exportPath: 'FO_HIW_OWNERSHIP.differentiator',
    proofGrade: 'behavior',
    text: 'This is a strong, honest differentiator from SaaS vendors who own your data and your platform.',
    evidence: [SELF_HOST],
  },
  {
    file: 'for-operators-how-it-works.ts',
    exportPath: 'FO_HIW_TIMELINE.paragraph1',
    proofGrade: 'behavior',
    text: 'Weeks, not quarters. The discovery call gives you the range for your specific scope.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators-how-it-works.ts',
    exportPath: 'FO_HIW_TIMELINE.paragraph2',
    proofGrade: 'behavior',
    text: 'We do not promise specific day-counts. The work is fixed-bid (Step 2), so the timeline is part of the scope you and we agree on in writing. What we do not do is "live in 14 days": that is a marketing promise, not an engineering reality.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators-how-it-works.ts',
    exportPath: 'FO_HIW_CLOSING.body',
    proofGrade: 'outcome',
    text: 'Book the discovery call. 30 minutes, free. We walk through your business and decide whether we are the right team for it.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_HERO.subtitle',
    proofGrade: 'outcome',
    text: 'A self-serve managed version of the runtime: sign up in a browser, configure your business, get a hosted product without an agency engagement. It does not ship today. This page is the honest roadmap.',
    evidence: [COMMERCIAL_POLICY, ROADMAP],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_STATUS.heading',
    proofGrade: 'outcome',
    text: 'Not built. On the roadmap.',
    evidence: [ROADMAP],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_STATUS.paragraph1',
    proofGrade: 'behavior',
    text: 'RevealUI Cloud does not exist today. There is no signup, no billing, no managed hosting you can configure in a browser.',
    evidence: [COMMERCIAL_POLICY, ROADMAP],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_STATUS.paragraph2',
    proofGrade: 'behavior',
    text: '(operator-lane studio-voice copy; path-pinned so the phrasing stays out of the fleet-voice register scan)',
    match: 'path',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_STATUS.paragraph3',
    proofGrade: 'behavior',
    text: 'This page is the honest version of the question "is there a managed offering?" Yes, on the roadmap; no, not yet.',
    evidence: [COMMERCIAL_POLICY, ROADMAP],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_WOULD_BE.heading',
    proofGrade: 'outcome',
    text: 'When RevealUI Cloud ships, you would:',
    evidence: [ROADMAP],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_WOULD_BE.capabilities[0].body',
    proofGrade: 'outcome',
    text: 'No agency call required. Email, payment method, business name: the SaaS-shape onboarding most operators expect.',
    evidence: [ROADMAP],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_WOULD_BE.capabilities[1].title',
    proofGrade: 'behavior',
    text: 'Configure the business in a browser.',
    evidence: [ROADMAP],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_WOULD_BE.capabilities[1].body',
    proofGrade: 'outcome',
    text: 'Name, branding, products, billing rates, customer-facing copy: all set up through a configuration UI, no code.',
    evidence: [ROADMAP],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_WOULD_BE.capabilities[2].title',
    proofGrade: 'behavior',
    text: 'Get a hosted instance in your account.',
    evidence: [ROADMAP],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_WOULD_BE.capabilities[2].body',
    proofGrade: 'outcome',
    text: 'The runtime, deployed and managed by RevealUI Studio, on infrastructure registered to your business.',
    evidence: [ROADMAP, SELF_HOST],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_WOULD_BE.capabilities[3].title',
    proofGrade: 'behavior',
    text: 'Operate via the admin dashboard.',
    evidence: [ROADMAP],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_WOULD_BE.capabilities[3].body',
    proofGrade: 'outcome',
    text: 'Same admin UI as the agency-delivered version. Same RBAC, same primitives.',
    evidence: [RBAC_ABAC, COLLECTIONS],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_WOULD_BE.capabilities[4].title',
    proofGrade: 'behavior',
    text: 'Receive product support directly.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_WOULD_BE.capabilities[4].body',
    proofGrade: 'outcome',
    text: 'Defined response times, defined escalation paths, included in the price. Not the bespoke retainer the agency offers: a productized support contract.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_WOULD_BE.closing',
    proofGrade: 'behavior',
    text: 'This is the SaaS-shape mental model operators arrive with. RevealUI Cloud is what fulfills it, when it ships.',
    evidence: [ROADMAP],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_PREREQS.heading',
    proofGrade: 'outcome',
    text: 'What has to be true before RevealUI Cloud ships.',
    evidence: [ROADMAP],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_PREREQS.intro',
    proofGrade: 'behavior',
    text: 'Four things must be in place before the managed offering can move from roadmap to real:',
    evidence: [ROADMAP],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_PREREQS.prerequisites[0].title',
    proofGrade: 'behavior',
    text: 'A managed SKU needs more than product billing.',
    evidence: [BILLING, ROADMAP],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_PREREQS.prerequisites[0].body',
    proofGrade: 'outcome',
    text: 'Self-serve product tiers can charge in live mode today. A managed Cloud offering still needs automated per-operator provisioning, an operator configuration UI, and a productized support contract before signup means a hosted instance. Those three are unbuilt; the agency engagement is the path that ships.',
    evidence: [BILLING, ROADMAP],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_PREREQS.prerequisites[1].title',
    proofGrade: 'behavior',
    text: 'A provisioning path that stands up a per-operator hosted instance, without a human.',
    evidence: [ROADMAP],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_PREREQS.prerequisites[1].body',
    proofGrade: 'outcome',
    text: 'This is real engineering work, unbuilt today. The agency engagement stands up each operator manually; the managed offering needs that automated.',
    evidence: [ROADMAP],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_PREREQS.prerequisites[2].title',
    proofGrade: 'behavior',
    text: 'An operator-legible configuration UI.',
    evidence: [ROADMAP],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_PREREQS.prerequisites[2].body',
    proofGrade: 'outcome',
    text: 'The operator configures the business in a browser: branding, products, payments, copy. The UI to do that does not exist today.',
    evidence: [ROADMAP],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_PREREQS.prerequisites[3].title',
    proofGrade: 'behavior',
    text: 'A defined support contract for self-serve operators.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_PREREQS.prerequisites[3].body',
    proofGrade: 'outcome',
    text: 'The agency engagement has support baked into the relationship. A self-serve tier needs an explicit shape (what is included, response times, escalation) that the agency motion does not currently formalize.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_PREREQS.closing',
    proofGrade: 'behavior',
    text: 'Each prerequisite is a multi-week-to-multi-month engineering effort. The work is funded by revenue from the agency engagement.',
    evidence: [COMMERCIAL_POLICY, ROADMAP],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_TODAY.heading',
    proofGrade: 'outcome',
    text: 'Book the agency engagement.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_TODAY.body',
    proofGrade: 'outcome',
    text: '(operator-lane studio-voice copy; path-pinned so the phrasing stays out of the fleet-voice register scan)',
    match: 'path',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_TODAY.detailLink.label',
    proofGrade: 'path',
    text: 'Read how the engagement works →',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_WAITLIST.heading',
    proofGrade: 'outcome',
    text: 'Enterprise is a license. Contact sales.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_WAITLIST.body',
    proofGrade: 'outcome',
    text: 'You self-host. Studio does not operate a customer VM. Inquire: Enterprise is not a public monthly SKU.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators-managed.ts',
    exportPath: 'FO_MANAGED_WAITLIST.successMessage',
    proofGrade: 'path',
    text: 'Enterprise is inquire / Contact sales.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'LOCAL_AI_SECTION.heading',
    proofGrade: 'outcome',
    text: 'Your agents run on models you host.',
    evidence: [OPEN_WEIGHT],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'LOCAL_AI_SECTION.body',
    proofGrade: 'outcome',
    text: 'By default, agents run on open-weight models on infrastructure you control. Their work stays in your boundary. Your AI bill is your own inference cost.',
    evidence: [OPEN_WEIGHT, LLM_CLIENT],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'LOCAL_AI_SECTION.beats[0].body',
    proofGrade: 'outcome',
    text: 'In the default config, inference runs where you host it. Content agents read and write does not leave your boundary for a hosted model API.',
    evidence: [OPEN_WEIGHT],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'LOCAL_AI_SECTION.beats[1].body',
    proofGrade: 'outcome',
    text: 'You pay for your own inference and compute, not a per-token tax that scales with usage.',
    evidence: [OPEN_WEIGHT],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'LOCAL_AI_SECTION.beats[2].body',
    proofGrade: 'outcome',
    text: 'When you want a frontier model, add it in one config line: opt-in, never assumed.',
    evidence: [PROVIDERS, OPENAI_COMPAT],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'LOCAL_AI_SECTION.snippet.caption',
    proofGrade: 'behavior',
    text: 'One line picks your model runner. Frontier providers stay opt-in adapters, never the default.',
    evidence: [LLM_CLIENT],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'LOCAL_AI_SECTION.snippet.lines[0].note',
    proofGrade: 'behavior',
    text: 'gemma3 on your box, port 9090 (default runner)',
    evidence: [LLM_CLIENT],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'LOCAL_AI_SECTION.snippet.lines[1].note',
    proofGrade: 'behavior',
    text: 'qwen2.5:3b on your box, port 11434',
    evidence: [OLLAMA],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'LOCAL_AI_SECTION.dogfood',
    proofGrade: 'behavior',
    text: 'The maintainers run local inference themselves on Inference Snaps and Ollama.',
    evidence: [OPEN_WEIGHT, OLLAMA],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'LOCAL_AI_SECTION.honesty',
    proofGrade: 'behavior',
    text: 'Local inference needs an open-weight model runner (Ollama or Ubuntu Inference Snaps) and enough hardware. Frontier models still lead the hardest work, which is why they stay one config line away.',
    evidence: [OPEN_WEIGHT, LLM_CLIENT],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'LOCAL_AI_PAGE.h1',
    proofGrade: 'outcome',
    text: 'Run your AI on infrastructure you own.',
    evidence: [OPEN_WEIGHT, SELF_HOST],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'LOCAL_AI_PAGE.lead',
    proofGrade: 'outcome',
    text: 'RevealUI is open-model first. The runtime does not require a hosted model API. Open-weight models are the default. A frontier provider is one opt-in config line, not the default. Ownership leads. Local AI is how you prove it.',
    evidence: [OPEN_WEIGHT, PROVIDERS],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'LOCAL_AI_PAGE.pillars[0].title',
    proofGrade: 'outcome',
    text: 'Your data stays in your boundary',
    evidence: [OPEN_WEIGHT],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'LOCAL_AI_PAGE.pillars[0].body',
    proofGrade: 'outcome',
    text: 'In the default config, agents run on an open-weight model you host. No hosted model API sits between your code and your business data.',
    evidence: [OPEN_WEIGHT],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'LOCAL_AI_PAGE.pillars[1].title',
    proofGrade: 'outcome',
    text: 'Your inference cost, not a per-token tax',
    evidence: [OPEN_WEIGHT],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'LOCAL_AI_PAGE.pillars[1].body',
    proofGrade: 'outcome',
    text: 'You pay for your own inference and compute, not a per-token fee that scales with usage. Frontier API prices have moved up; local and commodity inference keep falling.',
    evidence: [OPEN_WEIGHT, MARKET_CITATIONS],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'LOCAL_AI_PAGE.pillars[2].title',
    proofGrade: 'outcome',
    text: 'Frontier is one opt-in line away',
    evidence: [PROVIDERS, OPENAI_COMPAT],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'LOCAL_AI_PAGE.pillars[2].body',
    proofGrade: 'outcome',
    text: 'Start on open weights running locally. When a task needs a frontier model, add the provider as an opt-in adapter, not as the default.',
    evidence: [PROVIDERS, OPENAI_COMPAT],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'LOCAL_AI_PAGE.marketProof.heading',
    proofGrade: 'outcome',
    text: 'Open and local models already run where data cannot leave.',
    evidence: [MARKET_CITATIONS],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'LOCAL_AI_PAGE.marketProof.body',
    proofGrade: 'outcome',
    text: 'In regulated and high-stakes work, teams already self-host open-weight models so sensitive data stays inside their boundary. That is where RevealUI fits: good enough and yours beats best and rented.',
    evidence: [MARKET_CITATIONS],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'LOCAL_AI_PAGE.marketProof.adopters[0].detail',
    proofGrade: 'behavior',
    text: 'Finance, defense, and other regulated teams already run open-weight models on infrastructure they control when sensitive data must stay inside their boundary.',
    evidence: [MARKET_CITATIONS],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'LOCAL_AI_PAGE.marketProof.adopters[0].source',
    proofGrade: 'behavior',
    text: 'Market pattern, not RevealUI customers',
    evidence: [MARKET_CITATIONS],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'LOCAL_AI_PAGE.marketProof.disclaimer',
    proofGrade: 'behavior',
    text: 'This is an industry pattern, not a RevealUI customer list. Use it to place the runtime, not as social proof of our install base.',
    evidence: [MARKET_CITATIONS],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'LOCAL_AI_PAGE.roadmap.body',
    proofGrade: 'outcome',
    text: 'An air-gapped, container-image path for fully disconnected environments. Not shipped yet. Tracked on the roadmap.',
    evidence: [ROADMAP],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'PROVIDER_SWITCH.modes.local.model',
    proofGrade: 'behavior',
    text: 'gemma3, open-weight (US-origin)',
    evidence: [LLM_CLIENT, OPEN_WEIGHT],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'PROVIDER_SWITCH.modes.local.cost',
    proofGrade: 'behavior',
    text: 'Your inference cost, no per-token fee',
    evidence: [OPEN_WEIGHT],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'PROVIDER_SWITCH.modes.frontier.model',
    proofGrade: 'behavior',
    text: 'GPT or any OpenAI-compatible provider',
    evidence: [OPENAI_COMPAT, OLLAMA, LLM_CLIENT],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'PROVIDER_SWITCH.modes.frontier.locus',
    proofGrade: 'behavior',
    text: 'Calls the vendor API you choose',
    evidence: [PROVIDERS],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'PROVIDER_SWITCH.modes.frontier.config',
    proofGrade: 'behavior',
    text: 'add a frontier adapter, one config line',
    evidence: [OPENAI_COMPAT],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'FRONTIER_PATHWAY.heading',
    proofGrade: 'outcome',
    text: 'Start local. Escalate on purpose.',
    evidence: [PROVIDERS],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'FRONTIER_PATHWAY.steps[0].body',
    proofGrade: 'outcome',
    text: 'Agents run on an open-weight model on your machine. No hosted provider required to start.',
    evidence: [OPEN_WEIGHT],
  },
  {
    file: 'local-ai.ts',
    exportPath: 'FRONTIER_PATHWAY.steps[1].body',
    proofGrade: 'outcome',
    text: 'When a task needs a frontier model, add the provider in one config line. Opt-in, never assumed.',
    evidence: [OPENAI_COMPAT, PROVIDERS],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_HERO.eyebrow',
    text: 'License contract for the Pro packages',
    evidence: [LICENSE_SPLIT],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_HERO.subhead',
    text: '(interpolated: FSL count from METRICS.licenseSplit.fsl)',
    match: 'path',
    evidence: [LICENSE_SPLIT],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_HERO.body.prefix',
    text: '(interpolated: MIT + FSL counts from METRICS.licenseSplit)',
    match: 'path',
    evidence: [LICENSE_SPLIT, LICENSE_MIT],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_HERO.body.suffix',
    text: '(interpolated: internal-package count from METRICS.licenseSplit.internal)',
    match: 'path',
    evidence: [LICENSE_SPLIT, FSL_PEERS_CITATION],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_HERO.ogSubtitle',
    text: 'Source-visible. Commercially usable. MIT in two years.',
    evidence: [LICENSE_MIT],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_CONTRACT_SECTION.eyebrow',
    text: 'The contract, in plain English',
    evidence: [FAIR_SOURCE_PAGE],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_CONTRACT_CARDS[0].body',
    text: 'Ship Fair Source code in your product, charge customers, run it in production. No royalties, no per-seat fees, no usage caps.',
    evidence: [FAIR_SOURCE_PAGE, LICENSE_MIT],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_CONTRACT_CARDS[1].title',
    text: 'Read and modify the source',
    evidence: [REPO],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_CONTRACT_CARDS[1].body',
    text: 'Every line is on GitHub. Fork it, patch it, audit it for security. The source is the source of truth. There is no closed binary hiding behind it.',
    evidence: [REPO],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_CONTRACT_CARDS[2].title',
    text: 'Self-host on your own infra',
    evidence: [SELF_HOST],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_CONTRACT_CARDS[2].body',
    text: 'Run it in your VPC, on bare metal, or air-gapped. RevealUI does not phone home and does not depend on a vendor service to function.',
    evidence: [SELF_HOST, NO_TELEMETRY],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_CONTRACT_CARDS[3].title',
    text: 'Build a competing developer platform',
    evidence: [FAIR_SOURCE_PAGE],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_CONTRACT_CARDS[3].body',
    text: 'You cannot ship a substantially similar developer platform that competes with RevealUI on top of these packages. This is the only restriction. After two years, even this restriction lifts and the release becomes plain MIT.',
    evidence: [FAIR_SOURCE_PAGE, LICENSE_MIT],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_PACKAGES_SECTION.heading',
    text: 'Which RevealUI packages are Fair Source.',
    evidence: [LICENSE_SPLIT],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_PACKAGES_SECTION.body.prefix',
    text: 'Five packages carry FSL-1.1-MIT: the four published to npm are listed below, plus the private',
    evidence: [LICENSE_SPLIT],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_PACKAGES_SECTION.body.suffix',
    text: 'workspace package. Every other RevealUI package is plain MIT: no non-compete, no time limit, fully open source.',
    evidence: [LICENSE_MIT, LICENSE_SPLIT],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_PACKAGES_SECTION.footer.prefix',
    text: "Looking for a specific package's license? Run",
    evidence: [LICENSE_SPLIT],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_PACKAGES_SECTION.footer.suffix',
    text: ': npm always tells the truth.',
    evidence: [LICENSE_SPLIT],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_PACKAGES[0].purpose',
    text: 'AI agents, CRDT memory, LLM provider abstractions, orchestration',
    evidence: [MEMORY, PROVIDERS, ORCHESTRATOR],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_PACKAGES[1].purpose',
    text: 'AI harness adapters, workboard coordination, JSON-RPC primitives',
    evidence: [HARNESS_ADAPTER, HARNESS_WORKBOARD],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_PACKAGES[2].purpose',
    text: 'MCP framework: server hypervisor, adapter pattern, tool discovery',
    evidence: [HYPERVISOR, MCP_SERVERS],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_PACKAGES[3].purpose',
    text: 'External service integrations: Stripe billing and email delivery.',
    evidence: [SERVICES_STRIPE],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_CLOCK_SECTION.heading',
    text: 'Every release auto-converts to MIT.',
    evidence: [LICENSE_MIT],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_CLOCK_SECTION.body',
    text: "The 2-year timer starts on each release's publish date. Older releases reach MIT first; newer releases start their own clock from their own publish date. The clause does not require any action from RevealUI Studio. It is in the license text and self-executing.",
    evidence: [LICENSE_MIT, FAIR_SOURCE_PAGE],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_CLOCK_SECTION.steps[0].title',
    text: 'Release publishes under FSL-1.1-MIT',
    evidence: [FAIR_SOURCE_PAGE],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_CLOCK_SECTION.steps[0].body',
    text: 'Source on GitHub. Installable from npm. The 2-year clock starts ticking the moment the version tag lands.',
    evidence: [REPO, FAIR_SOURCE_PAGE],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_CLOCK_SECTION.steps[1].body',
    text: 'All freedoms apply (use commercially, modify, self-host) except the non-compete clause. You build on it, you ship products with it, you charge customers for those products.',
    evidence: [FAIR_SOURCE_PAGE],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_CLOCK_SECTION.steps[2].title',
    text: 'Two years later: plain MIT',
    evidence: [LICENSE_MIT],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_CLOCK_SECTION.steps[2].body',
    text: 'That specific release auto-converts to plain MIT. The non-compete clause lifts; the license becomes OSI-approved open source.',
    evidence: [LICENSE_MIT],
  },
];
