import {
  A2A_ROUTES,
  ADMIN_LICENSE_PAGE,
  AGENCY_PERPETUAL_FEATURES,
  AUDIT_ANCHOR_API,
  AUDIT_ANCHOR_VERIFY_CLI,
  AUDIT_ANCHOR_VERIFY_TEST,
  AUDIT_LOG_FEATURE_MAX,
  AUDIT_MERKLE,
  AUDIT_RECEIPTS_DOC,
  AUDIT_ROW_SIGNER,
  AUDIT_SIGN_ROUNDTRIP,
  AUTH_SESSIONS,
  BILLING,
  BIO,
  CHECKOUT_PERPETUAL_ROUTE,
  CLI_CREATE,
  COLLECTIONS,
  COMMERCIAL_POLICY,
  EMAIL_AGENT,
  FAIR_SOURCE_PAGE,
  FEATURES_MATRIX,
  LICENSE_MIT,
  LICENSE_SPLIT,
  LIVE_AGENT_CARD,
  MCP_SERVERS,
  MEMORY,
  OPEN_WEIGHT,
  PERPETUAL,
  PERPETUAL_MINT_LIMITS,
  PERPETUAL_MINT_LIMITS_TEST,
  PERPETUAL_NEVER_EXPIRES_TEST,
  PRICING_FALLBACKS,
  PROVIDERS,
  RBAC_ABAC,
  REPO,
  REVCON_REPO,
  REVDEV_REPO,
  REVFORGE_REF,
  REVSKILLS_REPO,
  REVVAULT_REPO,
  ROADMAP,
  SELF_HOST,
  SLA_PAGE,
  STARTER_KIT,
  STARTER_KIT_GETTING_STARTED,
  STARTER_KIT_RECEIPT_TEST,
  TASK_QUOTA,
  THIS_SITE,
  TIER_GATES,
  TIER_LIMITS,
  TRIAL,
  WAITLIST,
  X402,
  X402_FACILITATOR,
} from './shared-refs.js';
import type { ClaimEntry } from './types.js';

export const claimsPart2: readonly ClaimEntry[] = [
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_AGENCY_VALUE_BAND.points[1]',
    text: 'White-label stamping via RevForge, in private preview.',
    evidence: [REVFORGE_REF, FEATURES_MATRIX],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_AGENCY_VALUE_BAND.points[2]',
    text: 'Each client owns their data, infrastructure, and Stripe account. Clean handoff, no lock-in.',
    evidence: [SELF_HOST, COMMERCIAL_POLICY],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_AGENCY_VALUE_BAND.points[3]',
    text: 'One runtime, one upgrade cadence across every client you serve.',
    evidence: [PERPETUAL],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_STARTER_KIT.body',
    text: 'A content-only kit for builders who want governed agent recipes and signed receipt demos on top of create-revealui, without buying a Pro subscription. Not a Pro entitlement and not a full Fleet stamp.',
    evidence: [STARTER_KIT, STARTER_KIT_GETTING_STARTED, CLI_CREATE, STARTER_KIT_RECEIPT_TEST],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_STARTER_KIT.points[0]',
    text: 'npm create-revealui path plus Postgres-only bootstrap scripts',
    evidence: [STARTER_KIT_GETTING_STARTED, CLI_CREATE],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_STARTER_KIT.points[1]',
    text: 'Governed agent recipes that write a receipt you can verify offline',
    evidence: [STARTER_KIT, STARTER_KIT_RECEIPT_TEST],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_STARTER_KIT.points[2]',
    text: 'Ships as content and scripts, not a Pro license key or runtime upgrade',
    evidence: [STARTER_KIT, COMMERCIAL_POLICY],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_STARTER_KIT.points[3]',
    text: 'Checkout on Stripe; private GitHub repo access and Substack invite are manual at launch volume',
    evidence: [STARTER_KIT],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_STARTER_KIT.primaryCta.label',
    text: 'Buy the RevealUI Starter Kit',
    evidence: [STARTER_KIT],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_STARTER_KIT.secondaryCta.label',
    text: 'Read the kit getting-started guide',
    evidence: [STARTER_KIT_GETTING_STARTED],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_AGENCY_FOUNDING_KIT.heading',
    text: 'RevealUI Agency Founding Kit',
    evidence: [AGENCY_PERPETUAL_FEATURES, ADMIN_LICENSE_PAGE],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_AGENCY_FOUNDING_KIT.body',
    // Resolved string: fleetDeploymentPrice is interpolated from AGENCY_ENGAGEMENT_LADDER.
    text: 'The middle rung for small agencies and MSPs: a signed Agency-tier license (Max features, up to 10 client deployments) plus the path to stamp branded, self-hosted kits for your clients. Not the $299 content-only Starter Kit, and not the $25,000 done-with-you Fleet engagement.',
    match: 'path',
    evidence: [
      AGENCY_PERPETUAL_FEATURES,
      CHECKOUT_PERPETUAL_ROUTE,
      ADMIN_LICENSE_PAGE,
      PERPETUAL_MINT_LIMITS,
      PERPETUAL_MINT_LIMITS_TEST,
      PERPETUAL_NEVER_EXPIRES_TEST,
    ],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_AGENCY_FOUNDING_KIT.points[0]',
    text: 'Agency Perpetual license key that never expires, with one year of support included',
    evidence: [AGENCY_PERPETUAL_FEATURES, PERPETUAL, PERPETUAL_NEVER_EXPIRES_TEST],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_AGENCY_FOUNDING_KIT.points[1]',
    text: 'Up to 10 client deployments under one Agency license (Max-tier runtime entitlements)',
    evidence: [
      AGENCY_PERPETUAL_FEATURES,
      PERPETUAL_MINT_LIMITS,
      PERPETUAL_MINT_LIMITS_TEST,
      TIER_LIMITS,
    ],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_AGENCY_FOUNDING_KIT.points[2]',
    text: 'Checkout on Stripe through your RevealUI account license page after you sign in',
    evidence: [CHECKOUT_PERPETUAL_ROUTE, ADMIN_LICENSE_PAGE, BILLING],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_AGENCY_FOUNDING_KIT.points[3]',
    text: 'Monthly Max subscription at $299 per month is available if you are not ready for the one-time buy',
    evidence: [PRICING_FALLBACKS, BILLING],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_AGENCY_FOUNDING_KIT.primaryCta.label',
    text: 'Buy the Agency Founding Kit',
    evidence: [ADMIN_LICENSE_PAGE, CHECKOUT_PERPETUAL_ROUTE],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_AGENCY_FOUNDING_KIT.secondaryCta.label',
    text: 'Compare perpetual licenses on this page',
    evidence: [PERPETUAL, AGENCY_PERPETUAL_FEATURES],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_AGENCY_FOUNDING_KIT.monthlyEscape.label',
    text: 'See Max monthly subscription',
    evidence: [PRICING_FALLBACKS, BILLING],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_AGENTS_SECTION.subhead',
    text: 'Agents discover, authenticate, and pay without human intervention.',
    evidence: [LIVE_AGENT_CARD, AUTH_SESSIONS, X402],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_AGENT_A2A.body.prefix',
    text: 'Agents find RevealUI via a standard Agent Card at',
    evidence: [LIVE_AGENT_CARD, A2A_ROUTES],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_AGENT_A2A.body.suffix',
    text: '. Capabilities, skills, and pricing all machine-readable.',
    evidence: [LIVE_AGENT_CARD],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_AGENT_X402.body',
    text: 'RevealUI implements the HTTP 402 payment protocol. Built on the open x402 standard, with a Coinbase-compatible facilitator implemented. Agents pay agents over standard HTTP. No accounts, no subscriptions. The rail ships in the code and activates when the operator configures a receiving wallet; it is not switched on today.',
    evidence: [X402, X402_FACILITATOR],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_AGENT_MCP.body',
    text: 'N production MCP servers including Stripe, Neon, Vercel, Playwright, Next.js DevTools, content management, and email. Marketplace discovery coming soon. (interpolated: N from METRICS.mcpServers)',
    match: 'path',
    evidence: [MCP_SERVERS],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_DONE_FOR_YOU.heading',
    text: 'Want it built and handed over?',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_DONE_FOR_YOU.body',
    text: 'RevealUI Studio ships fixed-bid work on the runtime. Starting prices below. Discovery scopes the engagement. Full detail lives on the Studio site and the product Services page.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_DONE_FOR_YOU.rungs[0].note',
    text: 'Fixed-bid written assessment of your project, schema, deployment, and security posture. Credited toward a Fleet deployment if you proceed within 30 days.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_DONE_FOR_YOU.rungs[1].note',
    text: 'Your RevealUI instance is set up, configured, and deployed to production, with a full handoff session included.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_DONE_FOR_YOU.rungs[2].note',
    text: 'A branded, self-hosted RevealUI deployment for your business or your clients. Starting point, scoped in discovery.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_DONE_FOR_YOU.rungs[3].note',
    text: 'Bespoke platform engagement, 4 to 12 week sprints. Starting point, scoped in discovery.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_DONE_FOR_YOU.secondaryCta.label',
    text: 'See full services on Studio →',
    evidence: [{ kind: 'url', ref: 'https://revealuistudio.com', note: 'agency site link label' }],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_FINAL_CTA.title',
    text: 'Start free with full source access.',
    evidence: [LICENSE_MIT, TIER_LIMITS],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_FINAL_CTA.subtitle',
    text: 'Every tier ships the complete source. Upgrade when your business needs Pro features.',
    evidence: [LICENSE_MIT, TIER_GATES],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_NEWSLETTER_LABEL',
    text: 'Not ready yet? Get release updates by email.',
    evidence: [WAITLIST],
  },
  {
    file: 'pricing.ts',
    exportPath: 'SUBSCRIPTION_TIERS[0].description',
    text: 'Perfect for trying out RevealUI and small projects.',
    evidence: [TIER_LIMITS],
  },
  {
    file: 'pricing.ts',
    exportPath: 'SUBSCRIPTION_TIERS[0].features[0]',
    text: 'Unlimited admin collections',
    evidence: [COLLECTIONS],
  },
  {
    file: 'pricing.ts',
    exportPath: 'SUBSCRIPTION_TIERS[0].features[5]',
    text: 'Local AI inference (Inference Snaps / Ollama)',
    evidence: [OPEN_WEIGHT],
  },
  {
    file: 'pricing.ts',
    exportPath: 'SUBSCRIPTION_TIERS[1].description',
    text: 'For software companies building production products.',
    evidence: [TIER_LIMITS],
  },
  {
    file: 'pricing.ts',
    exportPath: 'SUBSCRIPTION_TIERS[1].features[0]',
    text: 'Unlimited admin collections',
    evidence: [COLLECTIONS],
  },
  {
    file: 'pricing.ts',
    exportPath: 'SUBSCRIPTION_TIERS[1].features[4]',
    text: 'AI agents (local + cloud via RevealUI harness)',
    evidence: [OPEN_WEIGHT, PROVIDERS],
  },
  {
    file: 'pricing.ts',
    exportPath: 'SUBSCRIPTION_TIERS[1].features[9]',
    text: '10,000 agent tasks/month included',
    evidence: [TIER_LIMITS],
  },
  {
    file: 'pricing.ts',
    exportPath: 'SUBSCRIPTION_TIERS[1].features[10]',
    text: 'RevVault desktop app (encrypted secret management)',
    evidence: [REVVAULT_REPO],
  },
  {
    file: 'pricing.ts',
    exportPath: 'SUBSCRIPTION_TIERS[1].features[11]',
    text: 'RevVault rotation engine (automated credential lifecycle)',
    evidence: [REVVAULT_REPO],
  },
  {
    file: 'pricing.ts',
    exportPath: 'SUBSCRIPTION_TIERS[1].features[12]',
    text: 'Email support (48h response)',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'pricing.ts',
    exportPath: 'SUBSCRIPTION_TIERS[1].cta',
    text: 'Start your 7-day free trial',
    evidence: [TRIAL],
  },
  {
    file: 'pricing.ts',
    exportPath: 'SUBSCRIPTION_TIERS[2].description',
    text: 'For teams that need AI memory, advanced inference, and compliance tooling.',
    evidence: [MEMORY, PROVIDERS, RBAC_ABAC],
  },
  {
    file: 'pricing.ts',
    exportPath: 'SUBSCRIPTION_TIERS[2].features[3]',
    text: 'Full AI memory (working + episodic + vector)',
    evidence: [MEMORY],
  },
  {
    file: 'pricing.ts',
    exportPath: 'SUBSCRIPTION_TIERS[2].features[4]',
    text: 'Advanced inference configuration (coming soon)',
    evidence: [PROVIDERS],
  },
  {
    file: 'pricing.ts',
    exportPath: 'SUBSCRIPTION_TIERS[2].features[5]',
    text: 'Signed audit log plus downloadable Merkle roots you verify offline',
    evidence: [
      AUDIT_ROW_SIGNER,
      AUDIT_MERKLE,
      AUDIT_ANCHOR_API,
      AUDIT_ANCHOR_VERIFY_CLI,
      AUDIT_ANCHOR_VERIFY_TEST,
      AUDIT_SIGN_ROUNDTRIP,
      AUDIT_LOG_FEATURE_MAX,
      AUDIT_RECEIPTS_DOC,
    ],
  },
  {
    file: 'pricing.ts',
    exportPath: 'SUBSCRIPTION_TIERS[2].features[6]',
    text: '50,000 agent tasks/month included',
    evidence: [TIER_LIMITS],
  },
  {
    file: 'pricing.ts',
    exportPath: 'SUBSCRIPTION_TIERS[2].features[7]',
    text: 'RevKit environment provisioning (coming soon)',
    evidence: [ROADMAP],
  },
  {
    file: 'pricing.ts',
    exportPath: 'SUBSCRIPTION_TIERS[2].features[8]',
    text: 'Email support (24h response)',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'pricing.ts',
    exportPath: 'SUBSCRIPTION_TIERS[2].cta',
    text: 'Start your 7-day free trial',
    evidence: [TRIAL],
  },
  {
    file: 'pricing.ts',
    exportPath: 'SUBSCRIPTION_TIERS[3].description',
    text: 'Full ecosystem access with scale, compliance, and agent payments.',
    evidence: [TIER_LIMITS, RBAC_ABAC, X402],
  },
  {
    file: 'pricing.ts',
    exportPath: 'SUBSCRIPTION_TIERS[3].features[3]',
    text: 'Session-based auth + OAuth',
    evidence: [AUTH_SESSIONS],
  },
  {
    file: 'pricing.ts',
    exportPath: 'SUBSCRIPTION_TIERS[3].features[4]',
    text: 'Full inference suite (all open models)',
    evidence: [PROVIDERS, OPEN_WEIGHT],
  },
  {
    file: 'pricing.ts',
    exportPath: 'SUBSCRIPTION_TIERS[3].features[5]',
    text: 'x402 agent payments (USDC, coming soon)',
    evidence: [X402, X402_FACILITATOR],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PERPETUAL_TIERS[0].description',
    text: 'Pro features, forever. No subscription required.',
    evidence: [PERPETUAL],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PERPETUAL_TIERS[0].renewal',
    text: '$149/yr for continued support',
    evidence: [PERPETUAL, PRICING_FALLBACKS],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PERPETUAL_TIERS[0].features[2]',
    text: '1 year priority support included',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PERPETUAL_TIERS[0].features[3]',
    text: 'All Pro updates released during support period',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PERPETUAL_TIERS[0].features[4]',
    text: 'Private GitHub repo access',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PERPETUAL_TIERS[1].description',
    text: 'RevealUI Fleet license for agencies. Sell branded RevealUI to your clients without per-site subscriptions.',
    evidence: [PERPETUAL, REVFORGE_REF],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PERPETUAL_TIERS[1].renewal',
    text: '$799/yr for continued support',
    evidence: [PERPETUAL, PRICING_FALLBACKS],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PERPETUAL_TIERS[1].features[2]',
    text: 'Up to 10 client deployments',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PERPETUAL_TIERS[1].features[3]',
    text: '1 year priority support included',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PERPETUAL_TIERS[1].features[4]',
    text: 'All Max updates released during support period',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PERPETUAL_TIERS[1].features[5]',
    text: 'Private GitHub repo access',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PERPETUAL_TIERS[2].description',
    text: 'Full self-hosted Enterprise tier with unlimited deployments.',
    evidence: [PERPETUAL, SELF_HOST],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PERPETUAL_TIERS[2].renewal',
    text: '$3,999/yr for continued support',
    evidence: [PERPETUAL, PRICING_FALLBACKS],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PERPETUAL_TIERS[2].features[0]',
    text: 'All Enterprise tier features',
    evidence: [TIER_LIMITS],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PERPETUAL_TIERS[2].features[2]',
    text: 'Unlimited self-hosted deployments',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PERPETUAL_TIERS[2].features[3]',
    text: '1 year priority support included',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PERPETUAL_TIERS[2].features[4]',
    text: 'All Enterprise tier updates released during support period',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PERPETUAL_TIERS[2].features[5]',
    text: 'Private GitHub repo + Docker image access',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'pricing-faq.ts',
    exportPath: 'PRICING_FAQS[0].question',
    text: 'Can I use the Free tier for commercial projects?',
    evidence: [
      { kind: 'code', ref: 'LICENSE', note: 'question copy; the answer carries the claims' },
    ],
  },
  {
    file: 'pricing-faq.ts',
    exportPath: 'PRICING_FAQS[0].answer',
    text: 'Yes. The Free tier is fully open-source (MIT) and can be used for commercial projects. You get full source code access and can deploy it anywhere you like.',
    evidence: [LICENSE_MIT, SELF_HOST],
  },
  {
    file: 'pricing-faq.ts',
    exportPath: 'PRICING_FAQS[1].question',
    text: 'What happens after the free trial ends?',
    evidence: [TRIAL],
  },
  {
    file: 'pricing-faq.ts',
    exportPath: 'PRICING_FAQS[1].answer',
    text: "Pro and Max tiers include a 7-day free trial. After the trial ends, you'll be charged the monthly rate. You can cancel anytime during the trial without being charged.",
    evidence: [TRIAL, BILLING],
  },
  {
    file: 'pricing-faq.ts',
    exportPath: 'PRICING_FAQS[2].question',
    text: 'How does agent task billing work?',
    evidence: [TASK_QUOTA],
  },
  {
    file: 'pricing-faq.ts',
    exportPath: 'PRICING_FAQS[2].answer',
    text: 'Every paid subscription includes a monthly task allowance: 10,000 tasks on Pro, 50,000 on Max, unlimited on Enterprise. Metered overage billing ships later; nothing is charged beyond the allowance today.',
    evidence: [TIER_LIMITS, TASK_QUOTA],
  },
  {
    file: 'pricing-faq.ts',
    exportPath: 'PRICING_FAQS[3].question',
    text: 'What are perpetual licenses?',
    evidence: [PERPETUAL],
  },
  {
    file: 'pricing-faq.ts',
    exportPath: 'PRICING_FAQS[3].answer',
    text: 'A perpetual license is a one-time purchase that gives you a license key for the corresponding tier, forever, with no monthly subscription required. Support and updates are included for 1 year; after that, renew your support contract or keep using the version you have.',
    evidence: [PERPETUAL, COMMERCIAL_POLICY],
  },
  {
    file: 'pricing-faq.ts',
    exportPath: 'PRICING_FAQS[4].question',
    text: 'What is the RevealUI Starter Kit?',
    evidence: [STARTER_KIT],
  },
  {
    file: 'pricing-faq.ts',
    exportPath: 'PRICING_FAQS[4].answer',
    text: 'The Starter Kit is a $299 one-time, content-only product. It packages create-revealui onboarding, Postgres bootstrap, and governed agent recipes that demonstrate signed receipts you can verify offline. It does not include a Pro subscription entitlement or a full RevealUI Fleet stamp. Checkout is on Stripe. After purchase we invite you to the private kit repo and Substack section within one business day.',
    evidence: [STARTER_KIT, STARTER_KIT_GETTING_STARTED, CLI_CREATE, STARTER_KIT_RECEIPT_TEST],
  },
  {
    file: 'pricing-faq.ts',
    exportPath: 'PRICING_FAQS[5].question',
    text: 'What is the RevealUI Agency Founding Kit?',
    evidence: [AGENCY_PERPETUAL_FEATURES, ADMIN_LICENSE_PAGE],
  },
  {
    file: 'pricing-faq.ts',
    exportPath: 'PRICING_FAQS[5].answer',
    text: 'The Agency Founding Kit is the Agency Perpetual license productized for small agencies and MSPs: $8,499 one-time for Max-tier runtime entitlements with up to 10 client deployments, one year of support, and a license key that never expires. You check out through your signed-in account license page on Stripe. It is not the $299 content-only Starter Kit, and it is not the high-touch done-with-you Fleet engagement. A Max monthly subscription remains available if you prefer recurring billing.',
    evidence: [
      AGENCY_PERPETUAL_FEATURES,
      CHECKOUT_PERPETUAL_ROUTE,
      ADMIN_LICENSE_PAGE,
      PERPETUAL_MINT_LIMITS,
      PERPETUAL_MINT_LIMITS_TEST,
      PERPETUAL_NEVER_EXPIRES_TEST,
      STARTER_KIT,
    ],
  },
  {
    file: 'pricing-faq.ts',
    exportPath: 'PRICING_FAQS[6].question',
    text: 'Can I upgrade or downgrade my plan?',
    evidence: [BILLING],
  },
  {
    file: 'pricing-faq.ts',
    exportPath: 'PRICING_FAQS[6].answer',
    text: "Yes, you can upgrade your plan at any time. You'll be charged the prorated amount immediately. To downgrade, visit your billing portal or contact support. (interpolated: SITE.emails.support)",
    match: 'path',
    evidence: [BILLING],
  },
  {
    file: 'pricing-faq.ts',
    exportPath: 'PRICING_FAQS[7].question',
    text: 'How does AI inference work?',
    evidence: [OPEN_WEIGHT],
  },
  {
    file: 'pricing-faq.ts',
    exportPath: 'PRICING_FAQS[7].answer',
    text: 'Bring your own model. The default ships open-weight (Gemma-family and other open-weight models) via Ollama or Ubuntu Inference Snaps from Canonical (canonical default, Studio lifecycle pending), so your bill does not scale with usage. Switch to Claude, GPT, or any OpenAI-compatible provider in one config line. The runtime is provider-agnostic; the default is sovereignty-friendly.',
    evidence: [OPEN_WEIGHT, PROVIDERS],
  },
  {
    file: 'pricing-faq.ts',
    exportPath: 'PRICING_FAQS[8].question',
    text: 'What does "full source code access" mean?',
    evidence: [LICENSE_MIT],
  },
  {
    file: 'pricing-faq.ts',
    exportPath: 'PRICING_FAQS[8].answer',
    text: 'You get the complete RevealUI source code: every app and package is published in the public monorepo. Infrastructure packages (@revealui/core, auth, db, contracts, security, utils, config, cache, resilience, openapi, sync) are MIT-licensed. The five Pro packages (@revealui/ai, @revealui/engines, @revealui/harnesses, @revealui/mcp, @revealui/services) ship under Fair Source (FSL-1.1-MIT): source is visible, commercial use is permitted except for building a directly competing developer platform, and each release automatically converts to plain MIT two years after publication. All paid tiers add runtime entitlements (license validation, feature gates, priority updates) on top of that source access, and nothing is hidden behind a closed binary.',
    evidence: [LICENSE_SPLIT, LICENSE_MIT, REPO, TIER_GATES],
  },
  {
    file: 'pricing-faq.ts',
    exportPath: 'PRICING_FAQS[9].question',
    text: 'What is Fair Source (FSL-1.1-MIT)?',
    evidence: [FAIR_SOURCE_PAGE],
  },
  {
    file: 'pricing-faq.ts',
    exportPath: 'PRICING_FAQS[9].answer',
    text: "Fair Source is a middle path between closed commercial and plain open-source. Our five Pro packages (@revealui/ai, @revealui/engines, @revealui/harnesses, @revealui/mcp, @revealui/services) are source-visible on GitHub, installable from npm, and legally usable in commercial products, with one non-compete clause: you can't ship a substantially similar developer platform that competes with RevealUI on top of them. Two years after each release, that release automatically converts to MIT. Same license model used by Sentry, GitButler, and Keygen. Source-available under FSL: free for everyone except SaaS competitors. Pro plan = hosted infra + support, not npm-level enforcement. Full explainer at /fair-source.",
    evidence: [LICENSE_SPLIT, FAIR_SOURCE_PAGE, REPO],
  },
  {
    file: 'pricing-faq.ts',
    exportPath: 'PRICING_FAQS[10].question',
    text: 'Do you offer custom pricing for large teams?',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'pricing-faq.ts',
    exportPath: 'PRICING_FAQS[10].answer',
    text: 'Yes. If you need more than what the Enterprise tier offers, contact us to discuss custom pricing. See /sla for our standard support and uptime commitments. (interpolated: SITE.emails.support)',
    match: 'path',
    evidence: [COMMERCIAL_POLICY, SLA_PAGE],
  },
  {
    file: 'pricing-faq.ts',
    exportPath: 'PRICING_FAQS[11].answer',
    text: 'RevFleet is the RevealUI Studio product family: seven products that compose around the RevealUI runtime. RevealUI is the agentic business runtime. RevVault encrypts secrets (CLI MIT, desktop Pro). RevDev is the engineering harness for multi-agent coordination across Claude, Cursor, and Copilot (Studio + Console MIT, Daemon Fair Source). RevCon syncs editor configs (MIT). RevSkills is the Claude Code skills library (MIT). RevForge is the operator-side stamping tool that produces white-label trial kits (operator-only). RevMarket is the agent tool marketplace (bundled with the runtime, on the way). Use RevealUI standalone, or compose what you need.',
    evidence: [
      REVVAULT_REPO,
      REVDEV_REPO,
      REVCON_REPO,
      REVSKILLS_REPO,
      REVFORGE_REF,
      ROADMAP,
      REPO,
    ],
  },
  {
    file: 'pricing-faq.ts',
    exportPath: 'PRICING_FAQ_SECTION.heading',
    text: 'Frequently Asked Questions',
    evidence: [
      {
        kind: 'url',
        ref: 'https://revealui.com/pricing',
        note: 'section framing only; individual FAQ answers below carry the claims',
      },
    ],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_HERO.h1Lines[0]',
    text: 'Your business grows with you,',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_HERO.h1Lines[1]',
    text: 'and stays at the frontier.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_HERO.subtitle',
    text: '(operator-lane studio-voice copy; path-pinned so the phrasing stays out of the fleet-voice register scan)',
    match: 'path',
    evidence: [COMMERCIAL_POLICY, SELF_HOST],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_HERO.reverseLink.label',
    text: 'Are you a developer? See the runtime.',
    evidence: [REPO],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_WHAT_YOU_GET.heading',
    text: '(operator-lane studio-voice copy; path-pinned so the phrasing stays out of the fleet-voice register scan)',
    match: 'path',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_WHAT_YOU_GET.body',
    text: 'A working business: accounts, billing, content, and a place to operate the thing. Five capabilities, in plain English.',
    evidence: [AUTH_SESSIONS, BILLING, COLLECTIONS],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_WHAT_YOU_GET.cards[0].body',
    text: 'Real accounts with passwords, password resets, and roles. You decide who sees what. The admin you log into is the same admin your team uses.',
    evidence: [AUTH_SESSIONS, RBAC_ABAC],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_WHAT_YOU_GET.cards[1].body',
    text: 'Stripe Checkout, subscriptions, one-time charges, and a billing page customers can self-serve. Refunds and disputes are handled in the dashboard, not by emailing your accountant.',
    evidence: [BILLING],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_WHAT_YOU_GET.cards[2].body',
    text: 'One admin you log into to manage products, customers, content, and orders. No second tool. No spreadsheet stitched to a Stripe export.',
    evidence: [COLLECTIONS],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_WHAT_YOU_GET.cards[3].title',
    text: 'The software can do work on its own.',
    evidence: [EMAIL_AGENT],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_WHAT_YOU_GET.cards[3].body',
    text: 'An agent layer that drafts emails and runs recurring tasks. It runs on open AI models on your infrastructure, not on a per-token API. The AI bill is your inference cost, not a per-task tax.',
    evidence: [EMAIL_AGENT, OPEN_WEIGHT],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_WHAT_YOU_GET.cards[4].body',
    text: 'The code is yours. The data is yours. The Stripe account is yours. The hosting account is yours. If you ever want to walk away from RevealUI Studio, you take it with you and a different engineer can pick it up.',
    evidence: [SELF_HOST, REPO],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_HOW_WE_DELIVER.paragraph1',
    text: '(operator-lane studio-voice copy; path-pinned so the phrasing stays out of the fleet-voice register scan)',
    match: 'path',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_HOW_WE_DELIVER.paragraph2.before',
    text: 'A self-serve managed version (sign up, configure in a browser, get a hosted product without an engagement) is on the roadmap. See the ',
    evidence: [COMMERCIAL_POLICY, ROADMAP],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_HOW_WE_DELIVER.paragraph2.after',
    text: ' for what that means and when it might be ready. It does not ship today. If you want a working product now, the path is a build call.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_HOW_WE_DELIVER.paragraph3',
    text: '(operator-lane studio-voice copy; path-pinned so the phrasing stays out of the fleet-voice register scan)',
    match: 'path',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_PRICING.body',
    text: 'Every engagement is fixed-bid and starts with a discovery call that scopes the work. The numbers below are starting points, not final quotes.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_PRICING.rungs[0].body',
    text: 'A two-week, fixed-bid plan for a self-hosted, audited product your clients own: a reference architecture, a data-flow and audit map, a model plan, and a priced path to launch. Credited toward a Fleet deployment if you start one within 30 days.',
    evidence: [COMMERCIAL_POLICY, SELF_HOST],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_PRICING.rungs[1].body',
    text: 'A fixed-bid setup, live in two to four weeks: we configure your RevealUI instance, deploy it to production, and hand you the keys with a full handoff session. The fastest path from a signed engagement to a live product you operate yourself.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_PRICING.rungs[2].body',
    text: 'A branded, self-hosted runtime your clients use under your name, on your cloud, white-labeled per client. Built and delivered as a fixed-scope engagement, scoped in the Architecture Review. Ongoing support runs as a separate monthly plan.',
    evidence: [COMMERCIAL_POLICY, REVFORGE_REF, SELF_HOST],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_PRICING.rungs[3].body',
    text: 'A bespoke product on the same runtime, scoped to what your business needs beyond a standard Fleet deployment. A four-to-twelve-week statement of work, fixed-bid, scoped in discovery.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_PROOF.heading',
    text: 'Built by the engineer who built the runtime.',
    evidence: [BIO],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_PROOF.body',
    text: 'RevealUI Studio is one engineer, Joshua Vaughn, and the runtime he maintains. Ten years managing teams in telecommunications before this. The agency engagement is delivered by the same person who reviews every commit to the open-source codebase you will be running.',
    evidence: [BIO, REPO],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_PROOF.bulletIntro',
    text: 'That means three concrete things:',
    evidence: [BIO],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_PROOF.bullets[0]',
    text: '(operator-lane studio-voice copy; path-pinned so the phrasing stays out of the fleet-voice register scan)',
    match: 'path',
    evidence: [THIS_SITE, REPO],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_PROOF.bullets[1]',
    text: 'When a bug surfaces in your deployment, the person debugging it wrote that part of the runtime.',
    evidence: [BIO],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_PROOF.bullets[2]',
    text: 'When the runtime ships a new feature, your deployment gets it on the same release cadence as every other one.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_PROOF.links[0].label',
    text: 'Read the runtime on GitHub →',
    evidence: [REPO],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_DISCOVERY.body',
    text: '(operator-lane studio-voice copy; path-pinned so the phrasing stays out of the fleet-voice register scan)',
    match: 'path',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_DISCOVERY.link.label',
    text: 'Read how the engagement works →',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_FAQ.items[0].question',
    text: 'Do I need to know how to code?',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_FAQ.items[0].answer',
    text: '(operator-lane studio-voice copy; path-pinned so the phrasing stays out of the fleet-voice register scan)',
    match: 'path',
    evidence: [COMMERCIAL_POLICY, REPO],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_FAQ.items[1].question',
    text: 'Is this a website builder, like Wix or Squarespace?',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_FAQ.items[1].answer',
    text: '(operator-lane studio-voice copy; path-pinned so the phrasing stays out of the fleet-voice register scan)',
    match: 'path',
    evidence: [COMMERCIAL_POLICY, AUTH_SESSIONS, BILLING],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_FAQ.items[2].question',
    text: 'Who hosts it? What if RevealUI Studio goes away?',
    evidence: [SELF_HOST],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_FAQ.items[2].answer',
    text: 'You host it, on infrastructure in your name (Vercel for the app, Neon for the database, Stripe for billing). The code is open source. If RevealUI Studio ceased to exist tomorrow, your product keeps running on the same infrastructure with no change. Hiring a different engineer to take over the codebase is a normal hand-off, not a rescue mission.',
    evidence: [SELF_HOST, REPO, LICENSE_MIT],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_FAQ.items[3].answer',
    text: '(interpolated: engagement prices from AGENCY_ENGAGEMENT_LADDER)',
    match: 'path',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_FAQ.items[4].answer',
    text: 'Weeks, not quarters. The discovery call gives you the range for your specific scope.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_FAQ.items[5].question',
    text: 'Can you build my specific thing?',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_FAQ.items[5].answer',
    text: '(operator-lane studio-voice copy; path-pinned so the phrasing stays out of the fleet-voice register scan)',
    match: 'path',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'for-operators.ts',
    exportPath: 'FOR_OPERATORS_FAQ.items[6].answer',
    text: '(operator-lane studio-voice copy; path-pinned so the phrasing stays out of the fleet-voice register scan; note: still contains "process orders" with no order template, flagged for a follow-up copy sweep)',
    match: 'path',
    evidence: [EMAIL_AGENT, OPEN_WEIGHT, COMMERCIAL_POLICY],
  },
];
