import {
  AGENT_ROUTES,
  AUDIT_SIGNING,
  AUDIT_SIGNING_TEST,
  AUTH_SESSIONS,
  BILLING,
  CI_GATE,
  CLI_CREATE,
  COLLECTIONS,
  COMMERCIAL_POLICY,
  DEPLOY_TARGETS,
  DOCS,
  INFRA_COST_ESTIMATE,
  LICENSE_MIT,
  LICENSE_SPLIT,
  MCP_CONTENT,
  MCP_RESOURCE_DEFAULT,
  MCP_SERVERS,
  MEMORY,
  OPEN_STANDARDS,
  OPEN_WEIGHT,
  PERPETUAL,
  POSTGRES,
  PRICING_FALLBACKS,
  PROVIDERS,
  RBAC_ABAC,
  RECONCILE,
  REPO,
  ROADMAP,
  SELF_HOST,
  THIS_SITE,
  TIER_GATES,
  TIER_LIMITS,
  TRIAL,
  WEBHOOKS,
  X402,
} from './shared-refs.js';
import type { ClaimEntry } from './types.js';

export const claimsPart1: readonly ClaimEntry[] = [
  {
    file: 'home.ts',
    exportPath: 'HOME_BENEFITS[0].title',
    text: 'Keep a foundation you can reuse.',
    proofGrade: 'behavior',
    evidence: [LICENSE_MIT, LICENSE_SPLIT, TIER_LIMITS, REPO],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_BENEFITS[0].body',
    text: 'RevealFleet is the family of software behind RevealUI and the tools we use to build and operate it. The MIT core can be used in another app; paid runtime features follow your license limits.',
    proofGrade: 'behavior',
    evidence: [LICENSE_MIT, LICENSE_SPLIT, TIER_LIMITS, REPO],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_BENEFITS[1].title',
    text: 'Choose where inference runs.',
    proofGrade: 'behavior',
    evidence: [PROVIDERS, OPEN_WEIGHT],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_BENEFITS[1].body',
    text: 'Configure a supported local runner or hosted provider. Local inference needs suitable hardware; hosted providers process the model requests you send them.',
    proofGrade: 'behavior',
    evidence: [PROVIDERS, OPEN_WEIGHT],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_BENEFITS[2].title',
    text: 'Inspect supported agent activity.',
    proofGrade: 'behavior',
    evidence: [AUDIT_SIGNING, AUDIT_SIGNING_TEST, TIER_GATES],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_BENEFITS[2].body',
    text: 'When audit signing is configured, supported actions leave signed records. Pro adds downloadable Merkle roots and inclusion proofs. A record helps you investigate an action; it does not prove the business outcome was correct.',
    proofGrade: 'behavior',
    evidence: [AUDIT_SIGNING, AUDIT_SIGNING_TEST, TIER_GATES],
  },
  {
    file: 'pricing-teaser.ts',
    exportPath: 'PRICING_TEASER_TIERS[0].features[1]',
    proofGrade: 'behavior',
    text: 'Content APIs and admin components',
    evidence: [COLLECTIONS],
  },
  {
    file: 'pricing-teaser.ts',
    exportPath: 'PRICING_TEASER_TIERS[0].features[2]',
    proofGrade: 'behavior',
    text: 'Offers and Stripe integration',
    evidence: [BILLING, TIER_GATES],
  },

  {
    file: 'pricing-teaser.ts',
    exportPath: 'PRICING_TEASER_TIERS[0].features[1]',
    proofGrade: 'behavior',
    text: 'Content APIs and admin components',
    evidence: [COLLECTIONS],
  },
  {
    file: 'pricing-teaser.ts',
    exportPath: 'PRICING_TEASER_TIERS[0].features[2]',
    proofGrade: 'behavior',
    text: 'Offers and Stripe integration',
    evidence: [BILLING, TIER_GATES],
  },

  {
    file: 'site.ts',
    exportPath: 'SITE.brandTagline',
    text: 'Build your business on software you can run yourself.',
    evidence: [LICENSE_MIT, OPEN_WEIGHT, SELF_HOST],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_HERO.eyebrow',
    proofGrade: 'behavior',
    text: 'Self-hostable. Source available.',
    evidence: [LICENSE_MIT, SELF_HOST],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_HERO.h1',
    proofGrade: 'outcome',
    text: 'Build your business on software you can run yourself.',
    evidence: [
      {
        kind: 'code',
        ref: 'packages',
        note: 'five primitives implemented once and reused across products on one monorepo runtime',
      },
      {
        kind: 'test',
        ref: 'apps/marketing/app/__tests__/hero-variant.test.ts#serves the L1 default hero by default',
        note: 'locks the known-for H1 as the homepage default after Brand LOCK 2026-09-15',
      },
      LICENSE_MIT,
      SELF_HOST,
    ],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_HERO_OWNERSHIP.h1',
    proofGrade: 'outcome',
    text: 'Run your business software on infrastructure you control.',
    evidence: [
      {
        kind: 'code',
        ref: 'packages',
        note: 'prior default H1 retained as ?hero=ownership rollback preview',
      },
      {
        kind: 'test',
        ref: 'apps/marketing/app/__tests__/hero-variant.test.ts#serves the ownership rollback for ?hero=ownership',
        note: 'locks ownership H1 as optional rollback variant',
      },
      LICENSE_MIT,
      SELF_HOST,
    ],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_HERO.subtitle.sentence1',
    proofGrade: 'outcome',
    text: 'RevealUI brings People, Content, Offers, Payments, and Agents into one self-hosted runtime.',
    evidence: [SELF_HOST, COLLECTIONS, RBAC_ABAC, BILLING, AGENT_ROUTES],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_HERO.subtitle.sentence2',
    proofGrade: 'outcome',
    text: 'Start with the MIT-licensed core. Add Pro for agent tools, memory, and MCP integrations.',
    evidence: [LICENSE_MIT, TIER_GATES, AGENT_ROUTES, MEMORY, MCP_SERVERS],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_HERO.subtitle.support',
    proofGrade: 'behavior',
    text: 'Use accounts and infrastructure you control. Hosting, database services, and model usage are separate costs.',
    evidence: [SELF_HOST, INFRA_COST_ESTIMATE, BILLING, PROVIDERS],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_HERO_FOUNDATION.h1',
    proofGrade: 'outcome',
    text: 'Build on shared business primitives with supported integrations.',
    evidence: [
      MCP_SERVERS,
      MCP_CONTENT,
      SELF_HOST,
      {
        kind: 'code',
        ref: 'packages',
        note: 'sanctioned A/B variant of HOME_HERO.h1; known-for #5 keep-the-stack, not receipts-only',
      },
    ],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_HERO_L2.h1',
    proofGrade: 'outcome',
    text: 'Configure agents for the business data and permissions you choose.',
    evidence: [
      {
        kind: 'code',
        ref: 'packages',
        note: 'corpus L2 leverage-frame A/B (06-copy-corpus §4.1); owner go 2026-07-31 via ?hero=l2, not default traffic',
      },
      {
        kind: 'test',
        ref: 'apps/marketing/app/__tests__/hero-variant.test.ts#serves the L2 leverage-frame for ?hero=l2',
        note: 'locks L2 H1 as optional experiment variant',
      },
      LICENSE_MIT,
      SELF_HOST,
    ],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_PROBLEM.heading',
    proofGrade: 'outcome',
    text: 'Choose how to build your business runtime.',
    evidence: [
      {
        kind: 'code',
        ref: 'packages',
        note: 'framing sentence; the three-path comparison below carries the claims',
      },
    ],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_PROBLEM.body',
    proofGrade: 'outcome',
    text: 'Compare a shared runtime with connecting separate services or adding business features to an agent framework. Configure and maintain the services you choose.',
    evidence: [AUTH_SESSIONS, COLLECTIONS, BILLING, LICENSE_MIT],
  },
  // pathBlurbs claims retired (GAP-480 landing de-dupe): blurbs removed from
  // the Problem band; body + matrix remain the single comparison device.
  {
    file: 'home.ts',
    exportPath: 'HOME_PROBLEM.rows[0].sprawl',
    proofGrade: 'path',
    text: 'Configure an authentication service',
    evidence: [
      {
        kind: 'url',
        ref: 'https://revealui.com/pricing',
        note: 'competitor-column framing; cost detail lives on the pricing page',
      },
    ],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_PROBLEM.rows[0].revealui',
    proofGrade: 'behavior',
    text: 'Sign-in, roles, and policies built in',
    evidence: [AUTH_SESSIONS, RBAC_ABAC],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_PROBLEM.rows[1].sprawl',
    proofGrade: 'path',
    text: 'Connect a content service and admin interface',
    evidence: [
      {
        kind: 'url',
        ref: 'https://revealui.com/pricing',
        note: 'competitor-column framing; cost detail lives on the pricing page',
      },
    ],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_PROBLEM.rows[1].revealui',
    proofGrade: 'behavior',
    text: 'Your content model, with admin UI and API',
    evidence: [COLLECTIONS, OPEN_STANDARDS],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_PROBLEM.rows[2].sprawl',
    proofGrade: 'behavior',
    text: 'Integrate Stripe checkout and webhooks',
    evidence: [BILLING, WEBHOOKS],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_PROBLEM.rows[3].sprawl',
    proofGrade: 'behavior',
    text: 'Connect tools and permissions to each service',
    evidence: [MCP_CONTENT, RBAC_ABAC],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_PROBLEM.rows[3].agentOnly',
    proofGrade: 'behavior',
    text: 'Configure tools and business access',
    evidence: [MCP_CONTENT, TIER_GATES],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_PROBLEM.rows[2].revealui',
    proofGrade: 'behavior',
    text: 'Test-mode checkout, subscriptions, and webhook handling',
    evidence: [BILLING, WEBHOOKS, RECONCILE],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_PROBLEM.rows[3].revealui',
    proofGrade: 'behavior',
    text: 'Supported agent tools use configured API permissions and plan limits',
    evidence: [MCP_CONTENT, MCP_RESOURCE_DEFAULT],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_PROBLEM.footnote',
    proofGrade: 'behavior',
    text: 'Capability only. Pricing is on the pricing page (interpolated: Pro price from pricing-fallbacks). Vercel, Cloudflare, and Fly are deploy targets, not competitors.',
    match: 'path',
    evidence: [PRICING_FALLBACKS, DEPLOY_TARGETS],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_DEMO.heading',
    proofGrade: 'outcome',
    text: 'Install locally. Test checkout. Point an agent at the same data.',
    evidence: [CLI_CREATE],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_DEMO.body',
    proofGrade: 'outcome',
    text: 'Create a local project, configure its services, and test a supported workflow. Agent tools require Pro and a configured model provider.',
    evidence: [CLI_CREATE, BILLING, MCP_CONTENT],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_DEMO.mockupCaption.prefix',
    proofGrade: 'path',
    text: 'Example admin interface built with',
    evidence: [
      {
        kind: 'code',
        ref: 'apps/marketing/app/components/landing/ProductFrame.tsx',
        note: 'composed from StatusDot/VerdictChip, not a screenshot',
      },
    ],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_DEMO.mockupCaption.suffix',
    proofGrade: 'path',
    text: 'components. The three beats are the local install path.',
    evidence: [CLI_CREATE],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_DEMO.beats[0].body',
    proofGrade: 'behavior',
    text: 'Create a local project, then configure the database, authentication, and services your template needs.',
    evidence: [CLI_CREATE, AUTH_SESSIONS, WEBHOOKS, MCP_CONTENT],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_DEMO.beats[1].body',
    proofGrade: 'behavior',
    text: 'Configure Stripe test credentials and webhooks, then test sign-up and checkout. Configure live credentials before accepting real payments.',
    evidence: [
      AUTH_SESSIONS,
      BILLING,
      {
        kind: 'code',
        ref: 'apps/server/src/lib/validate-startup.ts',
        note: 'STRIPE_LIVE_MODE flip validated at boot',
      },
    ],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_DEMO.beats[2].title',
    proofGrade: 'behavior',
    text: 'Point an agent at the same data.',
    evidence: [MCP_CONTENT, TIER_GATES],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_DEMO.beats[2].body',
    proofGrade: 'behavior',
    text: 'With Pro, configure a supported model provider and agent tools. Use the content API under the configured permissions and plan limits.',
    evidence: [PROVIDERS, MCP_CONTENT, TIER_GATES],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_FAQ.items[0].answer',
    proofGrade: 'behavior',
    text: 'Use your own repository, database, and hosting accounts. The core uses MIT; Pro packages follow their published license terms and require license validation. Integrations have their own dependencies.',
    evidence: [LICENSE_MIT, LICENSE_SPLIT, SELF_HOST, TIER_GATES, PROVIDERS],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_FAQ.items[1].answer',
    proofGrade: 'behavior',
    text: 'Used in production by the team that maintains it. Automated tests and security checks cover defined properties; review the source and validate your own deployment before launch.',
    evidence: [CI_GATE, THIS_SITE],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_FAQ.items[2].question',
    proofGrade: 'path',
    text: 'How is this different from stitching separate tools together?',
    evidence: [
      { kind: 'code', ref: 'packages', note: 'question copy; the answer carries the claims' },
    ],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_FAQ.items[2].answer',
    proofGrade: 'outcome',
    text: 'RevealUI shares People, Content, Offers, Payments, and Agents across one self-hosted runtime. Configure the services and integrations you need; paid agent features require the appropriate license.',
    evidence: [AUTH_SESSIONS, COLLECTIONS, BILLING, AGENT_ROUTES, DEPLOY_TARGETS],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_FAQ.items[3].answer',
    proofGrade: 'behavior',
    text: 'Yes. The core uses MIT; Pro packages use FSL-1.1-MIT and follow their published conversion terms. You operate the infrastructure. Paid features require the appropriate license and configuration; read the Fair Source guide for details.',
    evidence: [LICENSE_SPLIT, LICENSE_MIT, SELF_HOST, POSTGRES],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_FAQ.items[4].question',
    proofGrade: 'path',
    text: 'What does agent-native mean for my product?',
    evidence: [
      {
        kind: 'code',
        ref: 'packages/mcp/src',
        note: 'question copy; the answer carries the claims',
      },
    ],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_FAQ.items[4].answer',
    proofGrade: 'behavior',
    text: 'Supported agent tools access your content through the configured API permissions and plan limits. Configure the agent identity, credentials, and model provider for your deployment.',
    evidence: [TIER_GATES, MCP_CONTENT, MCP_RESOURCE_DEFAULT, OPEN_STANDARDS],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_FAQ.items[5].question',
    proofGrade: 'path',
    text: 'How does AI inference work?',
    evidence: [OPEN_WEIGHT],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_FAQ.items[5].answer',
    proofGrade: 'behavior',
    text: 'Configure a supported local runner or hosted provider. Local inference needs suitable hardware; hosted providers process the requests you send and charge for usage. Read the local-first guide for setup.',
    evidence: [OPEN_WEIGHT, PROVIDERS],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_FAQ.items[6].question',
    proofGrade: 'path',
    text: 'How do agent payments work?',
    evidence: [X402],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_FAQ.items[6].answer',
    proofGrade: 'behavior',
    text: 'RevealUI includes an HTTP 402 (x402) payment rail so agents can pay over standard HTTP when an operator turns it on. The rail ships in the code and stays off by default (X402_ENABLED off). It is not a live payments product today. See the agents section on the pricing page for current status.',
    evidence: [X402],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_GET_STARTED.heading',
    proofGrade: 'outcome',
    text: 'Start on your machine today.',
    evidence: [CLI_CREATE],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_GET_STARTED.body',
    proofGrade: 'outcome',
    text: 'Create a local app with npx create-revealui@latest or a public GitHub template. Configure the services your template needs before testing your workflow. The Apify actor is a separate pay-per-event agent run, not an app installer.',
    evidence: [
      CLI_CREATE,
      {
        kind: 'code',
        ref: 'apps/server/src/lib/validate-startup.ts',
        note: 'live-mode flip validated at boot',
      },
    ],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_GET_STARTED.cli.caption',
    proofGrade: 'behavior',
    text: 'Create a RevealUI app locally.',
    evidence: [
      CLI_CREATE,
      {
        kind: 'code',
        ref: 'apps/admin/src/app/api/auth/sign-up/route.ts',
        note: 'signup takes no payment method',
      },
    ],
  },
  {
    file: 'home.ts',
    exportPath: 'HOME_GET_STARTED.newsletter.label',
    proofGrade: 'path',
    text: 'Not ready to start? Get product updates when they ship.',
    evidence: [
      {
        kind: 'code',
        ref: 'apps/server/src/routes/waitlist.ts',
        note: 'newsletter capture endpoint',
      },
    ],
  },
  {
    file: 'primitives.ts',
    exportPath: 'HOME_PRIMITIVES_SECTION.eyebrow',
    proofGrade: 'behavior',
    text: 'Five primitives. One login.',
    evidence: [
      AUTH_SESSIONS,
      {
        kind: 'code',
        ref: 'packages/engines/src',
        note: 'the five business primitives behind one session',
      },
    ],
  },
  {
    file: 'primitives.ts',
    exportPath: 'HOME_PRIMITIVES_SECTION.heading',
    proofGrade: 'outcome',
    text: 'The five things every business runs on.',
    evidence: [
      {
        kind: 'code',
        ref: 'packages/engines/src',
        note: 'people, content, offers, payments, agents',
      },
    ],
  },
  {
    file: 'primitives.ts',
    exportPath: 'HOME_PRIMITIVES_SECTION.body',
    proofGrade: 'outcome',
    text: 'People, Content, Offers, and Payments share one runtime. Pro adds agent tools; configure the services and permissions your deployment needs.',
    evidence: [OPEN_STANDARDS, COLLECTIONS, AGENT_ROUTES],
  },
  {
    file: 'primitives.ts',
    exportPath: 'HOME_PRIMITIVES_SECTION.docsLink.label',
    proofGrade: 'path',
    text: 'See the primitive reference →',
    evidence: [DOCS],
  },
  {
    file: 'primitives.ts',
    exportPath: 'HOME_PRIMITIVES[0].body',
    proofGrade: 'outcome',
    text: 'Your team signs in once. Roles and policies decide who can do what.',
    evidence: [AUTH_SESSIONS, RBAC_ABAC],
  },
  {
    file: 'primitives.ts',
    exportPath: 'HOME_PRIMITIVES[1].body',
    proofGrade: 'outcome',
    text: 'Define your content once. The admin UI and API come with it.',
    evidence: [
      COLLECTIONS,
      { kind: 'code', ref: 'packages/core/src/richtext', note: 'Lexical rich text' },
    ],
  },
  {
    file: 'primitives.ts',
    exportPath: 'HOME_PRIMITIVES[2].body',
    proofGrade: 'outcome',
    text: 'Plans and feature gates decide what each customer and agent can use.',
    evidence: [
      TIER_GATES,
      TIER_LIMITS,
      { kind: 'code', ref: 'packages/core/src/features.ts', note: 'tier feature matrix' },
    ],
  },
  {
    file: 'primitives.ts',
    exportPath: 'HOME_PRIMITIVES[3].body',
    proofGrade: 'behavior',
    text: 'Configure Stripe credentials and webhooks for test-mode checkout and subscriptions. Go live with live credentials when you are ready to accept payments.',
    evidence: [BILLING, WEBHOOKS, RECONCILE],
  },
  {
    file: 'primitives.ts',
    exportPath: 'HOME_PRIMITIVES[4].body',
    proofGrade: 'outcome',
    text: 'Pro adds agent tools. Configure a supported local runner or hosted model provider; hardware and model usage are separate costs.',
    evidence: [OPEN_WEIGHT, PROVIDERS],
  },
  {
    file: 'proof.ts',
    exportPath: 'PROOF_SECTION.heading',
    proofGrade: 'outcome',
    text: 'Read the code before you build on it.',
    evidence: [REPO],
  },
  {
    file: 'proof.ts',
    exportPath: 'PROOF_SECTION.body',
    proofGrade: 'behavior',
    text: 'The source is public. Review the MIT and FSL licenses, inspect the code, and try the runtime before you commit.',
    evidence: [REPO, LICENSE_MIT],
  },
  {
    file: 'proof.ts',
    exportPath: 'PROOF_TRUST.body',
    proofGrade: 'behavior',
    text: 'Your security team can inspect the full source. Core packages use MIT; Pro packages use FSL-1.1-MIT. Review the terms for the packages you will use.',
    evidence: [REPO, LICENSE_SPLIT],
  },
  {
    file: 'proof.ts',
    exportPath: 'PROOF_TRUST.changelogCta.label',
    proofGrade: 'path',
    text: 'See what shipped this month →',
    evidence: [
      { kind: 'url', ref: 'https://github.com/RevealUIStudio/revealui/blob/main/CHANGELOG.md' },
    ],
  },
  {
    file: 'proof.ts',
    exportPath: 'LIVE_METRICS.heading',
    proofGrade: 'behavior',
    text: 'Every number here is pinned to the codebase.',
    evidence: [LICENSE_SPLIT],
  },
  {
    file: 'proof.ts',
    exportPath: 'LIVE_METRICS.body',
    proofGrade: 'behavior',
    text: 'These counts are checked on each pull request. If the code changes and a number drifts, the build fails before it can ship.',
    evidence: [LICENSE_SPLIT, CI_GATE],
  },
  {
    file: 'proof.ts',
    exportPath: 'PROOF_DEPLOYERS.heading',
    proofGrade: 'outcome',
    text: 'Built for people who deploy, not only demo.',
    evidence: [
      {
        kind: 'url',
        ref: 'https://revealuistudio.com',
        note: 'Studio/agency is the reference forward-deploy practice (ADR 2026-07-21)',
      },
    ],
  },
  {
    file: 'proof.ts',
    exportPath: 'PROOF_DEPLOYERS.body',
    proofGrade: 'outcome',
    text: 'Install yourself, hire Studio, or bring your own forward-deployed engineer. The outcome is the same: a self-hosted runtime on infrastructure you own.',
    evidence: [
      REPO,
      {
        kind: 'url',
        ref: 'https://revealuistudio.com',
        note: 'hire-us path; Fleet Stamp / Custom Build on agency services',
      },
      {
        kind: 'url',
        ref: 'https://revealui.com',
        note: 'self-install product path',
      },
    ],
  },
  {
    file: 'proof.ts',
    exportPath: 'PROOF_DEPLOYERS.foil',
    proofGrade: 'outcome',
    text: 'Studio hands you a runtime on infra you run. You keep the repo and the database.',
    evidence: [
      REPO,
      {
        kind: 'url',
        ref: 'https://revealuistudio.com',
        note: 'positioning foil: customer-owned runtime after handoff, not a rented outcome',
      },
    ],
  },
  {
    file: 'pricing-teaser.ts',
    exportPath: 'PRICING_TEASER_SECTION.heading',
    proofGrade: 'outcome',
    text: 'Start free. Add agents when you need them.',
    evidence: [LICENSE_MIT, TIER_GATES, MCP_CONTENT, AUDIT_SIGNING],
  },
  {
    file: 'pricing-teaser.ts',
    exportPath: 'PRICING_TEASER_SECTION.body',
    proofGrade: 'behavior',
    text: 'Free gives you the core runtime. Paid licenses add agent features and higher limits. You provide the infrastructure and model access.',
    evidence: [LICENSE_MIT, TIER_GATES, TIER_LIMITS, TRIAL],
  },
  {
    file: 'pricing-teaser.ts',
    exportPath: 'PRICING_TEASER_TIERS[0].description',
    proofGrade: 'behavior',
    text: 'Build with the MIT-licensed core and run it on your infrastructure.',
    evidence: [LICENSE_MIT, SELF_HOST],
  },
  {
    file: 'pricing-teaser.ts',
    exportPath: 'PRICING_TEASER_TIERS[0].features[3]',
    proofGrade: 'behavior',
    text: 'Core packages use the MIT license.',
    evidence: [LICENSE_MIT, LICENSE_SPLIT],
  },
  {
    file: 'pricing-teaser.ts',
    exportPath: 'PRICING_TEASER_TIERS[1].description',
    proofGrade: 'behavior',
    text: 'Add agent tools, shared memory, and MCP integrations.',
    evidence: [TIER_GATES, MEMORY, MCP_SERVERS],
  },
  {
    file: 'pricing-teaser.ts',
    exportPath: 'PRICING_TEASER_TIERS[1].features[1]',
    proofGrade: 'behavior',
    text: '10,000 agent tasks / month included',
    evidence: [TIER_LIMITS],
  },
  {
    file: 'pricing-teaser.ts',
    exportPath: 'PRICING_TEASER_TIERS[1].features[2]',
    proofGrade: 'behavior',
    text: 'Pro AI features (agents, MCP, memory), beta in production',
    evidence: [
      TIER_GATES,
      MEMORY,
      { kind: 'code', ref: 'packages/mcp/src', note: 'MCP hypervisor + servers' },
    ],
  },
  {
    file: 'pricing-teaser.ts',
    exportPath: 'PRICING_TEASER_LINKS[0].description',
    proofGrade: 'behavior',
    text: 'Max adds unattended inference and higher limits.',
    evidence: [MEMORY, { kind: 'code', ref: 'packages/ai/src/inference', note: 'inference layer' }],
  },
  {
    file: 'pricing-teaser.ts',
    exportPath: 'PRICING_TEASER_LINKS[1].description',
    proofGrade: 'behavior',
    text: 'Enterprise is scoped with sales.',
    evidence: [COMMERCIAL_POLICY],
  },
  {
    file: 'pricing-teaser.ts',
    exportPath: 'PRICING_TEASER_FOOTER.caption.prefix',
    proofGrade: 'behavior',
    text: 'Deploys to Vercel, Cloudflare, Fly, Hetzner, or self-host.',
    evidence: [DEPLOY_TARGETS],
  },
  {
    file: 'pricing-teaser.ts',
    exportPath: 'PRICING_TEASER_FOOTER.caption.suffix',
    proofGrade: 'behavior',
    text: 'produces a standard Node bundle.',
    evidence: [{ kind: 'command', ref: 'pnpm build', note: 'turbo build to a plain Node bundle' }],
  },
  {
    file: 'products.ts',
    exportPath: 'PRODUCTS_PAGE_HERO.subtitle',
    proofGrade: 'outcome',
    text: 'Choose a license for your self-hosted RevealUI runtime. Compare Free, Pro, Max, Enterprise, and Pro Perpetual.',
    evidence: [REPO, SELF_HOST, TIER_GATES],
  },
  {
    file: 'products.ts',
    exportPath: 'PRODUCTS_FLAGSHIP.priceLabel',
    proofGrade: 'behavior',
    text: 'Free to self-host · Pro tier optional',
    evidence: [LICENSE_MIT, SELF_HOST, TIER_GATES],
  },
  {
    file: 'products.ts',
    exportPath: 'PRODUCTS_FLAGSHIP.tagline',
    proofGrade: 'outcome',
    text: 'The self-hosted business runtime',
    evidence: [AGENT_ROUTES, SELF_HOST],
  },
  {
    file: 'products.ts',
    exportPath: 'PRODUCTS_FLAGSHIP.body',
    proofGrade: 'outcome',
    text: 'People, content, offers, payments, and agents in one runtime your team and your agents share. Licensed as Free, Pro, Max, Enterprise inquire, or Pro Perpetual.',
    evidence: [AUTH_SESSIONS, COLLECTIONS, BILLING, AGENT_ROUTES, MCP_CONTENT],
  },
  {
    file: 'products.ts',
    exportPath: 'PRODUCTS_STATS_SECTION.heading',
    proofGrade: 'outcome',
    text: 'Inspect what you will build on.',
    evidence: [CI_GATE],
  },
  {
    file: 'products.ts',
    exportPath: 'PRODUCTS_STATS_SECTION.body',
    proofGrade: 'outcome',
    text: 'Read the source, tests, and release history before you choose.',
    evidence: [CI_GATE, REPO],
  },
  {
    file: 'products.ts',
    exportPath: 'PRODUCTS_CTA_SECTION.body',
    proofGrade: 'outcome',
    text: 'Create an app locally and follow the setup guide for your chosen template.',
    evidence: [REPO, CLI_CREATE],
  },
  {
    file: 'products.ts',
    exportPath: 'PRODUCTS_CTA_SECTION.cliSnippet',
    proofGrade: 'behavior',
    text: 'npx create-revealui@latest my-app',
    evidence: [CLI_CREATE],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_HERO.title',
    proofGrade: 'outcome',
    text: 'Choose a license for the runtime you run.',
    evidence: [AUDIT_SIGNING, AUDIT_SIGNING_TEST, SELF_HOST],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_HERO.subtitle',
    text: 'Start with Free. Choose Pro or Max for agent features and higher limits. Enterprise licenses are scoped with sales. All plans are self-hosted.',
    evidence: [PRICING_FALLBACKS, SELF_HOST, PERPETUAL],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_HERO_SUBTEXT.prefix',
    text: 'All plans run as self-hosted installations under your license. Enterprise is a license, not a hosted VM. Need a human?',
    evidence: [SELF_HOST, COMMERCIAL_POLICY, PERPETUAL, ROADMAP],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_HERO_SUBTEXT.suffix',
    text: 'Need implementation? Studio is a separate path (Consultation, Pilot, Launch). This catalog is licenses only.',
    evidence: [
      PERPETUAL,
      {
        kind: 'test',
        ref: 'apps/marketing/app/routes/__tests__/PricingPage.test.tsx#renders the license catalog and the product-site quote calculator',
        note: 'pricing helper names Consultation, Pilot, and Launch and does not print Studio dollars',
      },
    ],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_TRACK_A_SECTION.heading',
    text: 'Choose monthly or annual billing.',
    evidence: [BILLING],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_TRACK_A_SECTION.body',
    text: 'Paid subscriptions include an agent task allowance. Pro and Max include a 7-day free trial.',
    evidence: [TIER_LIMITS, TRIAL],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_VALUE_BAND.body',
    text: 'Build on shared accounts, content, offers, and billing. Add the agent layer when you need it. Your license covers RevealUI; hosting, your database, and model usage are separate costs.',
    evidence: [INFRA_COST_ESTIMATE, SELF_HOST],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_VALUE_BAND.points[0]',
    text: 'One runtime, not five separate SaaS subscriptions',
    evidence: [INFRA_COST_ESTIMATE, SELF_HOST],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_VALUE_BAND.points[1]',
    text: 'Self-host on Vercel, Cloudflare, Fly, Hetzner, or your own metal',
    evidence: [DEPLOY_TARGETS],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_VALUE_BAND.points[2]',
    text: 'Full source code access on every tier',
    evidence: [LICENSE_MIT, REPO],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_VALUE_BAND.points[3]',
    text: 'You provide model access and pay your infrastructure or provider costs',
    evidence: [OPEN_WEIGHT],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_TRIAL_NOTE',
    text: 'Pro and Max include a 7-day free trial. Cancel during the trial and you pay nothing. First purchase, including annual, has a 14-day refund. No prorate after 14 days.',
    evidence: [TRIAL],
  },
  {
    file: 'pricing.ts',
    exportPath: 'PRICING_TRACK_C_SECTION.body',
    text: 'Pro Perpetual lets you keep using your licensed version without a monthly subscription. Review the included update and support period before buying.',
    evidence: [PERPETUAL, COMMERCIAL_POLICY],
  },
];
