import {
  AGENT_CHAT,
  AGENT_ROUTES,
  AUDIT_ANCHOR_API,
  AUDIT_ANCHOR_SCHEMA,
  AUDIT_ANCHOR_VERIFY,
  AUDIT_ANCHOR_VERIFY_CLI,
  AUDIT_ANCHOR_VERIFY_TEST,
  AUDIT_LOG_FEATURE_MAX,
  AUDIT_LOG_SCHEMA,
  AUDIT_MERKLE,
  AUDIT_PUBLIC_KEY_ROUTE,
  AUDIT_RECEIPTS_DOC,
  AUDIT_ROW_SIGNER,
  AUDIT_SIGN_ROUNDTRIP,
  AUDIT_SIGNING,
  AUDIT_SIGNING_TEST,
  AUTH_SESSIONS,
  BILLING,
  BIO,
  CI_GATE,
  CLAIMS_INDEX,
  CLAIMS_PAGE_ROUTE,
  CLAIMS_ROUTE_MAP,
  CLAIMS_VALIDATOR,
  DOCS_APP,
  ENGINES,
  FAIR_SOURCE_PAGE,
  FSL_PEERS_CITATION,
  LEGAL_CONTACT_CONTENT,
  LEGAL_PRIVACY_CONTENT,
  LEGAL_REFUND_CONTENT,
  LEGAL_SECURITY_CONTENT,
  LICENSE_ED25519,
  LICENSE_MIT,
  LICENSE_SPLIT,
  MEMORY,
  PERPETUAL,
  POSTGRES,
  RBAC_ABAC,
  REFUND_ROUTE,
  REVFORGE_REF,
  ROADMAP,
  SELF_HOST,
  SSO_ADMIN_UI,
  SSO_AUTH_ROUTES,
  SSO_SAML_PURE,
  SSO_SETUP_DOC,
  THIS_SITE,
} from './shared-refs.js';
import type { ClaimEntry } from './types.js';

export const claimsPart4: readonly ClaimEntry[] = [
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_PEERS_SECTION.heading',
    text: 'The same license model used by serious infrastructure projects.',
    evidence: [FSL_PEERS_CITATION],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_PEERS[0].note',
    text: 'Application monitoring; flagship FSL adopter (license they originally co-authored with FOSSA).',
    evidence: [FSL_PEERS_CITATION],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_PEERS[1].note',
    text: 'Git client for branch management. FSL across the stack.',
    evidence: [FSL_PEERS_CITATION],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_PEERS[2].note',
    text: 'License management infrastructure; FSL on their core engine.',
    evidence: [FSL_PEERS_CITATION],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_FAQ_SECTION.heading',
    text: 'Detailed answers, not lawyer-speak.',
    evidence: [FAIR_SOURCE_PAGE],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_FAQS[0].question',
    text: 'Is Fair Source open source?',
    evidence: [FAIR_SOURCE_PAGE],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_FAQS[0].answer',
    text: 'Not in the OSI-approved sense: the non-compete clause means it is "source-available" rather than "open source." But for almost every practical purpose (read, modify, deploy, charge for products built on top), the freedoms match what most builders need from open source. After two years per release, the clause lifts and the code becomes plain MIT, which IS OSI open source.',
    evidence: [FAIR_SOURCE_PAGE, LICENSE_MIT],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_FAQS[1].question',
    text: 'What counts as a "competing developer platform"?',
    evidence: [FAIR_SOURCE_PAGE],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_FAQS[1].answer',
    text: '(interpolated: SITE.emails.founder)',
    match: 'path',
    evidence: [FAIR_SOURCE_PAGE],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_FAQS[2].question',
    text: 'When exactly does each release convert to MIT?',
    evidence: [LICENSE_MIT],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_FAQS[2].answer',
    text: 'Two years after the publish date of that specific release. So each release of @revealui/ai becomes MIT on its own 2-year anniversary, and a newer release starts its own clock from its own publish date. Older releases reach MIT first; this is intentional.',
    evidence: [LICENSE_MIT, FAIR_SOURCE_PAGE],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_FAQS[3].question',
    text: 'Why not just use plain MIT for everything?',
    evidence: [FAIR_SOURCE_PAGE],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_FAQS[3].answer',
    text: 'The Pro packages represent meaningful R&D investment in agent runtimes and harness coordination. Plain MIT lets a competitor fork the entire stack on day one and undercut the project on price, leaving the studio with no path to sustain the work. Fair Source closes that specific risk while keeping every other freedom you need. It is a deliberate middle path between "everything free, no business model" and "closed proprietary."',
    evidence: [FAIR_SOURCE_PAGE],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_FAQS[4].question',
    text: 'How is the Pro tier enforced if the source is visible?',
    evidence: [LICENSE_ED25519],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_FAQS[4].answer',
    text: 'License enforcement is at runtime in the hosted product, not baked into the npm packages. The hosted RevealUI API checks Ed25519-signed license JWTs and gates Pro API routes; the packages themselves ship ungated, so self-hosters run them freely. FSL is the legal protection: the source is visible and you can run it, but shipping a competing developer platform on top of it is exactly what the non-compete clause prohibits, with civil remedies available. Two years after each release, that release becomes plain MIT.',
    evidence: [LICENSE_ED25519, FAIR_SOURCE_PAGE],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_FAQS[5].question',
    text: 'What about the rest of the RevealUI packages?',
    evidence: [LICENSE_MIT],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_FAQS[5].answer',
    text: 'Every other RevealUI package is plain MIT, no non-compete clause, no time limit, fully open source. That is the OSS substrate (auth, content, billing primitives, admin UI, presentation system, router, etc.). Fair Source applies to five packages: @revealui/ai, @revealui/engines, @revealui/harnesses, @revealui/mcp, and @revealui/services.',
    evidence: [LICENSE_MIT, LICENSE_SPLIT],
  },
  {
    file: 'fair-source.ts',
    exportPath: 'FAIR_SOURCE_CTA.body',
    text: 'FSL-1.1-MIT is short, plain English, and authored by the FOSSA legal team. Two pages. Read it before you ship.',
    evidence: [FAIR_SOURCE_PAGE],
  },
  {
    file: 'philosophy.ts',
    exportPath: 'PHILOSOPHY.sections[0].body',
    text: "Human progress accelerates when the outputs of today's work become the inputs of tomorrow's work.",
    evidence: [BIO],
  },
  {
    file: 'philosophy.ts',
    exportPath: 'PHILOSOPHY.sections[1].body',
    text: 'Most software effort evaporates. The project ships, the lessons scatter, and the next project starts from zero. Tools that promise productivity make the work faster. They do not make the next project start further ahead.',
    evidence: [BIO],
  },
  {
    file: 'philosophy.ts',
    exportPath: 'PHILOSOPHY.sections[2].body',
    text: 'RevealUI is built for compounding. Five primitives, People, Content, Offers, Payments, and Agents, are a contract you implement once and reuse in every product you ship. A deployment that works can be stamped into a branded, domain-locked RevealUI Fleet kit through RevForge, today in private preview. An agent that works in your business keeps its memory in a store you own, so the record of your work is an asset, not an afterthought.',
    evidence: [ENGINES, REVFORGE_REF, MEMORY],
  },
  {
    file: 'philosophy.ts',
    exportPath: 'PHILOSOPHY.sections[3].body',
    text: "Large organizations buy this kind of accumulation with headcount. RevealUI packages it as software you self-host, so a small team can build on yesterday's work instead of repeating it.",
    evidence: [BIO, SELF_HOST],
  },
  {
    file: 'philosophy.ts',
    exportPath: 'PHILOSOPHY.sections[4].body',
    text: 'Used in production by the team that maintains it.',
    evidence: [THIS_SITE],
  },
  {
    file: 'roadmap.ts',
    exportPath: 'ROADMAP_HERO.subtitle',
    text: 'What we have shipped and what we are building next.',
    evidence: [ROADMAP],
  },
  {
    file: 'roadmap.ts',
    exportPath: 'ROADMAP_SHIPPED[0].name',
    text: 'Perpetual Licenses (Track C)',
    evidence: [PERPETUAL],
  },
  {
    file: 'roadmap.ts',
    exportPath: 'ROADMAP_SHIPPED[0].description',
    text: 'Buy a license once and own Pro, Max, or Enterprise tier features for life, with no subscription required. Perpetual checkout is live today, and each license includes 1 year of priority support and updates.',
    evidence: [PERPETUAL],
  },
  {
    file: 'roadmap.ts',
    exportPath: 'ROADMAP_SHIPPED[1].description',
    text: 'Interact with an AI agent directly from the admin dashboard. Create content, query data, manage collections, and automate workflows through natural language, with streaming responses, tool visibility, and conversation history.',
    evidence: [AGENT_CHAT],
  },
  {
    file: 'roadmap.ts',
    exportPath: 'ROADMAP_SHIPPED[2].description',
    text: 'Documentation site live at docs.revealui.com with quick-start guides, API reference, architecture docs, and package reference. Video walkthroughs and collection cookbook coming soon.',
    evidence: [DOCS_APP],
  },
  {
    file: 'roadmap.ts',
    exportPath: 'ROADMAP_UPCOMING[0].description',
    text: 'A registry where developers publish and discover MCP servers and AI agent capabilities. Revenue share model for developers. Discoverable via Smithery, mcpt, and the RevealUI registry.',
    evidence: [ROADMAP],
  },
  {
    file: 'roadmap.ts',
    exportPath: 'ROADMAP_UPCOMING[1].name',
    text: 'Self-Hosted Docker Images (RevealUI Fleet)',
    evidence: [ROADMAP],
  },
  {
    file: 'roadmap.ts',
    exportPath: 'ROADMAP_UPCOMING[1].description',
    text: 'Official Docker images published to GitHub Container Registry for fully self-hosted deployment. Domain-locked licensing, air-gap capable.',
    evidence: [ROADMAP],
  },
  {
    file: 'roadmap.ts',
    exportPath: 'ROADMAP_UPCOMING[1].status',
    text: 'Planned: designed, not built',
    evidence: [ROADMAP],
  },
  {
    file: 'roadmap.ts',
    exportPath: 'ROADMAP_UPCOMING[2].description',
    text: 'A no-code visual builder for creating RevealUI sites. Drag-and-drop page building, component customization, and one-click deployment.',
    evidence: [ROADMAP],
  },
  {
    file: 'roadmap.ts',
    exportPath: 'ROADMAP_UPCOMING[3].description',
    text: 'OIDC and SAML SP-initiated federation for Enterprise accounts (Admin IdP config, test-connection, SP metadata). SCIM, advanced RBAC editor, and multi-region remain later enterprise work.',
    evidence: [ROADMAP, SSO_AUTH_ROUTES, SSO_ADMIN_UI, SSO_SAML_PURE, SSO_SETUP_DOC, RBAC_ABAC],
  },
  {
    file: 'roadmap.ts',
    exportPath: 'ROADMAP_UPCOMING[3].status',
    text: 'Shipped: Enterprise feature gate (OIDC + SAML SP-initiated)',
    evidence: [ROADMAP, SSO_AUTH_ROUTES, SSO_ADMIN_UI, SSO_SAML_PURE],
  },
  {
    file: 'roadmap.ts',
    exportPath: 'ROADMAP_CTA.title',
    text: 'Want to influence what ships next?',
    evidence: [ROADMAP],
  },
  {
    file: 'roadmap.ts',
    exportPath: 'ROADMAP_CTA.subtitle',
    text: 'We prioritize based on customer impact, product readiness, and community demand.',
    evidence: [ROADMAP],
  },
  {
    file: 'claims.ts',
    exportPath: 'CLAIMS_SIGNED_LEDGER_NOTE.body',
    text: 'Every action in the audit log is signed with a key you can check yourself. Verifying a record does not require our secret.',
    evidence: [AUDIT_ROW_SIGNER, AUDIT_SIGN_ROUNDTRIP],
  },
  {
    file: 'claims.ts',
    exportPath: 'CLAIMS_RECEIPT_HOLD_NOTE.body',
    text: 'On Max, the worker seals ranges of your signed audit log into Merkle roots you can download. You verify those roots offline with the published public key, without calling us. Free and Pro still get a signed log. Root delivery is Max. Checking a receipt is free either way.',
    evidence: [
      AUDIT_MERKLE,
      AUDIT_ANCHOR_SCHEMA,
      AUDIT_ANCHOR_API,
      AUDIT_ANCHOR_VERIFY,
      AUDIT_ANCHOR_VERIFY_CLI,
      AUDIT_ANCHOR_VERIFY_TEST,
      AUDIT_LOG_FEATURE_MAX,
      AUDIT_RECEIPTS_DOC,
    ],
  },
  {
    file: 'claims.ts',
    exportPath: 'CLAIMS_HERO.subtitle',
    text: 'Every sentence on this site that makes a claim about the product carries an entry below. Each one links to the code, the command, or the page that proves it.',
    evidence: [
      { ...CLAIMS_INDEX, note: `${CLAIMS_INDEX.note}; sentence 1, "carries an entry below"` },
      {
        ...CLAIMS_PAGE_ROUTE,
        note: `${CLAIMS_PAGE_ROUTE.note}; sentence 2, renders the code/command/page link per entry`,
      },
    ],
  },
  {
    file: 'claims.ts',
    exportPath: 'CLAIMS_LEDGER_INTRO',
    text: 'The ledger below is grouped by page, starting with the homepage and moving outward through the site.',
    evidence: [CLAIMS_ROUTE_MAP],
  },
  {
    file: 'claims.ts',
    exportPath: 'CLAIMS_KIND_LEGEND[0].description',
    text: 'A file or directory in the public repository that implements the claim.',
    evidence: [CLAIMS_PAGE_ROUTE],
  },
  {
    file: 'claims.ts',
    exportPath: 'CLAIMS_KIND_LEGEND[1].description',
    text: 'A command you can run yourself to reproduce the claim.',
    evidence: [CLAIMS_PAGE_ROUTE],
  },
  {
    file: 'claims.ts',
    exportPath: 'CLAIMS_KIND_LEGEND[2].description',
    text: 'A live page or endpoint that demonstrates the claim in production.',
    evidence: [CLAIMS_PAGE_ROUTE],
  },
  {
    file: 'claims.ts',
    exportPath: 'CLAIMS_KIND_LEGEND[3].description',
    text: 'A number pinned to the codebase and checked by the claim-drift gate.',
    evidence: [CLAIMS_PAGE_ROUTE, LICENSE_SPLIT],
  },
  {
    file: 'claims.ts',
    exportPath: 'CLAIMS_KIND_LEGEND[4].description',
    text: 'A named, non-skipped test in the repository that proves the claim in code.',
    evidence: [
      CLAIMS_PAGE_ROUTE,
      {
        kind: 'code',
        ref: 'scripts/validate/capability-claims.ts',
        note: 'validateTestRef asserts the test file exists, the title appears, and the test is not skip/todo',
      },
    ],
  },
  {
    file: 'claims.ts',
    exportPath: 'CLAIMS_HONESTY_RAILS_SECTION.intro',
    text: 'The validator that generates this page runs on every pull request and checks the following.',
    evidence: [CLAIMS_VALIDATOR, CI_GATE],
  },
  {
    file: 'claims.ts',
    exportPath: 'CLAIMS_HONESTY_RAILS_SECTION.checks[0]',
    text: 'Every covered sentence on the site carries a matching entry in this index.',
    evidence: [CLAIMS_VALIDATOR, CLAIMS_INDEX],
  },
  {
    file: 'claims.ts',
    exportPath: 'CLAIMS_HONESTY_RAILS_SECTION.checks[1]',
    text: "Each entry's text still matches the live copy, word for word.",
    evidence: [CLAIMS_VALIDATOR],
  },
  {
    file: 'claims.ts',
    exportPath: 'CLAIMS_HONESTY_RAILS_SECTION.checks[2]',
    text: 'Every code path an entry cites still exists in the tracked repository.',
    evidence: [
      { ...CLAIMS_VALIDATOR, note: `${CLAIMS_VALIDATOR.note}; the redaction-rail assertion` },
      {
        kind: 'test',
        ref: 'scripts/validate/__tests__/claims-evidence.test.ts#flags a code-kind ref to a path not tracked in the repo (proves red)',
        note: 'the redaction-rail assertion fails on an untracked code ref (proven red and green)',
      },
    ],
  },
  {
    file: 'claims.ts',
    exportPath: 'CLAIMS_HONESTY_RAILS_SECTION.notCheckedHeading',
    text: 'What this page does not check',
    evidence: [CLAIMS_VALIDATOR],
  },
  {
    file: 'claims.ts',
    exportPath: 'CLAIMS_HONESTY_RAILS_SECTION.doesNotCheck[0]',
    text: 'The gate does not check that the cited code actually does what the sentence claims.',
    evidence: [
      {
        kind: 'url',
        ref: 'https://github.com/RevealUIStudio/revealui',
        note: 'negative claim: the gate cannot verify code behavior, only that cited paths exist and cited text matches; verify by reading the validator source',
      },
    ],
  },
  {
    file: 'claims.ts',
    exportPath: 'CLAIMS_HONESTY_RAILS_SECTION.doesNotCheck[1]',
    text: 'That judgment is a human review layer, not an automated one.',
    evidence: [
      {
        kind: 'url',
        ref: 'https://revealui.com/claims',
        note: 'positive claim about process, not code; the honesty-rails copy itself is the disclosure',
      },
    ],
  },
  {
    file: 'receipt.ts',
    exportPath: 'RECEIPT_HERO_TITLE',
    text: 'Refund, handled by an agent',
    evidence: [REFUND_ROUTE, AGENT_ROUTES],
  },
  {
    file: 'receipt.ts',
    exportPath: 'RECEIPT_HERO_CAPTION.text',
    text: "If an agent did it, there's a receipt.",
    evidence: [
      AUDIT_SIGNING,
      AUDIT_SIGNING_TEST,
      AUDIT_LOG_SCHEMA,
      AUDIT_PUBLIC_KEY_ROUTE,
      REFUND_ROUTE,
      {
        ...AUDIT_RECEIPTS_DOC,
        note: 'Stage 4 S4-6: soft foil; sealed root download is Max (auditLog); verification never paid',
      },
      AUDIT_LOG_FEATURE_MAX,
    ],
  },
  {
    file: 'contact.ts',
    exportPath: 'CONTACT_HERO.subtitle',
    text: 'Questions about RevealUI? Interested in Enterprise or custom pricing? We would love to hear from you.',
    evidence: [
      LEGAL_CONTACT_CONTENT,
      { kind: 'url', ref: 'https://revealui.com/contact', note: 'public contact page' },
    ],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_META.intro',
    text: 'The RevealUI platform (revealui.com, admin.revealui.com, api.revealui.com, and docs.revealui.com, the "Service") is operated by REVEALUI STUDIO L.L.C., a Tennessee limited liability company ("we", "us", "our"). This Privacy Policy describes how we collect, use, and protect your personal information.',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[0].subsections[0].paragraph',
    text: 'When you create an account, we collect your email address, name, and password (stored as a bcrypt hash). If you sign up via OAuth (Google, GitHub), we receive your provider profile information.',
    evidence: [LEGAL_PRIVACY_CONTENT, AUTH_SESSIONS],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[0].subsections[1].paragraph',
    text: 'Payment processing is handled entirely by Stripe. We never store credit card numbers. We store your Stripe customer ID to link your account to your subscription.',
    evidence: [LEGAL_PRIVACY_CONTENT, BILLING],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[0].subsections[2].paragraph',
    text: 'We collect server logs (IP address, request path, user agent) for security monitoring and debugging. See §4 below for retention windows.',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[0].subsections[3].paragraph',
    text: 'Any content you create through the admin (posts, pages, media) is stored in your database. For hosted plans, this data is stored in NeonDB (PostgreSQL).',
    evidence: [LEGAL_PRIVACY_CONTENT, POSTGRES],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[1].heading',
    text: '2. How We Use Your Information',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[1].listItems[0]',
    text: 'To provide and maintain the Service',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[1].listItems[1]',
    text: 'To process payments and manage subscriptions',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[1].listItems[2]',
    text: 'To send transactional emails (password resets, billing notifications, license delivery)',
    evidence: [LEGAL_PRIVACY_CONTENT, AUTH_SESSIONS],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[1].listItems[3]',
    text: 'To detect and prevent fraud, abuse, and security incidents',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[1].listItems[4]',
    text: 'To diagnose application errors using error telemetry (Sentry). When an error occurs, a partial session recording of the moments preceding the crash may be captured to aid debugging. No proactive or continuous session recording is performed.',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[1].listItems[5]',
    text: 'To respond to support requests',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[1].paragraphs[0]',
    text: 'We do not sell your personal information. We do not use your data for advertising.',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[2].thirdParties[3].description',
    text: 'object storage (media uploads, generated assets)',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[2].thirdParties[4].description',
    text: 'transactional email delivery via Gmail API',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[2].thirdParties[5].description',
    text: 'application error tracking and crash-replay diagnostics',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[2].thirdParties[5].extra',
    text: 'Error data may include browser context, page URL, and a partial session recording captured at the time of an error. No continuous session recording is performed.',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[2].paragraphs[0]',
    text: 'For the full dated list of subprocessors with regions, data categories, and DPA links, see our Subprocessors page at https://revealui.com/legal/subprocessors. The Subprocessors page is the authoritative source; this section is a summary kept in sync with it.',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[3].heading',
    text: '4. Customer content and AI training',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[3].paragraphs[0]',
    text: 'We do not use customer content (the data, prompts, files, and configurations you submit to the Service) to train any general-purpose model. This commitment applies to any model we operate and to any third-party model accessed through the Service via our infrastructure.',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[3].paragraphs[1]',
    text: 'If you connect your own external LLM provider to RevealUI (your own OpenAI key, Anthropic key, or other provider), your data flows to that provider on terms you have agreed to with them. We do not intermediate those terms. You are responsible for understanding their training-data position.',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[3].paragraphs[2]',
    text: 'The default RevealUI configuration uses local AI inference (Ollama or Inference Snaps) that runs entirely on your own infrastructure. In that configuration, customer content does not leave your boundary at all.',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[4].paragraphs[0]',
    text: 'Account data is retained while your account is active. After account deletion, we permanently remove your personal data within 30 days. Application logs and error events are retained for 90 days. Infrastructure server logs (IP address, request path, user agent) are retained by our hosting provider per their policy. Billing records are retained as required by tax law (typically 7 years).',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[5].heading',
    text: '6. Your Rights (GDPR / CCPA)',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[5].listItems[0]',
    text: 'Access your personal data, available via your account settings or by contacting us',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[5].listItems[1]',
    text: 'Export your data: use the GDPR export endpoint in the admin',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[5].listItems[2]',
    text: 'Delete your account and all associated data: use the account deletion feature or contact us',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[5].listItems[3]',
    text: 'Correct inaccurate data: update your profile in the admin dashboard',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[5].listItems[4]',
    text: 'Object to processing: contact us at the email below',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[5].paragraphs[0]',
    text: 'California residents: Under the CCPA/CPRA you have the right to know what personal information we collect and to request its deletion. We do not sell or share personal information for cross-context advertising. We honor Global Privacy Control as a request to reject optional cookies.',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[6].paragraphs[0]',
    text: 'We protect your data using: bcrypt password hashing, session-based authentication with secure cookies, rate limiting and brute-force protection, HTTPS/TLS encryption in transit, and encrypted database connections.',
    evidence: [LEGAL_PRIVACY_CONTENT, AUTH_SESSIONS, POSTGRES],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[7].paragraphs[0]',
    text: 'Necessary cookies (session, role, CSRF, collaborative node id, and the consent cookie itself) run to provide the service. Optional analytics, Speed Insights, and Sentry replay stay off until you accept. Reject all is offered with the same prominence as Accept all. Global Privacy Control and Do Not Track are treated as reject-optional. The full inventory lives on the Cookie Policy at https://revealui.com/cookies.',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[8].paragraphs[0]',
    text: 'Hosted RevealUI is not a HIPAA-certified environment. Do not put protected health information on it without a signed Business Associate Agreement and the HIPAA configuration (REVEALUI_COMPLIANCE_PROFILE=hipaa). That profile turns optional telemetry off and signs idle admin sessions out after 15 minutes. Details: https://revealui.com/legal/hipaa.',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[9].paragraphs[0]',
    text: 'The Service is not intended for children under 13. We do not knowingly collect personal information from children under 13.',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[10].paragraphs[0]',
    text: 'We may update this Privacy Policy from time to time. We will notify registered users of material changes via email.',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/privacy.ts',
    exportPath: 'PRIVACY_SECTIONS[11].paragraphs[0]',
    text: '(interpolated: SITE email / domain embedded at runtime)',
    match: 'path',
    evidence: [LEGAL_PRIVACY_CONTENT],
  },
  {
    file: 'legal/refund-policy.ts',
    exportPath: 'REFUND_POLICY_META.intro',
    text: 'This page describes when you can get your money back from RevealUI Studio and how to ask for it. It applies to purchases made directly through revealui.com and admin.revealui.com.',
    evidence: [LEGAL_REFUND_CONTENT, REFUND_ROUTE],
  },
  {
    file: 'legal/refund-policy.ts',
    exportPath: 'REFUND_POLICY_SECTIONS[0].heading',
    text: '1. Perpetual licenses (Pro, Agency, and Enterprise Perpetual)',
    evidence: [LEGAL_REFUND_CONTENT, REFUND_ROUTE],
  },
  {
    file: 'legal/refund-policy.ts',
    exportPath: 'REFUND_POLICY_SECTIONS[0].paragraphs[0]',
    text: 'You may request a full refund within 14 days of purchase, for any reason, no questions asked. Refunds are processed within 5 business days. Your license key is revoked once the refund is issued.',
    evidence: [LEGAL_REFUND_CONTENT, REFUND_ROUTE],
  },
  {
    file: 'legal/refund-policy.ts',
    exportPath: 'REFUND_POLICY_SECTIONS[0].paragraphs[1]',
    text: 'After the 14-day window, refunds are available only for documented product defects, at our discretion.',
    evidence: [LEGAL_REFUND_CONTENT, REFUND_ROUTE],
  },
  {
    file: 'legal/refund-policy.ts',
    exportPath: 'REFUND_POLICY_SECTIONS[1].heading',
    text: '2. Subscriptions (Pro, Max, and Enterprise plans)',
    evidence: [LEGAL_REFUND_CONTENT, REFUND_ROUTE],
  },
  {
    file: 'legal/refund-policy.ts',
    exportPath: 'REFUND_POLICY_SECTIONS[1].paragraphs[0]',
    text: 'You can cancel a subscription at any time. Cancellation takes effect at the end of your current billing period, and there is no pro-rated refund for the unused portion of a billing cycle.',
    evidence: [LEGAL_REFUND_CONTENT, REFUND_ROUTE],
  },
  {
    file: 'legal/refund-policy.ts',
    exportPath: 'REFUND_POLICY_SECTIONS[1].paragraphs[1]',
    text: 'Your first month is refundable in full if you request it within 14 days of your initial paid charge.',
    evidence: [LEGAL_REFUND_CONTENT, REFUND_ROUTE],
  },
  {
    file: 'legal/refund-policy.ts',
    exportPath: 'REFUND_POLICY_SECTIONS[2].paragraphs[0]',
    text: 'Architecture Review, Fleet deployment, Custom Build, and other services sold by invoice are governed by the Master Service Agreement and Statement of Work for that engagement, not by this policy.',
    evidence: [LEGAL_REFUND_CONTENT, REFUND_ROUTE],
  },
  {
    file: 'legal/refund-policy.ts',
    exportPath: 'REFUND_POLICY_SECTIONS[3].heading',
    text: '4. How to request a refund',
    evidence: [LEGAL_REFUND_CONTENT, REFUND_ROUTE],
  },
  {
    file: 'legal/refund-policy.ts',
    exportPath: 'REFUND_POLICY_SECTIONS[3].listItems[0]',
    text: '(interpolated: SITE email / domain embedded at runtime)',
    match: 'path',
    evidence: [LEGAL_REFUND_CONTENT, REFUND_ROUTE],
  },
  {
    file: 'legal/refund-policy.ts',
    exportPath: 'REFUND_POLICY_SECTIONS[3].listItems[1]',
    text: 'We process eligible refunds within 5 business days of your request.',
    evidence: [LEGAL_REFUND_CONTENT, REFUND_ROUTE],
  },
  {
    file: 'legal/refund-policy.ts',
    exportPath: 'REFUND_POLICY_SECTIONS[3].listItems[2]',
    text: 'For a perpetual license, your license key is revoked once the refund is issued.',
    evidence: [LEGAL_REFUND_CONTENT, REFUND_ROUTE],
  },
  {
    file: 'legal/refund-policy.ts',
    exportPath: 'REFUND_POLICY_SECTIONS[4].paragraphs[0]',
    text: '(interpolated: SITE email / domain embedded at runtime)',
    match: 'path',
    evidence: [LEGAL_REFUND_CONTENT, REFUND_ROUTE],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_META.intro',
    text: 'RevealUI Studio is a solo-operator company building production software. Security is not a marketing line for us. It is a discipline we apply every day, and it determines whether real customers can trust us with their data. This page describes how we accept vulnerability reports, what we commit to in return, and the security posture our customers inherit when they self-host.',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[0].heading',
    text: '1. Reporting a vulnerability',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[0].paragraphs[0]',
    text: '(interpolated: SITE email / domain embedded at runtime)',
    match: 'path',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[0].paragraphs[1]',
    text: 'We do not currently publish a PGP key. If your report contains sensitive material (proof-of-concept payloads, user data exposure, exploit details), email us first and we will arrange an encrypted channel before you share specifics.',
    evidence: [
      LEGAL_SECURITY_CONTENT,
      {
        kind: 'code',
        ref: 'packages/security/src',
        note: 'crypto helpers; AES-256-GCM field encryption surface',
      },
    ],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[0].paragraphs[2]',
    text: 'We acknowledge receipt within 2 business days and aim to provide a substantive initial response within 5 business days. As a solo-operator company we cannot promise 24×7 triage, but we treat real security reports as our highest priority.',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[1].heading',
    text: '2. Our commitment to good-faith researchers',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[1].listPreamble',
    text: 'If you act in good faith and follow this policy, we commit to:',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[1].listItems[0]',
    text: 'Not pursue or support legal action against you for your research.',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[1].listItems[1]',
    text: 'Not contact law enforcement or your employer about your report.',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[1].listItems[2]',
    text: 'Work with you to understand and resolve the issue without unnecessary delay.',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[1].listItems[3]',
    text: 'Credit you publicly on this page when the issue is resolved, if you wish to be named. We will never publish your identity without your consent.',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[1].paragraphs[0]',
    text: 'We do not currently run a paid bug-bounty program. We are pre-revenue and cannot honestly promise bounty payouts that we may not be able to fund. If you find a material issue we will discuss recognition, swag, or (once we are revenue-generating) a discretionary reward.',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
  {
    file: 'legal/security.ts',
    exportPath: 'SECURITY_SECTIONS[2].listItems[0]',
    text: 'revealui.com (marketing site)',
    evidence: [LEGAL_SECURITY_CONTENT],
  },
];
