/**
 * RevealUI AI Response Formatting Utilities
 */

export function formatAIResponse(response: string, format: 'markdown' | 'html' | 'plain' = 'markdown'): string {
	switch (format) {
		case 'html':
			return convertToHTML(response)
		case 'plain':
			return convertToPlainText(response)
		case 'markdown':
		default:
			return enhanceMarkdown(response)
	}
}

function convertToHTML(text: string): string {
	// Basic markdown to HTML conversion
	let html = text

	// Headers
	html = html.replace(/^### (.*$)/gm, '<h3>$1</h3>')
	html = html.replace(/^## (.*$)/gm, '<h2>$1</h2>')
	html = html.replace(/^# (.*$)/gm, '<h1>$1</h1>')

	// Bold and italic
	html = html.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
	html = html.replace(/\*(.*?)\*/g, '<em>$1</em>')

	// Code blocks
	html = html.replace(/```([\s\S]*?)```/g, '<pre><code>$1</code></pre>')
	html = html.replace(/`([^`]+)`/g, '<code>$1</code>')

	// Lists
	html = html.replace(/^\* (.*$)/gm, '<li>$1</li>')
	html = html.replace(/^\d+\. (.*$)/gm, '<li>$1</li>')

	// Links
	html = html.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>')

	// Line breaks
	html = html.replace(/\n\n/g, '</p><p>')
	html = html.replace(/\n/g, '<br>')

	// Wrap in paragraph tags
	if (!html.includes('<p>')) {
		html = `<p>${html}</p>`
	}

	return html
}

function convertToPlainText(text: string): string {
	// Remove markdown formatting
	let plain = text

	// Remove headers
	plain = plain.replace(/^#+\s*/gm, '')

	// Remove bold/italic markers
	plain = plain.replace(/\*\*(.*?)\*\*/g, '$1')
	plain = plain.replace(/\*(.*?)\*/g, '$1')

	// Remove code markers
	plain = plain.replace(/```[\s\S]*?```/g, '[code block]')
	plain = plain.replace(/`([^`]+)`/g, '"$1"')

	// Remove links but keep text
	plain = plain.replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')

	// Clean up extra whitespace
	plain = plain.replace(/\n\n+/g, '\n\n')
	plain = plain.replace(/^\s+|\s+$/g, '')

	return plain
}

function enhanceMarkdown(text: string): string {
	// Add RevealUI branding and formatting enhancements
	let enhanced = text

	// Add code block language hints if missing
	enhanced = enhanced.replace(/```([\s\S]*?)```/g, (match, code) => {
		if (!code.includes('\n')) return match // Single line, probably inline
		const firstLine = code.split('\n')[0].toLowerCase()
		if (!firstLine.includes('javascript') && !firstLine.includes('typescript') &&
			!firstLine.includes('jsx') && !firstLine.includes('tsx')) {
			// Try to detect language
			if (code.includes('import') || code.includes('export') || code.includes('React')) {
				return `\`\`\`typescript\n${code}\`\`\``
			}
			if (code.includes('function') || code.includes('const') || code.includes('let')) {
				return `\`\`\`javascript\n${code}\`\`\``
			}
		}
		return match
	})

	// Add section headers for better organization
	if (!enhanced.includes('# ') && enhanced.length > 500) {
		enhanced = `# RevealUI AI Response\n\n${enhanced}`
	}

	// Add table of contents for long responses
	if (enhanced.split('\n').length > 20 && enhanced.includes('## ')) {
		const headers = enhanced.match(/^## (.*$)/gm)
		if (headers && headers.length > 2) {
			const toc = headers.map(h => {
				const title = h.replace('## ', '')
				const anchor = title.toLowerCase().replace(/[^a-z0-9]+/g, '-')
				return `- [${title}](#${anchor})`
			}).join('\n')

			enhanced = `# RevealUI AI Response\n\n## Table of Contents\n${toc}\n\n${enhanced.replace('# RevealUI AI Response\n\n', '')}`
		}
	}

	return enhanced
}

export function formatAIUsage(usage: {
	promptTokens: number
	completionTokens: number
	totalTokens: number
}): string {
	const costPerToken = 0.00015 // Approximate cost for GPT-4
	const estimatedCost = (usage.totalTokens * costPerToken).toFixed(4)

	return `**Usage Statistics:**
- Prompt tokens: ${usage.promptTokens.toLocaleString()}
- Completion tokens: ${usage.completionTokens.toLocaleString()}
- Total tokens: ${usage.totalTokens.toLocaleString()}
- Estimated cost: $${estimatedCost}

*Generated by RevealUI AI*`
}

export function formatError(error: string, context?: string): string {
	return `🚨 **RevealUI AI Error**

${error}

${context ? `**Context:** ${context}` : ''}

**Suggestions:**
- Check your API key configuration
- Verify network connectivity
- Try simplifying your prompt
- Contact RevealUI support if issues persist

*Error occurred at ${new Date().toISOString()}*`
}

export function createRevealUIWrapper(content: string, metadata?: {
	type?: 'response' | 'error' | 'suggestion'
	confidence?: number
	model?: string
}): string {
	const type = metadata?.type || 'response'
	const confidence = metadata?.confidence || 85
	const model = metadata?.model || 'RevealUI AI'

	const header = `🤖 **RevealUI AI ${type.charAt(0).toUpperCase() + type.slice(1)}**`
	const footer = `*Generated by ${model} with ${confidence}% confidence*`

	return `${header}\n\n${content}\n\n---\n${footer}`
}

