#!/usr/bin/env tsx
/**
 * Build the slug-manifest for chip 3 docs URL flatten.
 *
 * Walks suite-root `docs/**\/*.md`, applies the same exclusions as
 * the Vite docsCopyPlugin (INTERNAL_DOC_FILES + ignored dirs), and
 * writes a deterministic `app/lib/slug-manifest.ts` containing a
 * SLUG_TO_PATH map.
 *
 * Run via:
 *   pnpm --filter docs build:slug-manifest
 *   # or directly:
 *   tsx apps/docs/scripts/build-slug-manifest.ts
 *
 * Output is committed to git so the runtime resolver doesn't depend
 * on filesystem walks at module load. Re-run any time docs/ files
 * are added, removed, or renamed.
 */

import { readdir, writeFile } from 'node:fs/promises';
import { join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { pathToSlug } from '../app/lib/slug.js';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const DOCS_SOURCE = resolve(__dirname, '../../../docs');
const MANIFEST_OUT = resolve(__dirname, '../app/lib/slug-manifest.ts');

// Mirror INTERNAL_DOC_FILES from vite.config.ts. Keep in sync.
const INTERNAL_DOC_FILES = new Set([
  'MASTER_PLAN.md',
  'GOVERNANCE.md',
  'AI-AGENT-RULES.md',
  'AUTOMATION.md',
  'CI_ENVIRONMENT.md',
  'PRICE_COLLECTION.md',
  'PRODUCT_COLLECTION.md',
  'SECRETS-MANAGEMENT.md',
  'STANDARDS.md',
]);

const IGNORED_DIRS = new Set(['node_modules', '.next', 'dist', 'archive']);

interface Entry {
  slug: string;
  path: string;
}

async function walk(dir: string, prefix = ''): Promise<Entry[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const results: Entry[] = [];

  for (const entry of entries) {
    if (entry.name.startsWith('.')) continue;
    if (IGNORED_DIRS.has(entry.name)) continue;

    const fullPath = join(dir, entry.name);
    const relPath = prefix ? `${prefix}/${entry.name}` : entry.name;

    if (entry.isDirectory()) {
      results.push(...(await walk(fullPath, relPath)));
    } else if (entry.isFile() && entry.name.endsWith('.md')) {
      // Top-level INTERNAL_DOC_FILES exclusion (matches Vite plugin behavior)
      if (!prefix && INTERNAL_DOC_FILES.has(entry.name)) continue;
      results.push({ slug: pathToSlug(relPath), path: relPath });
    }
  }

  return results;
}

async function main(): Promise<void> {
  const entries = await walk(DOCS_SOURCE);
  entries.sort((a, b) => a.slug.localeCompare(b.slug));

  // Detect collisions before write — fail loudly.
  const seen = new Map<string, string>();
  const collisions: Array<[string, string, string]> = [];
  for (const { slug, path } of entries) {
    const prior = seen.get(slug);
    if (prior) {
      collisions.push([slug, prior, path]);
    } else {
      seen.set(slug, path);
    }
  }
  if (collisions.length > 0) {
    process.stderr.write(`\nERROR: ${collisions.length} slug collision(s) detected:\n`);
    for (const [slug, a, b] of collisions) {
      process.stderr.write(`  '${slug}' <- ${a} AND ${b}\n`);
    }
    process.stderr.write('\nResolve before regenerating manifest.\n');
    process.exit(1);
  }

  const lines: string[] = [
    '/**',
    ' * AUTO-GENERATED by apps/docs/scripts/build-slug-manifest.ts.',
    ' * Do not edit by hand. Regenerate via `pnpm --filter docs build:slug-manifest`.',
    ' *',
    ' * Maps lowercase-kebab slugs to their original docs/ file paths.',
    ' * Used by the markdown resolver to translate flat URLs',
    ' * (docs.revealui.com/admin-guide) into file fetches',
    ' * (/admin-guide.md served from public/).',
    ` * Generated: ${entries.length} entries.`,
    ' */',
    '',
    'export const SLUG_TO_PATH: Readonly<Record<string, string>> = Object.freeze({',
  ];

  for (const { slug, path } of entries) {
    lines.push(`  ${JSON.stringify(slug)}: ${JSON.stringify(path)},`);
  }

  lines.push('});');
  lines.push('');
  lines.push('export const PATH_TO_SLUG: Readonly<Record<string, string>> = Object.freeze(');
  lines.push('  Object.fromEntries(');
  lines.push('    Object.entries(SLUG_TO_PATH).map(([slug, path]) => [path, slug]),');
  lines.push('  ),');
  lines.push(');');
  lines.push('');
  lines.push('/** Resolve a slug to its docs/ file path, or null if unknown. */');
  lines.push('export function slugToPath(slug: string): string | null {');
  lines.push('  return SLUG_TO_PATH[slug] ?? null;');
  lines.push('}');
  lines.push('');
  lines.push('/** Resolve a docs/ file path to its slug, or null if unknown. */');
  lines.push('export function pathToSlugLookup(path: string): string | null {');
  lines.push('  return PATH_TO_SLUG[path] ?? null;');
  lines.push('}');
  lines.push('');

  await writeFile(MANIFEST_OUT, lines.join('\n'), 'utf8');

  process.stdout.write(`Generated ${MANIFEST_OUT} with ${entries.length} entries.\n`);
  const rel = relative(process.cwd(), MANIFEST_OUT);
  process.stdout.write(`Relative: ${rel}\n`);
}

main().catch((err) => {
  process.stderr.write(`build-slug-manifest failed: ${err}\n`);
  process.exit(1);
});
