import type { PageContext } from '../types/frontend.js';

// Re-export types for compatibility
export type { PageContext, PageContextInit } from '../types/frontend.js';

/**
 * HTML entity escaping map for preventing XSS
 */
const HTML_ESCAPE_MAP: Record<string, string> = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#x27;',
  '/': '&#x2F;',
};

/**
 * Escape HTML entities to prevent XSS attacks.
 *
 * @param str - String to escape
 * @returns Escaped string safe for HTML content
 *
 * @example
 * ```typescript
 * escapeHtml('<script>alert("xss")</script>')
 * // Returns: '&lt;script&gt;alert(&quot;xss&quot;)&lt;/script&gt;'
 * ```
 */
export function escapeHtml(str: string): string {
  return str.replace(/[&<>"'/]/g, (char) => HTML_ESCAPE_MAP[char] || char);
}

/**
 * Options for rendering an HTML shell
 */
export interface HTMLShellOptions {
  title?: string;
  description?: string;
  lang?: string;
  charset?: string;
  viewport?: string;
  styles?: string[];
  scripts?: string[];
  headContent?: string;
  bodyContent?: string;
  bodyAttributes?: Record<string, string>;
}

/**
 * Render a basic HTML shell for SSR.
 *
 * @param options - Options for the HTML shell
 * @returns Complete HTML document string
 *
 * @example
 * ```typescript
 * const html = renderHTMLShell({
 *   title: 'My Page',
 *   description: 'A sample page',
 *   bodyContent: '<div id="root">Loading...</div>',
 *   styles: ['/styles/main.css'],
 *   scripts: ['/js/app.js'],
 * })
 * ```
 */
export function renderHTMLShell(options: HTMLShellOptions = {}): string {
  const {
    title = 'Page',
    description = '',
    lang = 'en',
    charset = 'UTF-8',
    viewport = 'width=device-width, initial-scale=1.0',
    styles = [],
    scripts = [],
    headContent = '',
    bodyContent = '',
    bodyAttributes = {},
  } = options;

  const escapedTitle = escapeHtml(title);
  const escapedDescription = escapeHtml(description);

  const styleLinks = styles
    .map((href) => `  <link rel="stylesheet" href="${escapeHtml(href)}">`)
    .join('\n');

  const scriptTags = scripts
    .map((src) => `  <script src="${escapeHtml(src)}" defer></script>`)
    .join('\n');

  const bodyAttrs = Object.entries(bodyAttributes)
    .map(([key, value]) => `${escapeHtml(key)}="${escapeHtml(value)}"`)
    .join(' ');
  const bodyTag = bodyAttrs ? `<body ${bodyAttrs}>` : '<body>';

  return `<!DOCTYPE html>
<html lang="${lang}">
<head>
  <meta charset="${charset}">
  <meta name="viewport" content="${viewport}">
  <title>${escapedTitle}</title>
  ${escapedDescription ? `<meta name="description" content="${escapedDescription}">` : ''}
${styleLinks}
${headContent}
</head>
${bodyTag}
${bodyContent}
${scriptTags}
</body>
</html>`.trim();
}

/**
 * Render a page to HTML string for server-side rendering.
 *
 * This is a framework-agnostic utility for basic SSR. For React Server Components
 * and advanced features like Lexical rich text serialization, use the full
 * SSR handler at apps/mainframe/src/server/revealui-handler.tsx.
 *
 * @param pageData - The page data to render
 * @param context - Page context information
 * @returns HTML string
 *
 * @example
 * ```typescript
 * const html = renderPage(
 *   { title: 'Welcome', content: '<p>Hello world</p>' },
 *   { url: '/welcome', locale: 'en' }
 * )
 * ```
 */
export function renderPage(pageData: unknown, context: PageContext): string {
  void context;

  const data =
    pageData && typeof pageData === 'object' ? (pageData as Record<string, unknown>) : {};
  const title = typeof data.title === 'string' ? data.title : 'Page';
  const content = typeof data.content === 'string' ? data.content : '';
  const description =
    typeof data.description === 'string' ? data.description : 'Generated by RevealUI admin';

  // Escape title and description, but allow content to contain safe HTML
  const escapedTitle = escapeHtml(title);

  return renderHTMLShell({
    title,
    description,
    bodyContent: `  <div id="root">
    <h1>${escapedTitle}</h1>
    <div>${content}</div>
  </div>`,
  });
}
