#!/usr/bin/env tsx
/**
 * Generate Ed25519 Key Pair for License Signing
 *
 * Generates Ed25519 keys used by the webhook handler to sign JWT license keys
 * and by the API to verify them.
 *
 * Usage:
 *   pnpm stripe:keys              # Print keys for .env
 *   pnpm stripe:keys -- --write   # Append to .env file directly
 */

import { generateKeyPairSync } from 'node:crypto';
import { appendFileSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const log = {
  header: (msg: string) => console.log(`\n${'═'.repeat(60)}\n  ${msg}\n${'═'.repeat(60)}`),
  info: (msg: string) => console.log(`  ℹ ${msg}`),
  success: (msg: string) => console.log(`  ✓ ${msg}`),
  warn: (msg: string) => console.log(`  ⚠ ${msg}`),
  error: (msg: string) => console.error(`  ✗ ${msg}`),
};

function main(): void {
  const writeToEnv = process.argv.includes('--write');
  const envPath = resolve(import.meta.dirname, '../../.env');

  log.header('Ed25519 License Key Generator');

  // Check if keys already exist in .env
  try {
    const envContent = readFileSync(envPath, 'utf-8');
    if (
      envContent.includes('REVEALUI_LICENSE_PRIVATE_KEY=') &&
      !envContent.includes('REVEALUI_LICENSE_PRIVATE_KEY=\n') &&
      !envContent.includes('REVEALUI_LICENSE_PRIVATE_KEY=""')
    ) {
      log.warn('License keys already exist in .env');
      log.info(
        'Delete the existing REVEALUI_LICENSE_PRIVATE_KEY and REVEALUI_LICENSE_PUBLIC_KEY lines to regenerate',
      );
      return;
    }
  } catch {
    // .env doesn't exist  -  that's fine
  }

  log.info('Generating Ed25519 key pair...');

  const { publicKey, privateKey } = generateKeyPairSync('ed25519', {
    publicKeyEncoding: { type: 'spki', format: 'pem' },
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
  });

  // Escape newlines for .env format (single line)
  const privateKeyOneLine = privateKey.trim().replace(/\n/g, '\\n');
  const publicKeyOneLine = publicKey.trim().replace(/\n/g, '\\n');

  log.success('Key pair generated');

  if (writeToEnv) {
    const lines = [
      '',
      '# License signing keys (generated by pnpm stripe:keys)',
      `REVEALUI_LICENSE_PRIVATE_KEY="${privateKeyOneLine}"`,
      `REVEALUI_LICENSE_PUBLIC_KEY="${publicKeyOneLine}"`,
      '',
    ];

    appendFileSync(envPath, lines.join('\n'));
    log.success(`Keys written to ${envPath}`);
    log.warn('Do NOT commit .env to git');
  } else {
    log.header('Add to .env');
    console.log('');
    console.log(`REVEALUI_LICENSE_PRIVATE_KEY="${privateKeyOneLine}"`);
    console.log('');
    console.log(`REVEALUI_LICENSE_PUBLIC_KEY="${publicKeyOneLine}"`);
    console.log('');
    log.info('Or run with --write to append to .env automatically:');
    log.info('  pnpm stripe:keys -- --write');
  }
}

main();
