/**
 * Users primitive — identity, authentication, sessions, and access control.
 *
 * Re-exports from @revealui/auth, @revealui/db, and @revealui/contracts.
 */

// ── Auth: error types (re-exported for convenience) ─────────────────────────
export type {
  AuthSession,
  Session,
  SignInResult,
  SignUpResult,
  User,
} from '@revealui/auth';
// ── Auth: server-side operations ────────────────────────────────────────────
// ── Auth: React hooks ───────────────────────────────────────────────────────
export {
  AuthError,
  AuthenticationError,
  auditAccountLocked,
  auditLoginFailure,
  auditLoginSuccess,
  auditMfaDisabled,
  auditMfaEnabled,
  auditPasswordChange,
  auditPasswordReset,
  auditSessionRevoked,
  buildAuthUrl,
  changePassword,
  checkRateLimit,
  clearFailedAttempts,
  configureBruteForce,
  configureMagicLink,
  configureMFA,
  configurePasskey,
  configureRateLimit,
  countUserCredentials,
  createMagicLink,
  createSession,
  createStorage,
  DatabaseStorage,
  deleteAllUserSessions,
  deletePasskey,
  deleteSession,
  disableMFA,
  exchangeCode,
  generateAuthenticationChallenge,
  generateOAuthState,
  generatePasswordResetToken,
  generateRegistrationChallenge,
  getFailedAttemptCount,
  getLinkedProviders,
  getRateLimitStatus,
  getSession,
  getStorage,
  InMemoryStorage,
  initiateMFASetup,
  isAccountLocked,
  isMFAEnabled,
  isRecoverySession,
  isSignupAllowed,
  linkOAuthAccount,
  listPasskeys,
  OAuthAccountConflictError,
  recordFailedAttempt,
  regenerateBackupCodes,
  renamePasskey,
  resetPasswordWithToken,
  rotateSession,
  SessionError,
  signIn,
  signUp,
  storePasskey,
  TokenError,
  unlinkOAuthAccount,
  upsertOAuthUser,
  useMFASetup,
  useMFAVerify,
  usePasskeyRegister,
  usePasskeySignIn,
  useSession,
  useSignIn,
  useSignOut,
  useSignUp,
  validatePasswordResetToken,
  validatePasswordStrength,
  validateSessionBinding,
  verifyAuthentication,
  verifyBackupCode,
  verifyMagicLink,
  verifyMFACode,
  verifyMFASetup,
  verifyOAuthState,
  verifyRegistration,
} from '@revealui/auth';
// ── Contracts: user schemas & types ─────────────────────────────────────────
export {
  type CreateUserInput,
  CreateUserInputSchema,
  createUser,
  type UpdateUserInput,
  UpdateUserInputSchema,
  USER_SCHEMA_VERSION,
  type UserPreferences,
  UserPreferencesSchema,
  type UserRole,
  UserRoleSchema,
  UserSchema,
  type UserStatus,
  UserStatusSchema,
  type UserType,
  UserTypeSchema,
} from '@revealui/contracts';
// ── DB: user tables ─────────────────────────────────────────────────────────
export {
  failedAttempts,
  magicLinks,
  oauthAccounts,
  passkeys,
  passwordResetTokens,
  sessions,
  users,
} from '@revealui/db';
