#!/usr/bin/env tsx
/**
 * Em Dash Audit Script
 *
 * Scans user-facing files for em dash characters (U+2014) and &mdash; entities.
 * Em dashes are not used in RevealUI copy - use spaced hyphens ( - ) instead.
 *
 * Skips:
 *   - Code blocks (fenced ``` and inline backticks)
 *   - CHANGELOG files (auto-generated by changesets)
 *   - Build artifacts, node_modules, coverage, etc.
 *
 * Usage:
 *   pnpm audit:emdash            # Report findings
 *   pnpm audit:emdash --fix      # Auto-replace with " - "
 *   pnpm audit:emdash --json     # JSON output
 *
 * @module scripts/analyze/audit-emdash
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ErrorCode } from '@revealui/scripts/errors.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const workspaceRoot = join(__dirname, '../..');

const DEFAULT_EXCLUDE_DIRS = [
  'node_modules',
  'dist',
  'build',
  '.next',
  '.turbo',
  '.cursor',
  'coverage',
  '.git',
  '.nuxt',
  '.output',
  '.vercel',
  '.cache',
  'opensrc',
  'playwright-report',
  'test-results',
];

const SCAN_EXTENSIONS = ['.md', '.tsx', '.ts', '.html', '.jsx', '.js'];

/** Files to skip entirely (auto-generated or irrelevant). */
function shouldSkipFile(filePath: string): boolean {
  const name = filePath.split('/').pop() ?? '';
  // Skip changelogs (auto-generated by changesets)
  if (name === 'CHANGELOG.md') return true;
  // Skip lockfiles and generated manifests
  if (name === 'pnpm-lock.yaml') return true;
  if (name.endsWith('.d.ts')) return true;
  return false;
}

interface EmDashFinding {
  file: string;
  line: number;
  column: number;
  context: string;
  inCodeBlock: boolean;
}

function scanDirectorySync(dir: string, extensions: string[] = SCAN_EXTENSIONS): string[] {
  const files: string[] = [];

  function scan(currentDir: string, depth: number): void {
    if (depth > 50) return;

    try {
      const entries = readdirSync(currentDir, { withFileTypes: true });

      for (const entry of entries) {
        if (entry.name.startsWith('.')) continue;

        const fullPath = join(currentDir, entry.name);

        if (entry.isDirectory() && DEFAULT_EXCLUDE_DIRS.includes(entry.name)) {
          continue;
        }

        if (entry.isDirectory()) {
          scan(fullPath, depth + 1);
        } else if (entry.isFile()) {
          const ext = entry.name.substring(entry.name.lastIndexOf('.'));
          if (extensions.includes(ext)) {
            files.push(fullPath);
          }
        }
      }
    } catch {
      // Skip directories we can't read
    }
  }

  scan(dir, 0);
  return files;
}

/**
 * Detect whether a line is inside a fenced code block.
 * Tracks opening/closing ``` markers across lines.
 */
function buildCodeBlockMap(lines: string[]): boolean[] {
  const map: boolean[] = [];
  let insideCodeBlock = false;

  for (const line of lines) {
    const trimmed = line.trimStart();
    if (trimmed.startsWith('```')) {
      if (insideCodeBlock) {
        // Closing fence - this line is still inside
        map.push(true);
        insideCodeBlock = false;
      } else {
        // Opening fence - this line is inside
        insideCodeBlock = true;
        map.push(true);
      }
    } else {
      map.push(insideCodeBlock);
    }
  }

  return map;
}

/**
 * Check if an em dash at a given column is inside inline backticks on that line.
 */
function isInsideInlineCode(line: string, column: number): boolean {
  let insideBacktick = false;
  for (let i = 0; i < line.length && i < column; i++) {
    if (line[i] === '`') {
      insideBacktick = !insideBacktick;
    }
  }
  return insideBacktick;
}

function getContext(line: string, column: number, radius: number = 40): string {
  const start = Math.max(0, column - radius);
  const end = Math.min(line.length, column + radius + 1);
  let ctx = line.substring(start, end).trim();
  if (start > 0) ctx = '...' + ctx;
  if (end < line.length) ctx = ctx + '...';
  return ctx;
}

function scanFile(filePath: string): EmDashFinding[] {
  const findings: EmDashFinding[] = [];
  const content = readFileSync(filePath, 'utf8');
  const lines = content.split('\n');
  const codeBlockMap = buildCodeBlockMap(lines);
  const relPath = relative(workspaceRoot, filePath);

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    // Search for em dash character
    let col = line.indexOf('\u2014');
    while (col !== -1) {
      const inCode = codeBlockMap[i] || isInsideInlineCode(line, col);
      findings.push({
        file: relPath,
        line: i + 1,
        column: col + 1,
        context: getContext(line, col),
        inCodeBlock: inCode,
      });
      col = line.indexOf('\u2014', col + 1);
    }
    // Search for &mdash; entity
    col = line.indexOf('&mdash;');
    while (col !== -1) {
      const inCode = codeBlockMap[i] || isInsideInlineCode(line, col);
      findings.push({
        file: relPath,
        line: i + 1,
        column: col + 1,
        context: getContext(line, col),
        inCodeBlock: inCode,
      });
      col = line.indexOf('&mdash;', col + 7);
    }
  }

  return findings;
}

function fixFile(filePath: string): number {
  const content = readFileSync(filePath, 'utf8');
  const lines = content.split('\n');
  const codeBlockMap = buildCodeBlockMap(lines);
  let fixCount = 0;

  const fixedLines = lines.map((line, i) => {
    if (codeBlockMap[i]) return line;

    let result = '';
    let lastIndex = 0;

    // Process character by character to respect inline backticks
    const chars = [...line];
    let insideBacktick = false;

    for (let j = 0; j < chars.length; j++) {
      if (chars[j] === '`') {
        insideBacktick = !insideBacktick;
      }
    }

    // Simpler approach: rebuild line segments outside backticks
    insideBacktick = false;
    result = '';

    for (let j = 0; j < line.length; j++) {
      if (line[j] === '`') {
        insideBacktick = !insideBacktick;
        result += '`';
        continue;
      }

      if (insideBacktick) {
        result += line[j];
        continue;
      }

      // Check for em dash character
      if (line[j] === '\u2014') {
        result += ' - ';
        fixCount++;
        continue;
      }

      // Check for &mdash; entity
      if (line.substring(j, j + 7) === '&mdash;') {
        result += ' - ';
        fixCount++;
        j += 6; // Skip remaining chars of &mdash;
        continue;
      }

      result += line[j];
    }

    return result;
  });

  if (fixCount > 0) {
    writeFileSync(filePath, fixedLines.join('\n'));
  }

  return fixCount;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const args = process.argv.slice(2);
const jsonMode = args.includes('--json');
const fixMode = args.includes('--fix');

const files = scanDirectorySync(workspaceRoot).filter((f) => !shouldSkipFile(f));

if (fixMode) {
  // Fix mode: replace em dashes in-place
  let totalFixed = 0;
  let filesFixed = 0;

  for (const file of files) {
    const count = fixFile(file);
    if (count > 0) {
      totalFixed += count;
      filesFixed++;
      if (!jsonMode) {
        const rel = relative(workspaceRoot, file);
        console.log(`  Fixed ${count} em dash${count > 1 ? 'es' : ''} in ${rel}`);
      }
    }
  }

  if (jsonMode) {
    console.log(JSON.stringify({ totalFixed, filesFixed }));
  } else {
    console.log(
      `\nFixed ${totalFixed} em dash${totalFixed !== 1 ? 'es' : ''} across ${filesFixed} file${filesFixed !== 1 ? 's' : ''}.`,
    );
  }

  process.exit(ErrorCode.SUCCESS);
} else {
  // Audit mode: report findings
  const allFindings: EmDashFinding[] = [];

  for (const file of files) {
    const findings = scanFile(file);
    allFindings.push(...findings);
  }

  // Split into actionable vs code-block (informational)
  const actionable = allFindings.filter((f) => !f.inCodeBlock);
  const inCode = allFindings.filter((f) => f.inCodeBlock);

  // Group by directory for summary
  const byDir = new Map<string, number>();
  for (const f of actionable) {
    const dir = f.file.split('/').slice(0, 2).join('/');
    byDir.set(dir, (byDir.get(dir) ?? 0) + 1);
  }

  if (jsonMode) {
    console.log(
      JSON.stringify({
        total: actionable.length,
        inCodeBlocks: inCode.length,
        byDirectory: Object.fromEntries(byDir),
        findings: actionable.slice(0, 100),
      }),
    );
  } else {
    console.log('================================================================================');
    console.log('Em Dash Audit Report');
    console.log('================================================================================');
    console.log();
    console.log(`Total em dashes found: ${actionable.length}`);
    console.log(`  In code blocks (skipped): ${inCode.length}`);
    console.log();

    if (byDir.size > 0) {
      console.log('By Directory:');
      const sorted = [...byDir.entries()].sort((a, b) => b[1] - a[1]);
      for (const [dir, count] of sorted) {
        console.log(`  ${dir.padEnd(40)} ${count}`);
      }
      console.log();
    }

    if (actionable.length > 0) {
      // Group by file for readable output
      const byFile = new Map<string, EmDashFinding[]>();
      for (const f of actionable) {
        const arr = byFile.get(f.file) ?? [];
        arr.push(f);
        byFile.set(f.file, arr);
      }

      const fileEntries = [...byFile.entries()].sort((a, b) => b[1].length - a[1].length);
      const maxFiles = 30;

      console.log(
        `Top files (showing ${Math.min(maxFiles, fileEntries.length)} of ${fileEntries.length}):`,
      );
      for (const [file, findings] of fileEntries.slice(0, maxFiles)) {
        console.log(`\n  ${file} (${findings.length}):`);
        for (const f of findings.slice(0, 5)) {
          console.log(`    L${f.line}:${f.column}  ${f.context}`);
        }
        if (findings.length > 5) {
          console.log(`    ... and ${findings.length - 5} more`);
        }
      }
      console.log();
    }

    if (actionable.length > 0) {
      console.log(`\nRun with --fix to auto-replace all ${actionable.length} em dashes with " - "`);
      process.exit(ErrorCode.EXECUTION_ERROR);
    } else {
      console.log('No em dashes found in user-facing copy.');
      process.exit(ErrorCode.SUCCESS);
    }
  }
}
