/**
 * Admin Content-Security-Policy — single source of truth.
 *
 * Built per-request by the admin proxy (`src/proxy.ts`) and applied to every
 * page and `/api` response. This replaces the previous split between the static
 * `next.config.mjs` header (generated by `csp.mjs`) and the inline `/api` CSP in
 * `proxy.ts`. Those two sources had drifted apart (different directives) and both
 * gated `'unsafe-inline'` by environment without a nonce — which broke Next.js
 * App Router inline hydration on the production admin login page (regression
 * #848; interim re-allow shipped in #1068).
 *
 * Hardening model:
 *   - `script-src` carries a per-request `'nonce-<n>'` instead of
 *     `'unsafe-inline'`. Next.js reads the nonce from the request's
 *     `Content-Security-Policy` header and applies it to its framework, bundle,
 *     and inline bootstrap scripts (plus `<Script>` components).
 *   - We deliberately KEEP the external-script host allowlist (Stripe, Maps,
 *     Cloudinary, Vercel insights) in non-fleet mode and do NOT use
 *     `'strict-dynamic'`, which would make those host-sources be ignored. In
 *     fleet mode (`REVEALUI_FLEET_MODE=true`) the hosted third-party SDK domains
 *     are omitted — fleet kits are self-hosted and must not phone home to
 *     SaaS-specific endpoints. (`'unsafe-inline'` is ignored by CSP3 browsers
 *     whenever a nonce is present, so dropping it is the intended tightening,
 *     not a behaviour change for compliant browsers.)
 *   - `'unsafe-eval'` stays dev-only — React uses `eval` for dev error overlays;
 *     production React/Next do not.
 *   - `style-src` keeps `'unsafe-inline'` by design: Tailwind v4, Next, and the
 *     tenant brand `<style>` rely on inline styles, the XSS surface via style is
 *     far lower, and nonce-ing styles is out of scope here (script-src is the
 *     XSS-relevant surface this change targets).
 *
 * Edge-safe: pure string building + Web Crypto only (no Node APIs), so it runs
 * unchanged in the Edge proxy runtime.
 */

export interface AdminCspOptions {
  /** Per-request nonce (base64); generate with {@link generateNonce}. */
  nonce: string;
  /** `NODE_ENV === 'development'` — local `next dev`. Enables `'unsafe-eval'`. */
  isDev: boolean;
  /** `process.env.VERCEL` present — running on a Vercel deployment. */
  isVercel: boolean;
  /** `process.env.VERCEL_ENV === 'production'` — the production deployment. */
  isVercelProd: boolean;
  /** `NEXT_PUBLIC_API_URL` — the API origin the admin browser calls (trimmed, defaulted). */
  apiUrl: string;
  /** `NEXT_PUBLIC_SERVER_URL` — optional deployment origin; `''` when unset. */
  serverUrl: string;
  /**
   * `REVEALUI_FLEET_MODE === 'true'` — running as a fleet kit.
   * When true, hosted third-party SDK domains (Stripe.js, Vercel Analytics,
   * Google Maps, Cloudinary) are omitted from every CSP directive. Fleet kits
   * are self-hosted and must not include SaaS-specific external origins.
   */
  isFleetMode?: boolean;
}

/**
 * Generate a CSP nonce: 16 random bytes, base64-encoded. Uses Web Crypto so it
 * runs in the Edge runtime (matches the admin's existing `csrf-token.ts` style).
 */
export function generateNonce(): string {
  const bytes = crypto.getRandomValues(new Uint8Array(16));
  return btoa(String.fromCharCode(...bytes));
}

/**
 * Build the admin `Content-Security-Policy` header value for one request.
 *
 * Mirrors the previous page policy (the directives that were in `csp.mjs`)
 * verbatim for every directive except `script-src`, and folds in three
 * hardening directives the page policy lacked (`base-uri`, `form-action`,
 * `upgrade-insecure-requests`). `frame-ancestors` is intentionally NOT added —
 * page framing stays governed by the `X-Frame-Options: SAMEORIGIN` header so
 * the admin's same-origin live-preview iframe keeps working.
 */
export function buildAdminCsp(options: AdminCspOptions): string {
  const { nonce, isDev, isVercel, isVercelProd, apiUrl, serverUrl, isFleetMode = false } = options;
  const vercelPreview = isVercel && !isVercelProd;

  const scriptSrc = [
    "'self'",
    `'nonce-${nonce}'`,
    ...(isDev ? ["'unsafe-eval'"] : []),
    ...(isFleetMode
      ? []
      : [
          'https://checkout.stripe.com',
          'https://js.stripe.com',
          'https://maps.googleapis.com',
          'https://res.cloudinary.com',
          'https://cdn.vercel-insights.com',
        ]),
    ...(vercelPreview ? ['https://vercel.live', 'https://*.vercel.live'] : []),
  ];

  const frameSrc = [
    "'self'",
    ...(isFleetMode
      ? []
      : ['https://checkout.stripe.com', 'https://js.stripe.com', 'https://hooks.stripe.com']),
    ...(vercelPreview ? ['https://vercel.live', 'https://*.vercel.live'] : []),
  ];

  const connectSrc = [
    "'self'",
    ...(isFleetMode
      ? []
      : ['https://checkout.stripe.com', 'https://api.stripe.com', 'https://maps.googleapis.com']),
    apiUrl,
    ...(serverUrl ? [serverUrl] : []),
    ...(vercelPreview
      ? ['https://*.vercel.app', 'https://vercel.live', 'https://*.vercel.live']
      : []),
    ...(isVercel ? [] : ['http://localhost:3000', 'http://localhost:4000']),
  ];

  const directives = [
    "default-src 'self'",
    `script-src ${scriptSrc.join(' ')}`,
    "child-src 'self'",
    "style-src 'self' 'unsafe-inline'",
    `img-src 'self' ${isFleetMode ? '' : 'https://res.cloudinary.com https://*.stripe.com '}data: https://www.gravatar.com`,
    "font-src 'self' data:",
    `frame-src ${frameSrc.join(' ')}`,
    `connect-src ${connectSrc.join(' ')}`,
    ...(isFleetMode ? [] : ['object-src https://res.cloudinary.com']),
    "base-uri 'self'",
    "form-action 'self'",
    'upgrade-insecure-requests',
  ];

  return directives.join('; ');
}
