/**
 * Tool Base Interface
 *
 * Defines the structure for tools that agents can use
 */

import type { z } from 'zod/v4';

export interface ToolResult {
  success: boolean;
  data?: unknown;
  error?: string;
  /**
   * Concise text summary for the LLM context window.
   * When set, the runtime sends this to the model instead of serializing `data`.
   * Use this to keep tool results token-efficient while preserving full data in `data`.
   */
  content?: string;
  metadata?: {
    executionTime?: number;
    cost?: number;
    tokensUsed?: number;
    [key: string]: unknown;
  };
}

export interface Tool {
  /**
   * Unique tool name (used in LLM tool calls and deduplication)
   */
  name: string;

  /**
   * Human-readable display name shown in UI. Falls back to `name` if omitted.
   */
  label?: string;

  /**
   * Tool description (used for LLM tool selection)
   */
  description: string;

  /**
   * Zod schema for tool parameters
   */
  parameters: z.ZodSchema;

  /**
   * When true, the runtime pauses before executing this tool and
   * invokes the approval callback. Execution only proceeds if approved.
   */
  requiresApproval?: boolean;

  /**
   * Execute the tool with given parameters
   */
  execute(params: unknown): Promise<ToolResult>;

  /**
   * Optional: Validate parameters before execution
   */
  validate?(params: unknown): boolean;

  /**
   * Optional: Get tool metadata
   */
  getMetadata?(): {
    category?: string;
    version?: string;
    author?: string;
    [key: string]: unknown;
  };
}

/**
 * Request sent to the approval callback when a tool requires human approval.
 */
export interface ApprovalRequest {
  /** Tool being invoked */
  toolName: string;
  /** Human-readable tool label */
  toolLabel?: string;
  /** Parsed parameters the LLM wants to pass */
  params: unknown;
  /** Concise summary of what the tool will do (generated by the runtime) */
  description: string;
}

/**
 * Response from the approval callback.
 */
export interface ApprovalResponse {
  /** Whether the tool execution is approved */
  approved: boolean;
  /** Optional reason for denial (shown to LLM so it can adjust) */
  reason?: string;
}

/**
 * Callback invoked by the runtime when a tool with `requiresApproval` is
 * called. Implementations typically show a confirmation dialog in the UI
 * and resolve when the user responds.
 */
export type ApprovalCallback = (request: ApprovalRequest) => Promise<ApprovalResponse>;

/**
 * Tool execution context
 */
export interface ToolContext {
  agentId?: string;
  userId?: string;
  sessionId?: string;
  metadata?: Record<string, unknown>;
}

/**
 * Tool with context
 */
export interface ContextualTool extends Tool {
  executeWithContext(params: unknown, context: ToolContext): Promise<ToolResult>;
}
