/**
 * @revealui/types/core
 *
 * Core framework types only.
 * Use this subpath to import only framework types without schema types.
 */

// Re-export types from @revealui/core/types
// Using import-then-export pattern to ensure proper module resolution
import type {
  // Query Types
  Document,
  JsonObject,
  PopulateType,
  RelationshipMetadata,
  RevealDataObject,
  RevealDocument,
  RevealDocumentWithMeta,
  RevealOperator,
  RevealSelect,
  RevealSort,
  RevealValue,
  RevealWhere,
  RevealWhereField,
  SelectMode,
  SelectType,
  TypedFallbackLocale,
  TypeWithID,
  WhereClause,
  // User Types
  Permission,
  RevealUIPermission,
  RevealUITenant,
  RevealUIUser,
  RevealUser,
  User,
  // Request Types
  RequestContext,
  RevealRequest,
  // Runtime Types
  DatabaseAdapter,
  DatabaseResult,
  FindArgs,
  OperationOptions,
  PaginatedDocs,
  RevealCollection,
  RevealCreateOptions,
  RevealDeleteOptions,
  RevealFindOptions,
  RevealGlobal,
  RevealPaginatedResult,
  RevealUI,
  RevealUIInstance,
  RevealUILogger,
  RevealUpdateOptions,
  StorageAdapter,
  // Config Types
  GlobalAfterChangeHook,
  RevealAfterChangeHook,
  RevealAfterReadHook,
  RevealBeforeChangeHook,
  RevealCollectionConfig,
  RevealCollectionHooks,
  RevealConfig,
  RevealGlobalConfig,
  RevealHookContext,
  // Hook Types
  RevealUIFieldHook,
  RevealUIFieldValidator,
  RevealUIHookContext,
  RevealUIValidationRule,
  // Access Types
  Access,
  FieldAccess,
  RevealUIAccessArgs,
  RevealUIAccessContext,
  RevealUIAccessResult,
  RevealUIAccessRule,
  RevealUIFilterResult,
  // API Types
  APIResponse,
  EndpointHandler,
  EndpointHandlerArgs,
  REST_DELETE,
  REST_GET,
  REST_OPTIONS,
  REST_PATCH,
  REST_POST,
  RESTOptions,
  RevealHandler,
  // Rich Text Types
  RichTextEditor,
  RichTextFeature,
  // Plugin Types
  Plugin,
  PluginOptions,
  // Extension Types
  CustomComponent,
  RevealUICollectionConfig,
  RevealUIComponent,
  RevealUIContext,
  RevealUIEnhancedField,
  RevealUIField,
  RevealUIFieldType,
  RevealUIFrameworkContext,
  // Internal Types
  Block,
  BlocksField,
  CheckboxField,
  ClientCollectionConfig,
  ClientConfig,
  RevealUIBlock,
  RevealUIDependencyCheckArgs,
  RevealUIRichTextAdapter,
  RevealUISchemaArgs,
  RevealUITraverseFieldsArgs,
  RevealUITraverseFieldsResult,
} from '@revealui/core/types'

import { RevealOperators } from '@revealui/core/types'

// Re-export all types
export type {
  // Query Types
  Document,
  JsonObject,
  PopulateType,
  RelationshipMetadata,
  RevealDataObject,
  RevealDocument,
  RevealDocumentWithMeta,
  RevealOperator,
  RevealSelect,
  RevealSort,
  RevealValue,
  RevealWhere,
  RevealWhereField,
  SelectMode,
  SelectType,
  TypedFallbackLocale,
  TypeWithID,
  WhereClause,
  // User Types
  Permission,
  RevealUIPermission,
  RevealUITenant,
  RevealUIUser,
  RevealUser,
  User,
  // Request Types
  RequestContext,
  RevealRequest,
  // Runtime Types
  DatabaseAdapter,
  DatabaseResult,
  FindArgs,
  OperationOptions,
  PaginatedDocs,
  RevealCollection,
  RevealCreateOptions,
  RevealDeleteOptions,
  RevealFindOptions,
  RevealGlobal,
  RevealPaginatedResult,
  RevealUI,
  RevealUIInstance,
  RevealUILogger,
  RevealUpdateOptions,
  StorageAdapter,
  // Config Types
  GlobalAfterChangeHook,
  RevealAfterChangeHook,
  RevealAfterReadHook,
  RevealBeforeChangeHook,
  RevealCollectionConfig,
  RevealCollectionHooks,
  RevealConfig,
  RevealGlobalConfig,
  RevealHookContext,
  // Hook Types
  RevealUIFieldHook,
  RevealUIFieldValidator,
  RevealUIHookContext,
  RevealUIValidationRule,
  // Access Types
  Access,
  FieldAccess,
  RevealUIAccessArgs,
  RevealUIAccessContext,
  RevealUIAccessResult,
  RevealUIAccessRule,
  RevealUIFilterResult,
  // API Types
  APIResponse,
  EndpointHandler,
  EndpointHandlerArgs,
  REST_DELETE,
  REST_GET,
  REST_OPTIONS,
  REST_PATCH,
  REST_POST,
  RESTOptions,
  RevealHandler,
  // Rich Text Types
  RichTextEditor,
  RichTextFeature,
  // Plugin Types
  Plugin,
  PluginOptions,
  // Extension Types
  CustomComponent,
  RevealUICollectionConfig,
  RevealUIComponent,
  RevealUIContext,
  RevealUIEnhancedField,
  RevealUIField,
  RevealUIFieldType,
  RevealUIFrameworkContext,
  // Internal Types
  Block,
  BlocksField,
  CheckboxField,
  ClientCollectionConfig,
  ClientConfig,
  RevealUIBlock,
  RevealUIDependencyCheckArgs,
  RevealUIRichTextAdapter,
  RevealUISchemaArgs,
  RevealUITraverseFieldsArgs,
  RevealUITraverseFieldsResult,
}

// Re-export values (non-type exports)
export { RevealOperators }
