/**
 * @revealui/types/schema
 *
 * Schema contract types only.
 * Use this subpath to import only schema types without framework types.
 */

export type {
  // Core Contracts - from @revealui/schema/core
  AccessArgs,
  AccessFunction,
  AccessResult,
  AfterChangeHookArgs,
  AfterReadHookArgs,
  ArrayField,
  AuthConfig,
  BeforeChangeHookArgs,
  BeforeValidateHookArgs,
  CollectionAccess,
  CollectionAccessConfig,
  CollectionAdminConfig,
  CollectionAfterChangeHook,
  CollectionAfterReadHook,
  CollectionBeforeChangeHook,
  CollectionBeforeReadHook,
  CollectionBeforeValidateHook,
  CollectionConfig,
  CollectionHooks,
  CollectionHooksConfig,
  CollectionLabels,
  CollectionStructure,
  Config,
  CustomFieldTypeConfig,
  Field,
  FieldAccess,
  FieldAccessArgs,
  FieldAccessConfig,
  FieldAccessFunction,
  FieldAdminConfig,
  FieldHooksConfig,
  FieldOption,
  FieldStructure,
  FieldType,
  FieldValidateArgs,
  FieldValidateFunction,
  GlobalAccess,
  GlobalAccessConfig,
  GlobalAdminConfig,
  GlobalConfig,
  GlobalHooks,
  GlobalHooksConfig,
  GlobalLabels,
  GlobalStructure,
  GlobalVersionsConfig,
  GroupField,
  NumberField,
  PluginFieldExtension,
  RelationshipField,
  RevealRequest,
  RevealUICollectionConfig,
  RevealUIExtensions,
  RevealUIGlobalConfig,
  RowField,
  SanitizedCollectionConfig,
  SanitizedConfig,
  SanitizedGlobalConfig,
  SelectField,
  TabDefinition,
  TabsField,
  TextField,
  TypedCollectionConfig,
  TypedGlobalConfig,
  UploadConfig,
  ValidationResult,
  VersionsConfig,
  Where,
  // User Contracts
  CreateUserInput,
  Session,
  UpdateUserInput,
  User,
  UserPreferences,
  UserRole,
  UserStatus,
  UserType,
} from '@revealui/schema/core'

// Re-export entity types from main schema package
export type {
  // Page Contracts
  CreatePageInput,
  Page,
  PageLock,
  PageSeo,
  PageStatus,
  UpdatePageInput,
  // Site Contracts
  CreateSiteInput,
  Site,
  SiteCollaborator,
  SiteSeo,
  SiteSettings,
  SiteStatus,
  SiteTheme,
  UpdateSiteInput,
  // Block Contracts
  AccordionBlock,
  Block,
  BlockMeta,
  BlockStyle,
  BlockType,
  ButtonBlock,
  CodeBlock,
  ColumnsBlock,
  ComponentBlock,
  DividerBlock,
  EmbedBlock,
  FormBlock,
  GridBlock,
  HeadingBlock,
  HtmlBlock,
  ImageBlock,
  ListBlock,
  QuoteBlock,
  SpacerBlock,
  TableBlock,
  TabsBlock,
  TextBlock,
  VideoBlock,
  // Agent Contracts
  AgentActionRecord,
  AgentContext,
  AgentDefinition,
  AgentMemory,
  AgentState,
  Conversation,
  ConversationMessage,
  Intent,
  IntentType,
  MemorySource,
  MemoryType,
  ToolDefinition,
  ToolParameter,
  // Representation Contracts
  AgentActionDefinition,
  AgentConstraint,
  AgentRelation,
  AgentRepresentation,
  DualEntity,
  Embedding,
  EmbeddingModel,
  HumanRepresentation,
} from '@revealui/schema'
