#!/usr/bin/env tsx
/**
 * Test Coverage Gate — Phase 4.5.18
 *
 * Reads vitest coverage-summary.json files (generated by `pnpm test:coverage`)
 * and fails with an exit code of 1 if any package with significant source code
 * (>100 LOC) has 0% line coverage.
 *
 * This gate is warn-only in the CI pipeline — it reports violations but does
 * not block pushes. Run `pnpm test:coverage` first to generate reports.
 *
 * Usage:
 *   pnpm coverage:check
 *   tsx scripts/gates/test-coverage-gate.ts [--fail-on-zero]
 */

import { execFileSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(fileURLToPath(import.meta.url), '../../..');
const FAIL_ON_ZERO = process.argv.includes('--fail-on-zero');
const CHANGED_ONLY = process.argv.includes('--changed');

// Packages and apps to check
const SCAN_DIRS = ['packages', 'apps'];

// Minimum source LOC to require coverage data
const MIN_LOC_THRESHOLD = 100;

interface CoverageSummary {
  total: {
    lines: { pct: number; total: number; covered: number };
    statements: { pct: number; total: number; covered: number };
    functions: { pct: number; total: number; covered: number };
    branches: { pct: number; total: number; covered: number };
  };
}

interface PackageResult {
  name: string;
  path: string;
  sourceLoc: number;
  hasCoverageReport: boolean;
  linePct: number | null;
  testFiles: number;
}

interface PackageCandidate {
  name: string;
  path: string;
}

const COVERAGE_EXCLUSIONS = new Map<string, string>([
  [
    'packages/harnesses',
    'commercial package source is gitignored in this repo; excluded from public workspace coverage',
  ],
]);

const IGNORED_DIRECTORIES = new Set([
  'node_modules',
  'dist',
  '.next',
  '.turbo',
  'coverage',
  '.git',
  'results',
]);

function isTestFile(entry: string): boolean {
  return (
    entry.endsWith('.test.ts') ||
    entry.endsWith('.test.tsx') ||
    entry.endsWith('.test.js') ||
    entry.endsWith('.test.jsx') ||
    entry.endsWith('.spec.ts') ||
    entry.endsWith('.spec.tsx') ||
    entry.endsWith('.spec.js') ||
    entry.endsWith('.spec.jsx') ||
    entry.endsWith('.integration.test.ts') ||
    entry.endsWith('.integration.test.tsx')
  );
}

/** Count non-blank, non-comment source lines across .ts/.tsx files */
function countSourceLines(srcDir: string): number {
  if (!existsSync(srcDir)) return 0;
  let total = 0;

  function walk(dir: string): void {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) {
        if (IGNORED_DIRECTORIES.has(entry.name) || entry.name === '__tests__') continue;
        walk(full);
      } else if (entry.name.endsWith('.ts') || entry.name.endsWith('.tsx')) {
        try {
          const content = readFileSync(full, 'utf-8');
          for (const line of content.split('\n')) {
            const trimmed = line.trim();
            if (trimmed && !trimmed.startsWith('//') && !trimmed.startsWith('*')) {
              total++;
            }
          }
        } catch {
          // File removed between readdir and read — skip
        }
      }
    }
  }

  walk(srcDir);
  return total;
}

/** Count test files in a package */
function countTestFiles(pkgPath: string): number {
  let count = 0;

  function walk(dir: string): void {
    for (const entry of readdirSync(dir)) {
      const full = join(dir, entry);
      const stat = statSync(full);

      if (stat.isDirectory()) {
        if (IGNORED_DIRECTORIES.has(entry)) {
          continue;
        }
        walk(full);
        continue;
      }

      if (isTestFile(entry)) {
        count++;
      }
    }
  }

  walk(pkgPath);
  return count;
}

/** Read coverage summary JSON if it exists */
function readCoverageSummary(pkgPath: string): CoverageSummary | null {
  const paths = [
    join(pkgPath, 'coverage', 'coverage-summary.json'),
    join(pkgPath, 'coverage', 'coverage-final.json'), // alternative vitest output
  ];
  for (const p of paths) {
    if (existsSync(p)) {
      try {
        const raw = JSON.parse(readFileSync(p, 'utf-8')) as Record<string, unknown>;
        // coverage-summary.json has a "total" key
        if (raw.total) return raw as unknown as CoverageSummary;
      } catch {
        // Malformed — skip
      }
    }
  }
  return null;
}

function getPackageCandidates(): PackageCandidate[] {
  const candidates: PackageCandidate[] = [];

  for (const scanDir of SCAN_DIRS) {
    const dir = join(ROOT, scanDir);
    if (!existsSync(dir)) continue;

    for (const pkgName of readdirSync(dir)) {
      const pkgPath = join(dir, pkgName);
      if (!statSync(pkgPath).isDirectory()) continue;
      candidates.push({
        name: `${scanDir}/${pkgName}`,
        path: pkgPath,
      });
    }
  }

  return candidates.sort((a, b) => a.name.localeCompare(b.name));
}

function getChangedPackageNames(): Set<string> {
  let output = '';

  try {
    output = execFileSync(
      'git',
      ['diff', '--name-only', '--diff-filter=ACMR', 'HEAD~1', '--', 'apps', 'packages'],
      { cwd: ROOT, encoding: 'utf8' },
    );
  } catch (error) {
    if (
      typeof error === 'object' &&
      error !== null &&
      'stdout' in error &&
      typeof error.stdout === 'string'
    ) {
      output = error.stdout;
    }
  }

  const changedPackages = new Set<string>();
  for (const file of output
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)) {
    const parts = file.split('/');
    if (parts.length < 2) continue;
    const [scanDir, pkgName] = parts;
    if (!SCAN_DIRS.includes(scanDir)) continue;
    changedPackages.add(`${scanDir}/${pkgName}`);
  }

  return changedPackages;
}

function scan(): PackageResult[] {
  const results: PackageResult[] = [];
  const candidates = getPackageCandidates();
  const changedPackages = CHANGED_ONLY ? getChangedPackageNames() : null;

  for (const candidate of candidates) {
    if (changedPackages && !changedPackages.has(candidate.name)) {
      continue;
    }

    const srcDir = join(candidate.path, 'src');
    const sourceLoc = countSourceLines(srcDir);
    if (sourceLoc < MIN_LOC_THRESHOLD) continue;

    const summary = readCoverageSummary(candidate.path);
    const testFiles = countTestFiles(candidate.path);

    results.push({
      name: candidate.name,
      path: candidate.path,
      sourceLoc,
      hasCoverageReport: summary !== null,
      linePct: summary?.total.lines.pct ?? null,
      testFiles,
    });
  }

  return results;
}

function main(): void {
  console.log('\n============================================================');
  console.log('Test Coverage Gate');
  console.log('============================================================\n');
  if (CHANGED_ONLY) {
    console.log('ℹ️  Changed-only coverage scope enabled.\n');
  }

  const results = scan();
  if (CHANGED_ONLY && results.length === 0) {
    console.log('ℹ️  No changed apps/packages with >100 LOC were found in this scope.\n');
  }
  const excludedCoveragePackages = results.filter((r) => COVERAGE_EXCLUSIONS.has(r.name));
  const scopedResults = results.filter((r) => !COVERAGE_EXCLUSIONS.has(r.name));
  const noCoverage: PackageResult[] = [];
  const zeroCoverage: PackageResult[] = [];
  const withCoverage: PackageResult[] = [];

  for (const r of scopedResults) {
    if (!r.hasCoverageReport) {
      noCoverage.push(r);
    } else if (r.linePct === 0) {
      zeroCoverage.push(r);
    } else {
      withCoverage.push(r);
    }
  }

  const hasAnyCoverageReports = withCoverage.length > 0 || zeroCoverage.length > 0;

  // ── Packages with coverage data ──────────────────────────────────────────
  if (withCoverage.length > 0) {
    console.log('✅ Packages with coverage data:');
    for (const r of withCoverage) {
      const pct = r.linePct?.toFixed(1) ?? '?';
      console.log(
        `   ${r.name.padEnd(35)} ${pct}% lines   (${r.testFiles} test files, ${r.sourceLoc} LOC)`,
      );
    }
    console.log();
  }

  // ── Intentionally excluded packages ──────────────────────────────────────
  if (excludedCoveragePackages.length > 0) {
    console.log('ℹ️  Packages excluded from public coverage expectations:');
    for (const r of excludedCoveragePackages) {
      const reason = COVERAGE_EXCLUSIONS.get(r.name) ?? 'excluded';
      console.log(`   ${r.name.padEnd(35)} ${reason}`);
    }
    console.log();
  }

  // ── Packages missing coverage reports ────────────────────────────────────
  if (noCoverage.length > 0) {
    if (hasAnyCoverageReports) {
      console.log('⚠️  Packages missing coverage reports:');
      for (const r of noCoverage) {
        const testNote = r.testFiles === 0 ? '0 test files' : `${r.testFiles} test files`;
        console.log(`   ${r.name.padEnd(35)} ${testNote}, ${r.sourceLoc} LOC`);
      }
    } else {
      console.log('ℹ️  No coverage reports were generated in this run.');
      console.log('   Run `pnpm test:coverage` to produce workspace coverage artifacts.');
    }
    console.log();
  }

  // ── Packages with 0% coverage ────────────────────────────────────────────
  if (zeroCoverage.length > 0) {
    console.log('❌ Packages with 0% line coverage:');
    for (const r of zeroCoverage) {
      console.log(`   ${r.name.padEnd(35)} ${r.testFiles} test files, ${r.sourceLoc} LOC`);
    }
    console.log();
  }

  // ── Summary ──────────────────────────────────────────────────────────────
  console.log('============================================================');
  console.log(`Scanned ${scopedResults.length} packages (>${MIN_LOC_THRESHOLD} LOC)`);
  console.log(`  ℹ️ Excluded:        ${excludedCoveragePackages.length}`);
  console.log(`  ✅ With coverage:   ${withCoverage.length}`);
  console.log(`  !  No report yet:  ${noCoverage.length}`);
  console.log(`  ❌ Zero coverage:   ${zeroCoverage.length}`);
  console.log('============================================================\n');

  // Priority packages with no tests at all (always warn regardless of report)
  const noTests = scopedResults.filter((r) => r.testFiles === 0);
  if (noTests.length > 0) {
    console.log('⚠️  Packages with >100 LOC and zero test files:');
    for (const r of noTests) {
      console.log(`   ${r.name} (${r.sourceLoc} LOC)`);
    }
    console.log();
  }

  if (FAIL_ON_ZERO && zeroCoverage.length > 0) {
    console.log('❌ Gate failed: packages with 0% coverage found');
    process.exit(1);
  }

  if (noCoverage.length > 0 && hasAnyCoverageReports) {
    console.log('i  Run `pnpm test:coverage` then re-run this gate for full results.');
  }

  if (zeroCoverage.length === 0 && noCoverage.length === 0) {
    console.log('✅ Coverage gate passed — all packages have coverage data.');
  }
}

main();
