/**
 * Generated Database Type for NeonDB
 *
 * This file is auto-generated by packages/db/src/types/generate.ts
 * DO NOT MODIFY MANUALLY - regenerate using: pnpm generate:types
 *
 * Generated: 2026-03-31T02:08:05.312Z
 *
 * This type matches the Supabase Database type structure for feature parity.
 * Tables are automatically discovered from packages/db/src/schema/*.ts
 */

import type {
  accountEntitlements,
  accountMemberships,
  accounts,
  accountSubscriptions,
  agentActions,
  agentContexts,
  agentCreditBalance,
  agentMemories,
  agentTaskUsage,
  aiMemorySessions,
  appLogs,
  auditLog,
  billingCatalog,
  boardColumns,
  boards,
  circuitBreakerState,
  codeProvenance,
  codeReviews,
  collabEdits,
  conversations,
  coordinationAgents,
  coordinationEvents,
  coordinationFileClaims,
  coordinationMail,
  coordinationQueueItems,
  coordinationSessions,
  coordinationWorkItems,
  crdtOperations,
  errorEvents,
  failedAttempts,
  gdprBreaches,
  gdprConsents,
  gdprDeletionRequests,
  globalFooter,
  globalHeader,
  globalSettings,
  jobs,
  licenses,
  magicLinks,
  marketplaceServers,
  marketplaceTransactions,
  media,
  messages,
  nodeIdMappings,
  oauthAccounts,
  orders,
  pageRevisions,
  pages,
  passkeys,
  passwordResetTokens,
  posts,
  processedWebhookEvents,
  products,
  ragChunks,
  ragDocuments,
  ragWorkspaces,
  rateLimits,
  registeredAgents,
  revealcoinPayments,
  revealcoinPriceSnapshots,
  sessions,
  siteCollaborators,
  sites,
  syncMetadata,
  tenantProviderConfigs,
  tenants,
  ticketComments,
  ticketLabelAssignments,
  ticketLabels,
  tickets,
  usageMeters,
  userApiKeys,
  userDevices,
  users,
  waitlist,
  yjsDocuments,
} from '../schema/index.js'

// =============================================================================
// Table Type Inferences
// =============================================================================

// Account Entitlements
export type AccountEntitlementsRow = typeof accountEntitlements.$inferSelect
export type AccountEntitlementsInsert = typeof accountEntitlements.$inferInsert
export type AccountEntitlementsUpdate = Partial<AccountEntitlementsInsert>

// Account Memberships
export type AccountMembershipsRow = typeof accountMemberships.$inferSelect
export type AccountMembershipsInsert = typeof accountMemberships.$inferInsert
export type AccountMembershipsUpdate = Partial<AccountMembershipsInsert>

// Accounts
export type AccountsRow = typeof accounts.$inferSelect
export type AccountsInsert = typeof accounts.$inferInsert
export type AccountsUpdate = Partial<AccountsInsert>

// Account Subscriptions
export type AccountSubscriptionsRow = typeof accountSubscriptions.$inferSelect
export type AccountSubscriptionsInsert = typeof accountSubscriptions.$inferInsert
export type AccountSubscriptionsUpdate = Partial<AccountSubscriptionsInsert>

// Agent Actions
export type AgentActionsRow = typeof agentActions.$inferSelect
export type AgentActionsInsert = typeof agentActions.$inferInsert
export type AgentActionsUpdate = Partial<AgentActionsInsert>

// Agent Contexts
export type AgentContextsRow = typeof agentContexts.$inferSelect
export type AgentContextsInsert = typeof agentContexts.$inferInsert
export type AgentContextsUpdate = Partial<AgentContextsInsert>

// Agent Credit Balance
export type AgentCreditBalanceRow = typeof agentCreditBalance.$inferSelect
export type AgentCreditBalanceInsert = typeof agentCreditBalance.$inferInsert
export type AgentCreditBalanceUpdate = Partial<AgentCreditBalanceInsert>

// Agent Memories
export type AgentMemoriesRow = typeof agentMemories.$inferSelect
export type AgentMemoriesInsert = typeof agentMemories.$inferInsert
export type AgentMemoriesUpdate = Partial<AgentMemoriesInsert>

// Agent Task Usage
export type AgentTaskUsageRow = typeof agentTaskUsage.$inferSelect
export type AgentTaskUsageInsert = typeof agentTaskUsage.$inferInsert
export type AgentTaskUsageUpdate = Partial<AgentTaskUsageInsert>

// Ai Memory Sessions
export type AiMemorySessionsRow = typeof aiMemorySessions.$inferSelect
export type AiMemorySessionsInsert = typeof aiMemorySessions.$inferInsert
export type AiMemorySessionsUpdate = Partial<AiMemorySessionsInsert>

// App Logs
export type AppLogsRow = typeof appLogs.$inferSelect
export type AppLogsInsert = typeof appLogs.$inferInsert
export type AppLogsUpdate = Partial<AppLogsInsert>

// Audit Log
export type AuditLogRow = typeof auditLog.$inferSelect
export type AuditLogInsert = typeof auditLog.$inferInsert
export type AuditLogUpdate = Partial<AuditLogInsert>

// Billing Catalog
export type BillingCatalogRow = typeof billingCatalog.$inferSelect
export type BillingCatalogInsert = typeof billingCatalog.$inferInsert
export type BillingCatalogUpdate = Partial<BillingCatalogInsert>

// Board Columns
export type BoardColumnsRow = typeof boardColumns.$inferSelect
export type BoardColumnsInsert = typeof boardColumns.$inferInsert
export type BoardColumnsUpdate = Partial<BoardColumnsInsert>

// Boards
export type BoardsRow = typeof boards.$inferSelect
export type BoardsInsert = typeof boards.$inferInsert
export type BoardsUpdate = Partial<BoardsInsert>

// Circuit Breaker State
export type CircuitBreakerStateRow = typeof circuitBreakerState.$inferSelect
export type CircuitBreakerStateInsert = typeof circuitBreakerState.$inferInsert
export type CircuitBreakerStateUpdate = Partial<CircuitBreakerStateInsert>

// Code Provenance
export type CodeProvenanceRow = typeof codeProvenance.$inferSelect
export type CodeProvenanceInsert = typeof codeProvenance.$inferInsert
export type CodeProvenanceUpdate = Partial<CodeProvenanceInsert>

// Code Reviews
export type CodeReviewsRow = typeof codeReviews.$inferSelect
export type CodeReviewsInsert = typeof codeReviews.$inferInsert
export type CodeReviewsUpdate = Partial<CodeReviewsInsert>

// Collab Edits
export type CollabEditsRow = typeof collabEdits.$inferSelect
export type CollabEditsInsert = typeof collabEdits.$inferInsert
export type CollabEditsUpdate = Partial<CollabEditsInsert>

// Conversations
export type ConversationsRow = typeof conversations.$inferSelect
export type ConversationsInsert = typeof conversations.$inferInsert
export type ConversationsUpdate = Partial<ConversationsInsert>

// Coordination Agents
export type CoordinationAgentsRow = typeof coordinationAgents.$inferSelect
export type CoordinationAgentsInsert = typeof coordinationAgents.$inferInsert
export type CoordinationAgentsUpdate = Partial<CoordinationAgentsInsert>

// Coordination Events
export type CoordinationEventsRow = typeof coordinationEvents.$inferSelect
export type CoordinationEventsInsert = typeof coordinationEvents.$inferInsert
export type CoordinationEventsUpdate = Partial<CoordinationEventsInsert>

// Coordination File Claims
export type CoordinationFileClaimsRow = typeof coordinationFileClaims.$inferSelect
export type CoordinationFileClaimsInsert = typeof coordinationFileClaims.$inferInsert
export type CoordinationFileClaimsUpdate = Partial<CoordinationFileClaimsInsert>

// Coordination Mail
export type CoordinationMailRow = typeof coordinationMail.$inferSelect
export type CoordinationMailInsert = typeof coordinationMail.$inferInsert
export type CoordinationMailUpdate = Partial<CoordinationMailInsert>

// Coordination Queue Items
export type CoordinationQueueItemsRow = typeof coordinationQueueItems.$inferSelect
export type CoordinationQueueItemsInsert = typeof coordinationQueueItems.$inferInsert
export type CoordinationQueueItemsUpdate = Partial<CoordinationQueueItemsInsert>

// Coordination Sessions
export type CoordinationSessionsRow = typeof coordinationSessions.$inferSelect
export type CoordinationSessionsInsert = typeof coordinationSessions.$inferInsert
export type CoordinationSessionsUpdate = Partial<CoordinationSessionsInsert>

// Coordination Work Items
export type CoordinationWorkItemsRow = typeof coordinationWorkItems.$inferSelect
export type CoordinationWorkItemsInsert = typeof coordinationWorkItems.$inferInsert
export type CoordinationWorkItemsUpdate = Partial<CoordinationWorkItemsInsert>

// Crdt Operations
export type CrdtOperationsRow = typeof crdtOperations.$inferSelect
export type CrdtOperationsInsert = typeof crdtOperations.$inferInsert
export type CrdtOperationsUpdate = Partial<CrdtOperationsInsert>

// Error Events
export type ErrorEventsRow = typeof errorEvents.$inferSelect
export type ErrorEventsInsert = typeof errorEvents.$inferInsert
export type ErrorEventsUpdate = Partial<ErrorEventsInsert>

// Failed Attempts
export type FailedAttemptsRow = typeof failedAttempts.$inferSelect
export type FailedAttemptsInsert = typeof failedAttempts.$inferInsert
export type FailedAttemptsUpdate = Partial<FailedAttemptsInsert>

// Gdpr Breaches
export type GdprBreachesRow = typeof gdprBreaches.$inferSelect
export type GdprBreachesInsert = typeof gdprBreaches.$inferInsert
export type GdprBreachesUpdate = Partial<GdprBreachesInsert>

// Gdpr Consents
export type GdprConsentsRow = typeof gdprConsents.$inferSelect
export type GdprConsentsInsert = typeof gdprConsents.$inferInsert
export type GdprConsentsUpdate = Partial<GdprConsentsInsert>

// Gdpr Deletion Requests
export type GdprDeletionRequestsRow = typeof gdprDeletionRequests.$inferSelect
export type GdprDeletionRequestsInsert = typeof gdprDeletionRequests.$inferInsert
export type GdprDeletionRequestsUpdate = Partial<GdprDeletionRequestsInsert>

// Global Footer
export type GlobalFooterRow = typeof globalFooter.$inferSelect
export type GlobalFooterInsert = typeof globalFooter.$inferInsert
export type GlobalFooterUpdate = Partial<GlobalFooterInsert>

// Global Header
export type GlobalHeaderRow = typeof globalHeader.$inferSelect
export type GlobalHeaderInsert = typeof globalHeader.$inferInsert
export type GlobalHeaderUpdate = Partial<GlobalHeaderInsert>

// Global Settings
export type GlobalSettingsRow = typeof globalSettings.$inferSelect
export type GlobalSettingsInsert = typeof globalSettings.$inferInsert
export type GlobalSettingsUpdate = Partial<GlobalSettingsInsert>

// Jobs
export type JobsRow = typeof jobs.$inferSelect
export type JobsInsert = typeof jobs.$inferInsert
export type JobsUpdate = Partial<JobsInsert>

// Licenses
export type LicensesRow = typeof licenses.$inferSelect
export type LicensesInsert = typeof licenses.$inferInsert
export type LicensesUpdate = Partial<LicensesInsert>

// Magic Links
export type MagicLinksRow = typeof magicLinks.$inferSelect
export type MagicLinksInsert = typeof magicLinks.$inferInsert
export type MagicLinksUpdate = Partial<MagicLinksInsert>

// Marketplace Servers
export type MarketplaceServersRow = typeof marketplaceServers.$inferSelect
export type MarketplaceServersInsert = typeof marketplaceServers.$inferInsert
export type MarketplaceServersUpdate = Partial<MarketplaceServersInsert>

// Marketplace Transactions
export type MarketplaceTransactionsRow = typeof marketplaceTransactions.$inferSelect
export type MarketplaceTransactionsInsert = typeof marketplaceTransactions.$inferInsert
export type MarketplaceTransactionsUpdate = Partial<MarketplaceTransactionsInsert>

// Media
export type MediaRow = typeof media.$inferSelect
export type MediaInsert = typeof media.$inferInsert
export type MediaUpdate = Partial<MediaInsert>

// Messages
export type MessagesRow = typeof messages.$inferSelect
export type MessagesInsert = typeof messages.$inferInsert
export type MessagesUpdate = Partial<MessagesInsert>

// Node Id Mappings
export type NodeIdMappingsRow = typeof nodeIdMappings.$inferSelect
export type NodeIdMappingsInsert = typeof nodeIdMappings.$inferInsert
export type NodeIdMappingsUpdate = Partial<NodeIdMappingsInsert>

// Oauth Accounts
export type OauthAccountsRow = typeof oauthAccounts.$inferSelect
export type OauthAccountsInsert = typeof oauthAccounts.$inferInsert
export type OauthAccountsUpdate = Partial<OauthAccountsInsert>

// Orders
export type OrdersRow = typeof orders.$inferSelect
export type OrdersInsert = typeof orders.$inferInsert
export type OrdersUpdate = Partial<OrdersInsert>

// Page Revisions
export type PageRevisionsRow = typeof pageRevisions.$inferSelect
export type PageRevisionsInsert = typeof pageRevisions.$inferInsert
export type PageRevisionsUpdate = Partial<PageRevisionsInsert>

// Pages
export type PagesRow = typeof pages.$inferSelect
export type PagesInsert = typeof pages.$inferInsert
export type PagesUpdate = Partial<PagesInsert>

// Passkeys
export type PasskeysRow = typeof passkeys.$inferSelect
export type PasskeysInsert = typeof passkeys.$inferInsert
export type PasskeysUpdate = Partial<PasskeysInsert>

// Password Reset Tokens
export type PasswordResetTokensRow = typeof passwordResetTokens.$inferSelect
export type PasswordResetTokensInsert = typeof passwordResetTokens.$inferInsert
export type PasswordResetTokensUpdate = Partial<PasswordResetTokensInsert>

// Posts
export type PostsRow = typeof posts.$inferSelect
export type PostsInsert = typeof posts.$inferInsert
export type PostsUpdate = Partial<PostsInsert>

// Processed Webhook Events
export type ProcessedWebhookEventsRow = typeof processedWebhookEvents.$inferSelect
export type ProcessedWebhookEventsInsert = typeof processedWebhookEvents.$inferInsert
export type ProcessedWebhookEventsUpdate = Partial<ProcessedWebhookEventsInsert>

// Products
export type ProductsRow = typeof products.$inferSelect
export type ProductsInsert = typeof products.$inferInsert
export type ProductsUpdate = Partial<ProductsInsert>

// Rag Chunks
export type RagChunksRow = typeof ragChunks.$inferSelect
export type RagChunksInsert = typeof ragChunks.$inferInsert
export type RagChunksUpdate = Partial<RagChunksInsert>

// Rag Documents
export type RagDocumentsRow = typeof ragDocuments.$inferSelect
export type RagDocumentsInsert = typeof ragDocuments.$inferInsert
export type RagDocumentsUpdate = Partial<RagDocumentsInsert>

// Rag Workspaces
export type RagWorkspacesRow = typeof ragWorkspaces.$inferSelect
export type RagWorkspacesInsert = typeof ragWorkspaces.$inferInsert
export type RagWorkspacesUpdate = Partial<RagWorkspacesInsert>

// Rate Limits
export type RateLimitsRow = typeof rateLimits.$inferSelect
export type RateLimitsInsert = typeof rateLimits.$inferInsert
export type RateLimitsUpdate = Partial<RateLimitsInsert>

// Registered Agents
export type RegisteredAgentsRow = typeof registeredAgents.$inferSelect
export type RegisteredAgentsInsert = typeof registeredAgents.$inferInsert
export type RegisteredAgentsUpdate = Partial<RegisteredAgentsInsert>

// Revealcoin Payments
export type RevealcoinPaymentsRow = typeof revealcoinPayments.$inferSelect
export type RevealcoinPaymentsInsert = typeof revealcoinPayments.$inferInsert
export type RevealcoinPaymentsUpdate = Partial<RevealcoinPaymentsInsert>

// Revealcoin Price Snapshots
export type RevealcoinPriceSnapshotsRow = typeof revealcoinPriceSnapshots.$inferSelect
export type RevealcoinPriceSnapshotsInsert = typeof revealcoinPriceSnapshots.$inferInsert
export type RevealcoinPriceSnapshotsUpdate = Partial<RevealcoinPriceSnapshotsInsert>

// Sessions
export type SessionsRow = typeof sessions.$inferSelect
export type SessionsInsert = typeof sessions.$inferInsert
export type SessionsUpdate = Partial<SessionsInsert>

// Site Collaborators
export type SiteCollaboratorsRow = typeof siteCollaborators.$inferSelect
export type SiteCollaboratorsInsert = typeof siteCollaborators.$inferInsert
export type SiteCollaboratorsUpdate = Partial<SiteCollaboratorsInsert>

// Sites
export type SitesRow = typeof sites.$inferSelect
export type SitesInsert = typeof sites.$inferInsert
export type SitesUpdate = Partial<SitesInsert>

// Sync Metadata
export type SyncMetadataRow = typeof syncMetadata.$inferSelect
export type SyncMetadataInsert = typeof syncMetadata.$inferInsert
export type SyncMetadataUpdate = Partial<SyncMetadataInsert>

// Tenant Provider Configs
export type TenantProviderConfigsRow = typeof tenantProviderConfigs.$inferSelect
export type TenantProviderConfigsInsert = typeof tenantProviderConfigs.$inferInsert
export type TenantProviderConfigsUpdate = Partial<TenantProviderConfigsInsert>

// Tenants
export type TenantsRow = typeof tenants.$inferSelect
export type TenantsInsert = typeof tenants.$inferInsert
export type TenantsUpdate = Partial<TenantsInsert>

// Ticket Comments
export type TicketCommentsRow = typeof ticketComments.$inferSelect
export type TicketCommentsInsert = typeof ticketComments.$inferInsert
export type TicketCommentsUpdate = Partial<TicketCommentsInsert>

// Ticket Label Assignments
export type TicketLabelAssignmentsRow = typeof ticketLabelAssignments.$inferSelect
export type TicketLabelAssignmentsInsert = typeof ticketLabelAssignments.$inferInsert
export type TicketLabelAssignmentsUpdate = Partial<TicketLabelAssignmentsInsert>

// Ticket Labels
export type TicketLabelsRow = typeof ticketLabels.$inferSelect
export type TicketLabelsInsert = typeof ticketLabels.$inferInsert
export type TicketLabelsUpdate = Partial<TicketLabelsInsert>

// Tickets
export type TicketsRow = typeof tickets.$inferSelect
export type TicketsInsert = typeof tickets.$inferInsert
export type TicketsUpdate = Partial<TicketsInsert>

// Usage Meters
export type UsageMetersRow = typeof usageMeters.$inferSelect
export type UsageMetersInsert = typeof usageMeters.$inferInsert
export type UsageMetersUpdate = Partial<UsageMetersInsert>

// User Api Keys
export type UserApiKeysRow = typeof userApiKeys.$inferSelect
export type UserApiKeysInsert = typeof userApiKeys.$inferInsert
export type UserApiKeysUpdate = Partial<UserApiKeysInsert>

// User Devices
export type UserDevicesRow = typeof userDevices.$inferSelect
export type UserDevicesInsert = typeof userDevices.$inferInsert
export type UserDevicesUpdate = Partial<UserDevicesInsert>

// Users
export type UsersRow = typeof users.$inferSelect
export type UsersInsert = typeof users.$inferInsert
export type UsersUpdate = Partial<UsersInsert>

// Waitlist
export type WaitlistRow = typeof waitlist.$inferSelect
export type WaitlistInsert = typeof waitlist.$inferInsert
export type WaitlistUpdate = Partial<WaitlistInsert>

// Yjs Documents
export type YjsDocumentsRow = typeof yjsDocuments.$inferSelect
export type YjsDocumentsInsert = typeof yjsDocuments.$inferInsert
export type YjsDocumentsUpdate = Partial<YjsDocumentsInsert>

// =============================================================================
// Relationships
// =============================================================================

/**
 * Relationship type matching Supabase structure
 */
export type Relationship = {
  foreignKeyName: string
  columns: string[]
  isOneToOne: boolean
  referencedRelation: string
  referencedColumns: string[]
}

/**
 * Relationship definitions matching Supabase structure (array format)
 * These are derived from Drizzle relations in packages/db/src/schema/index.ts
 * 
 * Note: isOneToOne is determined by Drizzle relation type:
 * - one() = isOneToOne: true
 * - many() = isOneToOne: false
 */
export type DatabaseRelationships = {
  accountEntitlements: Relationship[]
  accountMemberships: Relationship[]
  accounts: Relationship[]
  accountSubscriptions: Relationship[]
  agentActions: Relationship[]
  agentContexts: Relationship[]
  agentCreditBalance: Relationship[]
  agentMemories: Relationship[]
  agentTaskUsage: Relationship[]
  aiMemorySessions: Relationship[]
  appLogs: Relationship[]
  auditLog: Relationship[]
  billingCatalog: Relationship[]
  boardColumns: Relationship[]
  boards: Relationship[]
  circuitBreakerState: Relationship[]
  codeProvenance: Relationship[]
  codeReviews: Relationship[]
  collabEdits: Relationship[]
  conversations: Relationship[]
  coordinationAgents: Relationship[]
  coordinationEvents: Relationship[]
  coordinationFileClaims: Relationship[]
  coordinationMail: Relationship[]
  coordinationQueueItems: Relationship[]
  coordinationSessions: Relationship[]
  coordinationWorkItems: Relationship[]
  crdtOperations: Relationship[]
  errorEvents: Relationship[]
  failedAttempts: Relationship[]
  gdprBreaches: Relationship[]
  gdprConsents: Relationship[]
  gdprDeletionRequests: Relationship[]
  globalFooter: Relationship[]
  globalHeader: Relationship[]
  globalSettings: Relationship[]
  jobs: Relationship[]
  licenses: Relationship[]
  magicLinks: Relationship[]
  marketplaceServers: Relationship[]
  marketplaceTransactions: Relationship[]
  media: Relationship[]
  messages: Relationship[]
  nodeIdMappings: Relationship[]
  oauthAccounts: Relationship[]
  orders: Relationship[]
  pageRevisions: Relationship[]
  pages: Relationship[]
  passkeys: Relationship[]
  passwordResetTokens: Relationship[]
  posts: Relationship[]
  processedWebhookEvents: Relationship[]
  products: Relationship[]
  ragChunks: Relationship[]
  ragDocuments: Relationship[]
  ragWorkspaces: Relationship[]
  rateLimits: Relationship[]
  registeredAgents: Relationship[]
  revealcoinPayments: Relationship[]
  revealcoinPriceSnapshots: Relationship[]
  sessions: Relationship[]
  siteCollaborators: Relationship[]
  sites: Relationship[]
  syncMetadata: Relationship[]
  tenantProviderConfigs: Relationship[]
  tenants: Relationship[]
  ticketComments: Relationship[]
  ticketLabelAssignments: Relationship[]
  ticketLabels: Relationship[]
  tickets: Relationship[]
  usageMeters: Relationship[]
  userApiKeys: Relationship[]
  userDevices: Relationship[]
  users: Relationship[]
  waitlist: Relationship[]
  yjsDocuments: Relationship[]
}

// AccountEntitlements relationships
export const accountEntitlementsRelationships = [
  { foreignKeyName: 'account_entitlements_account_id_accounts_id_fk', columns: ['account_id'], isOneToOne: true, referencedRelation: 'accounts', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// AccountMemberships relationships
export const accountMembershipsRelationships = [
  { foreignKeyName: 'account_memberships_account_id_accounts_id_fk', columns: ['account_id'], isOneToOne: true, referencedRelation: 'accounts', referencedColumns: ['id'] },
  { foreignKeyName: 'account_memberships_user_id_users_id_fk', columns: ['user_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// Accounts relationships
export const accountsRelationships: readonly Relationship[] = []

// AccountSubscriptions relationships
export const accountSubscriptionsRelationships = [
  { foreignKeyName: 'account_subscriptions_account_id_accounts_id_fk', columns: ['account_id'], isOneToOne: true, referencedRelation: 'accounts', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// AgentActions relationships
export const agentActionsRelationships = [
  { foreignKeyName: 'agent_actions_conversation_id_conversations_id_fk', columns: ['conversation_id'], isOneToOne: true, referencedRelation: 'conversations', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// AgentContexts relationships
export const agentContextsRelationships: readonly Relationship[] = []

// AgentCreditBalance relationships
export const agentCreditBalanceRelationships: readonly Relationship[] = []

// AgentMemories relationships
export const agentMemoriesRelationships = [
  { foreignKeyName: 'agent_memories_site_id_sites_id_fk', columns: ['site_id'], isOneToOne: true, referencedRelation: 'sites', referencedColumns: ['id'] },
  { foreignKeyName: 'agent_memories_verified_by_users_id_fk', columns: ['verified_by'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// AgentTaskUsage relationships
export const agentTaskUsageRelationships: readonly Relationship[] = []

// AiMemorySessions relationships
export const aiMemorySessionsRelationships: readonly Relationship[] = []

// AppLogs relationships
export const appLogsRelationships: readonly Relationship[] = []

// AuditLog relationships
export const auditLogRelationships: readonly Relationship[] = []

// BillingCatalog relationships
export const billingCatalogRelationships: readonly Relationship[] = []

// BoardColumns relationships
export const boardColumnsRelationships = [
  { foreignKeyName: 'board_columns_board_id_boards_id_fk', columns: ['board_id'], isOneToOne: true, referencedRelation: 'boards', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// Boards relationships
export const boardsRelationships = [
  { foreignKeyName: 'boards_owner_id_users_id_fk', columns: ['owner_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// CircuitBreakerState relationships
export const circuitBreakerStateRelationships: readonly Relationship[] = []

// CodeProvenance relationships
export const codeProvenanceRelationships = [
  { foreignKeyName: 'code_provenance_reviewed_by_users_id_fk', columns: ['reviewed_by'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// CodeReviews relationships
export const codeReviewsRelationships = [
  { foreignKeyName: 'code_reviews_provenance_id_code_provenance_id_fk', columns: ['provenance_id'], isOneToOne: true, referencedRelation: 'code_provenance', referencedColumns: ['id'] },
  { foreignKeyName: 'code_reviews_reviewer_id_users_id_fk', columns: ['reviewer_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// CollabEdits relationships
export const collabEditsRelationships = [
  { foreignKeyName: 'collab_edits_document_id_yjs_documents_id_fk', columns: ['document_id'], isOneToOne: true, referencedRelation: 'yjs_documents', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// Conversations relationships
export const conversationsRelationships = [
  { foreignKeyName: 'conversations_user_id_users_id_fk', columns: ['user_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// CoordinationAgents relationships
export const coordinationAgentsRelationships: readonly Relationship[] = []

// CoordinationEvents relationships
export const coordinationEventsRelationships: readonly Relationship[] = []

// CoordinationFileClaims relationships
export const coordinationFileClaimsRelationships: readonly Relationship[] = []

// CoordinationMail relationships
export const coordinationMailRelationships: readonly Relationship[] = []

// CoordinationQueueItems relationships
export const coordinationQueueItemsRelationships: readonly Relationship[] = []

// CoordinationSessions relationships
export const coordinationSessionsRelationships: readonly Relationship[] = []

// CoordinationWorkItems relationships
export const coordinationWorkItemsRelationships: readonly Relationship[] = []

// CrdtOperations relationships
export const crdtOperationsRelationships: readonly Relationship[] = []

// ErrorEvents relationships
export const errorEventsRelationships: readonly Relationship[] = []

// FailedAttempts relationships
export const failedAttemptsRelationships: readonly Relationship[] = []

// GdprBreaches relationships
export const gdprBreachesRelationships: readonly Relationship[] = []

// GdprConsents relationships
export const gdprConsentsRelationships: readonly Relationship[] = []

// GdprDeletionRequests relationships
export const gdprDeletionRequestsRelationships: readonly Relationship[] = []

// GlobalFooter relationships
export const globalFooterRelationships: readonly Relationship[] = []

// GlobalHeader relationships
export const globalHeaderRelationships: readonly Relationship[] = []

// GlobalSettings relationships
export const globalSettingsRelationships: readonly Relationship[] = []

// Jobs relationships
export const jobsRelationships: readonly Relationship[] = []

// Licenses relationships
export const licensesRelationships = [
  { foreignKeyName: 'licenses_user_id_users_id_fk', columns: ['user_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// MagicLinks relationships
export const magicLinksRelationships = [
  { foreignKeyName: 'magic_links_user_id_users_id_fk', columns: ['user_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// MarketplaceServers relationships
export const marketplaceServersRelationships = [
  { foreignKeyName: 'marketplace_servers_developer_id_users_id_fk', columns: ['developer_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// MarketplaceTransactions relationships
export const marketplaceTransactionsRelationships = [
  { foreignKeyName: 'marketplace_transactions_server_id_marketplace_servers_id_fk', columns: ['server_id'], isOneToOne: true, referencedRelation: 'marketplace_servers', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// Media relationships
export const mediaRelationships = [
  { foreignKeyName: 'media_uploaded_by_users_id_fk', columns: ['uploaded_by'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// Messages relationships
export const messagesRelationships: readonly Relationship[] = []

// NodeIdMappings relationships
export const nodeIdMappingsRelationships: readonly Relationship[] = []

// OauthAccounts relationships
export const oauthAccountsRelationships = [
  { foreignKeyName: 'oauth_accounts_user_id_users_id_fk', columns: ['user_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// Orders relationships
export const ordersRelationships = [
  { foreignKeyName: 'orders_customer_id_users_id_fk', columns: ['customer_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// PageRevisions relationships
export const pageRevisionsRelationships = [
  { foreignKeyName: 'page_revisions_page_id_pages_id_fk', columns: ['page_id'], isOneToOne: true, referencedRelation: 'pages', referencedColumns: ['id'] },
  { foreignKeyName: 'page_revisions_created_by_users_id_fk', columns: ['created_by'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// Pages relationships
export const pagesRelationships = [
  { foreignKeyName: 'pages_site_id_sites_id_fk', columns: ['site_id'], isOneToOne: true, referencedRelation: 'sites', referencedColumns: ['id'] },
  { foreignKeyName: 'pages_parent_id_pages_id_fk', columns: ['parent_id'], isOneToOne: true, referencedRelation: 'pages', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// Passkeys relationships
export const passkeysRelationships = [
  { foreignKeyName: 'passkeys_user_id_users_id_fk', columns: ['user_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// PasswordResetTokens relationships
export const passwordResetTokensRelationships = [
  { foreignKeyName: 'password_reset_tokens_user_id_users_id_fk', columns: ['user_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// Posts relationships
export const postsRelationships = [
  { foreignKeyName: 'posts_author_id_users_id_fk', columns: ['author_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
  { foreignKeyName: 'posts_featured_image_id_media_id_fk', columns: ['featured_image_id'], isOneToOne: true, referencedRelation: 'media', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// ProcessedWebhookEvents relationships
export const processedWebhookEventsRelationships: readonly Relationship[] = []

// Products relationships
export const productsRelationships = [
  { foreignKeyName: 'products_owner_id_users_id_fk', columns: ['owner_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// RagChunks relationships
export const ragChunksRelationships: readonly Relationship[] = []

// RagDocuments relationships
export const ragDocumentsRelationships: readonly Relationship[] = []

// RagWorkspaces relationships
export const ragWorkspacesRelationships: readonly Relationship[] = []

// RateLimits relationships
export const rateLimitsRelationships: readonly Relationship[] = []

// RegisteredAgents relationships
export const registeredAgentsRelationships: readonly Relationship[] = []

// RevealcoinPayments relationships
export const revealcoinPaymentsRelationships: readonly Relationship[] = []

// RevealcoinPriceSnapshots relationships
export const revealcoinPriceSnapshotsRelationships: readonly Relationship[] = []

// Sessions relationships
export const sessionsRelationships = [
  { foreignKeyName: 'sessions_user_id_users_id_fk', columns: ['user_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// SiteCollaborators relationships
export const siteCollaboratorsRelationships = [
  { foreignKeyName: 'site_collaborators_site_id_sites_id_fk', columns: ['site_id'], isOneToOne: true, referencedRelation: 'sites', referencedColumns: ['id'] },
  { foreignKeyName: 'site_collaborators_user_id_users_id_fk', columns: ['user_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
  { foreignKeyName: 'site_collaborators_added_by_users_id_fk', columns: ['added_by'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// Sites relationships
export const sitesRelationships = [
  { foreignKeyName: 'sites_owner_id_users_id_fk', columns: ['owner_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// SyncMetadata relationships
export const syncMetadataRelationships: readonly Relationship[] = []

// TenantProviderConfigs relationships
export const tenantProviderConfigsRelationships = [
  { foreignKeyName: 'tenant_provider_configs_user_id_users_id_fk', columns: ['user_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// Tenants relationships
export const tenantsRelationships: readonly Relationship[] = []

// TicketComments relationships
export const ticketCommentsRelationships = [
  { foreignKeyName: 'ticket_comments_ticket_id_tickets_id_fk', columns: ['ticket_id'], isOneToOne: true, referencedRelation: 'tickets', referencedColumns: ['id'] },
  { foreignKeyName: 'ticket_comments_author_id_users_id_fk', columns: ['author_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// TicketLabelAssignments relationships
export const ticketLabelAssignmentsRelationships = [
  { foreignKeyName: 'ticket_label_assignments_ticket_id_tickets_id_fk', columns: ['ticket_id'], isOneToOne: true, referencedRelation: 'tickets', referencedColumns: ['id'] },
  { foreignKeyName: 'ticket_label_assignments_label_id_ticket_labels_id_fk', columns: ['label_id'], isOneToOne: true, referencedRelation: 'ticket_labels', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// TicketLabels relationships
export const ticketLabelsRelationships: readonly Relationship[] = []

// Tickets relationships
export const ticketsRelationships = [
  { foreignKeyName: 'tickets_board_id_boards_id_fk', columns: ['board_id'], isOneToOne: true, referencedRelation: 'boards', referencedColumns: ['id'] },
  { foreignKeyName: 'tickets_column_id_board_columns_id_fk', columns: ['column_id'], isOneToOne: true, referencedRelation: 'board_columns', referencedColumns: ['id'] },
  { foreignKeyName: 'tickets_assignee_id_users_id_fk', columns: ['assignee_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
  { foreignKeyName: 'tickets_reporter_id_users_id_fk', columns: ['reporter_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
  { foreignKeyName: 'tickets_parent_ticket_id_tickets_id_fk', columns: ['parent_ticket_id'], isOneToOne: true, referencedRelation: 'tickets', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// UsageMeters relationships
export const usageMetersRelationships = [
  { foreignKeyName: 'usage_meters_account_id_accounts_id_fk', columns: ['account_id'], isOneToOne: true, referencedRelation: 'accounts', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// UserApiKeys relationships
export const userApiKeysRelationships = [
  { foreignKeyName: 'user_api_keys_user_id_users_id_fk', columns: ['user_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// UserDevices relationships
export const userDevicesRelationships: readonly Relationship[] = []

// Users relationships
export const usersRelationships: readonly Relationship[] = []

// Waitlist relationships
export const waitlistRelationships: readonly Relationship[] = []

// YjsDocuments relationships
export const yjsDocumentsRelationships: readonly Relationship[] = []


// =============================================================================
// Enums
// =============================================================================

/**
 * Database enums (currently none, but structure ready for future enums)
 * When enums are added to Drizzle schemas, they will be included here
 */
export interface DatabaseEnums {
  // Enums will be added here as they are defined in the schema
}

// =============================================================================
// Main Database Type (Supabase-compatible structure)
// =============================================================================

/**
 * Centralized Database type matching Supabase structure
 *
 * This provides feature parity with Supabase's Database type:
 * - Full type safety for all tables
 * - Row, Insert, Update types for each table
 * - Relationships information
 * - Enums support
 *
 * @example
 * ```typescript
 * import type { Database } from '@revealui/db/types'
 *
 * type User = Database['public']['Tables']['users']['Row']
 * type NewUser = Database['public']['Tables']['users']['Insert']
 * ```
 */
export type Database = {
  public: {
    Tables: {
      account_entitlements: {
        Row: AccountEntitlementsRow
        Insert: AccountEntitlementsInsert
        Update: AccountEntitlementsUpdate
        Relationships: typeof accountEntitlementsRelationships
      }
      account_memberships: {
        Row: AccountMembershipsRow
        Insert: AccountMembershipsInsert
        Update: AccountMembershipsUpdate
        Relationships: typeof accountMembershipsRelationships
      }
      accounts: {
        Row: AccountsRow
        Insert: AccountsInsert
        Update: AccountsUpdate
        Relationships: typeof accountsRelationships
      }
      account_subscriptions: {
        Row: AccountSubscriptionsRow
        Insert: AccountSubscriptionsInsert
        Update: AccountSubscriptionsUpdate
        Relationships: typeof accountSubscriptionsRelationships
      }
      agent_actions: {
        Row: AgentActionsRow
        Insert: AgentActionsInsert
        Update: AgentActionsUpdate
        Relationships: typeof agentActionsRelationships
      }
      agent_contexts: {
        Row: AgentContextsRow
        Insert: AgentContextsInsert
        Update: AgentContextsUpdate
        Relationships: typeof agentContextsRelationships
      }
      agent_credit_balance: {
        Row: AgentCreditBalanceRow
        Insert: AgentCreditBalanceInsert
        Update: AgentCreditBalanceUpdate
        Relationships: typeof agentCreditBalanceRelationships
      }
      agent_memories: {
        Row: AgentMemoriesRow
        Insert: AgentMemoriesInsert
        Update: AgentMemoriesUpdate
        Relationships: typeof agentMemoriesRelationships
      }
      agent_task_usage: {
        Row: AgentTaskUsageRow
        Insert: AgentTaskUsageInsert
        Update: AgentTaskUsageUpdate
        Relationships: typeof agentTaskUsageRelationships
      }
      ai_memory_sessions: {
        Row: AiMemorySessionsRow
        Insert: AiMemorySessionsInsert
        Update: AiMemorySessionsUpdate
        Relationships: typeof aiMemorySessionsRelationships
      }
      app_logs: {
        Row: AppLogsRow
        Insert: AppLogsInsert
        Update: AppLogsUpdate
        Relationships: typeof appLogsRelationships
      }
      audit_log: {
        Row: AuditLogRow
        Insert: AuditLogInsert
        Update: AuditLogUpdate
        Relationships: typeof auditLogRelationships
      }
      billing_catalog: {
        Row: BillingCatalogRow
        Insert: BillingCatalogInsert
        Update: BillingCatalogUpdate
        Relationships: typeof billingCatalogRelationships
      }
      board_columns: {
        Row: BoardColumnsRow
        Insert: BoardColumnsInsert
        Update: BoardColumnsUpdate
        Relationships: typeof boardColumnsRelationships
      }
      boards: {
        Row: BoardsRow
        Insert: BoardsInsert
        Update: BoardsUpdate
        Relationships: typeof boardsRelationships
      }
      circuit_breaker_state: {
        Row: CircuitBreakerStateRow
        Insert: CircuitBreakerStateInsert
        Update: CircuitBreakerStateUpdate
        Relationships: typeof circuitBreakerStateRelationships
      }
      code_provenance: {
        Row: CodeProvenanceRow
        Insert: CodeProvenanceInsert
        Update: CodeProvenanceUpdate
        Relationships: typeof codeProvenanceRelationships
      }
      code_reviews: {
        Row: CodeReviewsRow
        Insert: CodeReviewsInsert
        Update: CodeReviewsUpdate
        Relationships: typeof codeReviewsRelationships
      }
      collab_edits: {
        Row: CollabEditsRow
        Insert: CollabEditsInsert
        Update: CollabEditsUpdate
        Relationships: typeof collabEditsRelationships
      }
      conversations: {
        Row: ConversationsRow
        Insert: ConversationsInsert
        Update: ConversationsUpdate
        Relationships: typeof conversationsRelationships
      }
      coordination_agents: {
        Row: CoordinationAgentsRow
        Insert: CoordinationAgentsInsert
        Update: CoordinationAgentsUpdate
        Relationships: typeof coordinationAgentsRelationships
      }
      coordination_events: {
        Row: CoordinationEventsRow
        Insert: CoordinationEventsInsert
        Update: CoordinationEventsUpdate
        Relationships: typeof coordinationEventsRelationships
      }
      coordination_file_claims: {
        Row: CoordinationFileClaimsRow
        Insert: CoordinationFileClaimsInsert
        Update: CoordinationFileClaimsUpdate
        Relationships: typeof coordinationFileClaimsRelationships
      }
      coordination_mail: {
        Row: CoordinationMailRow
        Insert: CoordinationMailInsert
        Update: CoordinationMailUpdate
        Relationships: typeof coordinationMailRelationships
      }
      coordination_queue_items: {
        Row: CoordinationQueueItemsRow
        Insert: CoordinationQueueItemsInsert
        Update: CoordinationQueueItemsUpdate
        Relationships: typeof coordinationQueueItemsRelationships
      }
      coordination_sessions: {
        Row: CoordinationSessionsRow
        Insert: CoordinationSessionsInsert
        Update: CoordinationSessionsUpdate
        Relationships: typeof coordinationSessionsRelationships
      }
      coordination_work_items: {
        Row: CoordinationWorkItemsRow
        Insert: CoordinationWorkItemsInsert
        Update: CoordinationWorkItemsUpdate
        Relationships: typeof coordinationWorkItemsRelationships
      }
      crdt_operations: {
        Row: CrdtOperationsRow
        Insert: CrdtOperationsInsert
        Update: CrdtOperationsUpdate
        Relationships: typeof crdtOperationsRelationships
      }
      error_events: {
        Row: ErrorEventsRow
        Insert: ErrorEventsInsert
        Update: ErrorEventsUpdate
        Relationships: typeof errorEventsRelationships
      }
      failed_attempts: {
        Row: FailedAttemptsRow
        Insert: FailedAttemptsInsert
        Update: FailedAttemptsUpdate
        Relationships: typeof failedAttemptsRelationships
      }
      gdpr_breaches: {
        Row: GdprBreachesRow
        Insert: GdprBreachesInsert
        Update: GdprBreachesUpdate
        Relationships: typeof gdprBreachesRelationships
      }
      gdpr_consents: {
        Row: GdprConsentsRow
        Insert: GdprConsentsInsert
        Update: GdprConsentsUpdate
        Relationships: typeof gdprConsentsRelationships
      }
      gdpr_deletion_requests: {
        Row: GdprDeletionRequestsRow
        Insert: GdprDeletionRequestsInsert
        Update: GdprDeletionRequestsUpdate
        Relationships: typeof gdprDeletionRequestsRelationships
      }
      global_footer: {
        Row: GlobalFooterRow
        Insert: GlobalFooterInsert
        Update: GlobalFooterUpdate
        Relationships: typeof globalFooterRelationships
      }
      global_header: {
        Row: GlobalHeaderRow
        Insert: GlobalHeaderInsert
        Update: GlobalHeaderUpdate
        Relationships: typeof globalHeaderRelationships
      }
      global_settings: {
        Row: GlobalSettingsRow
        Insert: GlobalSettingsInsert
        Update: GlobalSettingsUpdate
        Relationships: typeof globalSettingsRelationships
      }
      jobs: {
        Row: JobsRow
        Insert: JobsInsert
        Update: JobsUpdate
        Relationships: typeof jobsRelationships
      }
      licenses: {
        Row: LicensesRow
        Insert: LicensesInsert
        Update: LicensesUpdate
        Relationships: typeof licensesRelationships
      }
      magic_links: {
        Row: MagicLinksRow
        Insert: MagicLinksInsert
        Update: MagicLinksUpdate
        Relationships: typeof magicLinksRelationships
      }
      marketplace_servers: {
        Row: MarketplaceServersRow
        Insert: MarketplaceServersInsert
        Update: MarketplaceServersUpdate
        Relationships: typeof marketplaceServersRelationships
      }
      marketplace_transactions: {
        Row: MarketplaceTransactionsRow
        Insert: MarketplaceTransactionsInsert
        Update: MarketplaceTransactionsUpdate
        Relationships: typeof marketplaceTransactionsRelationships
      }
      media: {
        Row: MediaRow
        Insert: MediaInsert
        Update: MediaUpdate
        Relationships: typeof mediaRelationships
      }
      messages: {
        Row: MessagesRow
        Insert: MessagesInsert
        Update: MessagesUpdate
        Relationships: typeof messagesRelationships
      }
      node_id_mappings: {
        Row: NodeIdMappingsRow
        Insert: NodeIdMappingsInsert
        Update: NodeIdMappingsUpdate
        Relationships: typeof nodeIdMappingsRelationships
      }
      oauth_accounts: {
        Row: OauthAccountsRow
        Insert: OauthAccountsInsert
        Update: OauthAccountsUpdate
        Relationships: typeof oauthAccountsRelationships
      }
      orders: {
        Row: OrdersRow
        Insert: OrdersInsert
        Update: OrdersUpdate
        Relationships: typeof ordersRelationships
      }
      page_revisions: {
        Row: PageRevisionsRow
        Insert: PageRevisionsInsert
        Update: PageRevisionsUpdate
        Relationships: typeof pageRevisionsRelationships
      }
      pages: {
        Row: PagesRow
        Insert: PagesInsert
        Update: PagesUpdate
        Relationships: typeof pagesRelationships
      }
      passkeys: {
        Row: PasskeysRow
        Insert: PasskeysInsert
        Update: PasskeysUpdate
        Relationships: typeof passkeysRelationships
      }
      password_reset_tokens: {
        Row: PasswordResetTokensRow
        Insert: PasswordResetTokensInsert
        Update: PasswordResetTokensUpdate
        Relationships: typeof passwordResetTokensRelationships
      }
      posts: {
        Row: PostsRow
        Insert: PostsInsert
        Update: PostsUpdate
        Relationships: typeof postsRelationships
      }
      processed_webhook_events: {
        Row: ProcessedWebhookEventsRow
        Insert: ProcessedWebhookEventsInsert
        Update: ProcessedWebhookEventsUpdate
        Relationships: typeof processedWebhookEventsRelationships
      }
      products: {
        Row: ProductsRow
        Insert: ProductsInsert
        Update: ProductsUpdate
        Relationships: typeof productsRelationships
      }
      rag_chunks: {
        Row: RagChunksRow
        Insert: RagChunksInsert
        Update: RagChunksUpdate
        Relationships: typeof ragChunksRelationships
      }
      rag_documents: {
        Row: RagDocumentsRow
        Insert: RagDocumentsInsert
        Update: RagDocumentsUpdate
        Relationships: typeof ragDocumentsRelationships
      }
      rag_workspaces: {
        Row: RagWorkspacesRow
        Insert: RagWorkspacesInsert
        Update: RagWorkspacesUpdate
        Relationships: typeof ragWorkspacesRelationships
      }
      rate_limits: {
        Row: RateLimitsRow
        Insert: RateLimitsInsert
        Update: RateLimitsUpdate
        Relationships: typeof rateLimitsRelationships
      }
      registered_agents: {
        Row: RegisteredAgentsRow
        Insert: RegisteredAgentsInsert
        Update: RegisteredAgentsUpdate
        Relationships: typeof registeredAgentsRelationships
      }
      revealcoin_payments: {
        Row: RevealcoinPaymentsRow
        Insert: RevealcoinPaymentsInsert
        Update: RevealcoinPaymentsUpdate
        Relationships: typeof revealcoinPaymentsRelationships
      }
      revealcoin_price_snapshots: {
        Row: RevealcoinPriceSnapshotsRow
        Insert: RevealcoinPriceSnapshotsInsert
        Update: RevealcoinPriceSnapshotsUpdate
        Relationships: typeof revealcoinPriceSnapshotsRelationships
      }
      sessions: {
        Row: SessionsRow
        Insert: SessionsInsert
        Update: SessionsUpdate
        Relationships: typeof sessionsRelationships
      }
      site_collaborators: {
        Row: SiteCollaboratorsRow
        Insert: SiteCollaboratorsInsert
        Update: SiteCollaboratorsUpdate
        Relationships: typeof siteCollaboratorsRelationships
      }
      sites: {
        Row: SitesRow
        Insert: SitesInsert
        Update: SitesUpdate
        Relationships: typeof sitesRelationships
      }
      sync_metadata: {
        Row: SyncMetadataRow
        Insert: SyncMetadataInsert
        Update: SyncMetadataUpdate
        Relationships: typeof syncMetadataRelationships
      }
      tenant_provider_configs: {
        Row: TenantProviderConfigsRow
        Insert: TenantProviderConfigsInsert
        Update: TenantProviderConfigsUpdate
        Relationships: typeof tenantProviderConfigsRelationships
      }
      tenants: {
        Row: TenantsRow
        Insert: TenantsInsert
        Update: TenantsUpdate
        Relationships: typeof tenantsRelationships
      }
      ticket_comments: {
        Row: TicketCommentsRow
        Insert: TicketCommentsInsert
        Update: TicketCommentsUpdate
        Relationships: typeof ticketCommentsRelationships
      }
      ticket_label_assignments: {
        Row: TicketLabelAssignmentsRow
        Insert: TicketLabelAssignmentsInsert
        Update: TicketLabelAssignmentsUpdate
        Relationships: typeof ticketLabelAssignmentsRelationships
      }
      ticket_labels: {
        Row: TicketLabelsRow
        Insert: TicketLabelsInsert
        Update: TicketLabelsUpdate
        Relationships: typeof ticketLabelsRelationships
      }
      tickets: {
        Row: TicketsRow
        Insert: TicketsInsert
        Update: TicketsUpdate
        Relationships: typeof ticketsRelationships
      }
      usage_meters: {
        Row: UsageMetersRow
        Insert: UsageMetersInsert
        Update: UsageMetersUpdate
        Relationships: typeof usageMetersRelationships
      }
      user_api_keys: {
        Row: UserApiKeysRow
        Insert: UserApiKeysInsert
        Update: UserApiKeysUpdate
        Relationships: typeof userApiKeysRelationships
      }
      user_devices: {
        Row: UserDevicesRow
        Insert: UserDevicesInsert
        Update: UserDevicesUpdate
        Relationships: typeof userDevicesRelationships
      }
      users: {
        Row: UsersRow
        Insert: UsersInsert
        Update: UsersUpdate
        Relationships: typeof usersRelationships
      }
      waitlist: {
        Row: WaitlistRow
        Insert: WaitlistInsert
        Update: WaitlistUpdate
        Relationships: typeof waitlistRelationships
      }
      yjs_documents: {
        Row: YjsDocumentsRow
        Insert: YjsDocumentsInsert
        Update: YjsDocumentsUpdate
        Relationships: typeof yjsDocumentsRelationships
      }
    }
    Enums: DatabaseEnums
  }
}

// =============================================================================
// Type Utilities (for convenience)
// =============================================================================

/**
 * Extract Row type for a table
 */
export type TableRow<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

/**
 * Extract Insert type for a table
 */
export type TableInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']

/**
 * Extract Update type for a table
 */
export type TableUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']

/**
 * Extract Relationships for a table
 */
export type TableRelationships<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Relationships']
