/**
 * Generated Database Type for NeonDB
 *
 * This file is auto-generated by packages/db/src/types/generate.ts
 * DO NOT MODIFY MANUALLY - regenerate using: pnpm generate:types
 *
 * Generated: 2026-02-02T23:24:09.677Z
 *
 * This type matches the Supabase Database type structure for feature parity.
 * Tables are automatically discovered from packages/db/src/schema/*.ts
 */
import type { agentActions, agentContexts, agentMemories, conversations, crdtOperations, failedAttempts, globalFooter, globalHeader, globalSettings, media, messages, nodeIdMappings, pageRevisions, pages, passwordResetTokens, posts, rateLimits, sessions, siteCollaborators, sites, syncMetadata, userDevices, users } from '../schema/index.js';
export type AgentActionsRow = typeof agentActions.$inferSelect;
export type AgentActionsInsert = typeof agentActions.$inferInsert;
export type AgentActionsUpdate = Partial<AgentActionsInsert>;
export type AgentContextsRow = typeof agentContexts.$inferSelect;
export type AgentContextsInsert = typeof agentContexts.$inferInsert;
export type AgentContextsUpdate = Partial<AgentContextsInsert>;
export type AgentMemoriesRow = typeof agentMemories.$inferSelect;
export type AgentMemoriesInsert = typeof agentMemories.$inferInsert;
export type AgentMemoriesUpdate = Partial<AgentMemoriesInsert>;
export type ConversationsRow = typeof conversations.$inferSelect;
export type ConversationsInsert = typeof conversations.$inferInsert;
export type ConversationsUpdate = Partial<ConversationsInsert>;
export type CrdtOperationsRow = typeof crdtOperations.$inferSelect;
export type CrdtOperationsInsert = typeof crdtOperations.$inferInsert;
export type CrdtOperationsUpdate = Partial<CrdtOperationsInsert>;
export type FailedAttemptsRow = typeof failedAttempts.$inferSelect;
export type FailedAttemptsInsert = typeof failedAttempts.$inferInsert;
export type FailedAttemptsUpdate = Partial<FailedAttemptsInsert>;
export type GlobalFooterRow = typeof globalFooter.$inferSelect;
export type GlobalFooterInsert = typeof globalFooter.$inferInsert;
export type GlobalFooterUpdate = Partial<GlobalFooterInsert>;
export type GlobalHeaderRow = typeof globalHeader.$inferSelect;
export type GlobalHeaderInsert = typeof globalHeader.$inferInsert;
export type GlobalHeaderUpdate = Partial<GlobalHeaderInsert>;
export type GlobalSettingsRow = typeof globalSettings.$inferSelect;
export type GlobalSettingsInsert = typeof globalSettings.$inferInsert;
export type GlobalSettingsUpdate = Partial<GlobalSettingsInsert>;
export type MediaRow = typeof media.$inferSelect;
export type MediaInsert = typeof media.$inferInsert;
export type MediaUpdate = Partial<MediaInsert>;
export type MessagesRow = typeof messages.$inferSelect;
export type MessagesInsert = typeof messages.$inferInsert;
export type MessagesUpdate = Partial<MessagesInsert>;
export type NodeIdMappingsRow = typeof nodeIdMappings.$inferSelect;
export type NodeIdMappingsInsert = typeof nodeIdMappings.$inferInsert;
export type NodeIdMappingsUpdate = Partial<NodeIdMappingsInsert>;
export type PageRevisionsRow = typeof pageRevisions.$inferSelect;
export type PageRevisionsInsert = typeof pageRevisions.$inferInsert;
export type PageRevisionsUpdate = Partial<PageRevisionsInsert>;
export type PagesRow = typeof pages.$inferSelect;
export type PagesInsert = typeof pages.$inferInsert;
export type PagesUpdate = Partial<PagesInsert>;
export type PasswordResetTokensRow = typeof passwordResetTokens.$inferSelect;
export type PasswordResetTokensInsert = typeof passwordResetTokens.$inferInsert;
export type PasswordResetTokensUpdate = Partial<PasswordResetTokensInsert>;
export type PostsRow = typeof posts.$inferSelect;
export type PostsInsert = typeof posts.$inferInsert;
export type PostsUpdate = Partial<PostsInsert>;
export type RateLimitsRow = typeof rateLimits.$inferSelect;
export type RateLimitsInsert = typeof rateLimits.$inferInsert;
export type RateLimitsUpdate = Partial<RateLimitsInsert>;
export type SessionsRow = typeof sessions.$inferSelect;
export type SessionsInsert = typeof sessions.$inferInsert;
export type SessionsUpdate = Partial<SessionsInsert>;
export type SiteCollaboratorsRow = typeof siteCollaborators.$inferSelect;
export type SiteCollaboratorsInsert = typeof siteCollaborators.$inferInsert;
export type SiteCollaboratorsUpdate = Partial<SiteCollaboratorsInsert>;
export type SitesRow = typeof sites.$inferSelect;
export type SitesInsert = typeof sites.$inferInsert;
export type SitesUpdate = Partial<SitesInsert>;
export type SyncMetadataRow = typeof syncMetadata.$inferSelect;
export type SyncMetadataInsert = typeof syncMetadata.$inferInsert;
export type SyncMetadataUpdate = Partial<SyncMetadataInsert>;
export type UserDevicesRow = typeof userDevices.$inferSelect;
export type UserDevicesInsert = typeof userDevices.$inferInsert;
export type UserDevicesUpdate = Partial<UserDevicesInsert>;
export type UsersRow = typeof users.$inferSelect;
export type UsersInsert = typeof users.$inferInsert;
export type UsersUpdate = Partial<UsersInsert>;
/**
 * Relationship type matching Supabase structure
 */
export type Relationship = {
    foreignKeyName: string;
    columns: string[];
    isOneToOne: boolean;
    referencedRelation: string;
    referencedColumns: string[];
};
/**
 * Relationship definitions matching Supabase structure (array format)
 * These are derived from Drizzle relations in packages/db/src/schema/index.ts
 *
 * Note: isOneToOne is determined by Drizzle relation type:
 * - one() = isOneToOne: true
 * - many() = isOneToOne: false
 */
export type DatabaseRelationships = {
    agentActions: Relationship[];
    agentContexts: Relationship[];
    agentMemories: Relationship[];
    conversations: Relationship[];
    crdtOperations: Relationship[];
    failedAttempts: Relationship[];
    globalFooter: Relationship[];
    globalHeader: Relationship[];
    globalSettings: Relationship[];
    media: Relationship[];
    messages: Relationship[];
    nodeIdMappings: Relationship[];
    pageRevisions: Relationship[];
    pages: Relationship[];
    passwordResetTokens: Relationship[];
    posts: Relationship[];
    rateLimits: Relationship[];
    sessions: Relationship[];
    siteCollaborators: Relationship[];
    sites: Relationship[];
    syncMetadata: Relationship[];
    userDevices: Relationship[];
    users: Relationship[];
};
export declare const agentActionsRelationships: readonly [{
    readonly foreignKeyName: "agent_actions_conversation_id_conversations_id_fk";
    readonly columns: ["conversation_id"];
    readonly isOneToOne: true;
    readonly referencedRelation: "conversations";
    readonly referencedColumns: ["id"];
}];
export declare const agentContextsRelationships: readonly Relationship[];
export declare const agentMemoriesRelationships: readonly [{
    readonly foreignKeyName: "agent_memories_site_id_sites_id_fk";
    readonly columns: ["site_id"];
    readonly isOneToOne: true;
    readonly referencedRelation: "sites";
    readonly referencedColumns: ["id"];
}, {
    readonly foreignKeyName: "agent_memories_verified_by_users_id_fk";
    readonly columns: ["verified_by"];
    readonly isOneToOne: true;
    readonly referencedRelation: "users";
    readonly referencedColumns: ["id"];
}];
export declare const conversationsRelationships: readonly [{
    readonly foreignKeyName: "conversations_user_id_users_id_fk";
    readonly columns: ["user_id"];
    readonly isOneToOne: true;
    readonly referencedRelation: "users";
    readonly referencedColumns: ["id"];
}];
export declare const crdtOperationsRelationships: readonly Relationship[];
export declare const failedAttemptsRelationships: readonly Relationship[];
export declare const globalFooterRelationships: readonly Relationship[];
export declare const globalHeaderRelationships: readonly Relationship[];
export declare const globalSettingsRelationships: readonly Relationship[];
export declare const mediaRelationships: readonly [{
    readonly foreignKeyName: "media_uploaded_by_users_id_fk";
    readonly columns: ["uploaded_by"];
    readonly isOneToOne: true;
    readonly referencedRelation: "users";
    readonly referencedColumns: ["id"];
}];
export declare const messagesRelationships: readonly Relationship[];
export declare const nodeIdMappingsRelationships: readonly Relationship[];
export declare const pageRevisionsRelationships: readonly [{
    readonly foreignKeyName: "page_revisions_page_id_pages_id_fk";
    readonly columns: ["page_id"];
    readonly isOneToOne: true;
    readonly referencedRelation: "pages";
    readonly referencedColumns: ["id"];
}, {
    readonly foreignKeyName: "page_revisions_created_by_users_id_fk";
    readonly columns: ["created_by"];
    readonly isOneToOne: true;
    readonly referencedRelation: "users";
    readonly referencedColumns: ["id"];
}];
export declare const pagesRelationships: readonly [{
    readonly foreignKeyName: "pages_site_id_sites_id_fk";
    readonly columns: ["site_id"];
    readonly isOneToOne: true;
    readonly referencedRelation: "sites";
    readonly referencedColumns: ["id"];
}, {
    readonly foreignKeyName: "pages_parent_id_pages_id_fk";
    readonly columns: ["parent_id"];
    readonly isOneToOne: true;
    readonly referencedRelation: "pages";
    readonly referencedColumns: ["id"];
}];
export declare const passwordResetTokensRelationships: readonly [{
    readonly foreignKeyName: "password_reset_tokens_user_id_users_id_fk";
    readonly columns: ["user_id"];
    readonly isOneToOne: true;
    readonly referencedRelation: "users";
    readonly referencedColumns: ["id"];
}];
export declare const postsRelationships: readonly [{
    readonly foreignKeyName: "posts_author_id_users_id_fk";
    readonly columns: ["author_id"];
    readonly isOneToOne: true;
    readonly referencedRelation: "users";
    readonly referencedColumns: ["id"];
}, {
    readonly foreignKeyName: "posts_featured_image_id_media_id_fk";
    readonly columns: ["featured_image_id"];
    readonly isOneToOne: true;
    readonly referencedRelation: "media";
    readonly referencedColumns: ["id"];
}];
export declare const rateLimitsRelationships: readonly Relationship[];
export declare const sessionsRelationships: readonly [{
    readonly foreignKeyName: "sessions_user_id_users_id_fk";
    readonly columns: ["user_id"];
    readonly isOneToOne: true;
    readonly referencedRelation: "users";
    readonly referencedColumns: ["id"];
}];
export declare const siteCollaboratorsRelationships: readonly [{
    readonly foreignKeyName: "site_collaborators_site_id_sites_id_fk";
    readonly columns: ["site_id"];
    readonly isOneToOne: true;
    readonly referencedRelation: "sites";
    readonly referencedColumns: ["id"];
}, {
    readonly foreignKeyName: "site_collaborators_user_id_users_id_fk";
    readonly columns: ["user_id"];
    readonly isOneToOne: true;
    readonly referencedRelation: "users";
    readonly referencedColumns: ["id"];
}, {
    readonly foreignKeyName: "site_collaborators_added_by_users_id_fk";
    readonly columns: ["added_by"];
    readonly isOneToOne: true;
    readonly referencedRelation: "users";
    readonly referencedColumns: ["id"];
}];
export declare const sitesRelationships: readonly [{
    readonly foreignKeyName: "sites_owner_id_users_id_fk";
    readonly columns: ["owner_id"];
    readonly isOneToOne: true;
    readonly referencedRelation: "users";
    readonly referencedColumns: ["id"];
}];
export declare const syncMetadataRelationships: readonly Relationship[];
export declare const userDevicesRelationships: readonly Relationship[];
export declare const usersRelationships: readonly Relationship[];
/**
 * Database enums (currently none, but structure ready for future enums)
 * When enums are added to Drizzle schemas, they will be included here
 */
export type DatabaseEnums = {};
/**
 * Centralized Database type matching Supabase structure
 *
 * This provides feature parity with Supabase's Database type:
 * - Full type safety for all tables
 * - Row, Insert, Update types for each table
 * - Relationships information
 * - Enums support
 *
 * @example
 * ```typescript
 * import type { Database } from '@revealui/db/types'
 *
 * type User = Database['public']['Tables']['users']['Row']
 * type NewUser = Database['public']['Tables']['users']['Insert']
 * ```
 */
export type Database = {
    public: {
        Tables: {
            agent_actions: {
                Row: AgentActionsRow;
                Insert: AgentActionsInsert;
                Update: AgentActionsUpdate;
                Relationships: typeof agentActionsRelationships;
            };
            agent_contexts: {
                Row: AgentContextsRow;
                Insert: AgentContextsInsert;
                Update: AgentContextsUpdate;
                Relationships: typeof agentContextsRelationships;
            };
            agent_memories: {
                Row: AgentMemoriesRow;
                Insert: AgentMemoriesInsert;
                Update: AgentMemoriesUpdate;
                Relationships: typeof agentMemoriesRelationships;
            };
            conversations: {
                Row: ConversationsRow;
                Insert: ConversationsInsert;
                Update: ConversationsUpdate;
                Relationships: typeof conversationsRelationships;
            };
            crdt_operations: {
                Row: CrdtOperationsRow;
                Insert: CrdtOperationsInsert;
                Update: CrdtOperationsUpdate;
                Relationships: typeof crdtOperationsRelationships;
            };
            failed_attempts: {
                Row: FailedAttemptsRow;
                Insert: FailedAttemptsInsert;
                Update: FailedAttemptsUpdate;
                Relationships: typeof failedAttemptsRelationships;
            };
            global_footer: {
                Row: GlobalFooterRow;
                Insert: GlobalFooterInsert;
                Update: GlobalFooterUpdate;
                Relationships: typeof globalFooterRelationships;
            };
            global_header: {
                Row: GlobalHeaderRow;
                Insert: GlobalHeaderInsert;
                Update: GlobalHeaderUpdate;
                Relationships: typeof globalHeaderRelationships;
            };
            global_settings: {
                Row: GlobalSettingsRow;
                Insert: GlobalSettingsInsert;
                Update: GlobalSettingsUpdate;
                Relationships: typeof globalSettingsRelationships;
            };
            media: {
                Row: MediaRow;
                Insert: MediaInsert;
                Update: MediaUpdate;
                Relationships: typeof mediaRelationships;
            };
            messages: {
                Row: MessagesRow;
                Insert: MessagesInsert;
                Update: MessagesUpdate;
                Relationships: typeof messagesRelationships;
            };
            node_id_mappings: {
                Row: NodeIdMappingsRow;
                Insert: NodeIdMappingsInsert;
                Update: NodeIdMappingsUpdate;
                Relationships: typeof nodeIdMappingsRelationships;
            };
            page_revisions: {
                Row: PageRevisionsRow;
                Insert: PageRevisionsInsert;
                Update: PageRevisionsUpdate;
                Relationships: typeof pageRevisionsRelationships;
            };
            pages: {
                Row: PagesRow;
                Insert: PagesInsert;
                Update: PagesUpdate;
                Relationships: typeof pagesRelationships;
            };
            password_reset_tokens: {
                Row: PasswordResetTokensRow;
                Insert: PasswordResetTokensInsert;
                Update: PasswordResetTokensUpdate;
                Relationships: typeof passwordResetTokensRelationships;
            };
            posts: {
                Row: PostsRow;
                Insert: PostsInsert;
                Update: PostsUpdate;
                Relationships: typeof postsRelationships;
            };
            rate_limits: {
                Row: RateLimitsRow;
                Insert: RateLimitsInsert;
                Update: RateLimitsUpdate;
                Relationships: typeof rateLimitsRelationships;
            };
            sessions: {
                Row: SessionsRow;
                Insert: SessionsInsert;
                Update: SessionsUpdate;
                Relationships: typeof sessionsRelationships;
            };
            site_collaborators: {
                Row: SiteCollaboratorsRow;
                Insert: SiteCollaboratorsInsert;
                Update: SiteCollaboratorsUpdate;
                Relationships: typeof siteCollaboratorsRelationships;
            };
            sites: {
                Row: SitesRow;
                Insert: SitesInsert;
                Update: SitesUpdate;
                Relationships: typeof sitesRelationships;
            };
            sync_metadata: {
                Row: SyncMetadataRow;
                Insert: SyncMetadataInsert;
                Update: SyncMetadataUpdate;
                Relationships: typeof syncMetadataRelationships;
            };
            user_devices: {
                Row: UserDevicesRow;
                Insert: UserDevicesInsert;
                Update: UserDevicesUpdate;
                Relationships: typeof userDevicesRelationships;
            };
            users: {
                Row: UsersRow;
                Insert: UsersInsert;
                Update: UsersUpdate;
                Relationships: typeof usersRelationships;
            };
        };
        Enums: DatabaseEnums;
    };
};
/**
 * Extract Row type for a table
 */
export type TableRow<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
/**
 * Extract Insert type for a table
 */
export type TableInsert<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert'];
/**
 * Extract Update type for a table
 */
export type TableUpdate<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update'];
/**
 * Extract Relationships for a table
 */
export type TableRelationships<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Relationships'];
//# sourceMappingURL=database.d.ts.map