/**
 * Generated Database Type for NeonDB
 *
 * This file is auto-generated by packages/db/src/types/generate.ts
 * DO NOT MODIFY MANUALLY - regenerate using: pnpm generate:types
 *
 * Generated: 2026-02-18T03:33:14.099Z
 *
 * This type matches the Supabase Database type structure for feature parity.
 * Tables are automatically discovered from packages/db/src/schema/*.ts
 */

import type {
  agentActions,
  agentContexts,
  agentMemories,
  auditLog,
  boardColumns,
  boards,
  codeProvenance,
  codeReviews,
  conversations,
  crdtOperations,
  failedAttempts,
  globalFooter,
  globalHeader,
  globalSettings,
  licenses,
  media,
  messages,
  nodeIdMappings,
  pageRevisions,
  pages,
  passwordResetTokens,
  posts,
  rateLimits,
  sessions,
  siteCollaborators,
  sites,
  syncMetadata,
  ticketComments,
  ticketLabelAssignments,
  ticketLabels,
  tickets,
  userDevices,
  users,
  waitlist,
  yjsDocuments,
} from '../schema/index.js'

// =============================================================================
// Table Type Inferences
// =============================================================================

// Agent Actions
export type AgentActionsRow = typeof agentActions.$inferSelect
export type AgentActionsInsert = typeof agentActions.$inferInsert
export type AgentActionsUpdate = Partial<AgentActionsInsert>

// Agent Contexts
export type AgentContextsRow = typeof agentContexts.$inferSelect
export type AgentContextsInsert = typeof agentContexts.$inferInsert
export type AgentContextsUpdate = Partial<AgentContextsInsert>

// Agent Memories
export type AgentMemoriesRow = typeof agentMemories.$inferSelect
export type AgentMemoriesInsert = typeof agentMemories.$inferInsert
export type AgentMemoriesUpdate = Partial<AgentMemoriesInsert>

// Audit Log
export type AuditLogRow = typeof auditLog.$inferSelect
export type AuditLogInsert = typeof auditLog.$inferInsert
export type AuditLogUpdate = Partial<AuditLogInsert>

// Board Columns
export type BoardColumnsRow = typeof boardColumns.$inferSelect
export type BoardColumnsInsert = typeof boardColumns.$inferInsert
export type BoardColumnsUpdate = Partial<BoardColumnsInsert>

// Boards
export type BoardsRow = typeof boards.$inferSelect
export type BoardsInsert = typeof boards.$inferInsert
export type BoardsUpdate = Partial<BoardsInsert>

// Code Provenance
export type CodeProvenanceRow = typeof codeProvenance.$inferSelect
export type CodeProvenanceInsert = typeof codeProvenance.$inferInsert
export type CodeProvenanceUpdate = Partial<CodeProvenanceInsert>

// Code Reviews
export type CodeReviewsRow = typeof codeReviews.$inferSelect
export type CodeReviewsInsert = typeof codeReviews.$inferInsert
export type CodeReviewsUpdate = Partial<CodeReviewsInsert>

// Conversations
export type ConversationsRow = typeof conversations.$inferSelect
export type ConversationsInsert = typeof conversations.$inferInsert
export type ConversationsUpdate = Partial<ConversationsInsert>

// Crdt Operations
export type CrdtOperationsRow = typeof crdtOperations.$inferSelect
export type CrdtOperationsInsert = typeof crdtOperations.$inferInsert
export type CrdtOperationsUpdate = Partial<CrdtOperationsInsert>

// Failed Attempts
export type FailedAttemptsRow = typeof failedAttempts.$inferSelect
export type FailedAttemptsInsert = typeof failedAttempts.$inferInsert
export type FailedAttemptsUpdate = Partial<FailedAttemptsInsert>

// Global Footer
export type GlobalFooterRow = typeof globalFooter.$inferSelect
export type GlobalFooterInsert = typeof globalFooter.$inferInsert
export type GlobalFooterUpdate = Partial<GlobalFooterInsert>

// Global Header
export type GlobalHeaderRow = typeof globalHeader.$inferSelect
export type GlobalHeaderInsert = typeof globalHeader.$inferInsert
export type GlobalHeaderUpdate = Partial<GlobalHeaderInsert>

// Global Settings
export type GlobalSettingsRow = typeof globalSettings.$inferSelect
export type GlobalSettingsInsert = typeof globalSettings.$inferInsert
export type GlobalSettingsUpdate = Partial<GlobalSettingsInsert>

// Licenses
export type LicensesRow = typeof licenses.$inferSelect
export type LicensesInsert = typeof licenses.$inferInsert
export type LicensesUpdate = Partial<LicensesInsert>

// Media
export type MediaRow = typeof media.$inferSelect
export type MediaInsert = typeof media.$inferInsert
export type MediaUpdate = Partial<MediaInsert>

// Messages
export type MessagesRow = typeof messages.$inferSelect
export type MessagesInsert = typeof messages.$inferInsert
export type MessagesUpdate = Partial<MessagesInsert>

// Node Id Mappings
export type NodeIdMappingsRow = typeof nodeIdMappings.$inferSelect
export type NodeIdMappingsInsert = typeof nodeIdMappings.$inferInsert
export type NodeIdMappingsUpdate = Partial<NodeIdMappingsInsert>

// Page Revisions
export type PageRevisionsRow = typeof pageRevisions.$inferSelect
export type PageRevisionsInsert = typeof pageRevisions.$inferInsert
export type PageRevisionsUpdate = Partial<PageRevisionsInsert>

// Pages
export type PagesRow = typeof pages.$inferSelect
export type PagesInsert = typeof pages.$inferInsert
export type PagesUpdate = Partial<PagesInsert>

// Password Reset Tokens
export type PasswordResetTokensRow = typeof passwordResetTokens.$inferSelect
export type PasswordResetTokensInsert = typeof passwordResetTokens.$inferInsert
export type PasswordResetTokensUpdate = Partial<PasswordResetTokensInsert>

// Posts
export type PostsRow = typeof posts.$inferSelect
export type PostsInsert = typeof posts.$inferInsert
export type PostsUpdate = Partial<PostsInsert>

// Rate Limits
export type RateLimitsRow = typeof rateLimits.$inferSelect
export type RateLimitsInsert = typeof rateLimits.$inferInsert
export type RateLimitsUpdate = Partial<RateLimitsInsert>

// Sessions
export type SessionsRow = typeof sessions.$inferSelect
export type SessionsInsert = typeof sessions.$inferInsert
export type SessionsUpdate = Partial<SessionsInsert>

// Site Collaborators
export type SiteCollaboratorsRow = typeof siteCollaborators.$inferSelect
export type SiteCollaboratorsInsert = typeof siteCollaborators.$inferInsert
export type SiteCollaboratorsUpdate = Partial<SiteCollaboratorsInsert>

// Sites
export type SitesRow = typeof sites.$inferSelect
export type SitesInsert = typeof sites.$inferInsert
export type SitesUpdate = Partial<SitesInsert>

// Sync Metadata
export type SyncMetadataRow = typeof syncMetadata.$inferSelect
export type SyncMetadataInsert = typeof syncMetadata.$inferInsert
export type SyncMetadataUpdate = Partial<SyncMetadataInsert>

// Ticket Comments
export type TicketCommentsRow = typeof ticketComments.$inferSelect
export type TicketCommentsInsert = typeof ticketComments.$inferInsert
export type TicketCommentsUpdate = Partial<TicketCommentsInsert>

// Ticket Label Assignments
export type TicketLabelAssignmentsRow = typeof ticketLabelAssignments.$inferSelect
export type TicketLabelAssignmentsInsert = typeof ticketLabelAssignments.$inferInsert
export type TicketLabelAssignmentsUpdate = Partial<TicketLabelAssignmentsInsert>

// Ticket Labels
export type TicketLabelsRow = typeof ticketLabels.$inferSelect
export type TicketLabelsInsert = typeof ticketLabels.$inferInsert
export type TicketLabelsUpdate = Partial<TicketLabelsInsert>

// Tickets
export type TicketsRow = typeof tickets.$inferSelect
export type TicketsInsert = typeof tickets.$inferInsert
export type TicketsUpdate = Partial<TicketsInsert>

// User Devices
export type UserDevicesRow = typeof userDevices.$inferSelect
export type UserDevicesInsert = typeof userDevices.$inferInsert
export type UserDevicesUpdate = Partial<UserDevicesInsert>

// Users
export type UsersRow = typeof users.$inferSelect
export type UsersInsert = typeof users.$inferInsert
export type UsersUpdate = Partial<UsersInsert>

// Waitlist
export type WaitlistRow = typeof waitlist.$inferSelect
export type WaitlistInsert = typeof waitlist.$inferInsert
export type WaitlistUpdate = Partial<WaitlistInsert>

// Yjs Documents
export type YjsDocumentsRow = typeof yjsDocuments.$inferSelect
export type YjsDocumentsInsert = typeof yjsDocuments.$inferInsert
export type YjsDocumentsUpdate = Partial<YjsDocumentsInsert>

// =============================================================================
// Relationships
// =============================================================================

/**
 * Relationship type matching Supabase structure
 */
export type Relationship = {
  foreignKeyName: string
  columns: string[]
  isOneToOne: boolean
  referencedRelation: string
  referencedColumns: string[]
}

/**
 * Relationship definitions matching Supabase structure (array format)
 * These are derived from Drizzle relations in packages/db/src/schema/index.ts
 * 
 * Note: isOneToOne is determined by Drizzle relation type:
 * - one() = isOneToOne: true
 * - many() = isOneToOne: false
 */
export type DatabaseRelationships = {
  agentActions: Relationship[]
  agentContexts: Relationship[]
  agentMemories: Relationship[]
  auditLog: Relationship[]
  boardColumns: Relationship[]
  boards: Relationship[]
  codeProvenance: Relationship[]
  codeReviews: Relationship[]
  conversations: Relationship[]
  crdtOperations: Relationship[]
  failedAttempts: Relationship[]
  globalFooter: Relationship[]
  globalHeader: Relationship[]
  globalSettings: Relationship[]
  licenses: Relationship[]
  media: Relationship[]
  messages: Relationship[]
  nodeIdMappings: Relationship[]
  pageRevisions: Relationship[]
  pages: Relationship[]
  passwordResetTokens: Relationship[]
  posts: Relationship[]
  rateLimits: Relationship[]
  sessions: Relationship[]
  siteCollaborators: Relationship[]
  sites: Relationship[]
  syncMetadata: Relationship[]
  ticketComments: Relationship[]
  ticketLabelAssignments: Relationship[]
  ticketLabels: Relationship[]
  tickets: Relationship[]
  userDevices: Relationship[]
  users: Relationship[]
  waitlist: Relationship[]
  yjsDocuments: Relationship[]
}

// AgentActions relationships
export const agentActionsRelationships = [
  { foreignKeyName: 'agent_actions_conversation_id_conversations_id_fk', columns: ['conversation_id'], isOneToOne: true, referencedRelation: 'conversations', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// AgentContexts relationships
export const agentContextsRelationships: readonly Relationship[] = []

// AgentMemories relationships
export const agentMemoriesRelationships = [
  { foreignKeyName: 'agent_memories_site_id_sites_id_fk', columns: ['site_id'], isOneToOne: true, referencedRelation: 'sites', referencedColumns: ['id'] },
  { foreignKeyName: 'agent_memories_verified_by_users_id_fk', columns: ['verified_by'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// AuditLog relationships
export const auditLogRelationships: readonly Relationship[] = []

// BoardColumns relationships
export const boardColumnsRelationships = [
  { foreignKeyName: 'board_columns_board_id_boards_id_fk', columns: ['board_id'], isOneToOne: true, referencedRelation: 'boards', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// Boards relationships
export const boardsRelationships = [
  { foreignKeyName: 'boards_owner_id_users_id_fk', columns: ['owner_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// CodeProvenance relationships
export const codeProvenanceRelationships = [
  { foreignKeyName: 'code_provenance_reviewed_by_users_id_fk', columns: ['reviewed_by'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// CodeReviews relationships
export const codeReviewsRelationships = [
  { foreignKeyName: 'code_reviews_provenance_id_code_provenance_id_fk', columns: ['provenance_id'], isOneToOne: true, referencedRelation: 'code_provenance', referencedColumns: ['id'] },
  { foreignKeyName: 'code_reviews_reviewer_id_users_id_fk', columns: ['reviewer_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// Conversations relationships
export const conversationsRelationships = [
  { foreignKeyName: 'conversations_user_id_users_id_fk', columns: ['user_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// CrdtOperations relationships
export const crdtOperationsRelationships: readonly Relationship[] = []

// FailedAttempts relationships
export const failedAttemptsRelationships: readonly Relationship[] = []

// GlobalFooter relationships
export const globalFooterRelationships: readonly Relationship[] = []

// GlobalHeader relationships
export const globalHeaderRelationships: readonly Relationship[] = []

// GlobalSettings relationships
export const globalSettingsRelationships: readonly Relationship[] = []

// Licenses relationships
export const licensesRelationships = [
  { foreignKeyName: 'licenses_user_id_users_id_fk', columns: ['user_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// Media relationships
export const mediaRelationships = [
  { foreignKeyName: 'media_uploaded_by_users_id_fk', columns: ['uploaded_by'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// Messages relationships
export const messagesRelationships: readonly Relationship[] = []

// NodeIdMappings relationships
export const nodeIdMappingsRelationships: readonly Relationship[] = []

// PageRevisions relationships
export const pageRevisionsRelationships = [
  { foreignKeyName: 'page_revisions_page_id_pages_id_fk', columns: ['page_id'], isOneToOne: true, referencedRelation: 'pages', referencedColumns: ['id'] },
  { foreignKeyName: 'page_revisions_created_by_users_id_fk', columns: ['created_by'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// Pages relationships
export const pagesRelationships = [
  { foreignKeyName: 'pages_site_id_sites_id_fk', columns: ['site_id'], isOneToOne: true, referencedRelation: 'sites', referencedColumns: ['id'] },
  { foreignKeyName: 'pages_parent_id_pages_id_fk', columns: ['parent_id'], isOneToOne: true, referencedRelation: 'pages', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// PasswordResetTokens relationships
export const passwordResetTokensRelationships = [
  { foreignKeyName: 'password_reset_tokens_user_id_users_id_fk', columns: ['user_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// Posts relationships
export const postsRelationships = [
  { foreignKeyName: 'posts_author_id_users_id_fk', columns: ['author_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
  { foreignKeyName: 'posts_featured_image_id_media_id_fk', columns: ['featured_image_id'], isOneToOne: true, referencedRelation: 'media', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// RateLimits relationships
export const rateLimitsRelationships: readonly Relationship[] = []

// Sessions relationships
export const sessionsRelationships = [
  { foreignKeyName: 'sessions_user_id_users_id_fk', columns: ['user_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// SiteCollaborators relationships
export const siteCollaboratorsRelationships = [
  { foreignKeyName: 'site_collaborators_site_id_sites_id_fk', columns: ['site_id'], isOneToOne: true, referencedRelation: 'sites', referencedColumns: ['id'] },
  { foreignKeyName: 'site_collaborators_user_id_users_id_fk', columns: ['user_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
  { foreignKeyName: 'site_collaborators_added_by_users_id_fk', columns: ['added_by'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// Sites relationships
export const sitesRelationships = [
  { foreignKeyName: 'sites_owner_id_users_id_fk', columns: ['owner_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// SyncMetadata relationships
export const syncMetadataRelationships: readonly Relationship[] = []

// TicketComments relationships
export const ticketCommentsRelationships = [
  { foreignKeyName: 'ticket_comments_ticket_id_tickets_id_fk', columns: ['ticket_id'], isOneToOne: true, referencedRelation: 'tickets', referencedColumns: ['id'] },
  { foreignKeyName: 'ticket_comments_author_id_users_id_fk', columns: ['author_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// TicketLabelAssignments relationships
export const ticketLabelAssignmentsRelationships = [
  { foreignKeyName: 'ticket_label_assignments_ticket_id_tickets_id_fk', columns: ['ticket_id'], isOneToOne: true, referencedRelation: 'tickets', referencedColumns: ['id'] },
  { foreignKeyName: 'ticket_label_assignments_label_id_ticket_labels_id_fk', columns: ['label_id'], isOneToOne: true, referencedRelation: 'ticket_labels', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// TicketLabels relationships
export const ticketLabelsRelationships: readonly Relationship[] = []

// Tickets relationships
export const ticketsRelationships = [
  { foreignKeyName: 'tickets_board_id_boards_id_fk', columns: ['board_id'], isOneToOne: true, referencedRelation: 'boards', referencedColumns: ['id'] },
  { foreignKeyName: 'tickets_column_id_board_columns_id_fk', columns: ['column_id'], isOneToOne: true, referencedRelation: 'board_columns', referencedColumns: ['id'] },
  { foreignKeyName: 'tickets_assignee_id_users_id_fk', columns: ['assignee_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
  { foreignKeyName: 'tickets_reporter_id_users_id_fk', columns: ['reporter_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
  { foreignKeyName: 'tickets_parent_ticket_id_tickets_id_fk', columns: ['parent_ticket_id'], isOneToOne: true, referencedRelation: 'tickets', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// UserDevices relationships
export const userDevicesRelationships: readonly Relationship[] = []

// Users relationships
export const usersRelationships: readonly Relationship[] = []

// Waitlist relationships
export const waitlistRelationships: readonly Relationship[] = []

// YjsDocuments relationships
export const yjsDocumentsRelationships: readonly Relationship[] = []


// =============================================================================
// Enums
// =============================================================================

/**
 * Database enums (currently none, but structure ready for future enums)
 * When enums are added to Drizzle schemas, they will be included here
 */
export interface DatabaseEnums {
  // Enums will be added here as they are defined in the schema
}

// =============================================================================
// Main Database Type (Supabase-compatible structure)
// =============================================================================

/**
 * Centralized Database type matching Supabase structure
 *
 * This provides feature parity with Supabase's Database type:
 * - Full type safety for all tables
 * - Row, Insert, Update types for each table
 * - Relationships information
 * - Enums support
 *
 * @example
 * ```typescript
 * import type { Database } from '@revealui/db/types'
 *
 * type User = Database['public']['Tables']['users']['Row']
 * type NewUser = Database['public']['Tables']['users']['Insert']
 * ```
 */
export type Database = {
  public: {
    Tables: {
      agent_actions: {
        Row: AgentActionsRow
        Insert: AgentActionsInsert
        Update: AgentActionsUpdate
        Relationships: typeof agentActionsRelationships
      }
      agent_contexts: {
        Row: AgentContextsRow
        Insert: AgentContextsInsert
        Update: AgentContextsUpdate
        Relationships: typeof agentContextsRelationships
      }
      agent_memories: {
        Row: AgentMemoriesRow
        Insert: AgentMemoriesInsert
        Update: AgentMemoriesUpdate
        Relationships: typeof agentMemoriesRelationships
      }
      audit_log: {
        Row: AuditLogRow
        Insert: AuditLogInsert
        Update: AuditLogUpdate
        Relationships: typeof auditLogRelationships
      }
      board_columns: {
        Row: BoardColumnsRow
        Insert: BoardColumnsInsert
        Update: BoardColumnsUpdate
        Relationships: typeof boardColumnsRelationships
      }
      boards: {
        Row: BoardsRow
        Insert: BoardsInsert
        Update: BoardsUpdate
        Relationships: typeof boardsRelationships
      }
      code_provenance: {
        Row: CodeProvenanceRow
        Insert: CodeProvenanceInsert
        Update: CodeProvenanceUpdate
        Relationships: typeof codeProvenanceRelationships
      }
      code_reviews: {
        Row: CodeReviewsRow
        Insert: CodeReviewsInsert
        Update: CodeReviewsUpdate
        Relationships: typeof codeReviewsRelationships
      }
      conversations: {
        Row: ConversationsRow
        Insert: ConversationsInsert
        Update: ConversationsUpdate
        Relationships: typeof conversationsRelationships
      }
      crdt_operations: {
        Row: CrdtOperationsRow
        Insert: CrdtOperationsInsert
        Update: CrdtOperationsUpdate
        Relationships: typeof crdtOperationsRelationships
      }
      failed_attempts: {
        Row: FailedAttemptsRow
        Insert: FailedAttemptsInsert
        Update: FailedAttemptsUpdate
        Relationships: typeof failedAttemptsRelationships
      }
      global_footer: {
        Row: GlobalFooterRow
        Insert: GlobalFooterInsert
        Update: GlobalFooterUpdate
        Relationships: typeof globalFooterRelationships
      }
      global_header: {
        Row: GlobalHeaderRow
        Insert: GlobalHeaderInsert
        Update: GlobalHeaderUpdate
        Relationships: typeof globalHeaderRelationships
      }
      global_settings: {
        Row: GlobalSettingsRow
        Insert: GlobalSettingsInsert
        Update: GlobalSettingsUpdate
        Relationships: typeof globalSettingsRelationships
      }
      licenses: {
        Row: LicensesRow
        Insert: LicensesInsert
        Update: LicensesUpdate
        Relationships: typeof licensesRelationships
      }
      media: {
        Row: MediaRow
        Insert: MediaInsert
        Update: MediaUpdate
        Relationships: typeof mediaRelationships
      }
      messages: {
        Row: MessagesRow
        Insert: MessagesInsert
        Update: MessagesUpdate
        Relationships: typeof messagesRelationships
      }
      node_id_mappings: {
        Row: NodeIdMappingsRow
        Insert: NodeIdMappingsInsert
        Update: NodeIdMappingsUpdate
        Relationships: typeof nodeIdMappingsRelationships
      }
      page_revisions: {
        Row: PageRevisionsRow
        Insert: PageRevisionsInsert
        Update: PageRevisionsUpdate
        Relationships: typeof pageRevisionsRelationships
      }
      pages: {
        Row: PagesRow
        Insert: PagesInsert
        Update: PagesUpdate
        Relationships: typeof pagesRelationships
      }
      password_reset_tokens: {
        Row: PasswordResetTokensRow
        Insert: PasswordResetTokensInsert
        Update: PasswordResetTokensUpdate
        Relationships: typeof passwordResetTokensRelationships
      }
      posts: {
        Row: PostsRow
        Insert: PostsInsert
        Update: PostsUpdate
        Relationships: typeof postsRelationships
      }
      rate_limits: {
        Row: RateLimitsRow
        Insert: RateLimitsInsert
        Update: RateLimitsUpdate
        Relationships: typeof rateLimitsRelationships
      }
      sessions: {
        Row: SessionsRow
        Insert: SessionsInsert
        Update: SessionsUpdate
        Relationships: typeof sessionsRelationships
      }
      site_collaborators: {
        Row: SiteCollaboratorsRow
        Insert: SiteCollaboratorsInsert
        Update: SiteCollaboratorsUpdate
        Relationships: typeof siteCollaboratorsRelationships
      }
      sites: {
        Row: SitesRow
        Insert: SitesInsert
        Update: SitesUpdate
        Relationships: typeof sitesRelationships
      }
      sync_metadata: {
        Row: SyncMetadataRow
        Insert: SyncMetadataInsert
        Update: SyncMetadataUpdate
        Relationships: typeof syncMetadataRelationships
      }
      ticket_comments: {
        Row: TicketCommentsRow
        Insert: TicketCommentsInsert
        Update: TicketCommentsUpdate
        Relationships: typeof ticketCommentsRelationships
      }
      ticket_label_assignments: {
        Row: TicketLabelAssignmentsRow
        Insert: TicketLabelAssignmentsInsert
        Update: TicketLabelAssignmentsUpdate
        Relationships: typeof ticketLabelAssignmentsRelationships
      }
      ticket_labels: {
        Row: TicketLabelsRow
        Insert: TicketLabelsInsert
        Update: TicketLabelsUpdate
        Relationships: typeof ticketLabelsRelationships
      }
      tickets: {
        Row: TicketsRow
        Insert: TicketsInsert
        Update: TicketsUpdate
        Relationships: typeof ticketsRelationships
      }
      user_devices: {
        Row: UserDevicesRow
        Insert: UserDevicesInsert
        Update: UserDevicesUpdate
        Relationships: typeof userDevicesRelationships
      }
      users: {
        Row: UsersRow
        Insert: UsersInsert
        Update: UsersUpdate
        Relationships: typeof usersRelationships
      }
      waitlist: {
        Row: WaitlistRow
        Insert: WaitlistInsert
        Update: WaitlistUpdate
        Relationships: typeof waitlistRelationships
      }
      yjs_documents: {
        Row: YjsDocumentsRow
        Insert: YjsDocumentsInsert
        Update: YjsDocumentsUpdate
        Relationships: typeof yjsDocumentsRelationships
      }
    }
    Enums: DatabaseEnums
  }
}

// =============================================================================
// Type Utilities (for convenience)
// =============================================================================

/**
 * Extract Row type for a table
 */
export type TableRow<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

/**
 * Extract Insert type for a table
 */
export type TableInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']

/**
 * Extract Update type for a table
 */
export type TableUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']

/**
 * Extract Relationships for a table
 */
export type TableRelationships<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Relationships']
