/**
 * Generated Database Type for NeonDB
 *
 * This file is auto-generated by packages/db/src/types/generate.ts
 * DO NOT MODIFY MANUALLY - regenerate using: pnpm generate:types
 *
 * Generated: 2026-01-16T03:11:22.290Z
 *
 * This type matches the Supabase Database type structure for feature parity.
 * Tables are automatically discovered from packages/db/src/core/*.ts
 */

import type {
  agentActions,
  agentContexts,
  agentMemories,
  conversations,
  crdtOperations,
  failedAttempts,
  globalFooter,
  globalHeader,
  globalSettings,
  media,
  nodeIdMappings,
  pageRevisions,
  pages,
  posts,
  rateLimits,
  sessions,
  siteCollaborators,
  sites,
  users,
} from '../core/index.js'

// =============================================================================
// Table Type Inferences
// =============================================================================

// Agent Actions
export type AgentActionsRow = typeof agentActions.$inferSelect
export type AgentActionsInsert = typeof agentActions.$inferInsert
export type AgentActionsUpdate = Partial<AgentActionsInsert>

// Agent Contexts
export type AgentContextsRow = typeof agentContexts.$inferSelect
export type AgentContextsInsert = typeof agentContexts.$inferInsert
export type AgentContextsUpdate = Partial<AgentContextsInsert>

// Agent Memories
export type AgentMemoriesRow = typeof agentMemories.$inferSelect
export type AgentMemoriesInsert = typeof agentMemories.$inferInsert
export type AgentMemoriesUpdate = Partial<AgentMemoriesInsert>

// Conversations
export type ConversationsRow = typeof conversations.$inferSelect
export type ConversationsInsert = typeof conversations.$inferInsert
export type ConversationsUpdate = Partial<ConversationsInsert>

// Crdt Operations
export type CrdtOperationsRow = typeof crdtOperations.$inferSelect
export type CrdtOperationsInsert = typeof crdtOperations.$inferInsert
export type CrdtOperationsUpdate = Partial<CrdtOperationsInsert>

// Failed Attempts
export type FailedAttemptsRow = typeof failedAttempts.$inferSelect
export type FailedAttemptsInsert = typeof failedAttempts.$inferInsert
export type FailedAttemptsUpdate = Partial<FailedAttemptsInsert>

// Global Footer
export type GlobalFooterRow = typeof globalFooter.$inferSelect
export type GlobalFooterInsert = typeof globalFooter.$inferInsert
export type GlobalFooterUpdate = Partial<GlobalFooterInsert>

// Global Header
export type GlobalHeaderRow = typeof globalHeader.$inferSelect
export type GlobalHeaderInsert = typeof globalHeader.$inferInsert
export type GlobalHeaderUpdate = Partial<GlobalHeaderInsert>

// Global Settings
export type GlobalSettingsRow = typeof globalSettings.$inferSelect
export type GlobalSettingsInsert = typeof globalSettings.$inferInsert
export type GlobalSettingsUpdate = Partial<GlobalSettingsInsert>

// Media
export type MediaRow = typeof media.$inferSelect
export type MediaInsert = typeof media.$inferInsert
export type MediaUpdate = Partial<MediaInsert>

// Node Id Mappings
export type NodeIdMappingsRow = typeof nodeIdMappings.$inferSelect
export type NodeIdMappingsInsert = typeof nodeIdMappings.$inferInsert
export type NodeIdMappingsUpdate = Partial<NodeIdMappingsInsert>

// Page Revisions
export type PageRevisionsRow = typeof pageRevisions.$inferSelect
export type PageRevisionsInsert = typeof pageRevisions.$inferInsert
export type PageRevisionsUpdate = Partial<PageRevisionsInsert>

// Pages
export type PagesRow = typeof pages.$inferSelect
export type PagesInsert = typeof pages.$inferInsert
export type PagesUpdate = Partial<PagesInsert>

// Posts
export type PostsRow = typeof posts.$inferSelect
export type PostsInsert = typeof posts.$inferInsert
export type PostsUpdate = Partial<PostsInsert>

// Rate Limits
export type RateLimitsRow = typeof rateLimits.$inferSelect
export type RateLimitsInsert = typeof rateLimits.$inferInsert
export type RateLimitsUpdate = Partial<RateLimitsInsert>

// Sessions
export type SessionsRow = typeof sessions.$inferSelect
export type SessionsInsert = typeof sessions.$inferInsert
export type SessionsUpdate = Partial<SessionsInsert>

// Site Collaborators
export type SiteCollaboratorsRow = typeof siteCollaborators.$inferSelect
export type SiteCollaboratorsInsert = typeof siteCollaborators.$inferInsert
export type SiteCollaboratorsUpdate = Partial<SiteCollaboratorsInsert>

// Sites
export type SitesRow = typeof sites.$inferSelect
export type SitesInsert = typeof sites.$inferInsert
export type SitesUpdate = Partial<SitesInsert>

// Users
export type UsersRow = typeof users.$inferSelect
export type UsersInsert = typeof users.$inferInsert
export type UsersUpdate = Partial<UsersInsert>

// =============================================================================
// Relationships
// =============================================================================

/**
 * Relationship type matching Supabase structure
 */
export type Relationship = {
  foreignKeyName: string
  columns: string[]
  isOneToOne: boolean
  referencedRelation: string
  referencedColumns: string[]
}

/**
 * Relationship definitions matching Supabase structure (array format)
 * These are derived from Drizzle relations in packages/db/src/core/index.ts
 * 
 * Note: isOneToOne is determined by Drizzle relation type:
 * - one() = isOneToOne: true
 * - many() = isOneToOne: false
 */
export type DatabaseRelationships = {
  agentActions: Relationship[]
  agentContexts: Relationship[]
  agentMemories: Relationship[]
  conversations: Relationship[]
  crdtOperations: Relationship[]
  failedAttempts: Relationship[]
  globalFooter: Relationship[]
  globalHeader: Relationship[]
  globalSettings: Relationship[]
  media: Relationship[]
  nodeIdMappings: Relationship[]
  pageRevisions: Relationship[]
  pages: Relationship[]
  posts: Relationship[]
  rateLimits: Relationship[]
  sessions: Relationship[]
  siteCollaborators: Relationship[]
  sites: Relationship[]
  users: Relationship[]
}

// AgentActions relationships
export const agentActionsRelationships = [
  { foreignKeyName: 'agent_actions_conversation_id_conversations_id_fk', columns: ['conversation_id'], isOneToOne: true, referencedRelation: 'conversations', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// AgentContexts relationships
export const agentContextsRelationships: readonly Relationship[] = []

// AgentMemories relationships
export const agentMemoriesRelationships = [
  { foreignKeyName: 'agent_memories_site_id_sites_id_fk', columns: ['site_id'], isOneToOne: true, referencedRelation: 'sites', referencedColumns: ['id'] },
  { foreignKeyName: 'agent_memories_verified_by_users_id_fk', columns: ['verified_by'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// Conversations relationships
export const conversationsRelationships = [
  { foreignKeyName: 'conversations_user_id_users_id_fk', columns: ['user_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// CrdtOperations relationships
export const crdtOperationsRelationships: readonly Relationship[] = []

// FailedAttempts relationships
export const failedAttemptsRelationships: readonly Relationship[] = []

// GlobalFooter relationships
export const globalFooterRelationships: readonly Relationship[] = []

// GlobalHeader relationships
export const globalHeaderRelationships: readonly Relationship[] = []

// GlobalSettings relationships
export const globalSettingsRelationships: readonly Relationship[] = []

// Media relationships
export const mediaRelationships = [
  { foreignKeyName: 'media_uploaded_by_users_id_fk', columns: ['uploaded_by'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// NodeIdMappings relationships
export const nodeIdMappingsRelationships: readonly Relationship[] = []

// PageRevisions relationships
export const pageRevisionsRelationships = [
  { foreignKeyName: 'page_revisions_page_id_pages_id_fk', columns: ['page_id'], isOneToOne: true, referencedRelation: 'pages', referencedColumns: ['id'] },
  { foreignKeyName: 'page_revisions_created_by_users_id_fk', columns: ['created_by'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// Pages relationships
export const pagesRelationships = [
  { foreignKeyName: 'pages_site_id_sites_id_fk', columns: ['site_id'], isOneToOne: true, referencedRelation: 'sites', referencedColumns: ['id'] },
  { foreignKeyName: 'pages_parent_id_pages_id_fk', columns: ['parent_id'], isOneToOne: true, referencedRelation: 'pages', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// Posts relationships
export const postsRelationships = [
  { foreignKeyName: 'posts_author_id_users_id_fk', columns: ['author_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
  { foreignKeyName: 'posts_featured_image_id_media_id_fk', columns: ['featured_image_id'], isOneToOne: true, referencedRelation: 'media', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// RateLimits relationships
export const rateLimitsRelationships: readonly Relationship[] = []

// Sessions relationships
export const sessionsRelationships = [
  { foreignKeyName: 'sessions_user_id_users_id_fk', columns: ['user_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// SiteCollaborators relationships
export const siteCollaboratorsRelationships = [
  { foreignKeyName: 'site_collaborators_site_id_sites_id_fk', columns: ['site_id'], isOneToOne: true, referencedRelation: 'sites', referencedColumns: ['id'] },
  { foreignKeyName: 'site_collaborators_user_id_users_id_fk', columns: ['user_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
  { foreignKeyName: 'site_collaborators_added_by_users_id_fk', columns: ['added_by'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// Sites relationships
export const sitesRelationships = [
  { foreignKeyName: 'sites_owner_id_users_id_fk', columns: ['owner_id'], isOneToOne: true, referencedRelation: 'users', referencedColumns: ['id'] },
] as const satisfies readonly Relationship[]

// Users relationships
export const usersRelationships: readonly Relationship[] = []


// =============================================================================
// Enums
// =============================================================================

/**
 * Database enums (currently none, but structure ready for future enums)
 * When enums are added to Drizzle schemas, they will be included here
 */
export interface DatabaseEnums {
  // Enums will be added here as they are defined in the schema
}

// =============================================================================
// Main Database Type (Supabase-compatible structure)
// =============================================================================

/**
 * Centralized Database type matching Supabase structure
 *
 * This provides feature parity with Supabase's Database type:
 * - Full type safety for all tables
 * - Row, Insert, Update types for each table
 * - Relationships information
 * - Enums support
 *
 * @example
 * ```typescript
 * import type { Database } from '@revealui/db/types'
 *
 * type User = Database['public']['Tables']['users']['Row']
 * type NewUser = Database['public']['Tables']['users']['Insert']
 * ```
 */
export type Database = {
  public: {
    Tables: {
      agent_actions: {
        Row: AgentActionsRow
        Insert: AgentActionsInsert
        Update: AgentActionsUpdate
        Relationships: typeof agentActionsRelationships
      }
      agent_contexts: {
        Row: AgentContextsRow
        Insert: AgentContextsInsert
        Update: AgentContextsUpdate
        Relationships: typeof agentContextsRelationships
      }
      agent_memories: {
        Row: AgentMemoriesRow
        Insert: AgentMemoriesInsert
        Update: AgentMemoriesUpdate
        Relationships: typeof agentMemoriesRelationships
      }
      conversations: {
        Row: ConversationsRow
        Insert: ConversationsInsert
        Update: ConversationsUpdate
        Relationships: typeof conversationsRelationships
      }
      crdt_operations: {
        Row: CrdtOperationsRow
        Insert: CrdtOperationsInsert
        Update: CrdtOperationsUpdate
        Relationships: typeof crdtOperationsRelationships
      }
      failed_attempts: {
        Row: FailedAttemptsRow
        Insert: FailedAttemptsInsert
        Update: FailedAttemptsUpdate
        Relationships: typeof failedAttemptsRelationships
      }
      global_footer: {
        Row: GlobalFooterRow
        Insert: GlobalFooterInsert
        Update: GlobalFooterUpdate
        Relationships: typeof globalFooterRelationships
      }
      global_header: {
        Row: GlobalHeaderRow
        Insert: GlobalHeaderInsert
        Update: GlobalHeaderUpdate
        Relationships: typeof globalHeaderRelationships
      }
      global_settings: {
        Row: GlobalSettingsRow
        Insert: GlobalSettingsInsert
        Update: GlobalSettingsUpdate
        Relationships: typeof globalSettingsRelationships
      }
      media: {
        Row: MediaRow
        Insert: MediaInsert
        Update: MediaUpdate
        Relationships: typeof mediaRelationships
      }
      node_id_mappings: {
        Row: NodeIdMappingsRow
        Insert: NodeIdMappingsInsert
        Update: NodeIdMappingsUpdate
        Relationships: typeof nodeIdMappingsRelationships
      }
      page_revisions: {
        Row: PageRevisionsRow
        Insert: PageRevisionsInsert
        Update: PageRevisionsUpdate
        Relationships: typeof pageRevisionsRelationships
      }
      pages: {
        Row: PagesRow
        Insert: PagesInsert
        Update: PagesUpdate
        Relationships: typeof pagesRelationships
      }
      posts: {
        Row: PostsRow
        Insert: PostsInsert
        Update: PostsUpdate
        Relationships: typeof postsRelationships
      }
      rate_limits: {
        Row: RateLimitsRow
        Insert: RateLimitsInsert
        Update: RateLimitsUpdate
        Relationships: typeof rateLimitsRelationships
      }
      sessions: {
        Row: SessionsRow
        Insert: SessionsInsert
        Update: SessionsUpdate
        Relationships: typeof sessionsRelationships
      }
      site_collaborators: {
        Row: SiteCollaboratorsRow
        Insert: SiteCollaboratorsInsert
        Update: SiteCollaboratorsUpdate
        Relationships: typeof siteCollaboratorsRelationships
      }
      sites: {
        Row: SitesRow
        Insert: SitesInsert
        Update: SitesUpdate
        Relationships: typeof sitesRelationships
      }
      users: {
        Row: UsersRow
        Insert: UsersInsert
        Update: UsersUpdate
        Relationships: typeof usersRelationships
      }
    }
    Enums: DatabaseEnums
  }
}

// =============================================================================
// Type Utilities (for convenience)
// =============================================================================

/**
 * Extract Row type for a table
 */
export type TableRow<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

/**
 * Extract Insert type for a table
 */
export type TableInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']

/**
 * Extract Update type for a table
 */
export type TableUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']

/**
 * Extract Relationships for a table
 */
export type TableRelationships<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Relationships']
