/**
 * Verification Requirements for Documentation
 * Enforces truth-only claims in all documentation
 *
 * This module defines rules to prevent automated systems from making
 * false claims about completion, readiness, or quality without human verification.
 *
 * @dependencies
 * - None (standalone validation rules and utilities)
 */

export const VERIFICATION_RULES = {
  // No automated report can claim these without human verification
  forbiddenAutomatedClaims: [
    /✅\s*(COMPLETE|VERIFIED|SUCCESS|RESOLVED)/i,
    /ready for (staging|production)/i,
    /A[+-]?\s*\([0-9.]+\/10\)/i, // Grades like "A+ (9.8/10)"
    /B[+-]?\s*\([0-9.]+\/10\)/i, // Grades like "B- (7.5/10)"
    /[0-9]+(\.[0-9]+)?%\s*pass rate/i, // Pass rates like "96.7% pass rate"
    /production[- ]ready/i,
    /enterprise[- ]grade/i,
    /comprehensive tests/i,
    /fully tested/i,
    /all tests pass/i,
    /100%\s*(coverage|tested)/i,
  ],

  // All automated reports must include this disclaimer
  requiredDisclaimer: '⚠️ AUTOMATED ANALYSIS ONLY - NOT VERIFIED BY HUMANS',

  // Human review required fields for any "COMPLETE" claim
  requiredHumanReview: {
    reviewDate: 'ISO date string (YYYY-MM-DD)',
    reviewedBy: 'Name and email of reviewer',
    approvalStatus: 'approved | rejected | pending',
    verificationMethod: 'Description of how claims were verified',
    evidenceLinks: 'Links to test results, security scans, etc.',
    comments: 'Reviewer comments',
  },

  // Actual verification checklist
  verificationChecklist: [
    'Actual test suite run with results captured',
    'Actual code analysis performed (not pattern matching)',
    'Actual security scan completed',
    'Manual code review performed',
    'Stakeholder approval obtained',
  ],
}

/**
 * Validate that a document meets verification requirements
 */
export function validateVerificationClaims(
  content: string,
  filePath: string,
): { valid: boolean; errors: string[] } {
  const errors: string[] = []

  // Check for forbidden claims in automated content
  const isAutomated =
    content.includes('Auto-generated') ||
    content.includes('Generated by') ||
    content.includes('automation system') ||
    filePath.includes('generated') ||
    filePath.includes('-review-validated') ||
    filePath.includes('assessment-report')

  if (isAutomated) {
    // Check each forbidden pattern
    for (const pattern of VERIFICATION_RULES.forbiddenAutomatedClaims) {
      if (pattern.test(content)) {
        errors.push(
          `Automated report contains forbidden claim: ${pattern.source.replace(/\\/g, '')}`,
        )
      }
    }

    // Check for required disclaimer
    if (!content.includes(VERIFICATION_RULES.requiredDisclaimer)) {
      errors.push('Missing required disclaimer for automated report')
    }
  }

  // If document claims completion, check for human review
  if (/COMPLETE|VERIFIED|RESOLVED/i.test(content)) {
    const hasHumanReview =
      /reviewDate.*:.*[0-9]{4}-[0-9]{2}-[0-9]{2}/.test(content) &&
      /reviewedBy.*:.*\w+/.test(content)

    if (!hasHumanReview) {
      errors.push('Document claims completion without human review section')
    }
  }

  // Check for grade inflation without evidence
  const gradeMatch = content.match(/([A-F][+-]?)\s*\(([0-9.]+)\/10\)/i)
  if (gradeMatch && !content.includes('Human Review')) {
    const grade = gradeMatch[1]
    const score = parseFloat(gradeMatch[2])

    // Grades of A or B require human verification
    if (grade.toUpperCase().startsWith('A') || grade.toUpperCase().startsWith('B')) {
      if (score >= 7.0 && !content.includes('reviewedBy')) {
        errors.push(`Grade ${grade} (${score}/10) requires human verification`)
      }
    }
  }

  return {
    valid: errors.length === 0,
    errors,
  }
}

/**
 * Check if a file path indicates an automated report
 */
export function isAutomatedReport(filePath: string): boolean {
  const automatedPatterns = [
    /generated/i,
    /review-validated/i,
    /assessment-report/i,
    /audit-results/i,
    /-COMPLETE\.md$/i,
    /VERIFICATION.*REPORT/i,
  ]

  return automatedPatterns.some((pattern) => pattern.test(filePath))
}

/**
 * Generate human review template
 */
export function generateHumanReviewTemplate(): string {
  return `
## Human Review

**Status:** ⚠️ PENDING HUMAN REVIEW

**Review Checklist:**
- [ ] Manual code review completed
- [ ] Manual testing performed
- [ ] Security review completed
- [ ] Test coverage verified
- [ ] Documentation updated
- [ ] Stakeholder approval obtained

**Review Details:**
- **Review Date:** YYYY-MM-DD
- **Reviewed By:** Name <email@example.com>
- **Approval Status:** pending | approved | rejected
- **Verification Method:** [Describe how claims were verified]
- **Evidence Links:** [Links to test results, security scans, etc.]
- **Comments:** [Reviewer comments and notes]
`
}

/**
 * Validate documentation claim against actual evidence
 */
export interface ClaimEvidence {
  claim: string
  evidence: string[]
  verified: boolean
  notes?: string
}

export function validateClaimWithEvidence(claim: ClaimEvidence): {
  valid: boolean
  reason: string
} {
  if (!claim.verified) {
    return {
      valid: false,
      reason: 'Claim not marked as verified',
    }
  }

  if (!claim.evidence || claim.evidence.length === 0) {
    return {
      valid: false,
      reason: 'No evidence provided for claim',
    }
  }

  // Check that evidence is specific (not just generic statements)
  const genericEvidence = ['manual review', 'checked', 'verified', 'tested']
  const hasSpecificEvidence = claim.evidence.some(
    (e) => !genericEvidence.some((generic) => e.toLowerCase().includes(generic)),
  )

  if (!hasSpecificEvidence) {
    return {
      valid: false,
      reason: 'Evidence is too generic - need specific test results or scan outputs',
    }
  }

  return {
    valid: true,
    reason: 'Claim has specific evidence',
  }
}
