/**
 * Audit Trail Types
 *
 * Defines the schema for all audit events, entries, policies, and alerts.
 * The audit trail is an append-only, immutable log of all agent activity.
 * Agents receive a write-only emitter; humans control the observer.
 */

import { z } from 'zod';

// ─── Event Types ────────────────────────────────────────────────────────────

/** All possible audit event types */
export const AuditEventType = z.enum([
  // Agent lifecycle
  'agent:registered',
  'agent:unregistered',

  // Task execution
  'agent:task:started',
  'agent:task:completed',
  'agent:task:failed',
  'agent:task:timeout',

  // Tool usage
  'agent:tool:called',
  'agent:tool:result',
  'agent:tool:denied',

  // LLM interactions
  'agent:llm:request',
  'agent:llm:response',
  'agent:llm:error',

  // Memory operations
  'agent:memory:read',
  'agent:memory:write',
  'agent:memory:delete',

  // Delegation
  'agent:delegation:requested',
  'agent:delegation:completed',
  'agent:delegation:denied',

  // Policy and safety
  'policy:violation',
  'policy:warning',

  // BYOK key lifecycle
  'byok:key:accessed',

  // Human actions
  'human:agent:halted',
  'human:agent:resumed',
  'human:fleet:halted',
  'human:fleet:resumed',
  'human:policy:added',
  'human:policy:removed',
  'human:alert:acknowledged',
]);

export type AuditEventType = z.infer<typeof AuditEventType>;

// ─── Severity ───────────────────────────────────────────────────────────────

export const AuditSeverity = z.enum(['info', 'warn', 'critical']);
export type AuditSeverity = z.infer<typeof AuditSeverity>;

// ─── Audit Entry ────────────────────────────────────────────────────────────

/** A single immutable audit log entry */
export const AuditEntrySchema = z.object({
  /** Unique entry ID (UUID v4) */
  id: z.string().uuid(),
  /** When the event occurred */
  timestamp: z.date(),
  /** Type of event */
  eventType: AuditEventType,
  /** Severity classification */
  severity: AuditSeverity,
  /** Agent that triggered the event */
  agentId: z.string(),
  /** Task ID if applicable */
  taskId: z.string().optional(),
  /** Session or orchestration run ID */
  sessionId: z.string().optional(),
  /** Event-specific data */
  payload: z.record(z.string(), z.unknown()),
  /** Policy violations triggered by this event */
  policyViolations: z.array(z.string()).default([]),
});

export type AuditEntry = z.infer<typeof AuditEntrySchema>;

// ─── Audit Filter ───────────────────────────────────────────────────────────

/** Filters for querying audit entries (human-side only) */
export interface AuditFilter {
  agentId?: string;
  taskId?: string;
  sessionId?: string;
  eventTypes?: AuditEventType[];
  severity?: AuditSeverity[];
  startTime?: Date;
  endTime?: Date;
  limit?: number;
  offset?: number;
}

// ─── Policy Types ───────────────────────────────────────────────────────────

/** Action to take when a policy is violated */
export const PolicyAction = z.enum([
  'alert', // Generate an alert for human review
  'halt_agent', // Immediately halt the violating agent
  'halt_all', // Halt the entire agent fleet (emergency)
]);

export type PolicyAction = z.infer<typeof PolicyAction>;

/** A human-defined policy rule */
export interface AuditPolicy {
  /** Unique policy ID */
  id: string;
  /** Human-readable name */
  name: string;
  /** What this policy enforces */
  description: string;
  /** Severity when triggered */
  severity: AuditSeverity;
  /** Action to take on violation */
  action: PolicyAction;
  /** Condition function: receives the current entry and recent history */
  condition: (entry: AuditEntry, recentHistory: AuditEntry[]) => boolean;
  /** Whether this policy is active */
  enabled: boolean;
  /** Who created this policy */
  createdBy: string;
  /** When this policy was created */
  createdAt: Date;
}

// ─── Alert Types ────────────────────────────────────────────────────────────

/** An alert generated by a policy violation */
export interface AuditAlert {
  /** Unique alert ID */
  id: string;
  /** Policy that triggered this alert */
  policyId: string;
  /** Policy name for display */
  policyName: string;
  /** The audit entry that triggered it */
  triggeringEntryId: string;
  /** Agent involved */
  agentId: string;
  /** Alert severity */
  severity: AuditSeverity;
  /** Action taken (or recommended) */
  action: PolicyAction;
  /** When the alert was generated */
  createdAt: Date;
  /** Whether a human has acknowledged this alert */
  acknowledged: boolean;
  /** Who acknowledged it */
  acknowledgedBy?: string;
  /** When it was acknowledged */
  acknowledgedAt?: Date;
}

// ─── Agent Status ───────────────────────────────────────────────────────────

/** Tracked status of an agent from the audit system's perspective */
export interface AuditAgentStatus {
  agentId: string;
  halted: boolean;
  haltedBy?: string;
  haltedAt?: Date;
  haltReason?: string;
  totalEvents: number;
  totalViolations: number;
  lastEventAt?: Date;
}
