/**
 * Self-host local AI profile (host resource tiers).
 *
 * Written by harnesses `InferenceService.profileApply` (control plane).
 * Read by `createLLMClientFromEnv` to fill missing LLM_* env (self-host only).
 *
 * Tiers: idle | daily | snaps | heavy — see ADR US-origin + operator LOCAL-AI.md.
 * Hosted deployments must never load this file into a serverless process path.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';
import {
  DEFAULT_DAILY_OLLAMA_MODEL,
  DEFAULT_LOW_RAM_INFERENCE_SNAP,
  DEFAULT_US_ORIGIN_INFERENCE_SNAP,
} from './providers/us-origin-snaps.js';

export type LocalAiTier = 'idle' | 'daily' | 'snaps' | 'heavy';

export type LocalAiProvider = 'ollama' | 'inference-snaps' | null;

export interface LocalAiProfile {
  tier: LocalAiTier;
  provider: LocalAiProvider;
  model: string | null;
  baseURL: string | null;
  /** Ollama models directory (hot store) */
  ollamaModelsDir: string | null;
  /** Ollama keep_alive (e.g. "0" unloads after each request) */
  keepAlive: string | null;
  updatedAt: string;
  /** Optional free-text note (e.g. RAM warning) */
  note?: string;
}

export function getLocalAiProfilePath(): string {
  return (
    process.env.REVEALUI_INFERENCE_PROFILE_PATH ??
    join(homedir(), '.local', 'share', 'revealui', 'inference-profile.json')
  );
}

/** Shell-compat env file written alongside the JSON profile. */
export function getLocalAiActiveEnvPath(): string {
  return join(homedir(), '.config', 'revealui', 'local-ai.active.env');
}

/** Idle profile with best-effort hot model dir detection. */
export function emptyIdleProfile(): LocalAiProfile {
  const hot =
    process.env.OLLAMA_MODELS ??
    process.env.REVEALUI_MODELS_HOT ??
    (existsSync('/mnt/studio/models')
      ? '/mnt/studio/models/ollama'
      : join(homedir(), '.ollama', 'models'));
  return {
    tier: 'idle',
    provider: null,
    model: null,
    baseURL: null,
    ollamaModelsDir: hot,
    keepAlive: '0',
    updatedAt: new Date().toISOString(),
    note: 'AI stopped — IDE/dev headroom',
  };
}

export function loadLocalAiProfile(path: string = getLocalAiProfilePath()): LocalAiProfile | null {
  try {
    if (!existsSync(path)) return null;
    const raw = JSON.parse(readFileSync(path, 'utf8')) as LocalAiProfile;
    if (!raw || typeof raw.tier !== 'string') return null;
    return raw;
  } catch {
    return null;
  }
}

export function saveLocalAiProfile(
  profile: LocalAiProfile,
  path: string = getLocalAiProfilePath(),
): void {
  const dir = dirname(path);
  mkdirSync(dir, { recursive: true });
  writeFileSync(path, `${JSON.stringify(profile, null, 2)}\n`, 'utf8');

  // Shell-compat for operator tooling
  const envPath = getLocalAiActiveEnvPath();
  mkdirSync(dirname(envPath), { recursive: true });
  const lines = [
    `# generated by local-ai-profile ${profile.updatedAt}`,
    `export REVEALUI_LOCAL_AI_TIER=${profile.tier}`,
  ];
  if (profile.ollamaModelsDir) {
    lines.push(`export OLLAMA_MODELS=${profile.ollamaModelsDir}`);
  }
  if (profile.keepAlive != null) {
    lines.push(`export OLLAMA_KEEP_ALIVE=${profile.keepAlive}`);
  }
  if (profile.provider) {
    lines.push(`export LLM_PROVIDER=${profile.provider}`);
  } else {
    lines.push('unset LLM_PROVIDER');
  }
  if (profile.model) {
    lines.push(`export LLM_MODEL=${profile.model}`);
  } else {
    lines.push('unset LLM_MODEL');
  }
  if (profile.provider === 'inference-snaps' && profile.baseURL) {
    lines.push(`export INFERENCE_SNAPS_BASE_URL=${profile.baseURL}`);
  } else {
    lines.push('unset INFERENCE_SNAPS_BASE_URL');
  }
  if (profile.provider === 'ollama' && profile.baseURL) {
    lines.push(`export OLLAMA_BASE_URL=${profile.baseURL}`);
  }
  writeFileSync(envPath, `${lines.join('\n')}\n`, 'utf8');
}

/**
 * Fill missing process.env LLM_* keys from the self-host profile.
 * Never overrides explicit env. No-op when REVEALUI_SKIP_INFERENCE_PROFILE=1
 * or when REVEALUI_HOSTED=1 / VERCEL (hosted fail-closed).
 */
export function applyLocalAiProfileToEnv(
  env: NodeJS.ProcessEnv = process.env,
  profile: LocalAiProfile | null = loadLocalAiProfile(),
): void {
  if (env.REVEALUI_SKIP_INFERENCE_PROFILE === '1') return;
  if (env.REVEALUI_HOSTED === '1' || env.VERCEL === '1') return;
  if (!profile || profile.tier === 'idle') return;

  if (!env.LLM_PROVIDER && profile.provider) {
    env.LLM_PROVIDER = profile.provider;
  }
  if (!env.LLM_MODEL && profile.model) {
    env.LLM_MODEL = profile.model;
  }
  if (profile.provider === 'inference-snaps' && !env.INFERENCE_SNAPS_BASE_URL && profile.baseURL) {
    env.INFERENCE_SNAPS_BASE_URL = profile.baseURL;
  }
  if (profile.provider === 'ollama') {
    if (!env.OLLAMA_BASE_URL && profile.baseURL) {
      env.OLLAMA_BASE_URL = profile.baseURL.replace(/\/v1\/?$/, '');
    }
    if (!env.OLLAMA_MODELS && profile.ollamaModelsDir) {
      env.OLLAMA_MODELS = profile.ollamaModelsDir;
    }
    if (!env.OLLAMA_KEEP_ALIVE && profile.keepAlive != null) {
      env.OLLAMA_KEEP_ALIVE = profile.keepAlive;
    }
  }
}

export function profileDefaultsForTier(
  tier: LocalAiTier,
): Pick<LocalAiProfile, 'provider' | 'model' | 'baseURL' | 'keepAlive' | 'note'> {
  switch (tier) {
    case 'idle':
      return {
        provider: null,
        model: null,
        baseURL: null,
        keepAlive: '0',
        note: 'AI stopped — IDE/dev headroom',
      };
    case 'daily':
      return {
        provider: 'ollama',
        model: DEFAULT_DAILY_OLLAMA_MODEL,
        baseURL: 'http://127.0.0.1:11434',
        keepAlive: '0',
        note: 'Ollama daily default (qwen2.5:3b); weights unload after each request',
      };
    case 'snaps':
      return {
        provider: 'inference-snaps',
        model: DEFAULT_LOW_RAM_INFERENCE_SNAP,
        baseURL: null, // filled after snap status
        keepAlive: null,
        note: 'Inference Snap product path (US-origin allowlist)',
      };
    case 'heavy':
      return {
        provider: 'inference-snaps',
        model: DEFAULT_US_ORIGIN_INFERENCE_SNAP,
        baseURL: null,
        keepAlive: null,
        note: 'Heavy snap — needs substantial RAM; avoid concurrent IDE load on 4GB WSL',
      };
    default: {
      const _exhaustive: never = tier;
      return _exhaustive;
    }
  }
}
