// Default theme settings.
export const defaultThemeSettings = {
  maxWidth: {
    0: "max-w-3xl",
    1: "max-w-5xl",
    2: "max-w-7xl",
    3: "max-w-8xl",
    4: "max-w-9xl",
    5: "max-w-10xl",
    default: "max-w-full",
  },
  padding: {
    0: "p-0",
    1: "p-1",
    2: "p-2",
    default: "p-3",
  },
  breakpoints: {
    sm: "640px",
    md: "768px",
    lg: "1024px",
    xl: "1280px",
    "2xl": "1536px",
  },
  layoutType: {
    container: "container",
    flex: "flex",
    grid: "grid",
    stack: "stack",
  },
  customProps: {
    flex: {
      flexDirection: {
        row: "flex-row",
        col: "flex-col",
      },
      justifyContent: {
        start: "justify-start",
        center: "justify-center",
        end: "justify-end",
        between: "justify-between",
        around: "justify-around",
        evenly: "justify-evenly",
      },
      alignItems: {
        start: "items-start",
        center: "items-center",
        end: "items-end",
        stretch: "items-stretch",
        baseline: "items-baseline",
      },
      alignContent: {
        start: "content-start",
        center: "content-center",
        end: "content-end",
        between: "content-between",
        around: "content-around",
        evenly: "content-evenly",
      },
      flexWrap: {
        nowrap: "flex-nowrap",
        wrap: "flex-wrap",
        wrapReverse: "flex-wrap-reverse",
      },
      flexFlow: {
        row: "flex-row",
        col: "flex-col",
        rowWrap: "flex-row flex-wrap",
        colWrap: "flex-col flex-wrap",
        rowWrapReverse: "flex-row flex-wrap-reverse",
        colWrapReverse: "flex-col flex-wrap-reverse",
      },
      flexGrow: {
        0: "flex-grow-0",
        1: "flex-grow-1",
      },
      flexShrink: {
        0: "flex-shrink-0",
        1: "flex-shrink-1",
      },
      flexBasis: {
        auto: "flex-basis-auto",
        0: "flex-basis-0",
        full: "flex-basis-full",
      },
      flexOrder: {
        first: "order-first",
        last: "order-last",
        none: "order-none",
        1: "order-1",
        2: "order-2",
        3: "order-3",
        4: "order-4",
        5: "order-5",
        6: "order-6",
        7: "order-7",
        8: "order-8",
        9: "order-9",
        10: "order-10",
        11: "order-11",
        12: "order-12",
      },
      flexSelf: {
        auto: "self-auto",
        start: "self-start",
        center: "self-center",
        end: "self-end",
        stretch: "self-stretch",
      },
    },
    grid: {
      gridTemplateColumns: {
        1: "grid-cols-1",
        2: "grid-cols-2",
        3: "grid-cols-3",
        4: "grid-cols-4",
        5: "grid-cols-5",
        6: "grid-cols-6",
        7: "grid-cols-7",
        8: "grid-cols-8",
        9: "grid-cols-9",
        10: "grid-cols-10",
        11: "grid-cols-11",
        12: "grid-cols-12",
        none: "grid-cols-none",
      },
      gridTemplateRows: {
        1: "grid-rows-1",
        2: "grid-rows-2",
        3: "grid-rows-3",
        4: "grid-rows-4",
        5: "grid-rows-5",
        6: "grid-rows-6",
        none: "grid-rows-none",
      },
      gridTemplateAreas: {
        none: "grid-areas-none",
      },
      gridAutoColumns: {
        auto: "auto-cols-auto",
        min: "auto-cols-min",
        max: "auto-cols-max",
        fr: "auto-cols-fr",
      },
      gridAutoRows: {
        auto: "auto-rows-auto",
        min: "auto-rows-min",
        max: "auto-rows-max",
        fr: "auto-rows-fr",
      },
      gridAutoFlow: {
        row: "grid-flow-row",
        col: "grid-flow-col",
        rowDense: "grid-flow-row-dense",
        colDense: "grid-flow-col-dense",
      },
      grid: {
        rows: "rows",
        cols: "cols",
        gap: "gap",
        gapX: "gap-x",
        gapY: "gap-y",
        autoFlow: "auto-flow",
        autoRows: "auto-rows",
        autoCols: "auto-cols",
        templateRows: "template-rows",
        templateCols: "template-cols",
        templateAreas: "template-areas",
      },
      gridRow: {
        auto: "row-auto",
        span: "row-span",
        start: "row-start",
        end: "row-end",
      },
      gridColumn: {
        auto: "col-auto",
        span: "col-span",
        start: "col-start",
        end: "col-end",
      },
      gridArea: {
        auto: "area-auto",
      },
    },
  },
};
