/**
 * AUTO-GENERATED by apps/docs/scripts/build-slug-manifest.ts.
 * Do not edit by hand. Regenerate via `pnpm --filter docs build:slug-manifest`.
 *
 * Maps lowercase-kebab slugs to their original docs/ file paths.
 * Used by the markdown resolver to translate flat URLs
 * (docs.revealui.com/admin-guide) into file fetches
 * (/admin-guide.md served from public/).
 * Generated: 105 entries.
 */

export const SLUG_TO_PATH: Readonly<Record<string, string>> = Object.freeze({
  'admin-guide': 'ADMIN_GUIDE.md',
  'agent-rules/biome': 'agent-rules/biome.md',
  'agent-rules/conventions': 'agent-rules/conventions.md',
  'agent-rules/database-boundaries': 'agent-rules/database-boundaries.md',
  'agent-rules/evaluation-log': 'agent-rules/evaluation-log.md',
  'agent-rules/feature-gating': 'agent-rules/feature-gating.md',
  'agent-rules/monorepo': 'agent-rules/monorepo.md',
  'agent-rules/readme': 'agent-rules/README.md',
  'agent-rules/safety': 'agent-rules/safety.md',
  'agent-rules/tailwind-v4': 'agent-rules/tailwind-v4.md',
  'agent-rules/test-prompts': 'agent-rules/test-prompts.md',
  'agent-rules/testing': 'agent-rules/testing.md',
  'agent-rules/unused-declarations': 'agent-rules/unused-declarations.md',
  ai: 'AI.md',
  'ai/prompt-caching': 'ai/PROMPT_CACHING.md',
  'ai/response-caching': 'ai/RESPONSE_CACHING.md',
  'ai/semantic-caching': 'ai/SEMANTIC_CACHING.md',
  'api/readme': 'api/README.md',
  'api/rest-api/readme': 'api/rest-api/README.md',
  architecture: 'ARCHITECTURE.md',
  'architecture/adr-001-agent-first': 'architecture/ADR-001-agent-first.md',
  'architecture/adr-002-dual-database': 'architecture/ADR-002-dual-database.md',
  'architecture/adr-003-fair-source-licensing': 'architecture/ADR-003-fair-source-licensing.md',
  'architecture/adr-004-session-only-auth': 'architecture/ADR-004-session-only-auth.md',
  'architecture/adr-005-two-repo-model': 'architecture/ADR-005-two-repo-model.md',
  'architecture/ai-stack': 'architecture/ai-stack.md',
  'architecture/x402': 'architecture/x402.md',
  'audit-status': 'AUDIT_STATUS.md',
  auth: 'AUTH.md',
  'blog-drafts/01-why-we-built-revealui': 'blog-drafts/01-why-we-built-revealui.md',
  'blog-drafts/02-five-primitives': 'blog-drafts/02-five-primitives.md',
  'blog-drafts/03-open-source-and-pro': 'blog-drafts/03-open-source-and-pro.md',
  'blog-drafts/04-agent-first-future': 'blog-drafts/04-agent-first-future.md',
  'blog-drafts/05-getting-started': 'blog-drafts/05-getting-started.md',
  'blog/01-why-we-built-revealui': 'blog/01-why-we-built-revealui.md',
  'blog/02-http-402-payments': 'blog/02-http-402-payments.md',
  'blog/03-multi-agent-coordination': 'blog/03-multi-agent-coordination.md',
  'blog/04-local-first-ai-stack': 'blog/04-local-first-ai-stack.md',
  'blog/05-five-primitives': 'blog/05-five-primitives.md',
  'blog/06-open-source-and-pro': 'blog/06-open-source-and-pro.md',
  'blog/07-agent-first-future': 'blog/07-agent-first-future.md',
  'blog/08-getting-started': 'blog/08-getting-started.md',
  'build-your-business': 'BUILD_YOUR_BUSINESS.md',
  'checklists/stripe-checkout-verification': 'checklists/stripe-checkout-verification.md',
  'ci-cd-guide': 'CI_CD_GUIDE.md',
  'commercial-readiness': 'COMMERCIAL_READINESS.md',
  'component-catalog': 'COMPONENT_CATALOG.md',
  'core-stability': 'CORE_STABILITY.md',
  'credential-rotation-runbook': 'CREDENTIAL-ROTATION-RUNBOOK.md',
  database: 'DATABASE.md',
  'decisions/licensing-platform-evaluation': 'decisions/licensing-platform-evaluation.md',
  'deployment-runbook': 'DEPLOYMENT-RUNBOOK.md',
  'documentation-assessment': 'DOCUMENTATION_ASSESSMENT.md',
  'environment-variables-guide': 'ENVIRONMENT-VARIABLES-GUIDE.md',
  examples: 'EXAMPLES.md',
  'fair-source': 'FAIR_SOURCE.md',
  forge: 'FORGE.md',
  'guides/authentication': 'guides/authentication.md',
  'guides/billing': 'guides/billing.md',
  'guides/collections': 'guides/collections.md',
  'guides/deployment': 'guides/deployment.md',
  'guides/quick-start': 'guides/quick-start.md',
  'guides/readme': 'guides/README.md',
  index: 'INDEX.md',
  joshua: 'JOSHUA.md',
  'launch-checklist': 'LAUNCH-CHECKLIST.md',
  'linting-rules': 'LINTING_RULES.md',
  'local-first': 'LOCAL_FIRST.md',
  logging: 'LOGGING.md',
  marketplace: 'MARKETPLACE.md',
  performance: 'PERFORMANCE.md',
  pro: 'PRO.md',
  publishing: 'PUBLISHING.md',
  'quick-start': 'QUICK_START.md',
  reference: 'REFERENCE.md',
  roadmap: 'ROADMAP.md',
  'runbook-agent-dispatch-flag': 'runbook-agent-dispatch-flag.md',
  'script-management': 'SCRIPT_MANAGEMENT.md',
  secrets: 'SECRETS.md',
  'security/access-review-policy': 'security/ACCESS_REVIEW_POLICY.md',
  'security/asset-inventory': 'security/ASSET_INVENTORY.md',
  'security/backup-verification': 'security/BACKUP_VERIFICATION.md',
  'security/change-management-policy': 'security/CHANGE_MANAGEMENT_POLICY.md',
  'security/incident-response': 'security/INCIDENT_RESPONSE.md',
  'security/information-security-policy': 'security/INFORMATION_SECURITY_POLICY.md',
  'security/security-training': 'security/SECURITY_TRAINING.md',
  'security/soc2-audit-track': 'security/SOC2_AUDIT_TRACK.md',
  'security/templates/pentest-rfp': 'security/templates/pentest-rfp.md',
  'security/vendor-risk-assessments': 'security/VENDOR_RISK_ASSESSMENTS.md',
  'submodules/policy': 'submodules/POLICY.md',
  suite: 'SUITE.md',
  'suite/revcon': 'suite/revcon.md',
  'suite/revdev': 'suite/revdev.md',
  'suite/revealcoin': 'suite/revealcoin.md',
  'suite/revkit': 'suite/revkit.md',
  'suite/revskills': 'suite/revskills.md',
  'suite/revvault': 'suite/revvault.md',
  'system-tune/crash-postmortems': 'system-tune/CRASH-POSTMORTEMS.md',
  'system-tune/profiles': 'system-tune/PROFILES.md',
  testing: 'TESTING.md',
  'third-party-licenses': 'THIRD_PARTY_LICENSES.md',
  troubleshooting: 'TROUBLESHOOTING.md',
  'type-system-rules': 'TYPE-SYSTEM-RULES.md',
  vaughn: 'VAUGHN.md',
  'what-works-today': 'WHAT_WORKS_TODAY.md',
});

export const PATH_TO_SLUG: Readonly<Record<string, string>> = Object.freeze(
  Object.fromEntries(Object.entries(SLUG_TO_PATH).map(([slug, path]) => [path, slug])),
);

/** Resolve a slug to its docs/ file path, or null if unknown. */
export function slugToPath(slug: string): string | null {
  return SLUG_TO_PATH[slug] ?? null;
}

/** Resolve a docs/ file path to its slug, or null if unknown. */
export function pathToSlugLookup(path: string): string | null {
  return PATH_TO_SLUG[path] ?? null;
}
