/**
 * AUTO-GENERATED by apps/docs/scripts/build-slug-manifest.ts.
 * Do not edit by hand. Regenerate via `pnpm --filter docs build:slug-manifest`.
 *
 * Maps lowercase-kebab slugs to their original docs/ file paths.
 * Used by the markdown resolver to translate flat URLs
 * (docs.revealui.com/admin-guide) into file fetches
 * (/admin-guide.md served from public/).
 * Generated: 65 entries.
 */

export const SLUG_TO_PATH: Readonly<Record<string, string>> = Object.freeze({
  'admin-guide': 'ADMIN_GUIDE.md',
  ai: 'AI.md',
  'ai/prompt-caching': 'ai/PROMPT_CACHING.md',
  'ai/response-caching': 'ai/RESPONSE_CACHING.md',
  'ai/semantic-caching': 'ai/SEMANTIC_CACHING.md',
  'api/readme': 'api/README.md',
  'api/rest-api/readme': 'api/rest-api/README.md',
  architecture: 'ARCHITECTURE.md',
  'architecture/adr-001-agent-first': 'architecture/ADR-001-agent-first.md',
  'architecture/adr-002-dual-database': 'architecture/ADR-002-dual-database.md',
  'architecture/adr-003-fair-source-licensing': 'architecture/ADR-003-fair-source-licensing.md',
  'architecture/adr-004-session-only-auth': 'architecture/ADR-004-session-only-auth.md',
  'architecture/adr-005-two-repo-model': 'architecture/ADR-005-two-repo-model.md',
  'architecture/ai-stack': 'architecture/ai-stack.md',
  auth: 'AUTH.md',
  'blog/01-why-we-built-revealui': 'blog/01-why-we-built-revealui.md',
  'blog/02-http-402-payments': 'blog/02-http-402-payments.md',
  'blog/03-multi-agent-coordination': 'blog/03-multi-agent-coordination.md',
  'blog/04-local-first-ai-stack': 'blog/04-local-first-ai-stack.md',
  'blog/05-five-primitives': 'blog/05-five-primitives.md',
  'blog/06-open-source-and-pro': 'blog/06-open-source-and-pro.md',
  'blog/07-agent-first-future': 'blog/07-agent-first-future.md',
  'blog/08-getting-started': 'blog/08-getting-started.md',
  'blog/09-component-library': 'blog/09-component-library.md',
  'blog/10-own-your-data': 'blog/10-own-your-data.md',
  'build-your-business': 'BUILD_YOUR_BUSINESS.md',
  'component-catalog': 'COMPONENT_CATALOG.md',
  'core-stability': 'CORE_STABILITY.md',
  database: 'DATABASE.md',
  'decisions/2026-05-01-supabase-removal': 'decisions/2026-05-01-supabase-removal.md',
  'decisions/2026-05-08-deployment-target-vercel-not-k8s':
    'decisions/2026-05-08-deployment-target-vercel-not-k8s.md',
  'decisions/licensing-platform-evaluation': 'decisions/licensing-platform-evaluation.md',
  'environment-variables-guide': 'ENVIRONMENT-VARIABLES-GUIDE.md',
  examples: 'EXAMPLES.md',
  'fair-source': 'FAIR_SOURCE.md',
  fleet: 'FLEET.md',
  'fleet/revcon': 'fleet/revcon.md',
  'fleet/revdev': 'fleet/revdev.md',
  'fleet/revkit': 'fleet/revkit.md',
  'fleet/revskills': 'fleet/revskills.md',
  'fleet/revvault': 'fleet/revvault.md',
  forge: 'FORGE.md',
  'guides/authentication': 'guides/authentication.md',
  'guides/billing': 'guides/billing.md',
  'guides/collections': 'guides/collections.md',
  'guides/deployment': 'guides/deployment.md',
  'guides/quick-start': 'guides/quick-start.md',
  'guides/readme': 'guides/README.md',
  'guides/technology-stack': 'guides/technology-stack.md',
  'harness-protocol': 'HARNESS_PROTOCOL.md',
  index: 'INDEX.md',
  joshua: 'JOSHUA.md',
  'local-first': 'LOCAL_FIRST.md',
  logging: 'LOGGING.md',
  marketplace: 'MARKETPLACE.md',
  pro: 'PRO.md',
  'quick-start': 'QUICK_START.md',
  reference: 'REFERENCE.md',
  revfleet: 'REVFLEET.md',
  roadmap: 'ROADMAP.md',
  testing: 'TESTING.md',
  'third-party-licenses': 'THIRD_PARTY_LICENSES.md',
  troubleshooting: 'TROUBLESHOOTING.md',
  'what-works-today': 'WHAT_WORKS_TODAY.md',
});

export const PATH_TO_SLUG: Readonly<Record<string, string>> = Object.freeze(
  Object.fromEntries(Object.entries(SLUG_TO_PATH).map(([slug, path]) => [path, slug])),
);

/**
 * Legacy slug aliases preserved for backward-compat inbound links.
 * Each value points to a path also present in SLUG_TO_PATH; reverse
 * lookups via PATH_TO_SLUG always return the canonical slug.
 */
export const LEGACY_SLUG_ALIASES: Readonly<Record<string, string>> = Object.freeze({
  vaughn: 'HARNESS_PROTOCOL.md',
});

/** Resolve a slug to its docs/ file path, or null if unknown. Falls back to LEGACY_SLUG_ALIASES. */
export function slugToPath(slug: string): string | null {
  return SLUG_TO_PATH[slug] ?? LEGACY_SLUG_ALIASES[slug] ?? null;
}

/** Resolve a docs/ file path to its slug, or null if unknown. */
export function pathToSlugLookup(path: string): string | null {
  return PATH_TO_SLUG[path] ?? null;
}
