/**
 * Content primitive — pages, sites, blocks, rich text, and collections.
 *
 * Re-exports from @revealui/core, @revealui/db, and @revealui/contracts.
 */

// ── Contracts: page schemas ─────────────────────────────────────────────────
// ── Contracts: site schemas ─────────────────────────────────────────────────
// ── Contracts: content blocks ───────────────────────────────────────────────
export {
  type AccordionBlock,
  BLOCK_SCHEMA_VERSION,
  type BlockType,
  type ButtonBlock,
  type CodeBlock,
  type ColumnsBlock,
  type CreatePageInput,
  CreatePageInputSchema,
  type CreateSiteInput,
  CreateSiteInputSchema,
  canAgentEditSite,
  canUserPerformAction,
  computePagePath,
  countBlocks,
  createCodeBlock,
  createHeadingBlock,
  createImageBlock,
  createPage,
  createSite,
  createTextBlock,
  type DividerBlock,
  type EmbedBlock,
  estimateWordCount,
  findBlockById,
  type GridBlock,
  getPageBreadcrumbs,
  type HeadingBlock,
  type ImageBlock,
  isColumnsBlock,
  isContainerBlock,
  isGridBlock,
  isHeadingBlock,
  isImageBlock,
  isLockedByUser,
  isPageLocked,
  isTextBlock,
  type ListBlock,
  PAGE_SCHEMA_VERSION,
  type Page,
  type PageLock,
  PageLockSchema,
  PageSchema,
  type PageSeo,
  PageSeoSchema,
  type PageStatus,
  PageStatusSchema,
  type QuoteBlock,
  SITE_SCHEMA_VERSION,
  type Site,
  type SiteCollaborator,
  SiteCollaboratorSchema,
  SiteSchema,
  type SiteSeo,
  SiteSeoSchema,
  type SiteSettings,
  SiteSettingsSchema,
  type SiteStatus,
  SiteStatusSchema,
  type SiteTheme,
  SiteThemeSchema,
  type SpacerBlock,
  type TableBlock,
  type TabsBlock,
  type TextBlock,
  type UpdatePageInput,
  UpdatePageInputSchema,
  type UpdateSiteInput,
  UpdateSiteInputSchema,
  type VideoBlock,
  walkBlocks,
} from '@revealui/contracts';
// ── Core: collection & field types ──────────────────────────────────────────
export type {
  Block,
  BlocksField,
  CheckboxField,
  CollectionConfig,
  Field,
  GlobalConfig,
  GroupField,
  TextField,
} from '@revealui/core';
// ── Core: configuration & factories ─────────────────────────────────────────
// ── Core: rich text ─────────────────────────────────────────────────────────
// ── Core: access control helpers ────────────────────────────────────────────
// ── Core: plugins ───────────────────────────────────────────────────────────
export {
  anyone,
  authenticated,
  BoldFeature,
  buildConfig,
  createRevealUI,
  createRevealUIBlock,
  createRevealUICollection,
  createRevealUIField,
  FixedToolbarFeature,
  formBuilderPlugin,
  getRevealUI,
  HeadingFeature,
  ItalicFeature,
  LinkFeature,
  lexicalEditor,
  nestedDocsPlugin,
  redirectsPlugin,
  serializeLexicalState,
  UnderlineFeature,
  universalPostgresAdapter,
} from '@revealui/core';
// ── DB: content tables ──────────────────────────────────────────────────────
export {
  media,
  pageRevisions,
  pages,
  posts,
  siteCollaborators,
  sites,
} from '@revealui/db';
